lablup/backend.ai

scripts/install-dev.sh

Installation with `install-dev.sh` in CentOS breaks due to missing package `libsnappy-devel`.

fix: libsnappy-devel -> snappy-devel for RHEL/CentOS

---

scripts/install-dev.sh

Update psql command to be run with docker_exec.
Solving issue lablup/backend.ai#224
Tested with clean Ubuntu 16.04 instance (only pyenv, pyenv-virtualenv, docker, docker-compose installed)

Support install without Postgres installed

---

scripts/install-dev.sh

Changed admin id from "admiu@lablup.com" to "admin@lablup.com" in installation report.

fix(scripts/install-dev.sh): Fix typo in installation report for admin id

---

docs/README.md
docs/conf.py
docs/index.rst

This PR resolves a basic guide for building documentation of this project.
Please note that this guide is a quick-fix, which means it can be deprecated when automated documentation (at least API) is enabled.

docs: Add guide for documentation build

---

docker-compose.halfstack-2109.yml
docs/locales/ko_KR/LC_MESSAGES/common-api.po
scripts/install-dev.sh

During the installation process, the following message appeared because POSTGRES_CONTAINER_ID is ''.
`Error: No such container: psql`
In Docker container list, Name is "backendai-half-db-1" but there's a typo with "backendai-half-db_1" in install-dev.sh.

Fix/typo in install dev.sh

---

scripts/install-dev.sh

When a user tries to install in a low-end PC or a VM which have cores less than 4, `num-proc = 4` causes an installation error.

setup: change the value of num-proc to 1 of manager.toml

---

scripts/install-dev.sh

* Let's make it installable on M1 Macs.
- Apply additional build flags for Python, psycopg2-binary, and grpcio.
* Generalize #305 because docker-compose has different container name mangling behaviors for different versions. 😞

Add install-dev support on Apple Silicon (M1)

---

scripts/install-dev.sh

Currently we are building arm64 images with different tags due to some compatibility issues in Harbor.

fix: Pull and alias the arm64 Python image if installed on arm64 machines

---

scripts/install-dev.sh

fix syntax error in install script, sed inlace statement
the fixed script can install development environment.

fix: debug syntax err in install script

---

scripts/install-dev.sh

tester env script file is now divided into admin and user
Follow-up of #347 and #350, to match with #340.

feat: Update tester env script installation to use separate user/admin configs

---

scripts/install-dev.sh

fix to install default packages at install-dev.sh  on AWS Ubuntu & CentOS
- Ubuntu: `gcc`, `make`
- CentOS: `gcc`, `make`, `xz-devel`
close #366
It's the auto-installer's base package issue on the AWS Ubuntu  & CentOS instance.

fix to install default packages on AWS Ubuntu & CentOS

---

scripts/install-dev.sh

on install-dev.sh, option describe that python default version is `3.9.5`
However, on the file, already set ` PYTHON_VERSION="3.9.9"`
change python install version: `3.9.9` to `3.9.10`
change python default version description: `3.9.5` to `3.9.10`
close https://github.com/lablup/backend.ai/issues/356

Change python default version(3.9.10) & description

---

scripts/delete-dev.sh
scripts/install-dev.sh

- install-dev: Fix up grpcio wheel build for Python 3.10 and Apple Silicon (upstream: grpc/grpc#28387)
- fix: Explicitly clear GRPC build flags in Python 3.10
- fix: Reorder db init and image rescan because now 22.03+ uses the pgsql database for storing image metadata.
- fix: Explicitly set the architecture when making an initial alias of "python" image

installer: Fix up grpcio install issue on M1 and Python 3.10

---

scripts/install-dev.sh

add g++ package at install-dev.sh on Ubuntu
New backend.ai version[21.03] needs g++ package on Ubuntu
close https://github.com/lablup/backend.ai/issues/401

add g++ package at install-dev.sh on Ubuntu

---

changes/437.feature
src/ai/backend/manager/api/session.py

Execute keypair bootstrap script for batch compute session as well. I don't see any reason to skip the bootstrap script for batch session.

feat: execute keypair bootstrap script for batch compute session

---

changes/441.fix
scripts/install-dev.sh
src/ai/backend/agent/agent.py
src/ai/backend/agent/kernel.py
src/ai/backend/agent/stats.py

Dump kernel registry information to a file upon `KernelStartedEvent` or `KernelTerminatedEvent`. Saving at container start event did not ensure the existence of kernel object's `runner` attribute, which may cause `AttributeError` in restarting the Agent server.

fix: save kernel registry when KernelStartedEvent and KernelTerminatedEvent

---

changes/445.fix.md
python.lock
requirements.txt
src/ai/backend/common/config.py
src/ai/backend/web/server.py
tests/common/test_config.py

- `tomli` is chosen as the official stdlib `tomllib` in Python 3.11.
So let's use it for maximum compatibility.
ref) https://peps.python.org/pep-0680/

setup: Replace toml with tomli

---

changes/452.fix
src/ai/backend/agent/agent.py

This is a follow-up of https://github.com/lablup/backend.ai/pull/450.

fix: agent startup error due to `UnboundLocalError` in dumping the last registry

---

changes/455.fix.md
src/ai/backend/client/README.rst

Some backslashes in reStructuredText code-block is causing parsing errors of the client SDK README.

fix: Twine check failure of Client SDK wheel package

---

changes/438.fix
py
scripts/install-dev.sh
tools/pants-local

modify install and pants executing scripts for detail handling such as exporting `PY` env and check whether a temporary env exists

fix: Refine `install-dev.sh` and the `./py` wrapper

---

.gitignore
BUILD
changes/459.fix.md
src/ai/backend/web/BUILD

There are some dependencies that require manual definition and import-pkg name mapping.

fix: Missing dependencies for ai.backend.web

---

changes/442.fix.md
configs/testers/sample-env-tester.sh
scripts/install-dev.sh
src/ai/backend/test/cli_integration/admin/test_domain.py
src/ai/backend/test/cli_integration/admin/test_keypair.py
src/ai/backend/test/cli_integration/admin/test_keypair_resource_policy.py
src/ai/backend/test/cli_integration/admin/test_scaling_group.py
src/ai/backend/test/cli_integration/admin/test_user.py
src/ai/backend/test/cli_integration/conftest.py

Some test cases fail because of their outdated assertions; the responses from the latest client do not contain the expected message anymore. I found such mismatches from methods below:
- `ai.backend.test.cli_integration.admin.test_user#test_add_user`
- `ai.backend.test.cli_integration.admin.test_user#test_delete_user`
and they are fixed in this PR.
For details, please check the referenced issue below.
Refs:
- lablup/backend.ai#426

fix: Update integration test to work with the new repo structure

---

changes/460.fix.md
src/ai/backend/testutils/bootstrap.py

Occasionally running pytest on `tests/common/test_distributed.py` (observed twice) and `tests/agent/docker/agent.py` (observed once).
The root cause is unknown yet, but try to avoid potential races upon the etcd container fixture.

fix(testutils): Apply healthcheck to etcd container fixture too

---

changes/465.fix.md
py
src/ai/backend/test/cli_integration/admin/test_user.py

Refs:
- lablup/backend.ai#464
Changed it to ignore messages from `ls -d plugins/*/` when there is no plugin.

fix: Ignore plugins-not-found message

---

changes/463.fix.md
scripts/install-dev.sh

Refs:
- https://github.com/lablup/backend.ai/pull/442
There were some problems in previous PR;
1. `export` keyword was missing. Therefore, `BACKENDAI_TEST_CLIENT_ENV` was declared as bash variable rather than environment variable, which is not accessible from python runtime.
2. `$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )` means the path of the current script file, which is `/scripts`. However the actual scripts, `env-local-admin-api.sh` and `env-local-user-api.sh`, locate in root of the project. Therefore, it is changed to `${PWD}` which should be the root.
Sorry for the mistake.

fix(test): Add missing `export` keyword to `BACKENDAI_TEST_CLIENT_ENV` environment variable

---

changes/470.misc.md
configs/manager/halfstack.toml

* When installed on a VM, it should be accessible from the VM host.

fix(install-dev): Publicly open the manager's service-addr

---

changes/473.fix.md
src/ai/backend/agent/docker/intrinsic.py

add a btrfs subvolumn system call exception
Python os.statvfs syscall to btrfs subvolume(eg. /var/lib/docker/btrfs ) failed with permission error,
adding exception handling before os.statvfs syscall
close https://github.com/lablup/backend.ai/issues/454

fix: Add a subvolume syscall exception for btrfs (#454)

---

changes/475.fix.md
docker-compose.halfstack-2009.yml
docker-compose.halfstack-2103.yml
docker-compose.halfstack-2109.yml
docker-compose.halfstack-2203.yml
docker-compose.halfstack-ha.yml
docker-compose.halfstack-prod.yml

This PR updates PostgreSQL, Redis and etcd package versions to apply bugfixes on the packages.
* PostgreSQL: 13.1 → 13.7 (old versions)12.3 → 12.11
* Redis: 6.2.6 → 6.2.7 (old versions) 6.0.9 → 6.2.7
* etcd: 3.5.1 → 3.5.4 (old versions) 3.4.14 → 3.4.18

setup: Update required software versions

---

changes/488.fix.md
src/ai/backend/manager/models/storage.py
src/ai/backend/storage/api/manager.py

This PR resolves two things; setting the default value for `is_dir` parameter in the rename_file function, and providing more precise message in exception handling when virtual folder operation errors occurred on the same function.
I confirmed this issue during E2E testing for #443.

fix: Type correction on renaming file api

---

changes/492.fix.md
src/ai/backend/manager/api/exceptions.py
src/ai/backend/manager/api/vfolder.py

> ⚠️ NOTE: This PR is solving a critical issue which is related to data manipulation reported from several environments. Following @achimnol's suggestion, **It need to be applied not only for current upstream but also from 21.03.**
This PR resolves to prevent manager from deleting unexpected vfolder on deletion requests by raising error when there's the same name of vfolder in multiple accessible storage hosts.

fix: Raise explicit error if multiple entries found when deleting a vfolder

---

.gitignore
changes/497.fix.md
changes/497.misc.md

let git ignore `/scratches` directory which is created for kernels.
git keeps tracking the directory like below

git ignore kernel scratches

---

changes/498.misc.md
pants.toml
python-kernel.lock
python.lock
tools/flake8.lock
tools/isort.lock
tools/mypy.lock
tools/pytest.lock
tools/towncrier.lock

When generating lockfiles in different architectures (x86-64/arm64), an extra platform tag (which is not used actually) becomes alternating.  To avoid this issue, we could upgrade pex to 2.1.93.  Also upgrade Pants from 2.12.0rc2 to 2.12.0rc3.
You don't have to do anything special.  For source-based pants users, you need to manually checkout the new release tag, but there is no "release_2.12.0rc3" tag yet.  As there is no significant functional differences between rc2 and rc3, you may just stay as-is.
refs pantsbuild/pex#1685
refs https://github.com/pantsbuild/pants/blob/2.12.x/src/python/pants/notes/2.12.x.md

ci: Manually upgrade pex version to avoid platform-flapping issue

---

changes/505.fix.md
scripts/install-dev.sh

fix to check machine arch clearly
make sure to check machine architecture clearly to query the Docker registry.
Sometimes, some Linux VM's `$(uname -p)` result is 'Unknown'. So, changed `$(uname -p)`  to `$(uname -m)` and clearly shows `arm64` and `aarch64` on docker image pulling.

fix: Correct CPU arch detection in `install-dev.sh`

---

changes/514.fix
src/ai/backend/manager/scheduler/dispatcher.py

This PR resolves `prepare()` hanging infinitely when individual session's `start_session()` task inside `TaskGroup` hangs.    
This PR also changes `TaskGroup` to `PersistentTaskGroup`, as every `start_session()` call needs execution result.

fix: add timeout to `prepare()`'s `PersistentTaskGroup`

---

changes/519.misc.md
docs/dev/daily-workflows.rst
scripts/install-dev.sh
scripts/pre-push.sh

A follow-up to #518
* Enable pantsd by default when installed via sources (linux-aarch64).
This will reduce the latency of pants execution from the second run.
* If you are on a release branch, use it as the base branch to check
the changed files.

feat(install-dev): Enhance the pre-push hook

---

changes/524.feature.md
scripts/install-dev.sh

Sometimes it is confusing that we should run `install-dev.sh` from the build root instead of the inside of `scripts` directory.

feat(install-dev): Warn and exit if user is not on the build root.

---

changes/533.feature.md
src/ai/backend/client/cli/__init__.py
src/ai/backend/client/config.py

* This change was intended to be included in #493, but the encryption
logic is completely triggered by the client and optional, so let's
first silence the version compatibility warning in the CLI.

feat: Bump the client's target API version to v6.20220615

---

changes/534.fix.md
src/ai/backend/agent/docker/kernel.py
src/ai/backend/agent/kernel.py
src/ai/backend/agent/kubernetes/kernel.py

This PR fixes agent creation failing due to agent referencing unset `AbstractKernel.runner` object.

fix: `DockerKernel` object has no attribute `runner`

---

changes/540.fix.md
src/ai/backend/common/logging.py

In #538, we found that some (?) log messages have `None` value in the `'level'` key.

fix(logging): Do null-check of the 'level' value even if the key exists

---

changes/485.feature.md
scripts/install-dev.sh

Feat: Support for openSUSE installation
Support for openSUSE installation release versions.
example) openSUSE Leap 15.3 & openSUSE Tumbleweed
After installing docker compose as a plugin (Install the plugin manually, following the link https://docs.docker.com/compose/install/compose-plugin/ ), I checked that script can installed on  openSUSE Tumbleweed and Leap 15.3, Fedora Core 35.
close #404

feat: Support installation on openSUSE

---

changes/545.misc.md
pants.toml
python.lock

For infinite stream of questions about installing grpcio on M1 Mac and until this problem is ultimately fixed by Google, we decided to have our own PyPI distribution service: https://dist.backend.ai/pypi/simple/
**WARNING:** The exact list of packages served there may change over time depending on our needs, so we advise the general audience *not* to rely on this package index.
Special thanks to @jsirois for quickly patching pantsbuild/pex#1849!

setup: Introduce our own PyPI to workaround upstream issues

---

changes/547.misc.md
scripts/install-dev.sh

As #545 is merged, we now can install `grpcio` and `grpcio-tools` package on M1 Mac without building.

feat(install-dev.sh): remove manual grpcio wheel building section

---

scripts/install-dev.sh

fix: set the backend.ai-webui bug on install-dev.sh

fix(install-dev): A typo in sed expression while installing backend.ai-webui

---

changes/552.misc.md
pants.toml
python-kernel.lock
python.lock
tools/flake8.lock
tools/isort.lock
tools/mypy.lock
tools/pytest.lock
tools/towncrier.lock

Recent intermittent failures in our CI were due to pantsbuild/pex#1852 fixed in pex 2.1.99.

setup: Upgrade pex to 2.1.99

---

scripts/pre-push.sh

- macOS and BSD versions of `sed` uses the POSIX standard more strictly.
`\+` in regular expression is a GNU extension so we need to write it
as `\{1,\}` for maximum POSIX compatibility.
Also let's use the basic regex digit character class syntax.
ref: https://riptutorial.com/sed/topic/9436/bsd-macos-sed-vs--gnu-sed-vs--the-posix-sed-specification

ci: Make the pre-push branch check consistent in Mac/Linux

---

changes/525.feature.md
src/ai/backend/manager/api/session.py

Allow general users to force termination of their own sessions. (NOT OTHERS')
Related PR: https://github.com/lablup/backend.ai-webui/pull/1358

feat: allow user to force-terminate own sessions

---

changes/509.fix.md
docs/client/dev/testing.rst
docs/locales/ko/LC_MESSAGES/client/dev/testing.po
docs/locales/ko/LC_MESSAGES/migration/docker-hub-to-backendai-cr.po
docs/migration/docker-hub-to-backendai-cr.rst
scripts/install-dev.sh
src/ai/backend/manager/README.md

During the installation process of `backend.ai`, I found some warning messages that we are currently using deprecated apis, such as:
`backend.ai etcd alias` -> `backend.ai image alias`
`backend.ai mgr etcd rescan-images` -> `backend.ai mgr image rescan`
Therefore, I changed the code to use new APIs rather than the old ones. This is not an urgent fix but required for consistency on maintenance.

fix: Update deprecated `etcd` apis with `image` apis

---

changes/578.fix.md
scripts/install-dev.sh

fix: checking enable-cuda & enable-cuda-mock, modify cp cuda-mock.toml file
1. Clearly checking "--enable-cuda" and "--enable-cuda-mock" in the install-dev.sh
2. modify to copy cuda-mock.toml file
fix #577

fix: checking enable-cuda & enable-cuda-mock, modify cp cuda-mock.toml

---

.github/workflows/default.yml
.github/workflows/timeline-check.yml

Let's use `skip:ci`, `skip:changelog` labels to mark skipping specific workflows for PRs.

ci: Let workflows recognize skip:ci, skip:changelog labels

---

changes/582.feature
src/ai/backend/manager/api/scaling_group.py
src/ai/backend/manager/api/session.py

Return WSProxy advertise URL, if exists, by querying the value from the coordinator in starting an app service. Since the coordinator's `status` handler now returns the advertise address, the `query_wsproxy_version` method is renamed to `query_wsproxy_status`.
This PR resolves https://github.com/lablup/backend.ai/issues/581.

feat: support advertise URL for WSProxoy v2

---

changes/602.fix.md
scripts/install-dev.sh

Add check for the compatibility of `-f` flag of the `docker compose` command in user/root privileges.
close https://github.com/lablup/backend.ai/issues/596

feat(install-dev): Add check for `-f` flag compatibility of docker compose v2 in user/root privileges

---

.editorconfig
scripts/install-dev.sh
scripts/pre-commit
scripts/pre-commit.sh
scripts/pre-push
scripts/pre-push.sh

- scripts/pre-commit, scripts/pre-push will be added to actual hooks
while scripts/pre-commit.sh, scripts/pre-push.sh will remain as
updatable (versioned) implementation of them.
- Use a temporarily added git remote to resolve the "bad revision"
error when using `--changed-since` against a branch in a fork repo.
After this PR is merged, please update your git hooks as follows,
so that hooks could be versioned without manual updates:
**`.git/hooks/pre-commit`**:
```bash
BASE_PATH=$(cd "$(dirname "$0")"/../.. && pwd)
${BASE_PATH}/scripts/pre-commit.sh "$@"
```
**`.git/hooks/pre-push`**:
```bash
BASE_PATH=$(cd "$(dirname "$0")"/../.. && pwd)
${BASE_PATH}/scripts/pre-push.sh "$@"
```

feat(scripts): Improve pre-push hook and use updatable hooks

---

changes/599.feature.md
configs/webserver/sample.conf
src/ai/backend/common/validators.py
src/ai/backend/web/auth.py
src/ai/backend/web/config.py
src/ai/backend/web/proxy.py
src/ai/backend/web/server.py
src/ai/backend/web/template.py
src/ai/backend/web/templates/config.toml.j2
src/ai/backend/web/templates/config_ini.toml.j2
tests/common/test_validators.py
tests/webserver/test_auth.py

Resolves #590.
This PR also contains various improvements over configuration handling
of the web server and internal refactorings to improve the code quality.
**`common.validators`:**
* fix: Use the generic types correctly with `DelimiterSeperatedList`
* feat: Add `allow_blank`, `empty_str_as_empty_list` options to
`DelimiterSeperatedList`
* This PR keeps backward-compatibility of `tx.DelimiterSeperatedList`!
**`web.server` and `web.config` (new):**
* fix: Correct type annotation and return value usage of
`decrypt_payload()`
* refactor: Use trafaret to parse, validate, and convert the
configuration values from webserver.conf
- Now it requires all sections must be present in webserver.conf
even when they omit all of their belonging keys.
* refactor: Use Jinja2's `tojson` and `join` filters …

feat(web): Add `[service].static_path` option

---

changes/615.fix.md
src/ai/backend/manager/models/image.py

fix: incorrectly spelled word in ImageNotFound exception message.
Change & Correct word from 'Unkown' to 'Unknown'.
fix issue #614

fix: Incorrectly spelled word in ImageNotFound exception message

---

changes/630.feature.md
src/ai/backend/common/logging.py
src/ai/backend/manager/server.py
src/ai/backend/testutils/bootstrap.py
tests/agent/conftest.py
tests/manager/conftest.py

This PR is cherry-picked from #627 to split the feature addition as a standalone PR.
It adds `common.logging.LocalLogger` which supports `console` and `file` logging backends with the
Python's standard logging mechanism instead of relaying log records to the parent process.  Also it
adds the `logging_config` session-level test fixture called by the `local_config` fixtures in the
manager and agent test suites, so that any test case that directly/indirectly involves logging to
display pretty and proper log outputs.
There is a minor update of allowing `None` for the `colored` config parameter of the console log
handler to auto-detect whether stderr is a tty or not, to decide colored outputs.

feature: Improve logging in tests

---

changes/639.fix.md
src/ai/backend/client/cli/run.py

- In `backend.ai run` CLI command, the unspecified value of
`--assign-agent` option has been transformed as an empty list.
- In the server-side, this triggers the privilege check as the manager
treats an empty list as a valid list.
- Let the client CLI preserve the default `None` value when passing it
to the functional API wrappers and the manager.

fix: Insufficient privilege error of the `run` cmd run as a user

---

changes/650.fix.md
src/ai/backend/client/cli/__init__.py
src/ai/backend/client/cli/admin/__init__.py
src/ai/backend/client/cli/admin/session.py
src/ai/backend/client/cli/app.py
src/ai/backend/client/cli/config.py
src/ai/backend/client/cli/dotfile.py
src/ai/backend/client/cli/logs.py
src/ai/backend/client/cli/proxy.py
src/ai/backend/client/cli/run.py
src/ai/backend/client/cli/server_log.py
src/ai/backend/client/cli/session.py
src/ai/backend/client/cli/session_template.py
src/ai/backend/client/cli/vfolder.py

In this PR, `ai.backend.client.cli` is changed to use `CommandGroup`(**ai.backend.cli.main:main**, **cli.main** in short) rather than its own from **ai.backend.client.cli.main:main**(**client.main** in short). It seems that the previous one(**client.main:main**) has been used until we merged into a monorepo. However, since we are maintaining in a monorepo style, it is required to integrated one of two `cli`s into the other one. It seems reasonable to keep **cli.main:main** since it should be the main root of **cli**, and `ai.backend.client.cli` subpackage should remain as a part of it.
Before | After
------ | -----

fix: Change client.cli to use the same `ai.backend.cli.main:main` as its CommandGroup

---

changes/653.feature.md
src/ai/backend/manager/api/resource.py

I added `status_history` to the query field of `get_container_stats_for_period`. This is to check when resources are allocated by adding `scheduled_at` (one of the session history) to the Usage Logs page of the control panel.
**Related issue:**
- https://github.com/lablup/backend.ai-control-panel/issues/299
- https://github.com/lablup/backend.ai/issues/469

feat: Add `status_history` to the result of `get_container_stats_for_period()`

---

src/ai/backend/cli/extensions.py

Following the #486 As mentioned in the issue and #559  Merged PR,
I found a missing item about changing numeric exit code to enum value.
As a result, I modify missing item about changing numeric exitcode to enum value.

refactor: Fix a missing change of numeric exitcode to an enum value

---

changes/652.feature.md
configs/webserver/sample.conf
src/ai/backend/client/request.py
src/ai/backend/web/config.py
src/ai/backend/web/server.py
src/ai/backend/web/templates/config.toml.j2

- New API router: `/func/saml`.
- New config: `service.single_sign_on_vendors` which translates to `general.singleSignOnVendors` in Web-UI.
- This field is a comma-separated list of strings.
- The redirect responses (30X) are now transparently delivered to the downstream without raising `BackendAPIError`.
- https://github.com/lablup/backend.ai-webui/pull/1413

feat: add config to support SSO vendors

---

changes/661.fix.md
src/ai/backend/agent/stats.py

This PR fixes kernel stat (`REDIS_LIVE_DB.<kernel_id>`) not being updated to redis.

hotfix: kernel stat not pushed to redis db

---

changes/660.feature.md
configs/webserver/sample.conf
src/ai/backend/web/templates/config.toml.j2

This PR adds variable `enable_container_commit` in webserver configuration file for supporting container image commit operation on static build webui inside webserver.
Also, this feature is available from `22.09` and later versions.
Related PR: 
- #601
- [backend.ai-webui#1412](https://github.com/lablup/backend.ai-webui/pull/1412)

feat: Support image commit feature flag for webui

---

.github/workflows/timeline-check.yml

It is stated in the official github document that on: pull_request works for reopened, opened, and synchronize by default.
In addition to the corresponding action, when the label is changed, the action is activated.
`Note: More than one activity type triggers this event. For information about each activity type, see "[Webhook events and payloads](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request)." By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened. To trigger workflows by different activity types, use the types keyword. For more information, see "[Workflow syntax for GitHub Actions](https://docs.github.com/en/articles/workflow-syntax-for-github-actions#onevent_nametypes)." …

ci: label trigger timeline-check action

---

.github/workflows/auto_author_assign.yml

Most prs are assigned by the author, but there are some that are missing.
Automate this through github actions
It does not work in the following situations.
- Someone is already assigned as an assignee
- The author is a bot

ci: pr auto author assign

---

src/ai/backend/manager/cli/__main__.py
src/ai/backend/manager/cli/etcd.py

Following the #486 As mentioned in the issue and #559 , #655  Merged PRs,
I found a missing item about changing numeric exit code to enum value on Backend.AI Manager cli.
So, I also change some missing item about changing numeric exitcode to enum value.

refactor: modify a missing change of an enum value on Backend.AI Manager cli

---

changes/667.fix.md
src/ai/backend/manager/models/kernel.py

- Currently this triggers "Session Not Found" error in
`AgentRegistry.get_commit_status()`'s call to
`AgentRegistry.get_session()`.
- Terminated sessions will not be present in the agents.

fix: Skip non-running sessions when checking commit status

---

.github/labeler.yml
.github/workflows/label.yml

Added auto labeling ci for efficient pr management
If there is a change in the migration file that is created when the db schema is changed, create a require:db-migration tag
It is thought that auto labeling will be possible by checking the change of manager, agent, etc. composed of monorepo using this workflow.
In the future, I think it would be nice to be able to import the label assigned to the issue linked to Development.

ci: automatic db migration labeling

---

changes/681.feature.md
src/ai/backend/agent/server.py
src/ai/backend/manager/registry.py

This PR resolves lablup/backend.ai#680.
The `reason` message is restricted to `force-terminated` when forcing a termination. However, there is a necessity on providing a detailed `reason` message to describe the circumstance why the kernel has terminated.
In this PR, I changed the default value of the parameter `reason` to `None` and let it be `user-requested` or `force-terminated` only in case a caller does not pass the `reason` argument. This change provides support for custom `reason` messages, even with the condition `forced=True`, while it still maintains compatibility with the old version.

feat: Preserve the given value `reason` on forced kernel termination with a fallback

---

.github/labeler.yml

It detects changes in storage, agent, manager, common, and install-dev and auto-labels tags for each item.
I think it will be useful for situations where labeling is omitted, or for prs of people who do not have permission in the current repo.

ci: add auto-labeled items

---

.github/workflows/coverage.yml
.github/workflows/default.yml
.github/workflows/timeline-check.yml
changes/719.misc.md
docs/dev/daily-workflows.rst
pants.toml
pyproject.toml
python-kernel.lock
python.lock
tools/flake8.lock
tools/pytest.lock

* Bump the base Python version from 3.10.5 to 3.10.7 to reflect the bug fix of mis-truncated stack chain when an exception is thrown into coroutines (e.g., cancellation).
- refs python/cpython#93592
* Let GitHub action workflows take the Python version from `pants.toml` (the first match found)
- Now it is sufficient to modify `pants.toml` only when you upgrade Python.
- If the designated Python version is not available in [actions/python-versions](https://github.com/actions/python-versions), you may need to create an issue in [actions/setup-python](https://github.com/actions/setup-python/issues?q=is%3Aissue+author%3Aachimnol+is%3Aclosed) or wait a couple of days.
* NOTE: Developers should install Python 3.10.7 by their own (e.g., using pyenv) as Pants itself does not auto-install Python …

setup: Bump python version from 3.10.5 to 3.10.7

---

changes/699.feature.md
src/ai/backend/manager/models/agent.py
src/ai/backend/manager/models/gql.py

do not return AgentSummary and AgentSummaryList gql objects if `hide-agents` is true.
Follow-up of #645.
Resolves #640.

feat: Do not return AgentSummary if hide-agents is true

---

.github/labeler.yml
changes/727.fix.md
tools/pants-plugins/setupgen/register.py

When the main interpreter constraint in `pants.toml` says "==3.10.7", this PR will generate `.tar.gz`, `.whl` distributions with ">=3.10,<3.11" to allow installation on compatible Python versions, while keeping the exact Python versions in CI scripts and the build toolchain.

setup: Allow installation of package wheels on compatible Python versions

---

changes/725.fix
src/ai/backend/manager/models/user.py

Set concurrency used in purging a user only when there is a related keypair.

fix: unable to purge user when there is no related keyapir

---

pyproject.toml

Let's allow more precisely fit news fragment types.
* `.enhance.md`
* `.deps.md`

ci: Add new towncrier news fragment types

---

changes/731.feature.md
src/ai/backend/agent/docker/agent.py

This PR alters infiniband device mount mechanism to always mount infiniband devices if it exists regardless of if it's multicontainer session or not.

feat: always mount infiniband device if exists

---

changes/732.feature.md
configs/webserver/sample.conf
src/ai/backend/web/config.py
src/ai/backend/web/templates/config.toml.j2

This change adds webserver option to support session enqueue feature, introduced from https://github.com/lablup/backend.ai-webui/pull/1162 
A user cannot create a compute session when there is no available resource in the Agent hosts. In the absence of the resources, the session launcher dialog disables the CREATE button.
Some users / groups find this inconvenient since they have to wait until other users destroy their compute sessions to create their own. They rather wanted to create a PENDING session immediately and then get the RUNNING session automatically just after the resources are available. Therefore, queueing the session creation request feature added in backend.ai-webui, and it is configurable via `config.toml` as a global service option. 
This PR adds the …

add: support webserver option for session enqueue

---

changes/721.feature.md
scripts/extract-release-changelog.py

issue #691 
- Add commit history link between releases in release notes(`CHANGELOG_RELEASE.md`) by updating `scripts/extract-release-changelog.py`

feat: Add commit history between releases

---

changes/737.feature.md
src/ai/backend/agent/server.py
src/ai/backend/client/cli/admin/agent.py
src/ai/backend/client/cli/session.py
src/ai/backend/client/func/agent.py
src/ai/backend/client/func/session.py
src/ai/backend/client/output/fields.py
src/ai/backend/manager/api/session.py
src/ai/backend/manager/models/agent.py
src/ai/backend/manager/models/kernel.py
src/ai/backend/manager/registry.py

Implement kernel's abusing report API.
Add CLI command and add ComputeContainer graph field `abusing_report`.
example image)
abusing report is saved as following.
The report shows as following.
---
Since there are many unserializable items in agent's local_config that RPC function cannot parse, let agents return only a few items of local_config

feat: impl abusing report and agent local_config API

---

changes/772.feature.md
src/ai/backend/manager/models/kernel.py

This PR enables GraphQL queries to filter `ComputeSession` items by `id`. It is necessary for fetching multiple `ComputeSession` items by a list of their `id`.
Related PRs
- https://github.com/lablup/backend.ai-batch-workflow/pull/139

feat: Let GraphQL queries filter ComputeSession by id

---

changes/766.fix.md
src/ai/backend/manager/models/vfolder.py

This PR fixes extra vFolder access condition not applied when querying vFolder by using `query_accessible_vfolders()`.

fix: extra vfolder access restriction not applied

---

changes/775.fix.md
src/ai/backend/client/output/formatters.py
src/ai/backend/manager/models/agent.py

Managers try to resolve Agent's fields, whose status is not `ALIVE`.
Return `None` value before managers fetch RPC call to dead agents.

fix: skip resolving fields from dead agent

---

src/ai/backend/manager/api/vfolder.py
src/ai/backend/manager/models/vfolder.py

This PR fixes extra vFolder conditions not being applied properly when querying vFolders owned by myself. Follow-up of #766.

fix: vfolder permission condition not applied properly

---

changes/778.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/kernel.py
src/ai/backend/agent/kernel.py
src/ai/backend/agent/kubernetes/kernel.py
src/ai/backend/agent/server.py
src/ai/backend/manager/api/session.py
src/ai/backend/manager/registry.py

Unpack tar file before downloading the Docker session's selected file If you want to select Docker session's file, It'll be downloaded after packing to tar archive.
So, I unpacked tar archived the selected Docker session file, and then processed to download it.
close https://github.com/lablup/backend.ai/issues/774

Fix missing tar-unpack before downloading single file from container

---

.github/workflows/add-to-project.yml

close #777 
Added actions that are automatically added to the project when an issue is created.
A github token is required for permission, so you need to add a secret named `ADD_TO_PROJECT_PAT` to the repo settings to use it.

ci: add-to-project workflow

---

.github/workflows/default.yml
scripts/extract-release-changelog.py

This PR fixes release changelog containing invalid (or empty) previous tag due to `action/checkout` action fetching only current tag info.

fix: invalid previous tag added on changelog

---

changes/789.fix
src/ai/backend/storage/xfs/__init__.py

For a virtual folder which is created on XFS with quota support, the call to `get_uasge` is failing since the `inode_size` is a humanized string (e.g.: `1.6k`) while `VFolderUsage` requires integers for both of its parameters:
```shell
ERROR Error handling request
File "/home/bai/.pyenv/versions/bai-22.09-storage-proxy/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
resp = await request_handler(request)
File "/home/bai/.pyenv/versions/bai-22.09-storage-proxy/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/home/bai/.pyenv/versions/bai-22.09-storage-proxy/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request) …
```

fix(xfs): error in getting vfolder inode usage

---

.github/workflows/label.yml

The sync-labels option of the labeler, which syncs the current label according to this change, is not working properly.
It was an issue raised 2 months ago, but it is an issue that is not being dealt with and left unattended.
https://github.com/actions/labeler/issues/404
A branch with a bug-fixed version exists and changes to that version
https://github.com/actions/labeler/pull/405

ci: Fix sync-labels option error

---

changes/801.misc.md
docs/dev/daily-workflows.rst
pants.toml
pyproject.toml
python-kernel.lock
python.lock
tools/flake8.lock
tools/pytest.lock

Bump base Python version from 3.10.7 to 3.10.8 to resolve potential errors.
* Bump the base Python version from 3.10.7 to 3.10.8 to avoid spurious tracebacks from [asyncio](https://docs.python.org/release/3.10.8/library/asyncio.html#module-asyncio) when default executor cleanup is delayed until after the event loop is closed.
* NOTE: Developers should install Python 3.10.8 by their own (e.g., using pyenv) as Pants itself does not auto-install Python runtimes.
This PR resolves #798

setup: Update the base Python from 3.10.7 to 3.10.8

---

changes/821.fix.md
src/ai/backend/manager/api/session.py

* macOS (Apple Silicon)
* Backend.AI version: 22.09.2
* Response of GET /session/{session_name}/commit API has typo
* Issue described in [here](https://github.com/lablup/backend.ai/issues/795)
* Change response message: `stats` -> `status`
* This will help resolve the confusion of getting a "stats" key with a value that represents status.

fix: typo on session commit status API response

---

.github/workflows/default.yml

Like the previously modified #659, the default workflow detects when the label is changed and operates again.
Otherwise, skip:ci will not be recognized when labeling after pr is created.

ci: Relabeling should trigger the default workflow to apply `skip:ci` semantics

---

backend.ai
changes/819.misc
py

When I launch the servers (manager, agent, storage-proxy, webserver) with the `systemd` services, I was unable to terminate the server processes via `systemctl stop` command. This is because the `py` and `backend.ai` spawn a child subshell to execute the python server modules, so the scripts, not the server modules, are the ones that receive the termination signal. Eventually, the script processes are terminated after `TimeoutStopSec`, but the python server processes have been kept alive by changing the parent process to the `init`.
To avoid this kind of inconvenience, I prefixed the `exec` command in `py` and `backend.ai` scripts.

misc: do not create subshell in executing `py` and `backend.ai` scripts

---

pants.toml

refs https://github.com/pantsbuild/pants/blob/main/src/python/pants/notes/2.13.x.md
There is nothing to do for most developers as Pants will automatically re-bootstrap itself, _except_ when you're on Linux aarch64 setups. In that case, you need to manually do:
```console
$ cd tools/pants-src
$ git fetch --tags
$ git checkout release_2.13.1rc2
$ cd ../..
$ ./pants-local version
```

setup: Upgrade pants from 2.13.0rc0 to 2.13.1rc2

---

changes/841.misc.md
configs/agent/halfstack.toml
configs/manager/halfstack.toml
configs/manager/sample.toml
scripts/install-dev.sh
src/ai/backend/manager/config.py

When installing two or more agents/dev-setups in a single node, we need to be able to customize `ipc-base-path` of the manager and agent.
This PR also changes the manager's default `ipc-base-path` from `/tmp/backend.ai/manager/ipc` to `/tmp/backend.ai/ipc` for consistency.  As long as the manager instances are gracefully restarted upon updates, there should be no problems as the only content in the manager's IPC directory is the unix socket for relaying log records.
refs #496 -- Note that this PR does not implement the full requirements of #496 but only 
covers the update of `install-dev.sh` while assuming that the Docker daemon is separated.
It's a follow-up to lablup/backend.ai-agent#347.

setup: Add `--ipc-base-path` option to install-dev.sh

---

.gitignore
pants

refs #690
After merging this PR, it is recommended to run:
```console
$ rm -rf ~/.cache/pants/*
```
There is no difference to the daily workflows, but it allows using `.pants.bootstrap` file to override some pants configurations locally without modifying `pants.toml`, such as:
```
export PANTS_PROCESS_EXECUTION_LOCAL_PARALLELISM=16
```

repo: Upgrade ./pants script

---

docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po

@lizable, Added korean translation `vfolders.po` in #816 
I translated [vfloders page](https://github.com/lablup/backend.ai/blob/main/docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po).

docs: translated to korean manager/user-api/vfolders.po 

---

changes/845.fix.md
src/ai/backend/cli/types.py

close #844 
When sys.exit() receives a non-Int value as an argument, it is judged as a message and printed.
So, I modified the argument to receive enum.IntEnum.
refs. https://docs.python.org/3/library/sys.html#sys.exit

fix: Change `ExitCode` into `IntEnum` to remove unintended console output upon errorneous exits

---

.github/workflows/sbom.yml

There are actions that are officially provided by CycloneDX, so we used the workflow.
In the case of the v1 version or v1.0.0 version specified in the readme, it is not compatible with the latest CycloneDX, so v1.0.1 version was applied.
https://github.com/CycloneDX/gh-python-generate-sbom/tree/v1.0.1
close #739

ci: SBOM report manual trigger workflow

---

changes/840.fix.md
src/ai/backend/manager/api/resource.py

this resolves #839 
Modify calculating monthly stats logic so that number of sessions and resource usage is calculated appropriately during all session execution times.

fix: logical errors in calculating monthly stats

---

changes/850.fix.md
src/ai/backend/web/config.py

This PR fixes string parser option to prevent tokenizing WebUI plugin string into characters.
Example:
```ini
[plugin]
page = 't,e,s,t,-,p,l,u,g,i,n,,"
```

fix: webserver plugin string is broken

---

changes/853.fix.md
src/ai/backend/manager/cli/dbschema.py

This PR fixes `backend.ai mgr schema oneshot` command not creating `alembic_version` table properly after #702 is merged.

fix: oneshot command not creating `alembic_version` table

---

changes/849.fix.md
python.lock
requirements.txt
src/ai/backend/agent/agent.py
src/ai/backend/agent/resources.py
src/ai/backend/common/msgpack.py
src/ai/backend/common/types.py
src/ai/backend/manager/registry.py
tests/common/test_msgpack.py

Taken from https://github.com/lablup/backend.ai/pull/491/commits/39ab5756717af673570ba81002a41df2b41948ce (part of #491)
This PR improves it further by introducing [msgpack extended types](https://github.com/msgpack/msgpack-python#extended-types), allowing seamless serialization of UUIDs, enums, datetimes, Path, etc.

fix: Serialization failures when returning kernel creation results

---

changes/856.fix.md
src/ai/backend/manager/models/base.py

ResourceSlotColumn column type can get `None` value in `process_bind_param` and `process_result_value` methods.
Let those methods check `None` early and return.

Fix ResourceSlotColumn to check None type early

---

changes/882.fix.md
src/ai/backend/manager/models/gql.py

resolves: #879 
Get mutation name from `ResolveInfo.field_name` rather from `ResolveInfo.path[0]`, and this enable to use alias.
https://github.com/graphql-python/graphql-core/blob/main/src/graphql/type/definition.py#L613-L635
`ResolveInfo` has `field_name.

fix: Get field_name from ResolveInfo in gql middleware

---

src/ai/backend/runner/BUILD

This PR support for modifying typo in runner.BUILD dependency map table.

fix: Typo in runner BUILD file for Apple intel mac

---

.github/workflows/coverage.yml
.github/workflows/default.yml
.github/workflows/sbom.yml

- GitHub Action Runner `ubuntu-22.04` is now the default for
`ubuntu-latest`, and it only comes with Python 3.10.6 as the
pre-installed one.
ref) https://github.com/actions/runner-images/blob/ubuntu22/20221119.2/images/linux/Ubuntu2204-Readme.md

ci: Explicitly install Python 3.9 for Pants

---

scripts/install-dev.sh

PR #790 made error in install script.
This pr prevents from JSON parsing error when setting `allowed_vfolder_host` values in `domains`, `groups` and `users` tables

fix: Set correct vfolder host value in install script

---

changes/901.fix
src/ai/backend/agent/alloc_map.py

This PR fixes a bug which raises `zeroDivisionError: integer division or modulo by zero` when creating a compute session with CPU and memory only for a single numa node system. I'm not sure this is an optimal solution, so please feel free to update this PR.

fix: fallback to legacy allocation logic when there is no devices in allocation hint

---

changes/889.fix.md
src/ai/backend/manager/api/manager.py

This PR support that manager could be freezed.
resolve #888

fix: Request failure when freezing manager

---

changes/905.fix.md
src/ai/backend/agent/config.py

fix: Invalid default value of the agent's affinity-policy config option

---

src/ai/backend/common/web/session/__init__.py
src/ai/backend/common/web/session/redis_storage.py

This PR changes cookie name to legacy one to provide legacy web socket proxy support.
Related PR: #899

fix: rollback session cookie name to keep legacy support

---

changes/907.fix.md
src/ai/backend/manager/registry.py

fix: Mismatch of kernel and container hostnames in the host networking mode

---

changes/908.fix.md
src/ai/backend/agent/docker/intrinsic.py
src/ai/backend/agent/kubernetes/intrinsic.py

- The main memory can be treated as a continuous bulk, regardless of
the even-distribution policy or NUMA nodes.
A follow-up fix to #491

fix: Use FILL allocation strategy for the memory

---

changes/909.fix.md
src/ai/backend/agent/affinity_map.py
src/ai/backend/agent/alloc_map.py
tests/agent/test_affinity_map.py

When allocating n-th step compute devices using the allocation result
of the (n-1)-th step compute devices, we need to include the n-th step
compute devices when filtering them with the zero distance to (n-1)-th
step compute devices allocated in the prior step.
This is a follow-up fix to #491.

hotfix: Rewrite NUMA-aware allocation to support 3 or more NUMA nodes

---

pants.toml
tools/pants-plugins.lock

This would resolve the interpreter mismatch errors in some setups like macosx-arm64 platforms with Python 3.7 or 3.8 installed via pyenv.

setup: Restrict the pants-plugin resolve's Python compatibility to 3.9.x

---

docs/dev/daily-workflows.rst
pants
scripts/install-dev.sh
scripts/pre-commit

- Now we can use the same `./pants` in linux-aarch64 platforms
- doc: No longer `./pants-local`
- fix: Prevent duplication of pre-commit hook when retrying installs

setup: Unify `./pants` for linux-aarch64 platforms

---

changes/917.fix.md
src/ai/backend/client/cli/pretty.py

- "heavy" check/ballot marks -> plain check/ballot marks
✔, ✘ -> ✓, ✗
- Pants CLI and GitHub CLI are using the plain symbols.
- Many platforms treats heavy checkmarks as emoji icons and renders very differently when copy-and-pasted into browsers and office apps.
Windows Edge:
macOS Chrome:

fix: Use CLI unicode symbols that appear more consistently

---

changes/920.fix.md
src/ai/backend/manager/api/vfolder.py

fix: When deleting a vfolder and updating its status, use ID instead of name.

---

changes/925.fix.md
src/ai/backend/client/cli/session.py

- Use `click.echo()` to ensure flushing and stripping ANSI escape
sequences for redirected outputs.
- Use `json.dumps(..., indent=None)` to ensure JSON-compatible
single-line output.

ehn: Improve scriptability of `session events` CLI command

---

.github/workflows/default.yml

If you commit while all actions have not been executed, they will be executed simultaneously with new actions.
In this case, it cancels the previous actions action.
I think it will help reduce the cost by reducing the execution time of actions.

ci: cancel previously executed duplicated workflow

---

changes/947.feature
src/ai/backend/web/server.py

Remove the `Server` response header from Webserver, which could potentially provide attackers with the detailed server software version.

feat: remove Webserver's "Server" response header

---

scripts/install-dev.sh

This PR makes install-dev.sh install latest release of Python 3.9  when running on codespaces.

fix: codespaces not bootstrapped 

---

changes/949.feature.md
src/ai/backend/manager/api/resource.py

- Add a `session_id` column.
- Add a `cluster_mode` column to get to know if the corresponding session is single-node or multi-node.
related PR: https://github.com/lablup/backend.ai-control-panel/pull/464

feat: add `session_id` and `cluster_mode` column to `get_container_stats_for_period` API

---

changes/941.feature.md
src/ai/backend/client/cli/admin/scaling_group.py
src/ai/backend/client/func/scaling_group.py
src/ai/backend/client/output/fields.py
src/ai/backend/manager/models/scaling_group.py

follows #838 
This PR enables CRUD the `use_host_network` option of scaling group in the client-py.
related PR: https://github.com/lablup/backend.ai-control-panel/pull/459

feat: corresponds to client-py to CRUD scaling group's `use_host_network` option

---

changes/954.fix.md
src/ai/backend/manager/api/session_template.py

In order to avoid the following attribute error during converting from string to hex, the `resp` setting position was changed.

fix: set `resp` after setting `user_uuid` to avoid AttributeError

---

src/ai/backend/client/cli/vfolder.py

Modified the help message printed when the following are ran:
`./backend.ai vfolder upload --help`
`./backend.ai vfolder download --help`
(This is my first PR!)
fixes #883

doc: Update the help msg of  `vfolder upload -b`

---

src/ai/backend/manager/cli/__main__.py

A manager command seems not used alone (always used with arguments).
This PR prevents the manager command invocation without the arguments and makes the command print the default help message.
resolves: #969

fix: Show up the manager cli help when called without sub-command

---

changes/986.fix.md
src/ai/backend/agent/docker/agent.py

This PR lets the agent skip initialization of socket-relay container which is not working with Docker Desktop for Mac with the virtiofs file-sharing driver. (part of #976)
Ultimately we need to migrate VSOCK to avoid sharing paths of UNIX sockets between containers and the macOS host, but for now, we can simply temporarily disable the socket-relay because we don't have other places that use the socket-relay container actually on macOS setups.

fix: Workaround infinite restarting of UNIX socket-relay on Docker Desktop for Mac with virtiofs

---

changes/993.fix.md
src/ai/backend/agent/docker/agent.py

This PR resolves bind mount error when container starts on Docker for mac + virtioFS (#986)

bugfix: container does not start on macos after #986

---

src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/kubernetes/agent.py
src/ai/backend/agent/server.py
src/ai/backend/manager/registry.py

Overlay network creation is now handled by the manager.
For the k8s agent backend, it won't support our multi-node multi-container sessions because it is impossible for two different k8s clusters to share a single overlay network.

refactor: Remove no longer used codes

---

changes/995.fix.md
src/ai/backend/agent/docker/agent.py

This PR fixes issue `mpirun` failing to work when multiple host is provided on multi-node session.

fix: `mpirun` not working occassionally on muti-node session

---

.github/workflows/default.yml
changes/997.misc.md
docs/dev/daily-workflows.rst
pants.toml
pyproject.toml
python-kernel.lock
python.lock
src/ai/backend/agent/server.py
src/ai/backend/agent/utils.py
tools/black.lock
tools/flake8.lock
tools/isort.lock
tools/pants-plugins.lock
tools/pytest.lock
tools/towncrier.lock

Bump base Python version from 3.10.8 to 3.10.9 to resolve potential errors.
NOTE: Developers should install Python 3.10.9 by their own (e.g., using pyenv) as Pants itself does not auto-install Python runtimes.
```console
$ cd ~/.pyenv && git pull
$ cd ~/.pyenv/python-build && git pull
$ cd ~/.pyenv/pyenv-virtualenv && git pull
> # or, if you have installed "pyenv-update" plugin, simply run `pyenv update`
$ CONFIGURE_OPTS='--enable-optimizations' pyenv install 3.10.9
```
You may also need to update your Visual Studio Code, Vim, NeoVim configurations such as `.vim/coc-settings.json` and others. ([reference](https://docs.backend.ai/en/latest/dev/daily-workflows.html#using-ides-and-editors))

update: base python version from 3.10.8 to 3.10.9

---

src/ai/backend/runner/fantompass.py

Mark with "# pants: no-infer-dep" comment
The python 1 line code is indirect dependency of other explicit dependencies

refactor: mark with "# pants: no-infer-dep" comment

---

changes/1007.fix.md
src/ai/backend/client/func/agent.py
src/ai/backend/client/func/keypair.py
src/ai/backend/client/func/session.py
src/ai/backend/client/func/storage.py
src/ai/backend/client/func/user.py
src/ai/backend/client/func/vfolder.py
src/ai/backend/client/pagination.py

Remove unused loop in CLI `generate_paginated_results` function, remove some vars of the function and rename it

fix: Remove unused loop in cli function and rename it

---

changes/1006.feature.md
src/ai/backend/agent/docker/intrinsic.py

This is the following PR of #1000
This PR makes measuring container stats supports cgroup v2.
Like #1000, Following Backend.AI configuration is needed to test:
```toml
[container]
stats-type = "cgroup"
[debug]
log-stats = true
```

feat: Support cgroup v2 for container stat measures

---

changes/1005.feature.md
src/ai/backend/agent/utils.py
src/ai/backend/common/cgroup.py

Instead of using pids cgroup controller to list all PIDs in the given container, get the container ID of the given PID directly from `/proc/PID/cgroup`. 
cc #865

feat: Stop using pids cgroup controller

---

BUILD
changes/1010.deps.md
docker/agent/Dockerfile
docker/manager/Dockerfile
python.lock
requirements.txt
scripts/install-dev.sh
scripts/storage-proxy-spawn-ceph-clusters/install_storage_proxy.sh
src/ai/backend/agent/README.k8s.md
src/ai/backend/agent/README.md
src/ai/backend/agent/agent.py
src/ai/backend/manager/README.md
src/ai/backend/manager/registry.py
tests/manager/test_registry.py

This PR removes dependency to external module `python-snappy` and refactors compression/decompression steps to use zlib.

deps: replace snappy with zlib

---

changes/992.feature.md
src/ai/backend/agent/vendor/linux.py

This PR is part of #865 
The source of the number of available cores for the docker daemon now changed.
**Before**
- In cgroup v1, `/sys/fs/cgroup/cpuset/docker/cpuset.cpus`
**After**
- In cgroup v2, `/sys/fs/cgroup/system.slice/docker.service/cpuset.cpus.effective` 
- In cgroup v1, `/sys/fs/cgroup/cpuset/docker/cpuset.effective_cpus`
**Reason**
- In cgroup v2, `cpuset.cpus` represents the number of requested cores, not the number of available cores. However, it may be ignored by the parent cgroup and the actual number of available cores may be less than `cpuset.cpus`.
- But `cpuset.effective_cpus` and `cpuset.cpus.effective` represents the actual number of available cores, considering these constraints, so it is reasonable to use them.
- In cgroup v1, `cpuset.cpus` represents the number …

feat: Support cgroup v2 on get_available_cores()

---

.github/workflows/auto-label.yml

If the label of linkingissue is empty in version 1.2.0, there was an error and we upgraded it to version 1.3.0 that solved the problem.

ci: Upgrade auto-label-in-issue action

---

changes/1021.feature.md
pants.toml
tools/mypy.lock

resolves #1020
- New Release Versioning Scheme (x.y.z)
- Up to 40% faster than mypy 0.991
- Warn About Variables Used Before Definition [used-before-def]
- Detect Possibly Undefined Variables (Experimental)
- **Support the “Self” Type**
- Support ParamSpec in Type Aliases
- ParamSpec and Generic Self Types No Longer Experimental
See details [https://mypy-lang.blogspot.com/2023/02/mypy-10-released.html](https://mypy-lang.blogspot.com/2023/02/mypy-10-released.html)

setup: Upgrade mypy to 1.0.0

---

src/ai/backend/agent/agent.py
src/ai/backend/agent/kubernetes/agent.py
src/ai/backend/agent/resources.py
src/ai/backend/agent/server.py
src/ai/backend/agent/stats.py
src/ai/backend/agent/utils.py
src/ai/backend/agent/watcher.py
src/ai/backend/client/request.py
src/ai/backend/common/bgtask.py
src/ai/backend/common/events.py
src/ai/backend/manager/idle.py
src/ai/backend/manager/models/domain.py
src/ai/backend/manager/models/group.py
src/ai/backend/manager/models/user.py
src/ai/backend/manager/registry.py
src/ai/backend/storage/server.py

While working on background task, I found logs with `ai.backend.manager.background` as name, but there is no such module in Backend.AI. It turns out that it was moved to `ai.backend.common.bgtask` in #306, but logger name was hardcoded as literal and not changed.
It is idiomatic to use `__name__` to prevent this. While fixing the logger name of background task, I went through all calls to `logging.getLogger` and changed literals to `__name__`. Some places were using `__file__` and I fixed them too.

fix: Use logging.getLogger(__name__)

---

changes/1029.fix.md
src/ai/backend/manager/registry.py

Session concurrency has been calculated depending on the number of kernels, not sessions.
Let's calculate concurrency by the number of sessions.

fix: update concurrency by number of session rather kernel

---

changes/1038.feature
src/ai/backend/agent/docker/agent.py

We recently added a feature to update SSH keypair with GUI by #1032 and lablup/backend.ai-webui#1578. However, user-uploaded private key is written on `/home/work/id_container`, but not `/home/work/.ssh/id_rsa`, so user always specify the `id_container` file to issue a command that uses SSH private key.
This PR adds `~/.ssh/id_rsa` in addition to `id_container`, so ease users not to specify the SSH private key always, for example, in cloning a GitHub private repository from terminal.

feat: write `.ssh/id_rsa` in container start

---

changes/1040.fix
src/ai/backend/storage/vfs/__init__.py

Resolves https://github.com/lablup/giftbox/issues/74.

fix: do not raise error in deleting a vfolder when intermediate parent directories are not exist

---

src/ai/backend/manager/api/resource.py
src/ai/backend/manager/models/vfolder.py

There are some select statements which have a wrong condition.
This warning message occurs when we query such statments.
This PR remove all cartesian products, by correcting select statement conditions.

fix: correct query condition of select statments to remove cartesian products

---

changes/987.feature.md
scripts/install-dev.sh

For example, below command is not working with fish shell because [`unset` command is not supported in fish](https://stackoverflow.com/questions/30703860/how-do-i-unset-a-variable-in-the-fish-shell).
```
$ source ./env-local-admin-session.sh
```
This PR fixes this by using `set -e` command instead of `unset` when user works in fish.

feat: Add fish shell support to `install-dev.sh` script

---

changes/1033.feature.md
src/ai/backend/client/cli/pretty.py
src/ai/backend/client/cli/vfolder.py
src/ai/backend/manager/api/vfolder.py

Spinners are intended to be used in long background task which doesn't provide progress.
(If the background task can provide the progress, we can show the progress more visually by using like tqdm)
The use case is `vfolder clone`
- Reporting the progress from storage-proxy is not supported yet.
- Storage-proxy has various backends (VFS, PureStorage, CephFS, ..), and most of the storage backend operation doesn't provide the progress feature.
- Making our own operation on each backend for reporting the progress is not easy.
- Currently, if there is a large amount of files that need to be cloned, it will seem as if they are stuck on the client.
Tested on VFS.
refs: #898

feat: Spinner on client

---

src/ai/backend/client/cli/admin/session.py
src/ai/backend/client/cli/session.py

Since `Fieldspec` uses `alt_name` for key, we need to get the value by `session_id` not `id`.
How to test
```
./backend.ai admin session info <session_id>
```

fix: correct session `Fieldspec` of CLI

---

src/ai/backend/manager/api/resource.py

Update query statement for checking resource occupancy of kernel Since kernel table's `scaling_group` column is empty and has been migrated to session table.

fix: update query statement to check occupying resource from session related kernels

---

changes/1049.feature.md
src/ai/backend/client/cli/admin/image.py
src/ai/backend/client/cli/pretty.py
src/ai/backend/client/cli/vfolder.py

This PR includes a wrapper `ProgressViewer` that supports both spinner and tqdm for the progress of background tasks.
It always starts with the spinner and you can switch it to tqdm mode with the `ProgressViewer.to_tqdm()` method, mostly when you handle the `bgtask_update` event from SSE messages.
It could be applied to any background tasks regardless the backend operation supports the tracking feature. Currently applied on `image rescan` and `vfolder clone`.

feat: ProgressViewer on client

---

.gitignore
changes/1061.feature.md
scripts/install-dev.sh

Make `scripts/install-dev.sh` to preserve the full etcd content as `./dev.etcd.installed.json`
so that it could be used to easily restore the etcd container corrupted during development.

setup: Preserve the etcd config made by the installer

---

src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/vendor/linux.py

Docker added cgroup v2 support(#865) in [20.10](https://docs.docker.com/engine/release-notes/20.10/) (search for "Support cgroup2"). To support old Docker versions like 19.03, assume cgroup v1 if CgroupVersion key is absent.

fix: Assume cgroup v1 if CgroupVersion key is absent

---

CHANGELOG.md

#1078 Correct the changelog that was changed in the corresponding pr but was written incorrectly before.

docs: delete unnecessary package names

---

changes/template.md

close #1077
I removed versiondata.name from template from template.md because towncrier is operating based on the package, so towncrier fails when I modify the pakcage value.

ci: remove invalid package name from changlog

---

src/ai/backend/manager/api/session.py

This fixes session.py's `/start-service` API failing to execute due to invalid reference on table column.

fix: `/start-service` API failing

---

src/ai/backend/manager/models/alembic/versions/3efd66393bd0_add_totp_activated_at_column.py
src/ai/backend/manager/models/user.py

This PR adds `users.totp_created_at` column, which should be automatically set when user opts in to 2FA.

feat: add `users.totp_activated_at` column

---

.github/workflows/add-to-project.yml

`add-to-project` to automatically add issues to the integration board when they are generated.

ci: register on integrated project board

---

changes/1103.fix.md
src/ai/backend/client/cli/session.py

```
$ ./backend.ai watch mysession
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/Users/jopemachine/Desktop/backend.ai/src/ai/backend/cli/__main__.py", line 10, in <module>
main(max_content_width=shutil.get_terminal_size().columns - 2)
File "/Users/jopemachine/Desktop/backend.ai/dist/export/python/virtualenvs/python-default/3.11.2/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/jopemachine/Desktop/backend.ai/src/ai/backend/cli/extensions.py", line 25, in main
super().main(
File "/Users/jopemachine/Desktop/backend.ai/dist/export/python/virtualenvs/python-default/3.11.2/lib/python3.11/site-packages/click/ …
```

fix: Regression of `session watch` command

---

changes/1099.fix.md
src/ai/backend/client/cli/admin/license.py
src/ai/backend/client/cli/admin/scaling_group.py
src/ai/backend/client/cli/app.py
src/ai/backend/client/cli/dotfile.py
src/ai/backend/client/cli/model.py
src/ai/backend/client/cli/run.py
src/ai/backend/client/cli/session.py
src/ai/backend/client/cli/session_template.py
src/ai/backend/client/cli/vfolder.py
src/ai/backend/client/config.py
src/ai/backend/client/func/admin.py
src/ai/backend/client/func/resource.py
src/ai/backend/client/func/session.py
src/ai/backend/client/func/storage.py
src/ai/backend/client/request.py
src/ai/backend/client/session.py
src/ai/backend/common/events.py
src/ai/backend/common/logging.py
src/ai/backend/manager/cli/__main__.py

Fix typos and add proper whitespace in the comment and CLI help strings.

fix: Fix typos and add proper whitespace to the comments and CLI help strings

---

src/ai/backend/manager/api/session.py
src/ai/backend/manager/registry.py

related to #1058 
manager's registry has `kernel_creation_tracker` field and it is set by manager's event handler and set in `_create_kernels_in_one_agent` method.
`InvalidStateError` can be raised since `kernel_creation_tracker` is set by two independent methods.
This PR let check the tracker is done.

fix: Check kernel creation tracker cancellation before set result

---

.github/workflows/default.yml

Modify failed workflow because deploy-to-pypi has an invalid job name from needs.

ci: Correct incorrectly stated job name

---

.github/workflows/alembic-head-check.yml
scripts/check-multiple-alembic-heads.py

- This is much faster and does not require importing/installing the
source packages.
This resolves #1106 in the other way.

ci: Rewrite the alembic multi-head check workflow to do static analysis

---

changes/916.feature.md
src/ai/backend/accelerator/cuda_mock/plugin.py
src/ai/backend/accelerator/cuda_open/plugin.py
src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/docker/intrinsic.py
src/ai/backend/agent/docker/kernel.py
src/ai/backend/agent/kubernetes/intrinsic.py
src/ai/backend/agent/resources.py
src/ai/backend/agent/stats.py

This PR support that agent gather process list and process resource usage.
1. Collect process's cpu, mem, I/O usage stats using proc filesystem or 3rd party module.
2. Timer retrieve stats.
3. exclude to collect process stats from root user.
resolve #696

feat: agent gather process stats in container

---

src/ai/backend/agent/agent.py
src/ai/backend/agent/server.py
src/ai/backend/common/events.py
src/ai/backend/manager/registry.py

kernel_creation_id is now unused so I removed it.

refactor: Remove no longer required `kernel_creation_id`

---

changes/1067.feature.md
src/ai/backend/runner/entrypoint.sh

Fixes #1053.
Auto-start SSH agent and register the ssh key if it doesn't have a passphrase upon session startup in `entrypoint.sh`.
I tested the changes manually.
Here are the tested kernels' logs.
`ssh-add` fails without pending.
This PR makes `entrypoint.sh` execute `ssh-add` through a new session by `setsid` and pass the *null device* to the stdin of the new session.
Then `ssh-add` try to read the passphrase from the stdin or tty device, but because the null device discards the stdin and there is no available tty device in the session, `ssh-add` fails promptly without entering a pending state as you can see in the log below.
```
Kernel started at: 2023-02-28T02:42:04+00:00
Setting up uid and gid: 501:20
chown: cannot access '/opt/kernel/agent.sock': No such file or directory
Agent pid …
```

feat: Auto-start SSH agent upon session startup

---

.gitignore
scripts/delete-dev.sh
tools/pants-local

Support for `.pants.env` has been stopped after 24e5a1f.
Therefore, this PR removes several scripts relate to `.pants.env`.

fix: Remove script snippets relate to `.pants.env`

---

changes/1141.fix.md
src/ai/backend/kernel/app/__init__.py
src/ai/backend/kernel/base.py
src/ai/backend/kernel/c/__init__.py
src/ai/backend/kernel/cpp/__init__.py
src/ai/backend/kernel/git/__init__.py
src/ai/backend/kernel/golang/__init__.py
src/ai/backend/kernel/haskell/__init__.py
src/ai/backend/kernel/java/__init__.py
src/ai/backend/kernel/julia/__init__.py
src/ai/backend/kernel/lua/__init__.py
src/ai/backend/kernel/nodejs/__init__.py
src/ai/backend/kernel/octave/__init__.py
src/ai/backend/kernel/php/__init__.py
src/ai/backend/kernel/python/__init__.py
src/ai/backend/kernel/r/__init__.py
src/ai/backend/kernel/rust/__init__.py
src/ai/backend/kernel/scheme/__init__.py
src/ai/backend/kernel/vendor/h2o/__init__.py
src/ai/backend/runner/entrypoint.sh

Fixes https://github.com/lablup/giftbox/issues/216.
When `$USER_ID` is not 0 (root account), `ssh-agent` must run through the user account (`/home/work`).
This PR accomplish this by using `su-exec`.
Tested manually.

fix: `ssh-add` not working due to missing env-var inheritance and wrong process ownership

---

changes/1149.feature.md
src/ai/backend/manager/models/session.py

resolves https://github.com/lablup/giftbox/issues/157
related PR: https://github.com/lablup/backend.ai-control-panel/pull/565
Added the `user_name` field to the `ComputeSession` class to show the user name in the session list.

feat: add `user_name` to `ComputeSession` query field

---

changes/1159.feature.md
configs/agent/sample.toml
src/ai/backend/agent/agent.py
src/ai/backend/agent/config.py
src/ai/backend/agent/server.py

Let's limit the maximum concurrency of kernel creation tasks per each `create_kernels()` RPC call.
If there are too many containers to create at the same time, the container runtime (Docker) may fail with "context deadline exceeded" under certain conditions.

feat: Throttle the max concurrency of per-`create_kernels()` RPC call

---

changes/1161.feature.md
configs/webserver/sample.conf
src/ai/backend/web/config.py
src/ai/backend/web/templates/config.toml.j2

- Add `force_2FA` option to compose the corresponding WebUI config
- resolves [Add an option to enforce users 2FA#261](https://github.com/lablup/giftbox/issues/261)
- related PR: https://github.com/lablup/backend.ai-webui/pull/1628

feat: add `force_2FA` config on webserver

---

src/ai/backend/accelerator/cuda_mock/plugin.py
src/ai/backend/accelerator/cuda_open/plugin.py
src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/intrinsic.py
src/ai/backend/agent/kubernetes/intrinsic.py
src/ai/backend/common/types.py
src/ai/backend/manager/api/etcd.py

This resolves #1156. Ref #1153

feat: store accelerator metadata on redis

---

.github/workflows/default.yml

An error occurred due to duplicated actions being executed while merging multiple jobs into one, so fix it.

hotfix(ci): eliminate redundant action blocks added when merging jobs

---

changes/1167.feature.md
src/ai/backend/manager/api/resource.py
src/ai/backend/manager/models/session.py

- Add `full_name` instead of `username` to `ComputeSession`.
- Add `full_name` to `get_container_stats_for_period`.
- Admins have struggled with recognizing the user using the email. But for now, by this PR, admins can recognize the user easily.
- related PR: https://github.com/lablup/backend.ai-control-panel/pull/576
- follows https://github.com/lablup/backend.ai/pull/1149

feat: use `full_name` instead of `username` on certain queries

---

changes/1178.feature.md
configs/webserver/sample.conf
docs/install/install-from-package/install-webserver.rst
src/ai/backend/web/config.py
src/ai/backend/web/templates/config.toml.j2

To hide/show `Try preferred port` on the app dialog (WebUI), I added `allow_preferred_port` option on webserver
related: https://github.com/lablup/giftbox/issues/268

feat: add `allow_preferred_port` config on webserver

---

src/ai/backend/manager/models/session.py
src/ai/backend/manager/scheduler/dispatcher.py

After #576 , `status_changed` column is removed but session cancellation in scheduler still fetch an update statement to update `status_changed` column and wrong `status_history` value.

fix: pending timeout cancellation failing for PENDING session

---

changes/1182.feature.md
src/ai/backend/client/cli/admin/vfolder.py
src/ai/backend/client/func/vfolder.py
src/ai/backend/manager/api/vfolder.py

This PR partially resolves #408.
FYI: 
- Support changing the `owner` of vfolder, not `creator`.
- Support only users who can access the same storage host that vfolder is located. (It will be expanded in phase 2)
- Support changing `user` type of vfolder, not `group(project)` type. (This also will be implemented in phase 2)

feat: add API for changing vfolder ownership

---

changes/1100.fix.md
src/ai/backend/agent/docker/kernel.py
src/ai/backend/agent/kubernetes/kernel.py

Tested manually.
Tested commands:
```
$ ./backend.ai session ls 6b4ea30d-cd4b-42bc-8307-dcb9e7746228
$ ./backend.ai session ls 6b4ea30d-cd4b-42bc-8307-dcb9e7746228 /home/work
$ ./backend.ai session ls 6b4ea30d-cd4b-42bc-8307-dcb9e7746228 /home/work/.ssh
```
Above commands failed with the below error.
```
2023-02-24 14:09:35.509 ERROR ai.backend.manager.api.session [17278] LIST_FILES: exception
File "/Users/jopemachine/Desktop/backend.ai/src/ai/backend/manager/api/session.py", line 2414, in list_files
result = await root_ctx.registry.list_files(session, path)
^^^^^^^^^^^^^^^^^
File "/Users/jopemachine/Desktop/backend.ai/src/ai/backend/manager/registry.py", line 2201, in list_files
async with handle_session_exception(self.db, "list_files", session.id): …
```

fix: `session ls` not working

---

changes/1186.fix.md
src/ai/backend/manager/api/vfolder.py
src/ai/backend/runner/jail.ubuntu16.04.x86_64.bin

Related PR: #1182.
This PR resolves the logical error that can possibly occur during changing `ownership` of vfolder.
That is, deleting row(s) in `vfolder_invitations` and `vfolder_permissions` when the new owner of the vfolder and invitee are the same user.
Assume that User A created vfolder `foo` and shared it with User B with certain permissions.
After sharing, for some reason, the ownership of vfolder `foo` is changed from User A to User B.
Without removing "sharing log"(stored as a row in `vfolder_invitations` and `vfolder_permissions` table) when owner and invitee are identical, the shared vfolder remains and brings certain errors such as causing exceptions on deleting vfolder.
Therefore, I added two deleting transactions on two tables respectively that I mentioned above in the …

fix: delete permissions and invitation rows of transferred vFolder

---

changes/1185.feature.md
src/ai/backend/manager/api/session.py
src/ai/backend/manager/idle.py
src/ai/backend/manager/models/session.py

follow up #1160 
Update utilization idle checker's policy
- If the time window is infinite or zero, expire time is always `None`
- if the kernel's running time is shorter than initial grace period, expire time is  (initial grace period + time window size - (now - kernel creation time))
```
if now - kernel["created_at"] <= self.initial_grace_period + window_size)
-> expire_time = self.initial_grace_period + window_size - (now - kernel["created_at"])
```
- else, expire time is `None`.
Plus, the `utilization_extra` key of response has data like below
```
{
<RESOURCE_NAME_1> : [average_utilization, threshold],
<RESOURCE_NAME_2> : [average_utilization, threshold],
...
}
```

feat: update utilization based idle checker policy

---

.github/workflows/default.yml

After uploading to pypi, conda-pack is being created, so it was judged that there would be no problem in the order, but it was judged that it took time to find the package in pypi.
So, modified to install the newly built wheels files by passing them as artifacts.

ci: install local wheels when building conda-pack

---

changes/1202.feature.md
src/ai/backend/manager/idle.py

Return value will change like below.
The value of `thresholds_check_operator` is "or" or "and".
The resource data is under `utilization.extra.resources` (previously, it is under `utilization.extra`)
```
{
"utilization":{
"remaining":-1.0,
"remaining_time_type":"grace_period",
"extra":{
"thresholds_check_operator":"or", # or "and"
"resources":{
"cpu_util":[0.11, 10.0],
"mem":[37, 10],
"cuda_util":[0.0, 10.0],
"cuda_mem":[0, 10]
}
}
},
"session_lifetime":{
"remaining":null,
"remaining_time_type":"expire_after",
"extra":null
}
}
```

feat: Utilization checker returns `thresholds_check_operator`

---

changes/1205.fix.md
src/ai/backend/manager/idle.py

Calculate idle checker's remaining time to expire correctly.
Previously, `user_initial_grace_period` (=new user grace period) is added to all of checker's remaining time to expire, which is wrong.
Correct flow of calculating remaining time is below.
1. if `user_initial_grace_period` is set
- the baseline of idle time is one of `user_initial_grace_period` and `kernel_created_at`(=kernel creation time), whichever is later.
baseline: datetime type.
now: datetime type. the current time
timeout: timedelta type. the period of timeout. ex) 100 seconds
- if baseline is later than now, remaining time is ((baseline - now) + timeout)
- else, remaining time is (timeout - (now - baseline))
2. if `user_initial_grace_period` is not set, then just calculate the remaining time as we have done.
---
```
{ …
```

fix: calculate idle checker's expiration time correctly

---

python.lock
requirements.txt

This PR updates dependecy version of etcetra, an etcd client library to `0.1.15`. Etcetra `0.1.15` includes a patch which fixes lock TTL operating in a wrong manner.

deps: update etcetra to 0.1.15

---

changes/1214.fix.md
src/ai/backend/manager/api/resource.py

So far, monthly stat API do iteration for (2880 * num_kernels) times constantly and fetch Kernel stats from Redis for every iteration.
This PR reduce the iteration and the number of Redis fetch.
Waiting for server response 4.77 s
* Not "milisecond", it is "second"
Waiting for server response 140.08 ms

fix: Optimize monthly stat API

---

.github/labeler.yml

Labels have been reorganized.
Therefore, the setting of the labeler, which recognizes diff and automatically manages labels, also needs to be changed.

ci: Change labeler settings to match the newly reorganized label

---

.github/workflows/default.yml

https://github.com/lablup/backend.ai/actions/runs/4555894319/jobs/8035687984
Fix an issue where an action fails due to lack of a packaging dependency.

hotfix(ci): Add missing dependencies during build-conda-pack-for-windows

---

.github/workflows/default.yml

Due to my mistake while editing the workflow, the binary file was not being uploaded to the release assets from version 22.09.18.
You need to manually upload binary files from 22.09.18 to 22.09.21 if necessary.

ci: add missing source distribution extractables for releases

---

.github/workflows/label.yml

The size label was added while the label was recently reorganized.
Automatically manage the corresponding size label through actions.

ci: add size label automation actions job

---

changes/1231.fix.md
src/ai/backend/agent/stats.py

disabling until #1230 is resolved.

fix: disable collecting per-container statistics on macOS backend

---

scripts/agent/build-dropbear.sh

This PR updates dropbear build script with adding support for multi target (Ubuntu 16.04 / 18.04 / 20.04 / 22.04, Alpine Linux 3.8) binary build.

misc: update dropbear build script

---

changes/1250.feature.md
configs/webserver/sample.conf
src/ai/backend/web/config.py
src/ai/backend/web/templates/config.toml.j2

Add `system_SSH_image` config to webserver so that system-role ssh image used to support fast scp and sftp in file browser dialog can be specified.
related PR: https://github.com/lablup/backend.ai-webui/pull/1694

feat: add `system_SSH_Image` webserver config to specify the system-role ssh image for fast file uploading.

---

src/ai/backend/manager/models/alembic/versions/bedd92de93af_add_role_column_on_kernels_table.py

This PR updates migration script which creates `kernels.role` column to read maximum of 100 kernels at once.

fix: enhance stability of `kernels.role` migration script

---

python.lock
requirements.txt

As aio-libs/yarl#854 is resolved and yarl 1.9.2 is released it is safe to unpin version of yarl and upgrade to latest.

setup: upgrade yarl to 1.9.2

---

changes/1261.fix.md
python.lock
requirements.txt

Downgrading (again!) yarl version to 1.8 since [another regression](https://github.com/aio-libs/yarl/issues/862) is discovered which crashes image scanning on our side.

setup: downgrade yarl to 1.8

---

.github/workflows/default.yml

The corresponding shell script exists in the build-wheels job as well, but since there is no error, I looked into the difference with build-conda-pack-for-windows.
The shell execution environment is the most suspicious part, so the shell has been changed to bash.

ci: change shell of `build-conda-pack-for-windows` to `bash`

---

scripts/install-dev.sh

After urllib3 2.0 is released, we're experiencing `scripts/check-docker.py` failing to execute when running `scripts/install-dev.sh`. This PR limits version of urllib3 installed when running `install-dev.sh` to be set below 2.0.

setup: fix install-dev.sh failing on `check-docker.py` check

---

changes/1266.feature.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/docker/kernel.py
src/ai/backend/agent/kernel.py
src/ai/backend/agent/kubernetes/agent.py
src/ai/backend/agent/kubernetes/kernel.py

Add `agent_id` label to containers

---

tests/common/test_distributed.py

Let `test_distributed.py` use more localized test ID (`test_case_ns` fixture) instead of session-wide namespaces (`test_ns` fixture), to prevent potential overlaps of parallel execution with other event-related tests.

test: Improve flakkiness of the distributed lock test cases

---

src/ai/backend/common/lock.py
src/ai/backend/testutils/bootstrap.py
tests/common/redis/conftest.py
tests/common/redis/docker.py
tests/common/redis/redis-cluster.yml
tests/common/redis/utils.py

The root cause was the healthchecks—they hang randomly when we run `docker unpause`, causing the Docker Engine to fail with:
This makes an indefinite delay of several test cases and causes timeouts on other tests.
Note that, in production setups, there is no need to `pause` and `unpause` the database containers because the test suite uses them to simulate network partitioning, i.e., unresponsiveness of specific Redis containers when they form a Sentinel-based Redis cluster for an HA setup.

test: Remove healthchecks for redis containers in fixtures to avoid intermittent hangup

---

tools/pants-plugins/setupgen/register.py

https://pypi.org/project/backend.ai/
https://pypi.org/project/backend.ai-manager/
Packages prior to the existing monorepo included more information in the classifier.
In particular, the python version is indicated in required, but I thought it would be nice to have it in the package classification information, so I added it.

chore: Add the python version to the classifiers of package

---

changes/1288.fix.md
src/ai/backend/manager/models/session.py

Handle error of Session `status_changed` if any status is not registered in `status_history`.

fix: Handle `KeyError` on `session.status_changed` GraphQL resolver

---

tests/common/redis/test_list.py
tests/common/redis/test_list_cluster.py
tests/common/redis/test_stream_consume.py
tests/common/redis/test_stream_consume_cluster.py
tests/common/redis/test_stream_subscribe.py
tests/common/redis/test_stream_subscribe_cluster.py

Thanks to #1281, now we can safely parallelize our tests more!
This PR reduces the execution time of `pants test tests:: -- -m 'not integration'` to about 1min 20secs in a M1 Pro/Max machine.

test: Parallelize more!

---

src/ai/backend/manager/models/alembic/versions/bedd92de93af_add_role_column_on_kernels_table.py

Let's not query Update or Insert when the value is empty.

fix: Handle empty list when migrate kernel role

---

changes/1299.feature.md
src/ai/backend/manager/models/alembic/versions/210c4d9be768_add_keypair_resource_policy_max_.py
src/ai/backend/manager/models/kernel.py
src/ai/backend/manager/models/resource_policy.py
src/ai/backend/manager/models/session.py
src/ai/backend/manager/models/user.py
src/ai/backend/manager/registry.py
src/ai/backend/manager/scheduler/dispatcher.py
src/ai/backend/manager/scheduler/predicates.py

Follow-up of #1243. This PR introduces `keypair_resource_policies.max_concurrent_sftp_sessions` column. Sessions created from SFTP scaling groups will now follow this rule, overriding previous behavior, which does not limit maximum number of SFTP upload sessions. In contrast to normal sesions, `SYSTEM` sessions (also known as SFTP upload sessions) failing concurrency check will instantly transit to `CANCELLED` status rather than keeping its state at `SCHEDULING`. This is to feedback UI that user has reached its own concurrency limit.

feat: concurrency limit for system sessions

---

changes/1304.fix.md
src/ai/backend/manager/registry.py

In `destroy_session()`, using `kernel.session_id` which is not eager-loaded occurs error.
This pr fix it by using `session_id` which is already loaded.

fix: use session_id to destroy kernels instead of kernel.session_id

---

tests/common/redis/test_stream_consume_cluster.py
tests/common/test_etcd.py

- `tests/common/test_etcd.py`: Prefer timeouts with explicit waits for the results instead relying on sleeps.
- `tests/common/redis/test_stream_consume_cluster.py`: Relax the result check for allowed loss of messages.

test: Improve stability of flaky tests

---

.github/labeler.yml

Modify that the models path is missing in the middle of the labeler path that sets the required:db-migration label.

ci: Fix wrong db migration file path

---

.github/workflows/default.yml

- It is expected that no images remain after the build-push-action is executed.
And in build-push-action, check that a function to upload the same image with a different tag is provided, and upload using that function.
- Upgrade build-push-action@v2 to v4, which uses the deprecated nodejs12 version from github actions.

ci: fix `build-push-action` failing

---

src/ai/backend/agent/kernel.py
src/ai/backend/kernel/base.py

Follow-up PR of #1278. Fixes `KernelCodeRunner` waiting only for 10 seconds regardless of `max_wait_time` and `max_retries` values.

fix: agent not waiting for model service to load

---

src/ai/backend/client/cli/service.py
src/ai/backend/client/func/service.py
src/ai/backend/manager/api/service.py

Follow-up PR of #1278. Update API and CLI to also accept vFolder name and endpoint name as valid identifier.

feat: update POST `/service` API to also accept vFolder name

---

pants.toml
src/ai/backend/plugin/entrypoint.py

This PR fixes plugin discovery failures after #1317.

ci,test: Pass the build root path explicitly when running tests

---

changes/1322.fix.md
src/ai/backend/manager/registry.py

`resoures` key can exist with `None` value because [default creation config inserts None](https://github.com/lablup/backend.ai/blob/main/src/ai/backend/manager/api/session.py#L168-L185) into the argument.
Let's check nullable value in enqueue session.

fix: Check None value of config argument when enqueue session

---

changes/1326.fix.md
src/ai/backend/manager/registry.py

Set session status `PULLING` when any sibling kernel is pulling image.

fix: set session status not being set as `PULLING`

---

changes/1325.fix.md
src/ai/backend/manager/scheduler/dispatcher.py

Currently variable `agent` has an inconsistent type in `SchedulerDispatcher._schedule_multi_node_session()`.
It can be `AgentRow` type or `AgentId`(string) type depending on the condition.
Let's check the type strictly.

fix: ensure type of `agent_id` to be consistent

---

changes/1332.fix.md
src/ai/backend/agent/agent.py

This PR fixes heartbeat failing when public-host is set.

fix: heartbeat failing when public-host is set

---

changes/1333.fix.md
src/ai/backend/common/types.py
src/ai/backend/manager/api/session.py
src/ai/backend/manager/api/vfolder.py
src/ai/backend/manager/models/group.py
src/ai/backend/manager/models/user.py
src/ai/backend/manager/models/vfolder.py

Follow-up PR of #1191. Updates vFolder API logics which are utilizing old vFolder ID structure to use latest one, which causes `400` HTTP error when calling storage proxy API.

fix: manager vFolder API failing

---

.github/workflows/timeline-check.yml

..to avoid the segfault in latest Git with "--filter=blob:none" option
with sparse checkouts
refs lablup/sparse-checkout#2

ci: Update lablup/sparse-checkout action

---

src/ai/backend/manager/models/vfolder.py

```
async with db_engine.begin_session() as db_session:
def _query():
stmt = ...
await db_session.execute(stmt)
await execute_with_retry(_query)
```
```
def _query():
async with db_engine.begin_session() as db_session:
stmt = ...
await db_session.execute(stmt)
await execute_with_retry(_query)
```

fix: reopen db connection when retry delete vfolder query

---

.github/workflows/default.yml

To reduce the traffic from GitHub Actions (e.g., LFS), let's make our actions to fetch only the exactly required set of commits.
* For pushes, we fetch only the latest 2 commits.
* For pull requests, we fetch only the commits included in the PR (by taking the `github.event.pull_request.commits` context variable + 1) and the commits in the base branch (normally `main`) since the branching point (by taking the timestamp of the branching commit).
- This ensures `git merge-base HEAD <base-branch>` and `git diff <base-branch>...HEAD` to work as expected.

ci: Optimize the fetch depth for frequently executed actions

---

changes/1355.fix.md
src/ai/backend/storage/vfs/__init__.py
tests/storage-proxy/test_fsop_base.py

The File Listing API scans all sub-directories under a data folder in the current implementation, even when the 'recursive' option is off.
For example, for a data folder which contains `CI` directory only at the root,
the file listing API returns every file under the data folder by scanning all of the sub-directories.
This PR prevents this by not scanning every sub-directory when the `recursive` option is off. With this PR, only the `CI` directory is shown like image below.

fix: prevent scanning every sub-directories in listing vfolder files when `recursive` is `False`

---

changes/1357.fix.md
src/ai/backend/storage/migration.py

- Error handling for missing `quota_scope_ids` to prevent migration errors.
- Ensure target directories are created before moving source directories.
- Append file suffix in output migration filename to support multiple vfolder root volumes.

fix: enhance vfolder v3 directory migration script

---

changes/1359.fix.md
src/ai/backend/agent/docker/agent.py

Previous container's `service-ports` label:
```
"ai.backend.service-ports": "ipython:pty:3000,jupyter:http:8091,jupyterlab:http:8090,vscode:http:8180,tensorboard:http:6006,mlflow-ui:preopen:5000,nniboard:preopen:8080,",
```
Trailing comma causes session creation failure when image's `service-ports` is empty (`""`), which leaves a leading comma for the container's `service-ports`.
After this PR:
```
"ai.backend.service-ports": "ipython:pty:3000,jupyter:http:8091,jupyterlab:http:8090,vscode:http:8180,tensorboard:http:6006,mlflow-ui:preopen:5000,nniboard:preopen:8080",
```

fix: trailing comma added to container's `service-ports` label

---

.gitignore
changes/1358.fix.md
src/ai/backend/manager/models/keypair.py

In querying keypair list from clients, the following error is raised:
```
File "/home/devops/backend.ai-main/backend.ai/src/ai/backend/manager/models/keypair.py", line 452, in batch_load_by_ak
return await batch_result(
^^^^^^^^^^^^^^^^^^^
File "/home/devops/backend.ai-main/backend.ai/src/ai/backend/manager/models/base.py", line 635, in batch_result
objs_per_key[key_getter(row)] = obj_type.from_row(graph_ctx, row)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/devops/backend.ai-main/backend.ai/src/ai/backend/manager/models/keypair.py", line 217, in from_row
projects=row["groups_name"],
~~~^^^^^^^^^^^^^^^
File "/home/devops/backend.ai-main/backend.ai/dist/export/python/virtualenvs/python-default/3.11.3/lib/python3.11/site-packages/sqlalchemy/engine/cursor.py", line 628, in _key_fallback …
```

fix: unable to list keypairs by email or access key

---

changes/1376.fix.md
src/ai/backend/storage/gpfs/__init__.py
src/ai/backend/storage/weka/__init__.py

Follow-up PR of #1191. Fixes lablup/giftbox#439. Updates implementation of `get_fs_usage()` in GPFS and Weka backend to explicitly mention name of the attr parameters, since without it the order matters when initiating `CapacitiyUsage()` object.

fix: storage proxy reporting wrong stat on some backends

---

src/ai/backend/common/validators.py

This PR updates some keyword argument mismatches shown in several examples.
https://github.com/lablup/backend.ai/blob/ac6e0f45d427df05bcd6633b05b0559e5d063c07/src/ai/backend/common/validators.py#L539-L581
----
:books: Documentation preview :books:: https://sorna--1377.org.readthedocs.build/en/1377/
----
:books: Documentation preview :books:: https://sorna-ko--1377.org.readthedocs.build/ko/1377/

chore: Update docstring from `ai.backend.common.validators.TimeDuration` with valid keyword arguments

---

changes/1380.fix.md
src/ai/backend/manager/registry.py
src/ai/backend/manager/scheduler/dispatcher.py

This is a follow-up hotfix found from a recent deployment.
- Some Docker versions do not accept integer values in `com.docker.network.driver.mtu` network creation option but only strings. Let's force stringification always.
- We should use the kernel IDs insetad of session IDs when recording the scheduling results. It's a regression from #325. It has prevented working of multi-container sessions.

fix: Finalize per-kernel scheduling results using the correct kernel IDs

---

src/ai/backend/manager/scheduler/dispatcher.py

hotfix: match to kernel id instead of session_id

---

changes/1395.fix.md
src/ai/backend/manager/api/service.py
src/ai/backend/manager/api/session.py

When request creating session API, response notes that "session_name" is required.
> 
but when request parameter contain "session_name", response notes that "session_name" is not allowed key.
To resolve this ambiguity, session_name is added to the aliased key of session_name.
So, request contained "session_name" is allowed.

feat: add aliased key of `session_name`

---

changes/1398.fix.md
src/ai/backend/manager/api/vfolder.py

resolves: #1398 
**Done**
Originally `when creating/cloning vfolders` we `checked if two conditions are the same`, it's `name` and `host`.
To block creating/cloning vfolders with duplicate names even on different hosts, I `deleted a condition that checked whether if the host is same or not`. (Only conditions of checking names remains).
This will gradually make it impossible to create vfolder with names, whatever the host is.
**Test**
I executed postgres querys directly into it's docker container and checked if this works.

fix: delete vfolder conditions of checking host while creating/cloning vfolders

---

changes/1305.feature.md
src/ai/backend/client/cli/config.py

This PR resolves #1305 .
I just added code to print the reason for login failure.
**ScreenShot:**

feat: add failure message when login failed

---

changes/1412.fix.md
src/ai/backend/manager/models/session.py

1. Enable transit session status from `PULLING` to `CANCELLED` or `TERMINATED`
2. Remove `not in` syntax for better readability

fix: re-map session status transition

---

changes/1438.fix.md
scripts/install-dev.sh

This PR resolves #1438.
I added shell script codes to create `version.txt` including vfolder version when running `install-dev.sh`.
https://github.com/lablup/backend.ai/blob/5f4e51da796b9121adc491d4ed99153cdeedece2/scripts/install-dev.sh#L788-L793

fix: add shell script codes to create `version.txt` in `install-dev.sh`

---

changes/1447.fix.md
src/ai/backend/manager/config.py

This PR resolves #1447.
I added the `empty_str_as_empty_list=True` option to store `[]` instead of `['']` in etcd. 
However, we still need to resolve the issue of the registry project name responding as a string (e.g., `'[]'`) instead of a JSON array.

fix: Add `empty_str_as_empty_list=True` option in StringList

---

py

This PR changes old pants' notation(`./pants`) to the new one(`pants`).

fix: Change pants' notation from `./pants` to `pants`

---

changes/1460.feature.md
src/ai/backend/client/cli/admin/scaling_group.py
src/ai/backend/client/func/scaling_group.py
src/ai/backend/client/output/fields.py
src/ai/backend/manager/models/scaling_group.py

- Add `wsproxy_api_token` column to manager/model.
- Make it possible to CRUD `wsproxy_addr` and `wsproxy_api_token` in CLI.
follows https://github.com/lablup/backend.ai/pull/1278
related: https://github.com/lablup/backend.ai-control-panel/issues/660

feat: CRUD `wsproxy_addr`, `wsproxy_api_token` in CLI

---

changes/1479.feature.md
src/ai/backend/client/output/fields.py
src/ai/backend/manager/models/kernel.py

resolves https://github.com/lablup/backend.ai/issues/1351
result of `./backend.ai session info <session_id>`

feat: expose `preopen_ports` information on `Kernel` GQL Query

---

docs/dev/daily-workflows.rst

This PR fixed typo in daily workflow docs, VSCode settings for Ruff.
- `black` -> `ruff`
- ruff.interpreter
- ["dist/export/python/virtualenvs/**ruff**/3.11.4/bin/python"]
- ruff.path
- ["dist/export/python/virtualenvs/**ruff**/3.11.4/bin/ruff"]
----
:books: Documentation preview :books:: https://sorna--1476.org.readthedocs.build/en/1476/
----
:books: Documentation preview :books:: https://sorna-ko--1476.org.readthedocs.build/ko/1476/

docs: fix daily workflows documentation typo

---

.github/workflows/pr-number-assign.yml

Our repo is public and thus we won't need any special privileges to clone the repository.

ci: stop supplying `token` on news-fragments workflow

---

changes/1464.fix.md
src/ai/backend/client/request.py

- resolves https://github.com/lablup/backend.ai-ossca-2023/issues/3
- add check block for `variable is not None`.
- So, that makes correct error response when got ClientResponseError in FetchContextManager.
before
```
✗ [0] cannot access local variable 'raw_resp' where it is not associated with a value
```
after
```
✗ [0] BackendClientError("API endpoint response error.\n➜ ClientResponseError(RequestInfo(url=URL('http://127.0.0.1:6011/session'), method='POST', headers=<CIMultiDictProxy('Host': '127.0.0.1:6011', 'User-Agent': 'Backend.AI Client for Python 23.03.9.dev0', 'X-BackendAI-Domain': 'default', 'X-BackendAI-Version': 'v7.20230615', 'Date': '2023-07-20T08:29:03.767375+00:00', 'Content-Type': 'application/json', 'Authorization': 'BackendAI signMethod=HMAC-SHA256, …
```

fix: do not try to access undefined variable on client fetch

---

changes/1500.fix.md
src/ai/backend/manager/models/alembic/versions/bedd92de93af_add_role_column_on_kernels_table.py

```
kernels.c.role is None
```
SQL query condition like  this will not work as is.

fix: Correct null check in kernel role migration

---

changes/1501.feature.md
src/ai/backend/common/lock.py

When we use `RedisLock` with multiple managers, the managers do polling to get lock every 0.1 second.
Since it can cause a huge burden to Redis, let's reduce it by passing `sleep` argument to `AsyncRedisLock` to sleep for every polling.

feature: use AsyncRedisLock sleep

---

.github/workflows/auto-label.yml

auto-label-in-issue doesn't work properly with pull_request from a forked repo.
This is a problem caused by the permission of github_token.
This is solved by using pull_request_target.
auto-label-in-issue is not related to changes in the code, so it doesn't matter if it is executed based on the target branch.

ci: Change trigger of auto-label-in-issue to pull_request_target

---

src/ai/backend/storage/server.py

follow-up #1503 
storage proxy has a wrong consumer group.

fix: Storage proxy has wrong consumer group

---

scripts/check-backport-commits.py

This PR introduces `check-backport-commits.py` script, which checks if there is a merge commit marked as a backport target but still yet did its job. This scripts `gh` CLI to be installed and configured at the machine.    
To run script simply boot up the python runtime with `python scripts/check-bacport-commits.py <Target version to be released very soon>`.

misc: add script to check commits not yet backported

---

changes/1514.feature.md
changes/1514.fix.md
scripts/install-dev.sh

- resolves https://github.com/lablup/backend.ai-ossca-2023/issues/18, the second problem.
- just update etcd port as defined in `install-dev.sh`.

fix: Update etcd port script for storage proxy config

---

docs/conf.py

Having the copyright year in the previous year gives the impression of a poorly managed project.
So, the copyright year display is improved to display the current year.
close #1368 
----
:books: Documentation preview :books:: https://sorna--1485.org.readthedocs.build/en/1485/
----
:books: Documentation preview :books:: https://sorna-ko--1485.org.readthedocs.build/ko/1485/

ci: Print the copyright year as the current year

---

src/ai/backend/manager/config.py
src/ai/backend/manager/container_registry/base.py

This PR fixes an error raised when running image rescan functions: `./backend.ai mgr image rescan` or `./backend.ai admin image rescan`
```sh
2023-08-30 14:52:15.657 INFO ai.backend.manager.models.image [49069] Scanning kernel images from the registry "cr.backend.ai"
2023-08-30 14:52:15.658 ERROR ai.backend.manager.cli.image_impl [49069] An error occurred.
+ Exception Group Traceback (most recent call last):
|   File "/Users/rapsealk/Desktop/git/backend.ai-dev/src/ai/backend/manager/cli/image_impl.py", line 186, in rescan_images
|     await rescan_images_func(etcd, db, registry=registry, local=local)
|     ^^^^^^^^^^^^^^^^^
|   File "/Users/rapsealk/Desktop/git/backend.ai-dev/src/ai/backend/manager/models/image.py", line 115, in rescan_images
|     async with aiotools.TaskGroup() as tg:
| …
```

fix: use of invalid etcd config key when rescanning image

---

docs/README.md
docs/conf.py

Goal: Building pdf document
+ Add Sphinx extension to use SVG img in PDF https://github.com/lablup/backend.ai/commit/c2496fa9d70af564eaf86d890fa98c3d0c410ec9
+ Add guide for building PDF document https://github.com/lablup/backend.ai/commit/3294e3903d5f1f722f44bbe8ef35202bda212655
- Command
- Dependency

docs: add instructions about generating PDF document

---

docs/README.md
docs/conf.py

Follow-up PR of #1525. Updates docs/conf.py to switch PDF building engine to xelatex instead of pdflatex.
----
:books: Documentation preview :books:: https://sorna--1529.org.readthedocs.build/en/1529/
----
:books: Documentation preview :books:: https://sorna-ko--1529.org.readthedocs.build/ko/1529/

fix: PDF not generated on macOS

---

configs/agent/halfstack.toml
scripts/install-dev.sh
src/ai/backend/agent/agent.py
src/ai/backend/agent/config.py

follow-up #1495 
Set agent's `mount-path` local config to nullable since it is used only when `mount` or `umount` happens.

fix: set agent's `mount-path` config nullable

---

changes/1537.deps.md
python.lock
requirements.txt
tools/pytest.lock

This PR updates pinned version of etcetra dependency to 0.1.17. Updating etcetra to latest will also update its peer dependecy, `grpcio` and `grpcio-tools` to latest, which contains pre-built wheels for both macOS and Linux with aarch64 architectures. Yay!

deps: update etcetra to 0.1.17

---

changes/1541.feature.md
src/ai/backend/common/distributed.py
src/ai/backend/manager/idle.py

Let's preserve the GlobalTimer tick termination logs and set name for idle checker task for better debugging.

feature: preserve GlobalTimer tick termination logs

---

configs/storage-proxy/sample.toml
src/ai/backend/storage/config.py
src/ai/backend/storage/server.py

follow-up #1495 
change watcher socket path to nullable in config and raise error only when watcher is enabled.

fix: allow setting storage proxy watcher socket path config to null

---

.github/workflows/alembic-head-check.yml
.github/workflows/check-requirement.yml
.github/workflows/coverage.yml
.github/workflows/default.yml
.github/workflows/integration.yml
.github/workflows/pr-number-assign.yml
.github/workflows/sbom.yml
.github/workflows/timeline-check.yml

As nodejs v16 ends support on September 11th, we will upgrade checkout v3, which uses nodejs v16, to checkout v4, which uses nodejs v20.
https://endoflife.date/nodejs

ci: Bump checkout from v3 to v4

---

changes/1553.feature.md
src/ai/backend/manager/api/logs.py
src/ai/backend/manager/scheduler/dispatcher.py

Let's add `task_name` to all `GlobalTimer._tick_task` for better debugging.

chore: add task_name to all `GlobalTimer`

---

tools/black.lock
tools/mypy.lock

This doubles the performance of black and mypy in Linux aarch64 development setups by introducing mypyc-based builds.
Note that x86-64 and macOS setups have already been using the mypyc-based builds.
Benchmark:
- `mypy src`: 32.18s → 9.99s (with cleaning up `.mypy_cache` on each run)
- `black --check src`: 21.14s → 13.54s
References:
- https://github.com/lablup/backend.ai-oven/blob/main/pypi/projects/mypy/build.md
- https://github.com/lablup/backend.ai-oven/blob/main/pypi/projects/black/build.md
TMI:
- I tried to upgrade black (23.7 → 23.9) but its mypyc wheels were not published due to psf/black#3865. Let's upgrade it later.

ci: Introduce our custom-built linux-aarch64 wheels for black and mypy

---

changes/1559.fix.md
src/ai/backend/common/distributed.py
src/ai/backend/common/lock.py

Let `RedisLock` retry until acquire lock by re-raising `redis.LockError` as `asyncio.TimeoutError`

fix: Retry untill acquire `RedisLock`

---

changes/1561.fix.md
src/ai/backend/manager/api/vfolder.py

- follows https://github.com/lablup/backend.ai/pull/1517
- resolves https://github.com/lablup/backend.ai-control-panel/issues/672
- AttributeError occurs because folder id is typecast to UUID once again, even though folder id is entered as UUID.
- To Avoid AttributeError and make it possible to delete by vfolder id, I removed the repeated type casting with UUID.

fix: modified to avoid repeated type casting with UUID

---

.github/dependabot.yml

Manage the version of github actions with dependabot.
First, only actions officially provided by the github actions team are applied first.
In the case of other external actions, there may be unknown update history, so I think it is necessary to check.

ci: Manage actions version with dependabot

---

changes/1570.fix.md
src/ai/backend/agent/agent.py

When there is any cohabiting storage with agents, agents should skip mount/umount task and just produce succeed event rather than just return.
If https://github.com/lablup/backend.ai/pull/1560 merged earlier than this PR, this should be closed.

fix: Let agents fire storage (un)mount completion events even when coexisting with storage-proxy

---

changes/1571.fix.md
src/ai/backend/manager/models/keypair.py

follow-up #1533 
Since we migrate the `last_used` field of `keypairs` table into redis, we need to support resolver for `KeyPair` gql object.

fix: Resolve keypair last_used from Redis

---

scripts/pr-number-assign.py

close #1507 
- Fixes an issue where pr-number-assign misunderstanding a properly named news fragment file exists even if it is not when the PR number is correct.
- If there are multiple news fragments in one PR, exception handling is provided to handle cases where only some files are in the correct format.

ci: fix problems of pr-number-assign action

---

changes/1576.feature.md
scripts/pr-number-assign.py
src/ai/backend/web/templates/config.toml.j2

For resolving https://github.com/lablup/backend.ai-webui/issues/1919, make webui possible to read pipeline endpoint config from the webserver.

feat: add pipeline endpoint to the webserver templates

---

src/ai/backend/common/utils.py

add Type hints to `common.utils.Fstab`

chore: add type hints to `utils.Fstab`

---

changes/1579.fix.md
scripts/extract-release-changelog.py
src/ai/backend/manager/models/vfolder.py

1. Raise `VFolderOperationFailed` after delete vfolders row of successfully deleted vFolders.
2. Pass task name to `PersistentTaskGroup.create_task()` in `initiate_vfolder_removal`

fix: lazy raise of vFolder deletion failure

---

changes/1593.fix.md
configs/webserver/halfstack.conf
configs/webserver/sample.conf
scripts/install-dev.sh
src/ai/backend/common/config.py
src/ai/backend/manager/config.py
src/ai/backend/web/config.py
tests/agent/conftest.py
tests/common/redis_helper/test_connect.py
tests/common/redis_helper/test_list.py
tests/common/redis_helper/test_list_cluster.py
tests/common/redis_helper/test_pipeline.py
tests/common/redis_helper/test_pubsub.py
tests/common/redis_helper/test_stream_consume.py
tests/common/redis_helper/test_stream_consume_cluster.py
tests/common/redis_helper/test_stream_subscribe.py
tests/common/redis_helper/test_stream_subscribe_cluster.py
tests/common/redis_helper/utils.py
tests/common/test_distributed.py
tests/common/test_events.py
tests/manager/conftest.py

This PR makes `RedisHelperConfig` optional and makes a default value when is not specified.
And also add `redis_helper_default_config` to remove useless code redundancy of the test codes in the `common/config.py`.

fix: Make `RedisHelperConfig` optional and make default configs

---

changes/1591.fix.md
src/ai/backend/storage/api/manager.py

Let's handle external error of storage proxy to return error response with detail message rather than just leaving it.

fix: handle external error in storage proxy API

---

.github/workflows/default.yml
backend.ai-client.Dockerfile

close #1508 
In the build-client-image job of the default workflow, there was an issue where package download sometimes failed due to slow pypi indexing, so we have improved it so that packages can be found locally.

ci: use local wheels as a secondary repo

---

changes/1401.fix.md
src/ai/backend/manager/scheduler/dispatcher.py

This PR fixes some wrong exception-handling logics of `SchedulerDispatcher`.
(Errors occurring when attempting to explicitly allocate a session via the `--assign-agent` and the agent runs out of one of its resource slots.)
Tested manually by the below command.
```
❯ ./backend.ai run python -c 'print("hello world")' --assign-agent=i-ubuntu
(when the specified agent's resource slot is not enough)
```

fix: wrong exception handling logic of `SchedulerDispatcher` 

---

pants.toml

This allows Pantsbuild to find [asdf](https://asdf-vm.com/)-managed Python versions in addition to [pyenv](https://github.com/pyenv/pyenv)-managed Python versions.
The main advantage is unification of multiple runtime version managers like nvm, rbenv, etc.
To make the `./py` and `./backend.ai` commands to work, you may need to run:
```console
$ pants export --resolve=python-default
$ asdf local python "path:$(pwd)/dist/export/python/virtualenvs/python-default/3.11.4"
```
Existing pyenv-based setups should work like before.
If you are migrating from pyenv to asdf, you need to re-run `pants export` commands.

chore: Add asdf-managed Python versions to the interpreter search target

---

pants.toml
tools/pants-plugins/setupgen/register.py

* Updated the setupgen plugin to use the new imports.
* Added `[python-infer].use_rust_parser = true` for faster dependency resolution.
* Confirmed wheel packaging works like before, using our platform-specific dependency injection plugin.
You don't have to do anything special as pants will self-upgrade automatically.

chore: Upgrade Pants (2.16.0 -> 2.17.0)

---

changes/1606.feature.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/docker/kernel.py
src/ai/backend/agent/dummy/agent.py
src/ai/backend/agent/dummy/kernel.py
src/ai/backend/agent/kernel.py
src/ai/backend/agent/kubernetes/agent.py
src/ai/backend/agent/kubernetes/kernel.py
src/ai/backend/common/events.py
src/ai/backend/common/types.py
src/ai/backend/kernel/base.py
src/ai/backend/kernel/service_actions.py
src/ai/backend/manager/api/service.py
src/ai/backend/manager/registry.py
src/ai/backend/manager/scheduler/dispatcher.py

This should help user to deal with cases which server process starts fine at first but dies at sudden point.    
This PR also includes some minor improvements to the model service:
- Server process now starts with cwd set to `model_path` defined under `model-definition.yml`
- `run_command` pre-start action accepts optional argument `echo`, which carries out the stdout/stderr outputs to container log. This is set to false by default.

feat: check health status of model service actively

---

src/ai/backend/manager/models/gql.py

`resolve_scaling_groups_for_group` -> `resolve_scaling_groups_for_user_group`

fix: typos

---

pants.toml

- This is to avoid some potential bugs in pants' asdf version resolution
when the global version is different from what's in pants.toml.

chore: Prefer local pyenv/asdf Python versions

---

changes/1645.fix.md
src/ai/backend/agent/docker/agent.py

Docker containers do not expose their ports if they use macvlan.
Let's handle it for better debug.

fix: Raise error when a created docker container exposes no port

---

changes/1643.fix.md
src/ai/backend/manager/models/resource_policy.py

follows https://github.com/lablup/backend.ai/pull/1417
To resolve type mismatch between DB and schema, unify type of the `max_vfolder_count` to Integer.
| Before | After |
|--------|--------|
| DB (Integer):
https://github.com/lablup/backend.ai/blob/1419cf378b23d6b0e5dfbc9d0f4151bf4acc50f8/src/ai/backend/manager/models/resource_policy.py#L100 | same |
| Schema (BigInt): | Schema (Int): |
|https://github.com/lablup/backend.ai/blob/429c15574f03d37dec6a18b2dcfb00e9f815a9fc/src/ai/backend/manager/models/resource_policy.py#L410 | https://github.com/lablup/backend.ai/blob/7e50143e586db882ac085e4f68a9d726d9b7c208/src/ai/backend/manager/models/resource_policy.py#L485 | 

fix: change `max_vfolder_count` type from BigInt to Int

---

src/ai/backend/web/proxy.py

This PR simply adds version history tags to JWT claims, which are used for the pipeline service.
Refs
- #1350 
- release: 23.03.10 (aa1a38878834b5ec1c83d233b6e5bf26d2f33896)

chore(web.proxy): Add version history to pipeline JWT claims

---

changes/1666.feature.md
configs/webserver/sample.conf
src/ai/backend/web/config.py
src/ai/backend/web/templates/config.toml.j2

related PR: https://github.com/lablup/backend.ai-webui/pull/1998
Add `allow_custom_resource_allocation` option to webserver config file to display or hide the custom resource allocation on the session launcher.

feat: add `allow_custom_resource_allocation` to webserver config

---

changes/1664.feature.md
configs/webserver/sample.conf
src/ai/backend/web/config.py
src/ai/backend/web/templates/config.toml.j2

related PR: https://github.com/lablup/backend.ai-webui/pull/1996
Add `allow_app_download_panel` option to webserver config file to display or hide the webui app download panel.

add: add `allow_app_download_panel` option to webserver config

---

changes/1668.fix.md
src/ai/backend/manager/api/session_template.py

After https://github.com/lablup/backend.ai/pull/1406 is merged, request format for session template creation/update API has changed.
This PR updates the parameter of UPDATE API handler accordingly.

fix: handle request format changes on session template API

---

changes/1677.fix.md
src/ai/backend/manager/models/resource_policy.py
src/ai/backend/manager/models/utils.py

Deprecated graphql fields should not be removed.
The fields to be deleted should be marked with a deprecation message and deleted after a specified support period.

fix: restore removed graphene fields and set them deprecated

---

docs/dev/development-setup.rst

It may be confusing when repeating this example block would cause
unexpected queueing in the scheduler.
----
:books: Documentation preview :books:: https://sorna--1685.org.readthedocs.build/en/1685/
----
:books: Documentation preview :books:: https://sorna-ko--1685.org.readthedocs.build/ko/1685/

doc: Fix the tutorial to auto-remove the session

---

changes/1686.fix.md
src/ai/backend/common/logging.py
src/ai/backend/manager/cli/__main__.py
src/ai/backend/manager/cli/api.py
src/ai/backend/manager/cli/context.py
tests/manager/conftest.py

resolves #1681
Now we can run commands that do not require full "manager.toml" without
making dummy "manager.toml" and related config files.

fix: Lazy-load the local config in the manager CLI

---

changes/1698.fix.md
src/ai/backend/manager/models/group.py

follow-up #1688 
partial fix of #1697 
`ModifyGroupInput.user_update_mode` field can have `Undefined` value since #1688, let's allow the value.

fix: allow `Undefined` value to `ModifyGroupInput.user_update_mode`

---

.github/workflows/build-static-wsproxy.yml

We should favor the official release in the webui repository.
The first version that contains the static wsproxy (`local-proxy`) is [23.09.4](https://github.com/lablup/backend.ai-webui/releases/tag/v23.09.4).
The `build-static-wsproxy` workflow is for testing & debugging purpose.
Currently the macOS Applie Silicon runner seems to have performance/capacity issues...

ci: Fix build of static-wsproxy in macos

---

changes/1673.fix.md
src/ai/backend/agent/docker/kernel.py
src/ai/backend/agent/kubernetes/kernel.py

Related PR: https://github.com/lablup/backend.ai/pull/1665
If you create a symlink pointing to itself in a container and then connect the container by ssh, you will get a `Too many levels of symbolic links` error like below. (the symlink named 'abc' which could be created by `ln -s abc abc`)
```
work@main1[tzB9zs8e-session]:~$ ls -la
total 64
drwxr-xr-x 8 work work 4096 Oct 31 00:39 .
drwxr-xr-x 1 root root 4096 Oct 31 00:37 ..
-rw-rw-r-- 1 work work  147 Oct 31 00:37 .bash_profile
-rw-rw-r-- 1 work work  249 Oct 31 00:37 .bashrc
drwxr-xr-x 3 work work 4096 Oct 31 00:37 .cache
drwxr-xr-x 3 work work 4096 Oct 31 00:37 .config
drwxr-xr-x 3 work work 4096 Oct 31 00:37 .ipython
drwxrwxr-x 3 work work 4096 Oct 31 00:37 .jupyter
drwxr-xr-x 3 work work 4096 Oct 31 00:37 .local
-rw-r--r-- 1 root …
```

fix: infinite loop when malformed symbolic link exists in container

---

changes/1712.feature.md
src/ai/backend/manager/cli/context.py
src/ai/backend/manager/cli/etcd.py
src/ai/backend/manager/cli/image.py
src/ai/backend/manager/cli/image_impl.py
src/ai/backend/manager/container_registry/base.py
src/ai/backend/manager/container_registry/docker.py
src/ai/backend/manager/container_registry/harbor.py
src/ai/backend/manager/container_registry/local.py
src/ai/backend/manager/models/image.py

This PR resolves #1621.
* Implement rescanning a single image's metadata by specifying the full image and tag name.
* Disallow and deprecate rescanning a whole Docker Hub account (e.g., index.docker.io/lablup) to avoid the API rate limit.
* Ensure multi-arch compatibility with both Harbor and Docker Hub.
```shell
./backend.ai mgr image rescan cr.backend.ai
./backend.ai mgr image rescan index.docker.io/lablup/python:3.9-ubuntu22.04
./backend.ai mgr image rescan lablup/python:3.9-ubuntu22.04
```
> **Note**
> - Both rescanning registries or individual images require explicit configuration of registries (including credentials if required) in the shared config (etcd's `config/docker/registry` keys)
> - Users must specify the full image name including `index.docker.io` for Docker Hub images for …

feat: Per-image rescan with improved multi-arch support

---

.github/workflows/label.yml

Exclude lock files from calculating size labels.
This leads to confusion about the size of pr.

ci: Excluding lock files from size calculations

---

changes/1701.fix.md
src/ai/backend/storage/api/manager.py

There are some cases that error occurs in storage proxy's API error handler.
e.g) if it is impossible to resolve a file path because of permission or invalid path, `ValueError` is raised.

fix: handle error in storage API error handler

---

changes/1715.fix.md
src/ai/backend/manager/registry.py

fix: allow empty `auto_terminate_abusing_kernel` field from agent heartbeat

---

.github/workflows/default.yml
.github/workflows/sbom.yml

When releasing the sbom workflow that was previously executed manually, it is included and added to the artifact.

ci: Add sbom report to release artifact

---

changes/1731.fix.md
src/ai/backend/install/context.py

Yet another follow-up to #1694 and #1716.
Thanks to @reiden21 and @kimjmin !
- a-scie/jump#172
- Replace `sha256sum` with `shasum -a 256` (the latter works with Linux as well!) for when the homebrew setup does not have `coreutils` installed yet.
- Let `docker compose up` to pull if images are missing.

fix: Additional macOS installer issues

---

changes/1732.fix.md
src/ai/backend/agent/vendor/linux.py
src/ai/backend/common/cgroup.py
src/ai/backend/common/docker.py
src/ai/backend/install/docker.py
src/ai/backend/manager/container_registry/local.py
tests/common/test_docker.py

- Fix an installer regression in #1724 to inappropriately cache an aiohttp connector instance used to access the local Docker API
- Refactor the return value of `common.docker.get_docker_connector()` to provide richer information with extensible set of fields, by changing the tuple to a dataclass.
- Catch `ClientConnectorError` which wraps `PermissionError`, hiding the actual OS error instance. `except PermissionError:` was not properly executed.... :(

fix: Installer regression by #1724 and refactor docker connector for richer debug info

---

changes/1736.fix.md
configs/webserver/halfstack.conf
configs/webserver/sample.conf

Change the Redis port number in the webserver conf for `install_dev.sh` installation.

fix: default redis port in webserver conf

---

src/ai/backend/web/templates/config.toml.j2

refer #1735 
just a minor spelling change on a configuration name

fix: minor config name spelling change

---

scripts/download-webui-release.sh

Now that we abandon our current static webui (`src/ai/backend/web/static`) release mechanism we need this kind of script.

feat: add automated static webui unpack shell script

---

changes/1738.fix.md
src/ai/backend/manager/api/ratelimit.py

`rate_limit` column of keypairs table is nullable.
we should do null check.

fix: do null check on `rate_limit`

---

changes/1741.fix.md
src/ai/backend/common/config.py

follow-up: #1585
`trafaret.Float()` does not convert string value into float. It just check whether it can be float or not.
We should rather use `trafaret.ToFloat()`.

fix: convert redis config value

---

changes/1699.feature.md
src/ai/backend/manager/server.py

Since it is too hard to get `db` or other contexts of Manager from plugins, let's pass `RootContext` to plugins

feature: pass manager's RootContext to hook plugins

---

src/ai/backend/manager/models/user.py

follow-up #1749 
There was wrong codes of handling `groups` in `UserCreation` mutation.

fix: wrong group creation in mutate UserCreation

---

src/ai/backend/storage/cephfs/__init__.py

fix: ignore `os.setxattr` lint

---

changes/1787.fix.md
src/ai/backend/manager/models/user.py

Follow-up of #1674. This PR fixes `modify_user` mutation raising error when password is not supplied.

fix: password not updated when calling modify_user mutation

---

.editorconfig
changes/1789.fix.md
docs/README.md
docs/_static/css/customTheme.css
docs/client/dev/examples.rst
docs/client/dev/index.rst
docs/client/dev/session.rst
docs/client/func/index.rst
docs/conf.py
src/ai/backend/client/func/session.py

This is a documentation update to expand our client SDK usage scenarios.
It also improves the doc build speed by updating the intersphinx links, and fixes the code-block theme to be more readable using the GitHub Dark style from pygments.
To compliment the updated description of the SDK example for model serving, this PR adds a missing `ComputeSession.start_service()` functional API wrapper.
----
📚 Documentation preview 📚: https://sorna--1789.org.readthedocs.build/en/1789/
----
📚 Documentation preview 📚: https://sorna-ko--1789.org.readthedocs.build/ko/1789/

doc: Add Client SDK examples

---

docs/dev/daily-workflows.rst

This is a follow-up to #1771
----
📚 Documentation preview 📚: https://sorna--1827.org.readthedocs.build/en/1827/
----
📚 Documentation preview 📚: https://sorna-ko--1827.org.readthedocs.build/ko/1827/

doc: Update the dev guide to reflect Ruff unification

---

changes/1806.fix.md
scripts/install-dev.sh

resolves #1751
due to the [recent changes in pants install script](https://github.com/pantsbuild/setup/pull/144), the install directory of pants changed to ~/.local/bin

fix: Update Pants installation path from `~/bin` to `~/.local/bin`

---

.github/workflows/sbom.yml

https://github.com/lablup/backend.ai/actions/runs/7406811894?pr=1138
This is a change to resolve the node12 deprecated warning in the actions log above.

ci: Bump gh-python-generate-sbom from v1 to v2

---

changes/1811.feature.md
src/ai/backend/client/output/fields.py

Add `vfolder_mounts` field to session field of client's output to enable query the mount field.

feature: add vfolder_mounts client output field

---

src/ai/backend/common/config.py

Follow-up PR of #1749. This PR adds a default value of `metadata` config schema so that it can really be treated as an optional value.

fix: make `metadata` field of model definition optional

---

changes/1833.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/kernel/base.py

Follow-up PR of #1606. Fixes two issues:
- health checker reporting healthy when model server process has been terminated
- service health not falling into "UNHEALTHY" when it has never made to a HEALTHY status before

fix: health checker not working correctly

---

changes/1820.fix.md
src/ai/backend/manager/idle.py

resolves https://github.com/lablup/giftbox/issues/592
When sessions(or kernels) are created without allocating cuda or any other devices, the value of `kernel.occupied_slots` field would be like below.
```
{'cpu': Decimal('1'), 'mem': Decimal('335544320')}
```
If we set thresholds of resources which are not in `kernel.occupied_slots` field to util checker, the checker determines the utilization with default `0` value resource. Example values below.
```
{'cpu': Decimal('1'), 'mem': Decimal('335544320'), 'cuda': 0}
{'cpu': Decimal('1'), 'mem': Decimal('10'), 'cuda': 2}
```
In this PR, util checker does not determine utilization of resources that is not in `kernel.occupied_slots` value.
- …

fix: Exclude utilization checks for unallocated resources

---

changes/1837.fix.md
src/ai/backend/manager/models/vfolder.py

fix: Fill vfolder user and group field

---

src/ai/backend/manager/models/alembic/versions/c5ed277b7f7b_change_main_access_key_ondelete_to_set_.py

This PR is a follow-up of e9b81fc190f79da478783a0573f53947c0268b69.
Two alembic migration scripts* c5ed277b7f7b by #1775 and 8b2ec7e3d22a by #1835) have dependencies on each other.
https://github.com/lablup/backend.ai/blob/e9b81fc190f79da478783a0573f53947c0268b69/src/ai/backend/manager/models/alembic/versions/c5ed277b7f7b_change_main_access_key_ondelete_to_set_.py#L12-L13
https://github.com/lablup/backend.ai/blob/e9b81fc190f79da478783a0573f53947c0268b69/src/ai/backend/manager/models/alembic/versions/8b2ec7e3d22a_remove_unique_constraint_of_endpoint_url.py#L12-L13
- …

hotfix: Resolve cycle in alembic migration versions

---

src/ai/backend/manager/api/utils.py

Follow-up PR of #1804. Resolves Pydantic raising `TypeError` when response includes UUID object.

fix: pydantic raising 500 when response includes UUID

---

changes/1829.feature.md
src/ai/backend/manager/server.py

follow-up #1699 
let's pass a root context to plugins instead of a plugin context for easy accessibility to db

feature: Pass Root context of manager to plugins

---

changes/1852.feature.md
scripts/delete-dev.sh

This PR resolves #1802 by adding option "--skip-db".
1. User can delete all data volumes with no option.
`./scripts/delete-dev.sh`
2. User can skip to delete all data volumes with "--skip-db" option.
`./scripts/install-dev.sh --skip-db`
3. User can get help through the --help command.
`./scripts/install-dev.sh --help`
and then,
```
USAGE
./scripts/delete-dev.sh [OPTIONS]
OPTIONS
-h, --help         Show this help and exit
--skip-containers  Skip removal of docker resources (default: false)
--skip-venvs       Skip removal of temporary virtualenvs (default: false)
--skip-db       Skip removal of volume resources (default: false)
```
- Demonstrate the …

feature: update `delete-dev.sh` to remove DB volumes by default

---

changes/1855.misc.md
python.lock
requirements.txt
src/ai/backend/client/session.py
src/ai/backend/common/types.py
src/ai/backend/manager/container_registry/base.py

update pants lock file to apply 3.9.1 update and workaround mypy by adding `SSLContextType` type annotation

feat: aiohttp-3.9.1 update

---

changes/1850.fix.md
src/ai/backend/manager/api/vfolder.py

fix of vfolder query while making audit_logs
1. share
`ACTIVE_USER_STATUSES` is tuple so fixed operator from `==` to `in`
2. chage_vfolder_options
there was inconsistency between update and select statement which look for folder to update

fix: Query inconsistencies and mistakes in the vfolder share/change-ownership API handlers

---

changes/1873.fix.md
src/ai/backend/manager/registry.py

Insert `sessions` rows with valid `use_host_network` field.

fix: enqueue session with `use_host_network` field

---

src/ai/backend/manager/models/alembic/versions/caf54fcc17ab_add_id_columns_to_association_tables.py

follow-up #1818 
There could be mismatch between alembic migrations and real DB. I mistakenly write alembic scripts to delete primary keys from association tables in #576, but usually alembic does not delete the pk.
Since the primary keys remain in some DBs and don't remain in others, let's sync it in this patch by dropping existing pk in association tables and restore them when downgrade alembic

fix: drop existing primary keys of association tables

---

python.lock
src/ai/backend/client/session.py
src/ai/backend/common/types.py
src/ai/backend/manager/container_registry/base.py

This PR updates dependencies to its latest version. Note that type declaration of and variables typed as `SSLContextType` are modified to reflect changes of upstream (aiohttp).

chore(deps): update aiohttp to latest

---

changes/1878.fix.md
python.lock
requirements.txt
src/ai/backend/runner/dropbear.centos7.6.x86_64.bin
src/ai/backend/runner/dropbearconvert.centos7.6.x86_64.bin
src/ai/backend/runner/dropbearkey.centos7.6.x86_64.bin
src/ai/backend/runner/tmux.centos7.6.x86_64.bin

This PR adds various fixes to make CentOS 7 based images work on our latest Backend.AI Core.

fix: Backend.AI refusing to launch CentOS 7 based kernels

---

changes/1880.fix.md
src/ai/backend/agent/BUILD

This PR updates agent's `BUILD` file in order to include `watcher.py` back to agent wheel. `watcher.py`, a source code of our agent watcher, is set to be split out from Backend.AI Agent distribution artifact and be served as a standalone binary. Since majority of deployed Backend.AI clusters are relying on current Backend.AI Agent watcher distribution mechanism, we decided that until we polish our deployment policies to reflect those changes it is better to keep `watcher.py` into agent distribution artifact.
- docstrings in public …

fix: add watcher.py back to agent wheel

---

scripts/check-backport-commits.py

This PR updates `scripts/check-backport-commits.py` script to properly detect `rc` and `dev` patch versions.

feat: update backport checker script to detect rc/dev prefix

---

changes/1877.feature.md
configs/manager/halfstack.toml
configs/manager/sample.toml
src/ai/backend/manager/config.py
src/ai/backend/manager/models/utils.py
tests/manager/conftest.py

"connection is closed" `DBAPIError` can occur if we set timeout for connections. This is because the pools of SQLAlchemy is not fully synced with real connections.
Let's set `pool-recycle` config to replace timeout connections
- https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.pool_recycle
- https://docs.sqlalchemy.org/en/14/core/pooling.html#setting-pool-recycle
- https://community.fly.io/t/postgresql-connection-is-closed-error-after-a-few-minutes-of-activity/4768
- https://github.com/sqlalchemy/sqlalchemy/discussions/7657

feature: Set `pool-recycle` config to prevent using closed connection

---

changes/1886.fix.md
src/ai/backend/common/bgtask.py

When the client makes the EventSource channel later than the target bgtask has already finished, the server "simulates" a realtime event using the temporarily stored (up to 24 hours by default) task information from Redis.
The event name must be consistent for both the actual realtime event pushes and postmortem event pushes, for a seamless frontend implementation.
There was a typo missing "bg" in the postmortem event push logic. 😭 So, `bgtask_done` was reported as `task_done`...
This PR fixes this issue and refactors the bgtask module code a little bit more to prevent confusion of future code readers using latest Python conventions (such as `str.removeprefix()`).

fix: Make the event names consistent when reporting already-completed bgtask

---

.github/workflows/default.yml

The test job was running on the github hosted runner, but the lfs cache was set to use local-cache, so the cache was not being used at all.
This issue causes a lot of github lfs traffic and causes a lot of charges.

ci: Change lfs to use actions/cache in test job

---

.github/workflows/default.yml
scripts/extract-release-changelog.py

The prev_tag calculation was not performed properly after #1520.
The reason is that by default, only one commit log is fetched in actions/checkout, so prev_tag could not be calculated.

ci: Set fetch-depth to calculate prev_tag

---

src/ai/backend/client/cli/admin/scaling_group.py

This PR resolves #1293 by adding helper message for the `allowed_session_types` in create and modify commands of scaling group.
The commands work well even without `allowed_session_types`, but since `allowed_session_types` is set to the default values of `interactive` and `batch`, it may not operate as intended by the user. 
Therefore, a helper message has been added.

docs: add helper message for the allowed_session_types

---

changes/1916.fix.md
src/ai/backend/manager/models/base.py
src/ai/backend/manager/models/group.py
src/ai/backend/manager/models/user.py
src/ai/backend/manager/models/vfolder.py

follow-up #1719
resolves #1923
Clients cannot query relay nodes with "filter" and "order" argument properly.
Add `queryfilter_fieldspec` and `queryorder_colmap` as Relay node class variable and initiate `QueryFilterParser` or `QueryOrderParser` with them.

fix: GQL Relay node query builder does not have `queryfilter_fieldspec` and `queryorder_colmap`

---

.github/workflows/auto-label.yml

Now auto-label-in-issue reflects not only the label but also the issue's milestone in the PR.

ci: Upgrade version of auto-label-in-issue action

---

.github/workflows/alembic-head-check.yml
.github/workflows/default.yml
.github/workflows/docs-preview.yml
.github/workflows/timeline-check.yml

These workflows were triggered not only by branch changes such as commits, but also by label changes in pr, so they could be executed even after pr was merged.
However, since CI for already merged pr is meaningless, it saves resources by not executing it.

ci: PR that has already been merged will not run ci

---

src/ai/backend/manager/api/vfolder.py

This is a follow-up fix to #1862.
Since #1862 targets the main (24.03) branch only, I omit the news fragment as it's an immediate follow-up.

fix: Remove ref to the removed quota param when creating vfolders

---

.github/workflows/auto-label.yml

https://github.com/lablup/backend.ai/actions/runs/8032135076/job/21958781426
I think actions are failing due to lack of permission in auto-label-in-issue.

ci: Allow required permissions to auto-label-in-issue

---

changes/1934.fix.md
src/ai/backend/accelerator/cuda_open/plugin.py
src/ai/backend/accelerator/mock/plugin.py
src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/intrinsic.py
src/ai/backend/agent/stats.py
src/ai/backend/client/cli/session/execute.py
src/ai/backend/client/output/formatters.py
src/ai/backend/common/types.py

related to #1793 
* Replace `HardwareMetadata` to `dict` when class check because `TypedDict` does not support such functionality
* Add a missing parameter to default metric value formatter in the Client SDK's output framework.
- Also make it detectable via static type checks by improving type annotations.
* Refine and clarify the description of `MetricTypes`, with fixes of the `cuda_open` and `mock` plugin metric types.
- Rename `MetricTypes.USAGE` to `MetricTypes.GAUGE` to distinguish better from `MetricTypes.ACCUMULATION`.
- This renaming does not affect existing compute plugins:
- `MetricTypes.USAGE` is preserved for backward compatibility and evaluated as the same to `MetricTypes.GAUGE`.
- `metric.type` attribute does not change the processing/display of metric values at all. …

fix: CLI `agent info` related bugs

---

changes/1927.fix.md
src/ai/backend/manager/api/service.py
src/ai/backend/manager/api/utils.py
src/ai/backend/manager/api/vfolder.py

Currently, `web.Response` parsed from pydantic model cannot pass **HTTP status**.
For example, I cannot return web.Response with status code 204, it is always 200.
Let's add status code parameter to response model

fix: Allow passing HTTP status code via pydantic-based response models

---

src/ai/backend/manager/models/alembic/versions/7ff52ff68bfc_detail_vfolder_deletion_status.py
src/ai/backend/manager/models/base.py
src/ai/backend/manager/models/vfolder.py

The migration in #1892 requires a manual `alembic stamp` command after running the `alembic upgrade` command. This will break many developers and fieldops members.
This PR migrates the `vfolders.status` enum column to a VARCHAR(64) column to avoid complex enum value substitution and simplify the migration process.
* fix: Rewrite the vfolder status migration
- Remove errorneous commit during alembic migration scripts
- Use jsonb functions to convert the key names in the `status_history` column at once
* refactor: Add `models.base.StrEnumType` for stringified enum columns
> [!WARNING]
> You must downgrade the existing migration first BEFORE applying this PR's commit with a manual stamping afterwards,
> and then upgrade again AFTER applying this PR's commit (no longer manual stamping …

fix: Rewrite the vfolder status migration in #1892

---

src/ai/backend/manager/models/alembic/versions/41f332243bf9_add_missing_vfolder_indexes.py
src/ai/backend/manager/models/kernel.py
src/ai/backend/manager/models/vfolder.py

- It is a follow-up to #1892 and #1936.
- Adds `index=True` to the `kernels.role` column to avoid mismatch of DB
and migrations.

fix: Add missing indexes in the vfolders table

---

.github/workflows/default.yml

There are some networking issues from our self-hosted ARC runners to GitHub.
Until the issue is resolved, let's use GitHub-hosted standard runners.

chore(ci): Temporarily replace self-hosted arc runners with github-hosted runners

---

src/ai/backend/client/session.py

This PR is a follow-up to 714c1191c4634bcd2c9d21ba3fc764f40a5a1f36 to supply missing "f-string".
https://github.com/lablup/backend.ai/blob/9e56e5449acc8aefabcfa6aa4612b317bae9a2ec/src/ai/backend/client/session.py#L68-L74

fix: Typo in 714c119 using f-string (follow-up of follow-up of #1938)

---

changes/1958.feature.md
src/ai/backend/install/cli.py

This PR adds the --headless flag that:
* Runs as headless mode that skips terminal I/O
* Useful for automated installation procedure such as cloud-init.

feat: add headless flag option to installer

---

changes/1962.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/kernel/base.py
src/ai/backend/runner/entrypoint.sh

resolves #1959
This PR disables the user-site functionality for the krunner python commands to improve security and potential conflicts with the user-installed packages that may override some packages in the krunner.
Though, it does not disable it for the user-executed service-port apps that use the container's own Python runtime such as Jupyter notebooks (both the frontend server and the kernel processes). This is why I've put `-s` options individually instead of setting the `PYTHONNOUSERSITE=1` environment variable which may propagate to all sub-processes.

fix: Disable krunner's user site to avoid potential conflicts with user-installed packages

---

changes/1963.fix.md
src/ai/backend/manager/models/alembic/versions/589c764a18f1_change_endpoint_to_nullable.py
src/ai/backend/manager/models/alembic/versions/caf54fcc17ab_add_id_columns_to_association_tables.py

follow up #1935 and #1818
- When dropping primary keys, check if the table has any primary key
- Add some missing Table arguments in `589c764a18f1` alembic downgrade.

fix: alembic migration failing when primary key does not exist

---

.github/workflows/auto-label.yml

https://github.com/lablup/backend.ai/actions/runs/8438248840?pr=1758
Fixed a simple error that occurred because the code that outputs the milestone was faster than the if condition that checks if the milestone exists.
https://github.com/lablup/auto-label-in-issue/commit/c383a01c513347b9dfba7909f0f30ab53591fd05

ci: Bump auto-label-in-issue from 1.6.0 to 1.7.0

---

changes/1967.doc.md
docs/_static/css/customTheme.css

Related: #1965 
This PR fixes font resizing in ads footer, not in contents titles.
----
📚 Documentation preview 📚: https://sorna--1967.org.readthedocs.build/en/1967/
----
📚 Documentation preview 📚: https://sorna-ko--1967.org.readthedocs.build/ko/1967/

docs: resize only on footer text in ads popup

---

.github/workflows/default.yml
pants.toml

refs https://github.com/pantsbuild/pants/releases/tag/release_2.19.1
- **chore(repo): Upgrade pants to 2.19.1**
- **chore(ci): `pants lint` now includes the visibility check**

chore: Upgrade pants to 2.19.1

---

changes/1979.misc.md
src/ai/backend/manager/api/service.py
src/ai/backend/manager/api/utils.py

chore: Revert response type of service create API

---

changes/1984.misc.md
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/session.py

I forgot to add `requested_slots` field to ComputeSession GQL class in #576..

chore: Add `requested_slots` field to compute session GQL

---

changes/1988.fix.md
src/ai/backend/manager/api/vfolder.py

fix: Revert vfolder APIs response to raw `web.Response`

---

changes/1986.fix.md
src/ai/backend/manager/models/session.py

follow-up #1396 
function default arguments should never be a mutable object such as `list` or `dict`

fix: function default argument from a mutable object to None

---

changes/1991.enhance.md
configs/manager/halfstack.toml
configs/manager/sample.toml
src/ai/backend/manager/config.py
src/ai/backend/manager/models/utils.py
tests/manager/conftest.py

Considering situations such as DB HA settings, there may be many situations where DB processes are restarted. Optimistic connection pool handling(pool-recycle, #1877) does not fully cope with these frequent DB restarts, so we introduce pessimistic DB connection pool handling, `pool-pre-ping`.
`pool-pre-ping` setting eliminates DB error due to stale pooled connections by ping at the start of each connection pool checkout.
It adds a small overhead to the connection checkout process.
ref: https://docs.sqlalchemy.org/en/14/core/pooling.html#disconnect-handling-pessimistic

feat: Enable robust DB connection handling

---

1987.misc.md
changes/1987.misc.md
src/ai/backend/manager/api/utils.py

in #1927, I disallowed all `pydantic.BaseModel` as an API response and it is forced to return only `BaseResponseModel` now.
But it undermines API functions compatibility. let's allow `pydantic.BaseModel`.

chore: Allow `pydantic.BaseModel` as API handler return schema

---

pants.toml
src/ai/backend/common/logging.py

Follow-up of #1998. This PR appends new `pants.backend.experimental.python.lint.ruff.format` package to our `pants.toml` (ref: https://github.com/pantsbuild/pants/pull/20555) to make `pants fmt ::` command work again.

fix: `pants fmt` command not working

---

pyproject.toml

Follow-up PR of #1998. This PR explicitly marks `alembic` as a third party package on ruff's isort config to avoid ruff from think that the package pretending to be a first-party one. Those confusion is caused by our `ai.backend.manager.models.alembic` package having identical name with the third-party `alembic`.

fix: pre-commit hook raising false alarm

---

.github/workflows/update-api-schema.yml
gql-inspector-checker.js

- https://github.com/lablup/backend.ai/actions/runs/8564982449?pr=1993
'||' The part that could not handle undefined because it operates as an operator is '??' Modify to use operators.
- Upgrade stefanzweifel/git-auto-commit-action@v4 using node 16 version to v5 version.

ci: Modified to operate even in deprecation reason changed situations

---

changes/2014.feature.md
python.lock
requirements.txt
src/ai/backend/common/etcd.py
src/ai/backend/common/lock.py
src/ai/backend/manager/api/stream.py

This PR updates `etcd-client-py` to version 0.3.0 and updates `AsyncEtcd` to match the changed API.
Please refer to the PR below for the changes in version 0.3.0
Ref: https://github.com/lablup/etcd-client-py/pull/9

fix: Update `etcd-client-py` to 0.3.0

---

changes/2012.fix.md
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/kernel.py

- Add "id", "domain_name" and "access_key" parameters to `resolve_compute_container()` because `scoped_query()` decorator calls resolver functions with those arguments.
- `ComputeContainer.load_slice()` should parse rows in db `stream_scalars()`, not in `stream()`
- Add `kernel_id` field to ComputeContainer Graphene schema

fix: Malfunctions in compute container resolvers

---

changes/2032.feature.md
src/ai/backend/common/types.py
src/ai/backend/manager/registry.py

Fixed #2031.
Tested manually according to the following procedure.
If there is anything I missed, please let me know.
1. Create a single cluster session
2. Check the environment variables `BACKENDAI_CLUSTER_REPLICAS`, `BACKENDAI_CLUSTER_HOSTS`.
3. Check `~/.ssh/config` file.
4. Confirm if it is possible to connect using the `ssh main1` command.
```
❯ ./backend.ai session create cr.backend.ai/stable/python:3.9-ubuntu20.04
...
❯ cat ~/.ssh/config
Host main*
Port 2200
StrictHostKeyChecking no
IdentityFile /home/config/ssh/id_cluster
❯ ./backend.ai ssh pysdk-arnoldjohn
∙ running a temporary sshd proxy at localhost:9922 ... …
```

feat: Allow self-ssh in single-node single-container compute sessions

---

changes/2038.feature.md
src/ai/backend/agent/server.py

This PR allows agent to host a UNIX domain socket which produces up-to-date snapshot of agent's `kernel_registry` and `computers` property. By exposing these informations admins should be able to monitor discrepancies of accelerator allocation status between agent and manager easier. The server can be accessed by `nc` ing socket file (e.g. `nc -U /tmp/backend.ai/ipc/agent-registry-snapshot.sock`).

feat: UNIX socket server to report agent status

---

changes/2043.feature.md
src/ai/backend/manager/registry.py

Tested manually.
```
❯ ./backend.ai ssh gPNsIaBh-session
∙ running a temporary sshd proxy at localhost:9922 ...
...
work@main1[gPNsIaBh-session]:~$ env | grep BACKENDAI_
BACKENDAI_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
BACKENDAI_CLUSTER_HOST=main1
BACKENDAI_CLUSTER_IDX=1
BACKENDAI_CLUSTER_SIZE=1
BACKENDAI_CLUSTER_LOCAL_RANK=0
BACKENDAI_CLUSTER_ROLE=main
BACKENDAI_USER_UUID=f38dea23-50fa-42a0-b5ae-338f5f4693f4
BACKENDAI_KERNEL_ID=6bd9443b-def0-41ab-aea3-aa5280c8e1ab
BACKENDAI_PREOPEN_PORTS=
BACKENDAI_SERVICE_PORTS=ipython:pty:3000,jupyter:http:8070,jupyterlab:http:8090
BACKENDAI_CLUSTER_REPLICAS=main:1
BACKENDAI_KERNEL_IMAGE=cr.backend.ai/stable/python:3.9-ubuntu20.04
BACKENDAI_SESSION_NAME=gPNsIaBh-session
BACKENDAI_USER_EMAIL=admin@lablup.com …
```

feat: Expose user info to session environment variables

---

changes/2055.fix.md
src/ai/backend/manager/api/vfolder.py

> NOTE: This bug has been reported by @agatha197 
This PR fixes delete operation failing issue when owner and user doesn't match by adding `allowe_privileged_access` according to `user_role` argument value only if the value is `SUPERADMIN` or `ADMIN`.  

fix: allow bypassing ownership check when admin role user tries to delete folder

---

changes/493.feature.md
src/ai/backend/client/auth.py
src/ai/backend/web/proxy.py
tests/client/test_auth.py

This is a follow-up of #484.
Let's automatically encrypt the payloads for user authentication and password change requests if the manager/webserver API endpoint uses the plain HTTP.

feat: Support encrypted requests in the client SDK

---

docs/dev/daily-workflows.rst
pants.toml
plugins/README.md

`./pants` is deprecated and we should use `pants` by installing it via brew or manually downloaded `scie`-based executable.
----
📚 Documentation preview 📚: https://sorna--2046.org.readthedocs.build/en/2046/
----
📚 Documentation preview 📚: https://sorna-ko--2046.org.readthedocs.build/ko/2046/

docs: Update invocation of the pants command

---

.github/workflows/coverage.yml
.github/workflows/integration.yml
actions/init-pants/action.yml

https://github.com/pantsbuild/actions/pull/29
The pr that corrects the use of deprecated node16 has been merged and distributed as v8 version.
In the case of init-pants, which I am modifying to use as a cache for self-hosted runners, I do not understand the principle well, so I need confirmation from @kyujin-cho 

ci: Bump init-pants from v5 to v8

---

.github/labeler.yml
.github/workflows/label.yml

As the labeler became version v5, its usage has changed.
```
any: match ALL globs against ANY changed path
all: match ALL globs against ALL changed paths
```
From the existing two rules that could be used,
```
any-glob-to-any-file: ANY glob must match against ANY changed file
any-glob-to-all-files: ANY glob must match against ALL changed files
all-globs-to-any-file: ALL globs must match against ANY changed file
all-globs-to-all-files: ALL globs must match against ALL changed files
```
It has been added so that it can be used in 4 ways.
- Contents in the `docs` …

ci: Bump actions/labeler from 4 to 5

---

changes/2035.doc.md
docs/install/install-from-package/prepare-cache-service.rst
docs/install/install-from-package/prepare-config-service.rst
docs/install/install-from-package/prepare-database.rst

Docker compose 'version' element has been deprecated and shows up with an obsoleted error.
On the install from Package guide, remove docker compose top-level element 'version'
Following the document https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-top-level-element , The top-level version property is defined by the Compose Specification for backward compatibility. It is only informative.
As a result, On the install from Package documents need to remove deprecated top-level version element.
Fixed https://github.com/lablup/backend.ai/issues/2034
- …

docs: remove docker compose top-level element 'version'

---

changes/2062.fix.md
src/ai/backend/manager/models/resource_usage.py

Currently resource usage APIs calculates all project/session/kernel resource in a wrong way.
1. We did not deep-copy `ResourceUsage` objects when we register it to project/session/kernel resource usage and that causes referenced fields of `ResourceUsage` are shared with unrelated project/session usages. e.g. kernel-1 has `nfs={"/vfroot/foo"}` and kernel-2 has `nfs={"/vfroot/bar"}` but the usage API results kernel-1 has `nfs={"/vfroot/foo", "/vfroot/bar"}`.
2. `total_usage` is doubled or tripled in project/session resource usages because `total_usage` is initiated when it is registered as a child resource group and project/session resource usages add the `total_usage` again after initiate a child resource group. Let's initiate child resource usages with "zero" ResourceUsage.
**Checklist:** …

fix: Resource usage wrong calculation

---

changes/2056.fix.md
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/group.py

----
📚 Documentation preview 📚: https://sorna--2056.org.readthedocs.build/en/2056/
----
📚 Documentation preview 📚: https://sorna-ko--2056.org.readthedocs.build/ko/2056/

fix: Wrong usage of dataloader in GQL group resolver

---

changes/2084.fix.md
src/ai/backend/manager/api/session.py
src/ai/backend/manager/models/session.py
src/ai/backend/manager/registry.py

This PR fixes querying `compute_session_list` with `commit_status` field raising timeout when there are large enough amount of kernels residing in the query scope. On current implementation every single `commit_status` resolver performed single followed by a database query, resulting in bursting request to both Redis and PostgreSQL. To solve these bottlenecks this PR refactored implementations of both `AgentRegistry.get_commit_status()` and `ComputeSession.resolve_commit_status()` methods so that it can benefit from redis' pipeline feature.
----
📚 Documentation preview 📚: https://sorna--2084.org.readthedocs.build/en/2084/
----
📚 Documentation preview 📚: https://sorna-ko--2084.org.readthedocs.build/ko/2084/

fix: timeout on `compute_session_list` GQL Query

---

changes/2079.feature.md
python.lock
requirements.txt
src/ai/backend/common/etcd_etcetra.py
src/ai/backend/common/lock.py
src/ai/backend/manager/config.py
src/ai/backend/manager/server.py

This PR brings back `etcetra` flavored `AsyncEtcd` implementation so that the client can remain as an option for our lock backend. These changes are temporary painkillers and should be reverted once `etcd-client-py` gets mature enough to rely on.

feat: bring back etcetra on `etcdlock`

---

tests/common/test_distributed.py

Follow up of #2079. This PR updates test cases of `test_distributed` so it can also take a look at `etcetra`-backend `etcdlock` implementation.

chore(tests): update `test_distributed` unit test definition

---

changes/2102.fix.md
src/ai/backend/manager/models/resource_usage.py

follow-up #2062, #962
`KernelResourceUsage.total_usage` field is empty currently
Let's not initiate its `total_usage` field with 0(or null) values.

fix: Initialization of kernel-level usage aggregation in the resource usage API

---

src/ai/backend/client/cli/admin/domain.py
src/ai/backend/client/func/domain.py

Domain's purge help text explains delete.
Of course, delete and purge are words used with similar meanings, but there is a command called domain delete, which can confuse users.
```
Delete the given virtual folder.
Purge the given virtual folder.
```
I modified it by referring to the vfolder delete and purge help phrases above.

fix: Modify help text for delete and purge domain

---

changes/2080.feature.md
configs/manager/sample.toml
src/ai/backend/common/lock.py
src/ai/backend/manager/config.py
src/ai/backend/manager/server.py

Some distribute locks need detail configuration.
Let's enable it with config validation backward compatibility.

feat: Make distributed-lock backends configurable

---

.github/workflows/backport.yml

For automation, use the PAT of the newly created OCTODOG account.

ci: Fix backport workflow’s PAT settings

---

src/ai/backend/test/cli_integration/user/test_vfolder.py

follow-up #1778 
Many of cli integration test codes check success by asserting output messages.
Some CLI output message changed in #1803 and we need to update the test codes. 

fix: Wrong success check of vfolder cli integration test

---

src/ai/backend/client/cli/extensions.py

follow-up #2147 
Updated mypy found an typing error in main branch
Let's fix it !!

fix: typing update in CLI decorator function

---

changes/2144.fix.md
src/ai/backend/storage/gpfs/gpfs_client.py

- Place retrying codes into async-attempt context so that it can actually wait for `wait_for` seconds.
- Skip waiting `create_fileset` job when the given fileset already exists
Tested on real GPFS API server

fix: Make GPFS plugin reliable

---

changes/2155.fix.md
src/ai/backend/manager/scheduler/dispatcher.py

Currently, a scheduler fetches one list of all pending session in a given scaling group and it iterates them to schedule pending sessions one by one.
If one of the pending sessions raises `InstanceNotAvailable` or `GenericBadRequest` exceptions (which is normal), the scheduler skips all trailing pending sessions in the list.
The scheduler should keep iterating, not stop scheduling.

fix: Ensure that all pending sessions are picked by schedulers

---

changes/2077.fix.md
src/ai/backend/manager/cli/__main__.py

follow-up #576 
Let the `backend.ai mgr clear-history` command clears session records as well as kernel records.

fix: clear-history sessions as well as kernels

---

README.md
scripts/download-webui-release.sh

https://github.com/lablup/backend.ai/commit/a24796ddbe4abf166572f3c116da6b62354248b1
As the method of updating the built webui file has been changed to downloading the distribution from the subtree, there is no need to add backend.ai-app remotely.
Additionally, exception handling logic for the script has been added.
----
📚 Documentation preview 📚: https://sorna--2131.org.readthedocs.build/en/2131/
----
📚 Documentation preview 📚: https://sorna-ko--2131.org.readthedocs.build/ko/2131/

docs: Remove scripts not needed for webui update

---

changes/2162.fix.md
src/ai/backend/agent/docker/agent.py
src/ai/backend/manager/registry.py
src/ai/backend/runner/entrypoint.sh

Fixes #2151, follow-up of #1530.
This PR fixes the security vulnerability in `sudo_session_enabled` that was implemented using environment variables.

fix: Security vulnerability of sudo session enablement

---

changes/2170.fix.md
src/ai/backend/storage/api/manager.py
src/ai/backend/storage/netapp/__init__.py
src/ai/backend/storage/netapp/netappclient.py

There might be a slight delay between qtree-creation-job success response and the directory creation.
Let's poll after `create_qtree`

fix: Netapp `create_qtree` timing issue

---

changes/2036.feature.md
src/ai/backend/manager/models/alembic/versions/31463788c713_add_index_sessions_vfolder_mounts.py
src/ai/backend/manager/models/base.py
src/ai/backend/manager/models/session.py
src/ai/backend/manager/models/vfolder.py

resolves #776 
- The mount lookup happens only when we **"delete"** vfolders, not when we **"delete-forever"** them since it is already disallowed to delete-forever the READY vfolders
- Apply [GIN index](https://www.postgresql.org/docs/current/datatype-json.html#JSON-INDEXING) to `sessions.vfolder_mounts` column

feature: Prevent deleting mounted folders

---

scripts/check-docker.py
scripts/install-dev.sh

This PR resolves `install-dev.sh` script failing due to recent changes in `requests` library by lifting up dependencies to `requests` and instead benefiting from `aiohttp`'s native Unix Domain Socket connector feature.

fix: `check-docker.py` script not working

---

src/ai/backend/manager/models/base.py

This PR implements new `gql_mutation_wrapper()` to get rid of logics duplicated at `simple_db_mutate_returning_item()` and `simple_db_mutate()` and to allow GQL Mutation resolvers higher level of customization.

feat: implement `gql_mutation_wrapper()` function

---

changes/2165.feature.md
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/endpoint.py
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/group.py
src/ai/backend/manager/models/user.py
src/ai/backend/manager/models/vfolder.py

This PR adds new `VirtualFolderNode` GQL Query, which acts as an another version of `VirtualFolder` GQL Query with relay support.
----
📚 Documentation preview 📚: https://sorna--2165.org.readthedocs.build/en/2165/
----
📚 Documentation preview 📚: https://sorna-ko--2165.org.readthedocs.build/ko/2165/
----
📚 Documentation preview 📚: https://sorna--2165.org.readthedocs.build/en/2165/
----
📚 Documentation preview 📚: https://sorna-ko--2165.org.readthedocs.build/ko/2165/

feat: implement Relay-style VirtualFolderNode GQL query

---

src/ai/backend/manager/api/service.py
src/ai/backend/manager/models/endpoint.py

This PR abstracts model service validation logic to another class so that it can be reused on consequent occurrences.
----
📚 Documentation preview 📚: https://sorna--2166.org.readthedocs.build/en/2166/
----
📚 Documentation preview 📚: https://sorna-ko--2166.org.readthedocs.build/ko/2166/
----
📚 Documentation preview 📚: https://sorna--2166.org.readthedocs.build/en/2166/
----
📚 Documentation preview 📚: https://sorna-ko--2166.org.readthedocs.build/ko/2166/

feat: split out predicate check logic

---

changes/2167.feature.md
src/ai/backend/manager/models/endpoint.py

This PR updates `ModifyEndpoint` so that it can perform same service validation process with service creation process.
---

feat: model service validation process for `ModifyEndpoint`

---

src/ai/backend/client/cli/service.py
src/ai/backend/client/func/service.py

This PR updates CLI to be aware of newly added `extra_mounts` parameter when creating or updating model service.

feat: update CLI to support controlling `extra_mounts` parameter

---

changes/2175.fix.md
src/ai/backend/manager/registry.py

This is an auto-generated backport PR of #2175 to the 24.03 release.

fix: invalid concurrency calculation logic (#2175)

---

src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/api/service.py
src/ai/backend/manager/models/endpoint.py

----
📚 Documentation preview 📚: https://sorna--2065.org.readthedocs.build/en/2065/
----
📚 Documentation preview 📚: https://sorna-ko--2065.org.readthedocs.build/ko/2065/

feat: expose `model_definition_filename` field to API responses

---

src/ai/backend/client/cli/service.py
src/ai/backend/client/func/service.py

This PR updates Backend.AI Client so that users can customize `model_definition_path` value when using Python SDK.

feat: update CLI to be aware of `model_definition_path` parameter

---

changes/2146.feature.md
src/ai/backend/client/cli/admin/resource_policy.py
src/ai/backend/client/func/keypair_resource_policy.py
src/ai/backend/client/output/fields.py
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/resource_policy.py

This is an auto-generated backport PR of #2146 to the 24.03 release.

feat: Add missing fields of keypair resource policy (#2146)

---

src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/api/service.py
src/ai/backend/manager/models/endpoint.py

This is an auto-generated backport PR of #2065 to the 24.03 release.

feat: expose `model_definition_filename` field to API responses (#2065)

---

changes/2124.fix.md
src/ai/backend/agent/agent.py

This is an auto-generated backport PR of #2124 to the 24.03 release.

fix: model server started on every kernels (#2124)

---

pants.toml

Release note: https://github.com/pantsbuild/pants/blob/release_2.21.0/src/python/pants/notes/2.21.x.md

chore: Upgrade pants to 2.21.0

---

pants.toml

This is an auto-generated backport PR of #2222 to the 24.03 release.

chore: Upgrade pants to 2.21.0 (#2222)

---

.github/workflows/backport.yml

To resolve the difference between the milestone and the actually managed Release branch, first check whether the branch actually exists in the milestone list and add it to the backport target.

ci: Check whether the branch actually exists

---

changes/2226.fix.md
src/ai/backend/client/cli/session/ssh.py

When packaged as SCIE-based executable, `backend.ai ssh` command does not work
because the inner Python subprocess cannot find the location of the
`ai.backend` package namespace.
This PR fixes this issue by executing the PEX package when the `PEX`
environment variable is detected.

fix: Self-execution under SCIE/PEX-based envs

---

changes/2226.fix.md
src/ai/backend/client/cli/session/ssh.py

This is an auto-generated backport PR of #2226 to the 24.03 release.

fix: Self-execution under SCIE/PEX-based envs (#2226)

---

changes/2229.feature.md
src/ai/backend/manager/scheduler/dispatcher.py

This PR adds an extra logic to `scale_services()` scheduler, which inspects existence of zombie routes (routes not removed despite upstream session already in dead status) and automatically clears it before starting route scheduling.

feat: collect zombie routes automatically

---

changes/2203.fix.md
src/ai/backend/manager/models/base.py

This is an auto-generated backport PR of #2202 to the 24.03 release.

fix: import graphql ast node correctly (#2202)

---

src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/api/service.py
src/ai/backend/manager/models/endpoint.py

Follow-up PR of #2200. Since current implementation of Backend.AI agent has no way to discover which folder is the one designated to act as model VFolder it is better to fundamentally block multiple MODEL vfolders from being attached to a session.
----
📚 Documentation preview 📚: https://sorna--2237.org.readthedocs.build/en/2237/
----
📚 Documentation preview 📚: https://sorna-ko--2237.org.readthedocs.build/ko/2237/

fix: disallow mounting `MODEL` VFolders via extra_mounts on model service

---

src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/api/service.py
src/ai/backend/manager/models/endpoint.py

This is an auto-generated backport PR of #2237 to the 24.03 release.

fix: disallow mounting  VFolders via extra_mounts on model service (#2237)

---

src/ai/backend/manager/models/image.py
src/ai/backend/manager/models/kernel.py

Upon changes applied from #2136 we need to ensure every `ImageRow`s passed to `ImageNode.from_row()` requires `aliases` relationships to be loaded.

fix: missing eager load to `aliases` row

---

src/ai/backend/manager/models/image.py
src/ai/backend/manager/models/kernel.py

This is an auto-generated backport PR of #2239 to the 24.03 release.

fix: missing eager load to `aliases` row (#2239)

---

src/ai/backend/manager/models/image.py

follow-up #1973 #2136
If superadmins request GQL images query with `filters=["customized"]` parameter, the resolver does not filter out images without any of `operation` or `customized` labels, and it returns all types of images.
Let's fix it

fix: Let GQL images resolver filter out image objects correctly

---

.github/workflows/backport.yml

If commit_message contains special characters in the shell string, such as backticks, there is a problem in that it is not processed as is.
Changed the string to be treated as a single quote and treated as all characters.

ci: Missing string in backticks in commit message of backport PR

---

.github/workflows/alembic-head-check.yml
.github/workflows/default.yml
.github/workflows/docs-preview.yml
.github/workflows/timeline-check.yml

If you use the method of adding flow:merge-queue to pr, which is one of the methods of using graphite's merge queue, all CIs triggered by labeled will be executed again, creating a bottleneck in the development cycle.

ci: If a graphite-related label is added, actions are not executed

---

.github/workflows/timeline-check.yml

As you upgrade to GitHub enterprise plan, the default permissions for actions change, so you must explicitly write the permissions required for the workflow.

ci: Explicitly adding permissions because the default permissions have changed

---

.github/workflows/update-api-schema.yml

follow-up #2265
Due to node.js v16 deprecated, upgraded to a version using node.js v20

ci: Bump graphql-inspector from 4.0.2 to 5.0.6

---

src/ai/backend/manager/models/utils.py
tests/manager/models/test_dbutils.py

This is a stacked PR migrated from #1817
Improve PostgreSQL connection management.
The point is replacing connection retry function `execute_with_retry()` to transaction retry function `execute_with_txn_retry()`.
`sqlalchemy.Connection` object and `sqlalchemy.Engine` object can open DB transactions.
We can open multiple transactions in a single DB connection by calling `Connection.begin()` while calling `Engine.begin()` opens a new DB connection for every transaction.
Currently Backend.AI Manager opens a new DB connection for every DB transaction and it can cause connection burden especially when it runs `models.utils.execute_with_retry()` which retries entire DB connection.
Let's decrease the connection burden by managing a lifecycle of `Connection`s and retry DB transaction within a …

feature: enhanced PostgreSQL connection mgmt

---

changes/2255.feature.md
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/endpoint.py

This PR updates `ModifyEndpoint` mutation to allow altering environment variable definition of model service session.

feat: allow modifying model service env var

---

.github/workflows/update-api-schema.yml

Same as #2265, the default value of actions permission is changed to explicitly add write permission.

ci: Grant write permission required for actions

---

src/ai/backend/common/events_experimental.py
src/ai/backend/common/redis_client.py

Follow-up PR of #2041. Fixes `EventDispatcher` utilizing vanilla `msgpack` package instead of our customized one.

fix: invalid msgpack package utilized on experimental `EventDispatcher`

---

changes/2287.fix.md
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/gql.py

This is an auto-generated backport PR of #2287 to the 24.03 release.

fix: incorrect parameter defined under `endpoint_list` query (#2287)

---

changes/2288.fix.md
src/ai/backend/agent/docker/agent.py

This is an auto-generated backport PR of #2288 to the 24.03 release.

fix: `ai.backend.service-ports` container label syntax broken (#2288)

---

changes/2289.fix.md
src/ai/backend/manager/container_registry/harbor.py

This is an auto-generated backport PR of #2289 to the 24.03 release.

fix: improve stability of `untag_image_from_registry` mutation (#2289)

---

changes/2291.fix.md
src/ai/backend/agent/docker/intrinsic.py

This is an auto-generated backport PR of #2291 to the 24.03 release.

fix: invalid container memory capacity reported (#2291)

---

changes/2290.fix.md
src/ai/backend/agent/docker/kernel.py
src/ai/backend/kernel/intrinsic.py

This is an auto-generated backport PR of #2290 to the 24.03 release.

fix: SSH not working between kernels started with customized image (#2290)

---

.github/workflows/update-api-schema.yml

This is an auto-generated backport PR of #1981 to the 24.03 release.

chore(deps): bump actions/setup-python from 4 to 5 (#1981)

---

.github/workflows/default.yml

This is an auto-generated backport PR of #2303 to the 23.09 release.

ci: Bump action-gh-release from v1 to v2 (#2303)

---

src/ai/backend/manager/models/kernel.py

We are migrating [imperative mapping](https://docs.sqlalchemy.org/en/20/orm/mapping_styles.html#imperative-mapping) to [declarative mapping](https://docs.sqlalchemy.org/en/20/orm/mapping_styles.html#imperative-mapping).
Add `KernelRow` declarative ORM class and leave `kernels` table object for compatibility

chore: Migrate imperative `kernels` table to declarative `KernelRow` ORM class

---

src/ai/backend/manager/models/alembic/versions/d7df3baf3779_add_vfolders_domain_name.py
src/ai/backend/manager/models/alembic/versions/fdb2dcdb8811_add_vfolder_permissions_id.py
src/ai/backend/manager/models/vfolder.py

Since we cannot move or migrate existing vfolders to other domain, let's add `domain_name` column to vfolders table.
And I added `vfolder_permissions.id` column for easy query

chore: Add `vfolders.domain_name` and `vfolder_permissions.id`

---

changes/2321.fix.md
src/ai/backend/agent/docker/intrinsic.py

This is an auto-generated backport PR of #2321 to the 24.03 release.

hotfix: metric collection not working (#2321)

---

changes/2318.fix.md
src/ai/backend/agent/agent.py

This is an auto-generated backport PR of #2318 to the 24.03 release.

hotfix: invalid enum string set as fallback value (#2318)

---

src/ai/backend/manager/api/vfolder.py

follow-up #2271 
Insert `vfolders.domain_name` when create a new vfolders

fix: insert vfolders with `domain_name`

---

changes/2250.fix.md
src/ai/backend/manager/models/gql.py

This pull request is a follow-up of #2136.
It has been observed that the `images(is_installed: Boolean)` GraphQL queries would fail to query `images(is_installed: false)` due to:
https://github.com/lablup/backend.ai/blob/05da1590095a61677402211cc84e74a07340b276/src/ai/backend/manager/models/gql.py#L1175-L1176
----
📚 Documentation preview 📚: https://sorna--2250.org.readthedocs.build/en/2250/
----
📚 Documentation preview 📚: https://sorna-ko--2250.org.readthedocs.build/ko/2250/

fix: Allow GraphQL query to non-installed images

---

.github/workflows/update-api-schema.yml

By default, events performed by github-actions-bot do not trigger other actions.
So, after the graphql action was executed, there was a problem where prs could not be merged because the action was not triggered.

ci: octodog performs graphql schema dump commit

---

.github/workflows/update-api-schema.yml

This is an auto-generated backport PR of #2344 to the 24.03 release.

ci: octodog performs graphql schema dump commit (#2344)

---

src/ai/backend/manager/models/utils.py

follow-up #2088 
When handling DB serialization error in `ai.backend.manager.models.utils.execute_with_txn_retry()`, the handling context should include the `async with begin_trx(bind=connection) as session_or_conn: ...` line since `SerializationError` occurs in `begin_trx()`.
```
File "/Users/sh/bai-dev/src/ai/backend/manager/models/utils.py", line 274, in execute_with_txn_retry
async with begin_trx(bind=connection) as session_or_conn:
File "/Users/sh/.pyenv/versions/3.12.2/lib/python3.12/contextlib.py", line 217, in __aexit__
await anext(self.gen)
File "/Users/sh/bai-dev/src/ai/backend/manager/models/utils.py", line 171, in begin_session
async with _begin_session(bind) as sess:
File "/Users/sh/.pyenv/versions/3.12.2/lib/python3.12/contextlib.py", line 217, in __aexit__
await …
```

fix: handle DB serialization error when transaction begins

---

.github/workflows/default.yml

Previously, GitHub has triggered the typecheck and test workflows when adding `flow:merge-queue` and `flow:hotfix` labels to add the PR to the Graphite merge-queue.
This is a duplicated check as the merge-queue itself will run the CI again.
Let's skip those workflows when just adding those `flow:*` labels.
This PR is a follow up of #2261, which did it for the lint and other required workflows.

ci: Skip typecheck & test when adding Graphite merge-queue labels

---

.github/workflows/pr-prefix.yml

This PR updates the PR title prefix checker as follows:
- Allow `chore:` in addition to the `chore(...):` pattern.
- Allow `deps:`.
- Allow `doc:` in addition to `docs:`.
- Align inner indentation of the error message for better readability.

ci: Update the regex and list of the PR title prefix checker

---

changes/2339.deps.md
python.lock
requirements.txt
src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/docker/intrinsic.py
src/ai/backend/agent/docker/kernel.py
src/ai/backend/agent/docker/utils.py
src/ai/backend/agent/dummy/kernel.py
src/ai/backend/agent/kernel.py
src/ai/backend/agent/kubernetes/intrinsic.py
src/ai/backend/agent/kubernetes/kernel.py
src/ai/backend/agent/kubernetes/utils.py

* fix,refactor: Various bug-fixes and code cleanup for session file up/download APIs
- Improve consistency of the local variable names to indicate whether a path-related value is for the host, for the container, or a logical subpath of the mountpoint. (e.g., `container_abspath`, `host_abspath`, `home_relpath`)
- Explicitly use `pathlib.PurePosixPath` to store and manipulate the container-side paths in the agent code, while using `pathlib.Path` to store and manipulate the host-side paths. The difference is that we CANNOT use `.resolve()` method in pure paths as it requires access to the filesystem.
- FYI: [pure paths](https://docs.python.org/3/library/pathlib.html#pure-paths) vs. [concrete paths](https://docs.python.org/3/library/pathlib.html#concrete-paths)
- I had to use …

deps: Upgrade aiodocker to 0.22

---

changes/2250.fix.md
src/ai/backend/manager/models/gql.py

This is an auto-generated backport PR of #2250 to the 24.03 release.

fix: Allow GraphQL query to non-installed images (#2250)

---

changes/2160.fix.md
src/ai/backend/manager/models/user.py

This is an auto-generated backport PR of #2160 to the 24.03 release.

fix: Handle user creation failure when model-store does not exists (#2160)

---

changes/2314.fix.md
src/ai/backend/manager/models/user.py

This is an auto-generated backport PR of #2314 to the 24.03 release.

fix: typo of user queryfilter (#2314)

---

changes/2245.fix.md
src/ai/backend/manager/api/vfolder.py

This is an auto-generated backport PR of #2245 to the 24.03 release.

fix: Avoid `ZeroDivisionError` in volume usage calculation (#2245)

---

changes/2392.fix.md
src/ai/backend/agent/server.py

follow-up #2038 
Cleanup agent process has not worked properly since cancelled `debug_server_task` is awaited.
`asyncio.Task` should not be awaited if it has already been cancelled.
ref: https://docs.python.org/3.12/library/asyncio-task.html#task-cancellation

fix: Skip waiting cancelled task to shutdown agent properly

---

changes/2392.fix.md
src/ai/backend/agent/server.py

This is an auto-generated backport PR of #2392 to the 24.03 release.

fix: Skip waiting cancelled task to shutdown agent properly (#2392)

---

changes/2178.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/agent.py
src/ai/backend/common/events.py

`sync_containers_lifecycle()` should work
We have 3 different sources of Kernel / Container data
1. Manager side DB
2. Agent side `kernel_registry`
3. Agent side actual docker containers
I tried to synchronize ALL Agent's data to Manager's DB but synchronizing actual containers to `kernel_registry` or manager's data needs to process container destruction tasks which take a long time.
Since `sync_containers_lifecycle()` task synchronizes actual containers to `kernel_registry` periodically in background, resource-sync API only needs to sync `kernel_registry` to Manager side DB if it is ensured that the background task stays alive and works as we expect.
- Keep `sync_container_lifecycles()` bgtask alive in a loop by handling any exceptions raised in the task.
- In the try-except context of …

fix: Keep `sync_container_lifecycles()` bgtask alive in a loop.

---

changes/2178.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/agent.py
src/ai/backend/common/events.py

This is an auto-generated backport PR of #2178 to the 24.03 release.

fix: Keep `sync_container_lifecycles()` bgtask alive in a loop. (#2178)

---

changes/2379.misc.md
pants.toml
scripts/clear-test-containers.sh
src/ai/backend/common/redis_helper.py
src/ai/backend/testutils/bootstrap.py
tests/BUILD
tests/common/BUILD
tests/common/conftest.py
tests/common/redis_helper/BUILD
tests/common/redis_helper/conftest.py
tests/common/redis_helper/docker.py
tests/common/redis_helper/redis-cluster.yml
tests/common/redis_helper/test_list.py
tests/common/redis_helper/types.py
tests/conftest.py
tests/manager/BUILD

This PR **_finally_** stabilizes the hanging test issue in the CI.
It introduces a _monotonically increasing counter_ to allocate TCP ports for all containers spawned in a single parallel-slot of test executions.
Also fixes a long-cherished problem with the duplicate module errors when running mypy via `pants check` due to a misplaced root directory `tests` in `pants.toml` (it shouldn't be there).
Increased the per-module test timeout for `test_distributed.py` from 30 seconds to 60 seconds as the etcdlock tests using the new EventDispatcher seems to take a little bit longer than expected.
> [!NOTE]
> In the future, we should increase the parallel slot multiplier in `get_next_tcp_port()` in the `ai.backend.testutils.bootstrap` module as we add more test cases using fixture containers.
> …

fix: Hanging tests due to docker-internal races for TCP ports

---

changes/2379.misc.md
pants.toml
scripts/clear-test-containers.sh
src/ai/backend/common/redis_helper.py
src/ai/backend/testutils/bootstrap.py
tests/BUILD
tests/common/BUILD
tests/common/conftest.py
tests/common/redis_helper/BUILD
tests/common/redis_helper/conftest.py
tests/common/redis_helper/docker.py
tests/common/redis_helper/redis-cluster.yml
tests/common/redis_helper/test_list.py
tests/common/redis_helper/types.py
tests/conftest.py
tests/manager/BUILD

This is an auto-generated backport PR of #2379 to the 24.03 release.

fix: Hanging tests due to docker-internal races for TCP ports (#2379)

---

src/ai/backend/testutils/bootstrap.py

It's a follow-up to #2396 and #2379.
This PR fixes a minor bug that may affect the local test runners who repeat running tests until the counter reaches the end of the range.

fix: A minor range calculation bug in #2396

---

.github/workflows/update-api-schema.yml

Backported-from: main (24.09)
Backport-of: 2267

ci: Bump graphql-inspector from 4.0.2 to 5.0.6 (#2267)

---

changes/2404.enhance.md
src/ai/backend/manager/models/alembic/versions/59a622c31820_remove_foreign_key_in_vfolders_user_and_project.py
src/ai/backend/manager/models/group.py
src/ai/backend/manager/models/user.py
src/ai/backend/manager/models/vfolder.py

refs #2376
Remove the foreign/check constraints preventing decoupling of user/vfolder deletions.

refactor: Remove the foreign key constraint of vfolders.{user,group}

---

changes/2409.feature.md
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/group.py

Added the `row_id`, `type` and `container_registry` fields to the `GroupNode` class in the `group.py` file. These fields were introduced in version 24.03.7.
Added three new fields to GroupNode class: `row_id`, `type`, and `container_registry`. Also updated `schema.graphql` and methods in `group.py` to reflect these changes.
Verify that the new fields are properly integrated and can be accessed as expected through the GraphQL queries.
These fields provide more detailed information about the group and have been introduced in the latest version 24.03.7 to improve the system's functionality.
- Demonstrate the flow of abstract/conceptual models with a …

feat: Add `row_id`, `type` and `container_registry` fields to GroupNode GQL schema

---

changes/2409.feature.md
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/group.py

This is an auto-generated backport PR of #2409 to the 24.03 release.

feat: Add `row_id`, `type` and `container_registry` fields to GroupNode GQL schema (#2409)

---

.github/workflows/default.yml
.github/workflows/sbom.yml

Invoke the SBOM report generation workflow when either:
- a tagged commit is pushed for releases. (Since the release workflow depends on the SBOM generation, this condition should be included.)
- a PR is merged.

ci: Invoke the SBOM report generation only when required

---

.github/workflows/default.yml
.github/workflows/sbom.yml

This is an auto-generated backport PR of #2407 to the 24.03 release.

ci: Invoke the SBOM report generation only when required (#2407)

---

changes/2415.fix.md
src/ai/backend/manager/api/exceptions.py

This pull request fixes potential errors caused by invalid attempt to serialize `UUID` object.
| Before | After |
| ------- | ----- |
| ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/xO1yT8FVVJioYjE5byZ6/213d9a20-e93e-4436-ab35-9dfa5174a053.png) | <img width="613" alt="스크린샷 2024-07-10 오후 4 38 20" src="https://github.com/lablup/backend.ai/assets/14137676/e2ee265c-b18c-4a52-8549-f1fe3c40ed7e"> |
----
📚 Documentation preview 📚: https://sorna--2415.org.readthedocs.build/en/2415/
----
📚 Documentation preview 📚: https://sorna-ko--2415.org.readthedocs.build/ko/2415/

fix: Utilize `ExtendedJSONEncoder` for error logging to handle `UUID` extra data

---

changes/2421.fix.md
src/ai/backend/manager/api/events.py

follow-up #576
Some functions in event module still reference the `kernels` table when processing session events.
They should reference the `sessions` table rather than `kernels` table.
----
📚 Documentation preview 📚: https://sorna--2421.org.readthedocs.build/en/2421/
----
📚 Documentation preview 📚: https://sorna-ko--2421.org.readthedocs.build/ko/2421/

fix: Change outdated reference in event module from kernels to sessions

---

changes/2421.fix.md
src/ai/backend/manager/api/events.py

This is an auto-generated backport PR of #2421 to the 24.03 release.

fix: Change outdated reference in event module from kernels to sessions (#2421)

---

changes/2429.fix.md
src/ai/backend/manager/api/vfolder.py
src/ai/backend/manager/models/vfolder.py

`query_accessible_vfolders()` does not query vfolders whose status is `DELETE_COMPLETE`.
Let's enable purge by allowing querying such vfolders.
----
📚 Documentation preview 📚: https://sorna--2429.org.readthedocs.build/en/2429/
----
📚 Documentation preview 📚: https://sorna-ko--2429.org.readthedocs.build/ko/2429/

fix: Allow specific status of vfolders to query to purge

---

src/ai/backend/manager/models/vfolder.py

fix: Allow vfolders in delete-pending status to be deleted forever

---

src/ai/backend/manager/models/vfolder.py

This is an auto-generated backport PR of #2431 to the 24.03 release.

fix: Allow vfolders in delete-pending status to be deleted forever (#2431)

---

src/ai/backend/manager/models/kernel.py
src/ai/backend/manager/models/session.py
src/ai/backend/manager/models/utils.py

As #2088 has been merged, we can control the lifetime of DB connections and DB transactions granularly. I suggest how we should manage DB connections and transactions.
There are two main entrypoints of the code paths in the Manager.
- API handlers (webapps)
- Event dispatch handlers (consumers, subscribers)
These entrypoints invoke inner layers like AgentRegistry and the database model functions.
Generally, it is better to reuse a single connection to perform multiple transactions.
- Ideally, we should keep only one database connection for each code path starting from an entrypoint.
- However, connection reuse should be implemented via connection pools, instead of the application logic, particularly when it is not feasible to predict how long an operation will take in the application …

chore: Impl status-update interface for Session/Kernel ORM objects

---

changes/2338.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/config.py

Let's make `sync_container_lifecycles()` task configurable to turn on/off and set the interval seconds.

feat: Enable to configure sync_container_lifecycles task

---

changes/2338.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/config.py

This is an auto-generated backport PR of #2338 to the 24.03 release.

feat: Enable to configure sync_container_lifecycles task (#2338)

---

changes/2316.misc.md
src/ai/backend/agent/docker/agent.py

- Separate the exception context of `container.create()` and `container.start()` to handle them granularly.
- Scratch clean codes to `clean_scratch()`

refactor: Handle container start error in separate try-catch context

---

changes/2415.fix.md
src/ai/backend/manager/api/exceptions.py

This is an auto-generated backport PR of #2415 to the 24.03 release.

fix: Utilize `ExtendedJSONEncoder` for error logging to handle `UUID` extra data (#2415)

---

changes/2404.enhance.md
src/ai/backend/manager/models/alembic/versions/59a622c31820_remove_foreign_key_in_vfolders_user_and_project.py
src/ai/backend/manager/models/group.py
src/ai/backend/manager/models/user.py
src/ai/backend/manager/models/vfolder.py

This is an auto-generated backport PR of #2404 to the 24.03 release.

refactor: Remove the foreign key constraint of vfolders.{user,group} (#2404)

---

changes/2436.fix.md
scripts/install-dev.sh
src/ai/backend/install/dev.py

https://github.com/lablup/backend.ai-webui/pull/2515
If the above pr is applied, webui will use pnpm as the package manager from now on.
So, in the webui build script part, we also use pnpm.

ci: Change package manager from npm to pnpm

---

changes/2436.fix.md
scripts/install-dev.sh
src/ai/backend/install/dev.py

This is an auto-generated backport PR of #2436 to the 24.03 release.

ci: Change package manager from npm to pnpm (#2436)

---

changes/2316.misc.md
src/ai/backend/agent/docker/agent.py

This is an auto-generated backport PR of #2316 to the 24.03 release.

refactor: Handle container start error in separate try-catch context (#2316)

---

.github/workflows/update-api-schema.yml

As backport automation was performed, a workflow to verify that the schema was correct became necessary even in previous release branches.
So, previously, the main branch's schema was used as the base file, but now the base branch's schema file is used.

ci: Schema uses the files of the base branch

---

.github/workflows/update-api-schema.yml

This is an auto-generated backport PR of #2412 to the 24.03 release.

ci: Schema uses the files of the base branch (#2412)

---

docs/client/cli/sessions.rst
docs/locales/ko/LC_MESSAGES/client/cli/sessions.po

This is an auto-generated backport PR of #1758 to the 24.03 release.

docs: Update the docs for options of the session list command (#1758)

---

changes/2127.fix.md
src/ai/backend/manager/models/kernel.py
src/ai/backend/manager/models/session.py

This is an auto-generated backport PR of #2127 to the 24.03 release.

fix: Add missing `commit_session_to_file` to `OP_EXC` (#2127)

---

docs/dev/daily-workflows.rst

This is an auto-generated backport PR of #2025 to the 24.03 release.

docs: update guide about writing down new REST API (#2025)

---

changes/2134.fix.md
src/ai/backend/agent/docker/kernel.py
src/ai/backend/manager/registry.py

This is an auto-generated backport PR of #2134 to the 24.03 release.

fix: Pass ImageRef.canonical in `commit_session_to_file` (#2134)

---

changes/2449.deps.md
docs/dev/daily-workflows.rst
docs/install/install-from-package/os-preparation.rst
pants.toml
pyproject.toml
python-kernel.lock
python.lock
scripts/bootstrap-static-python.sh
scripts/delete-dev.sh
src/ai/backend/install/README.md
tools/black.lock
tools/coverage-py.lock
tools/mypy.lock
tools/pants-plugins/scie/README.md
tools/pants-plugins/scie/config.py
tools/pants-plugins/scie/subsystems.py
tools/pytest.lock
tools/ruff.lock
tools/setuptools.lock
tools/towncrier.lock

This is an auto-generated backport PR of #2449 to the 24.03 release.

deps: Upgrade Python (3.12.2 -> 3.12.4) (#2449)

---

changes/2424.fix.md
python.lock
requirements.txt

This is an auto-generated backport PR of #2424 to the 24.03 release.

deps: Update `inquirer` to remove dependency on deprecated `distutils` (#2424)

---

src/ai/backend/helpers/package.py
src/ai/backend/manager/cli/__main__.py

This is an auto-generated backport PR of #2023 to the 24.03 release.

chore: migrate `subprocess.call()` usages to `.run()` (#2023)

---

changes/2401.fix.md
src/ai/backend/manager/models/gql.py

This is an auto-generated backport PR of #2401 to the 24.03 release.

fix: Restrict GraphQL query to `user_nodes` field to require `superadmin` privilege (#2401)

---

.github/workflows/backport.yml

Similar to #2285, the default permissions of GITHUB_TOKEN have been reduced and the necessary permissions are granted directly in the workflow.
Add the pull-requests wirte permission to write a comment indicating that actions-bot must manually backport when backport fails.

ci: Grant pull request write permission to backport job

---

changes/2460.fix.md
src/ai/backend/agent/docker/intrinsic.py

This PR updates the filesystem pruning logic to excluded additional cases like
`/proc/docker/runtime-runc/moby/` filesystems temporarily created by Docker.

fix: Prune additional filesystem patterns from statvfs

---

.github/workflows/default.yml

This PR updates the runner configuration for building linux-aarch64 binaries to use GitHub-hosted Linux ARM64 runners (finally!).
It also explicitly sets the names on the checkout steps to clarify that they are not full clones but revision checkouts.

chore(ci): Update the arm64 runner config

---

changes/2460.fix.md
src/ai/backend/agent/docker/intrinsic.py

This is an auto-generated backport PR of #2460 to the 23.09 release.

fix: Prune additional filesystem patterns from statvfs (#2460)

---

changes/2317.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/kernel.py
src/ai/backend/agent/types.py

This is an auto-generated backport PR of #2317 to the 24.03 release.

fix: Omit cleaning containerless kernels which are still creating its container (#2317)

---

.github/workflows/alembic-head-check.yml
.github/workflows/assign-pr-number.yml
.github/workflows/backport.yml
.github/workflows/check-requirement.yml
.github/workflows/coverage.yml
.github/workflows/default.yml
.github/workflows/integration.yml
.github/workflows/sbom.yml
.github/workflows/timeline-check.yml
.github/workflows/update-api-schema.yml
tests/agent/conftest.py
tests/agent/docker/test_agent.py

We have been hitting a rapid increase of LFS storage bandwidth usage recent days.
This PR is an effort to optimize the usage.
It _explicitly disables_ LFS pulling in all per-commit GitHub Actions workflows, leaving LFS pulls only for:
- individual files only when required by selected tests, without caching
- the release/build jobs without caching (as there is no need to cache for such infrequent jobs)
- the integration (once per day, or manually triggered) and coverage tests (run per PR merge) with caching
**Example:**
In the agent tests, let developers use the `socket_relay_image` session-scoped fixture only in required test cases to pull the image tarball stored as LFS files.

ci: Minimize LFS fetches in CI

---

changes/2411.fix.md
src/ai/backend/manager/scheduler/dispatcher.py

This is an auto-generated backport PR of #2411 to the 24.03 release.

fix: Handle all possible exceptions when scheduling single node session (#2411)

---

src/ai/backend/web/assets/backend.ai-local-proxy-linux-arm64.zip
src/ai/backend/web/assets/backend.ai-local-proxy-linux-x64.zip
src/ai/backend/web/assets/backend.ai-local-proxy-macos-arm64.zip
src/ai/backend/web/assets/backend.ai-local-proxy-macos-x64.zip

This is an auto-generated backport PR of #2485 to the 24.03 release.

ci: Remove no longer used LFS files (#2485)

---

changes/2481.fix.md
src/ai/backend/agent/agent.py

This is an auto-generated backport PR of #2481 to the 24.03 release.

fix: `BACKEND_MODEL_NAME` env var overwritten (#2481)

---

changes/2483.fix.md
src/ai/backend/manager/api/utils.py

This is an auto-generated backport PR of #2483 to the 24.03 release.

fix: ignore request body of certain request methods (#2483)

---

changes/2482.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/manager/registry.py

This is an auto-generated backport PR of #2482 to the 24.03 release.

fix: preopen port colliding with image service port (#2482)

---

.github/workflows/coverage.yml

Add the missing codecove.io auth token, and let it skip explicit LFS pulls as `pants test :: -- -m 'not integration'` pulls individual LFS files only when required.

ci: Add missing codecov token and skip LFS pulls in coverage test

---

.github/workflows/coverage.yml

This is an auto-generated backport PR of #2495 to the 24.03 release.

ci: Add missing codecov token and skip LFS pulls in coverage test (#2495)

---

changes/2506.fix.md
src/ai/backend/manager/models/user.py

`modify_user` mutation checks `is_active` input value.
All input values that client does not specify get `Undefined` sentinel value rather than `None`.
Let's correct this check logic.

fix: Check null value of user mutation by `Undefined`

---

changes/2506.fix.md
src/ai/backend/manager/models/user.py

This is an auto-generated backport PR of #2506 to the 24.03 release.

fix: Check null value of user mutation by `Undefined` (#2506)

---

changes/2509.fix.md
src/ai/backend/manager/models/domain.py
src/ai/backend/manager/models/group.py

`groups.total_resource_slots` and `domains.total_resource_slots` fields are nullable.
Let's do null check on those values.

fix: Do null check on `total_resource_slots` value

---

changes/2509.fix.md
src/ai/backend/manager/models/domain.py
src/ai/backend/manager/models/group.py

This is an auto-generated backport PR of #2509 to the 24.03 release.

fix: Do null check on `total_resource_slots` value (#2509)

---

changes/2516.fix.md
src/ai/backend/agent/docker/agent.py
src/ai/backend/manager/registry.py

This is an auto-generated backport PR of #2516 to the 24.03 release.

fix: agent heartbeat not handled when agent reports image with invalid ame (#2516)
