scripts/list-all-public-images.py

There are two points that I'm not sure about my code.
1. It seems that aiojobs module is not needed here currently...
2. Should I do more Exception handling?

List all images concurrently

---

docs/install/_archive/prepare-database-for-manager.md
docs/install/prepare-database-for-manager.rst
scripts/install-dev.sh

Pull request for [manager#91](https://github.com/lablup/backend.ai-manager/issues/91).
Change in default config for vfolder mount in `scripts/install-dev.sh` and few docs.

General vfolder host

---

docs/admin-api/sessions.rst
docs/user-api/kernels.rst

Pull request for [manager#102](https://github.com/lablup/backend.ai-manager/issues/102).

Update docs: tag for session

---

docs/admin-api/sessions.rst
docs/common-api/convention.rst
docs/common-api/objects.rst
docs/user-api/exec-batch.rst
docs/user-api/exec-query.rst
docs/user-api/exec-stream.rst
docs/user-api/intro.rst
docs/user-api/kernels.rst
docs/user-api/vfolders.rst

PR for updating docs to follow API v1.4.
Still in progress.

Update docs to v1.4

---

scripts/install-dev.sh

Adding missed required library (snappy) on Darwin

---

docs/locales/ko_KR/LC_MESSAGES/concepts.po

한국어 번역 기여 테스트를 위한 PR입니다.
This PR is test PR for Korean Translation.

add simple translation about API overview

---

docs/locales/ko_KR/LC_MESSAGES/install.po

테스트 겸 한국어 번역 PR입니다.
This PR is test PR for Korean Translation.

add simple translation about install-docker

---

scripts/delete-dev.sh
scripts/install-dev.sh

Also fix some glitches due to recent repository structure changes.

feat: Add options to customize port numbers

---

docs/locales/ko_KR/LC_MESSAGES/user-api.po

This PR is a simple translation about Event Monitoring in user-api.po.

add simple translation about Event Monitoring

---

docs/locales/ko_KR/LC_MESSAGES/install.po

This PR is a simple translation about AutoScaling in install.po.

add simple translation about AutoScaling

---

docs/locales/ko_KR/LC_MESSAGES/dev.po

[2020 컨트리뷰톤] backend.ai 번역기여 테스트입니다.

add simple translation about kernel

---

src/ai/backend/meta/__init__.py

add simple translation about Configure Autoscaling

---

scripts/delete-dev.sh
scripts/install-dev.sh

feat: install-dev / delete-dev with console-server (#216)

---

docs/locales/ko_KR/LC_MESSAGES/user-api.po

한국어 번역 기여 테스트를 위한 PR입니다.
This PR is test PR for Korean Translation.

add simple translation about events in user-api

---

docs/locales/ko_KR/LC_MESSAGES/common-api.po

Translated into some Korean of common-api/auth

add simple translation about common api

---

docs/locales/ko_KR/LC_MESSAGES/index.po

This PR is a simple translation about Developer manuals.

add simple translation about Developer manuals

---

scripts/install-dev.sh

feat(scripts/install-dev): Migrate to new official container registry

---

scripts/install-dev.sh

> This repository is a meta repository where we only keep compatible version
> dependencies to individual components of Backend.AI.
> 
> Please head to appropriate Backend.AI sub-projects (e.g., manager, agent, kernels) to
> contribute your code unless you really have contribution here.
This PR resolves #256.

fix: Update naming 'console-server' to 'webserver' in install-dev.sh script

---

docker-compose.halfstack-2109.yml

feat: Update halfstack compose configs for 21.03 and 21.09

---

scripts/install-dev.sh

modify how manager runs in execution script
this PR closes #260

fix: change the python execution command in the installation script

---

scripts/install-dev.sh

Support "docker compose" command

---

scripts/install-dev.sh

fix: Install "wheel" package by default in virtual envs

---

scripts/install-dev.sh

fix(install-dev): Missing submodule init & update for the webserver

---

docker-compose.halfstack-main.yml
scripts/install-dev.sh

- feat: Let it install lxcfs on Ubuntu
- fix: Use the correct halfstack compose config depending on SERVER_BRANCH

fix(installer): Support lxcfs and correct the reference to halfstack source config

---

docker-compose.halfstack-2109.yml

Upgrade etcd to v3.5.0 to support arm64 architecture with single docker-compose config

fix(install-dev): Upgrade etcd to support arm64 architecture with single docker-compose config

---

docs/user-api/vfolders.rst

docs: add missing API docs for virtual folder

---

scripts/install-dev.sh

fix(install-dev): Missing pyenv init command

---

scripts/install-dev.sh

refs lablup/backend.ai-agent#298.

feat: Apple silicon and ARM64 support

---

scripts/install-dev.sh

scripts(install-dev): Update docker-compose version

---

src/ai/backend/meta/__init__.py

common-api.po 내의 Authentication 번역에 대한 PR 입니다.
This is PR for Authentication translation in common-api.po.

add simple translation about Authentication

---

scripts/install-dev.sh

Update install-dev.sh to change volume config to comment in toml file of storage proxy,
and let add volume config with var

fix: update storage proxy installation step

---

scripts/install-dev.sh

refactor: Single-source the example credentials in install-dev.sh

---

scripts/install-dev.sh

add [Tester](https://github.com/lablup/backend.ai-test) installation step in script.
this is related PR in Tester component https://github.com/lablup/backend.ai-test/pull/2

feat: install tester in script

---

docs/index.rst
docs/install/install-agent.rst
docs/install/install-manager.rst
docs/install/install-user-programs.rst
docs/user-api/sessions.rst

Fix
- Title level inconsistent.
- The document is not included in any toctree.

fix: docs build warning

---

scripts/install-dev.sh

scripts(install-dev): Set the default Python version to 3.10.2

---

.readthedocs.yml
changes/428.misc.md
docs/requirements.txt

Update configurations for documentation builds

docs: Update rtd configs

---

docs/locales/ko_KR/LC_MESSAGES/index.po

translate index.po into Korean

docs: translate index.po

---

changes/472.misc.md
scripts/diff-release.py

* You may check the backport status of PRs by running it like:
`python scripts/diff-release.py main 22.03`

feat: Import `diff-release.py` script from the legacy common repo

---

backend.ai
changes/457.fix
src/ai/backend/cli/main.py
src/ai/backend/cli/types.py
src/ai/backend/client/cli/__init__.py
src/ai/backend/client/cli/admin/agent.py
src/ai/backend/client/cli/admin/domain.py
src/ai/backend/client/cli/admin/group.py
src/ai/backend/client/cli/admin/image.py
src/ai/backend/client/cli/admin/keypair.py
src/ai/backend/client/cli/admin/resource_policy.py
src/ai/backend/client/cli/admin/scaling_group.py
src/ai/backend/client/cli/admin/session.py
src/ai/backend/client/cli/admin/storage.py
src/ai/backend/client/cli/admin/user.py
src/ai/backend/client/cli/admin/vfolder.py
src/ai/backend/client/cli/extensions.py

let cli root command passes context info and client commands create context from the info.

fix: client commands create own ctx from root cli ctx info

---

changes/506.misc.md
pants.toml
python-kernel.lock
python.lock
tools/flake8.lock
tools/isort.lock
tools/mypy.lock
tools/pytest.lock
tools/towncrier.lock

This re-resolves #498.
(pantsbuild/pants#15990 -> pantsbuild/pex#1817 -> pantsbuild/pex#1812)

ci: Update pex version to 2.1.94

---

changes/508.misc.md
pants.toml

2.12.0rc3 and 2.12.0 has only documentation changes.

setup: Upgrade Pants to 2.12.0

---

changes/518.misc.md
scripts/install-dev.sh
scripts/pre-push.sh

This will reduce the number of "fix: lint error", "fix: mypy error", etc. commits

feat(install-dev): Install the standard pre-push hook

---

changes/520.misc.md
scripts/install-dev.sh
scripts/pre-commit.sh
scripts/pre-push.sh
src/ai/backend/manager/server.py

* Run the auto-formatters in pre-commit hook
(The pre-push hook cannot modify the files to be pushed because
it already created the commit.)
* Improve install-dev.sh to check existence of hook scripts

feat(install-dev): Add pre-commit hook

---

changes/551.fix.md
scripts/install-dev.sh
src/ai/backend/plugin/entrypoint.py

Fix typo & check file on install-dev.sh
1. fix typo & check file on install-dev.sh

fix: fix typo & check file on install-dev.sh

---

.gitignore
docs/dev/daily-workflows.rst

- doc: Update litner/formatter tool usage guide for VSCode and Vim
- repo: Update gitignore for localized vim configs

doc: Update dev-guide for VSCode and Vim settings

---

.gitignore
docs/dev/daily-workflows.rst
pants.toml
pyproject.toml

Elaborate ALE/CoC settings for Vim and concrete configuration keys for VSCode

doc: Update IDE/Vim configuration guides

---

changes/592.fix.md
docs/install/version-management-and-upgrades.rst

fix: add alembic command for Pants-based development envrionment

---

scripts/install-dev.sh

Change exit code.
issue: [580](https://github.com/lablup/backend.ai/issues/580)

fix: change exit code from -1 to 1

---

tests/manager/conftest.py

ci: Prevent intermittent test failure due to db connection error

---

changes/611.fix.md
src/ai/backend/web/BUILD

fix: Add missing webserver jinja templates

---

changes/README.md

Let's add more concrete and detailed guide on how to write good commit messages, news fragments, and PR titles.

doc: Add README to the changes directory

---

scripts/delete-dev.sh

fix: add pant cache delete files to delete-dev.sh
close https://github.com/lablup/backend.ai/issues/622

fix(delete-dev): Delete `.pants.env` and `pants-local`

---

changes/664.fix.md
src/ai/backend/manager/BUILD

fix: Add lazy-imported cli modules missing in the package

---

docs/install/prepare-database-for-manager.rst

Update prepare-database-for-manager doc.

docs: Update prepare-database-for-manager doc.

---

docs/client/cli/apps.rst
docs/client/cli/sessions.rst

docs: modifying session command example code
1. backend.ai admin sessions => backend.ai admin session list
2. backend.ai download mysess id_container => backend.ai session download mysess id_container
close #631

docs: Update session-related commands from the official documentation

---

changes/676.fix.md
src/ai/backend/common/lock.py

fix: do not remove lock file when lock is not acquired

---

changes/626.feature.md
src/ai/backend/web/proxy.py
src/ai/backend/web/server.py

refactor: Change decrypt function to middleware

---

changes/689.fix
src/ai/backend/web/server.py

This is a follow-up fix for https://github.com/lablup/backend.ai/pull/626.

fix: unable to login from Web-UI since the decoded payload is not JSON loaded

---

changes/704.feature
configs/webserver/sample.conf
src/ai/backend/web/config.py
src/ai/backend/web/templates/config.toml.j2

feat: add new `hide_agents` webserver config to control the exposure of agent information to normal users

---

python.lock

deps: upgrade etcetra version to 0.1.11

---

configs/storage-proxy/sample.toml
scripts/install-dev.sh

misc: add config example for weka.io storage proxy

---

changes/782.fix.md
src/ai/backend/manager/models/base.py

fix: readable mutation error message

---

changes/820.fix
src/ai/backend/manager/registry.py

fix: return empty commit status when the session is not running

---

docs/locales/ko/LC_MESSAGES/manager/user-api/resource-presets.po

@lizable @kyujin-cho, Added korean translation `resource-presets.po` in #816

docs: translated to korean manager/user-api/resource-presets.po

---

README.md

close #793 
@lizable
@kyujin-cho

docs: Readme.md for update Badges

---

.github/workflows/auto-label.yml

Labels related to issues linked to PR are automatically attached to the PR.

ci: auto label in issue

---

python.lock
requirements.txt

setup: upgrade etcetra to 0.1.14

---

docs/install/install-from-package.rst
docs/install/install-from-source.rst

Let's remove "TODO" in the docs...

doc: Update installation guides

---

docs/README.md
docs/locales/ko/LC_MESSAGES/README.po
docs/locales/ko/LC_MESSAGES/client/dev/session.po
docs/locales/ko/LC_MESSAGES/client/func/admin.po
docs/locales/ko/LC_MESSAGES/client/func/agent.po
docs/locales/ko/LC_MESSAGES/client/func/auth.po
docs/locales/ko/LC_MESSAGES/client/func/config.po
docs/locales/ko/LC_MESSAGES/client/func/keypair.po
docs/locales/ko/LC_MESSAGES/client/func/manager.po
docs/locales/ko/LC_MESSAGES/client/func/scaling-group.po
docs/locales/ko/LC_MESSAGES/client/func/session-template.po
docs/locales/ko/LC_MESSAGES/client/func/session.po
docs/locales/ko/LC_MESSAGES/client/func/vfolder.po
docs/locales/ko/LC_MESSAGES/client/lowlevel/request.po

Update README Documentation Python Ver.
3.10.7 to 3.10.8

docs: Update the Python versino in `docs/README.md`

---

changes/871.feature.md
src/ai/backend/manager/config.py
src/ai/backend/manager/models/utils.py
tests/manager/conftest.py

Let's make the database connection pool parameters to be configurable.

feat: Make db pool params configurable

---

changes/866.feature.md
configs/manager/halfstack.toml
configs/manager/sample.toml
src/ai/backend/manager/config.py
src/ai/backend/manager/server.py
tests/manager/conftest.py

This PR add support for loading just selected plugins with manager.
resolve #716

feat: allow manager to load selected plugin.

---

README.md

"Coming soon" has been deleted from README.md

docs: Remove outdated README.md line

---

docs/manager/user-api/vfolders.rst

Reflecting the decision to remove the dot used in places other than the sentence type mentioned in #828.

docs: remove meaningless dot in non-sentence form

---

CHANGELOG.md
README.md

Fix misspellings in README, CHANGE_LOG

doc: Fix typo in README and CHANGELOG

---

.github/workflows/integration.yml

close #741 
Add `script -q -e -c "bash {0}"` shell setting for tty use by `-i` option of `docker exec` according to the environment in github actions
Periodic execution using crontab
Executed by manual trigger using workflow_dispatch.

ci: Integration test automation workflow

---

changes/897.fix.md
src/ai/backend/client/cli/admin/domain.py
src/ai/backend/client/cli/admin/group.py
src/ai/backend/client/cli/admin/resource_policy.py
src/ai/backend/test/cli_integration/admin/test_domain.py
src/ai/backend/test/cli_integration/admin/test_keypair_resource_policy.py

This pr fix wrong values for `vfolder_host_permission` made by https://github.com/lablup/backend.ai/pull/790

fix: Update default vfolder permission value for cli

---

changes/902.fix.md
src/ai/backend/common/web/session/__init__.py
src/ai/backend/common/web/session/redis_storage.py
src/ai/backend/web/proxy.py

* Migrate `web.proxy.extra_config_headers` to `common.web`

hotfix: Invalid pkg cross reference

---

.github/workflows/default.yml

ci: uniform cache name

---

python.lock
src/ai/backend/manager/api/auth.py

This PR fixes type check failing on src/ai/backend/manager/api/auth.py file due to updates of dateutil's type definition.

fix: type check failing

---

changes/965.fix.md
configs/storage-proxy/sample.toml
scripts/install-dev.sh
src/ai/backend/storage/gpfs/__init__.py

fix: comment out gpfs config when using `install-dev.sh`

---

changes/972.misc.md
pants.toml
tools/mypy.lock

* setup: Upgrade mypy to 0.991 
https://github.com/lablup/backend.ai/issues/863

setup: Upgrade mypy to 0.991 

---

python.lock
requirements.txt

refactor: remove aioredis from requirements

---

src/ai/backend/client/cli/pagination.py
src/ai/backend/client/output/console.py

fix: truncated paginated list piped output

---

src/ai/backend/manager/models/alembic/versions/b6b884fbae1f_add_session_table.py

- none check on comparing row value

fix: hotfix session migration

---

changes/1017.feature.md
src/ai/backend/client/cli/vfolder.py
src/ai/backend/client/func/vfolder.py
src/ai/backend/client/output/fields.py
src/ai/backend/manager/api/vfolder.py

- Add vfolder status in api response
- Update vfolder cli `list`, `info` commands to show vfolder's status

feature: Add vfolder status in api response and update cli to follow

---

changes/1026.feature.md
src/ai/backend/client/cli/admin/vfolder.py
src/ai/backend/client/func/vfolder.py
src/ai/backend/manager/api/vfolder.py

- add: status in shared_vfolder_info API response
- fix: make groupId optional in list_shared_vfolders API

feat: add `list_shared_vfolders` API on CLI

---

changes/1018.feature.md
src/ai/backend/manager/api/vfolder.py
src/ai/backend/manager/models/group.py
src/ai/backend/manager/models/user.py
src/ai/backend/manager/models/vfolder.py

delete vfolder under `PersistentTaskGroup`

feat: delete vfolders asynchronously

---

scripts/pr-number-assign.py

Fix little mistake in pr-number-assign.py in scripts folder.

fix: add script file for news fragment number

---

changes/1073.feat.md
changes/1073.feature.md
src/ai/backend/manager/models/image.py

feat: shorten response time of `image_list` GQL query

---

.github/workflows/default.yml
pants.ci.toml
src/ai/backend/testutils/bootstrap.py
tests/common/redis/docker.py
tests/storage-proxy/test_netapp.py
tests/storage-proxy/test_purestorage.py
tests/storage-proxy/test_xfs.py

This PR updates halfstack container fixtures to wrap container creation with filelock so that duplicate ports won't be assigned.

ci: more stable container creation for halfstack services

---

changes/1090.feature.md
src/ai/backend/kernel/__main__.py

This prevents kernel runner from being killed by killall python.

feat: Set process title for kernel runner

---

python.lock
requirements.txt

Upgrade krunner-static-gnu to 4.1.0 and krunner-alpine to 5.1.0, with the updated volume versions.

setup: Upgrade krunner dependencies

---

pants.toml

- dev6 includes a fix for mypy cache management (pantsbuild/pants#18043)

setup: Upgrade pants to 2.16.0.dev7

---

.github/workflows/alembic-head-check.yml

ci: Fix alembic-head-check workflow

---

README.md

docs: renew README.md

---

.github/workflows/default.yml

- Correctly correct the incorrectly named 'backend.ai-client' file name to 'backend.ai_client'.
- Specify the version name in the conda-pack file.
- Fix problems that failed to get previous release versions.

ci: Fix windows conda pack

---

changes/1142.feature
src/ai/backend/client/func/user.py
src/ai/backend/client/output/fields.py
src/ai/backend/manager/models/user.py

feat: account for `totp_activated` field in updating user

---

docs/dev/daily-workflows.rst

----
:books: Documentation preview :books:: https://sorna--1152.org.readthedocs.build/en/1152/
----
:books: Documentation preview :books:: https://sorna-ko--1152.org.readthedocs.build/ko/1152/

doc: Update the pants reset guide

---

src/ai/backend/agent/agent.py
src/ai/backend/manager/registry.py

fix: use `KEYS` for Redis keyspace in redis script

---

src/ai/backend/manager/idle.py

fix: return correct value in SessionLifetimeChecker

---

changes/1188.fix.md
src/ai/backend/client/cli/admin/vfolder.py
src/ai/backend/client/func/vfolder.py
src/ai/backend/manager/api/vfolder.py

Related PR: #1186.
For providing a better user interface on Backend.AI CLI, I slightly changed API argument and corresponding functions.
(user id -> user email)

refactor: change user_id input to user email

---

src/ai/backend/manager/idle.py

follow up: #1185 
Delete utilization expire time only after initial grace period

fix: delete utilization expire time after initial grace period

---

docs/locales/ko/LC_MESSAGES/concepts/faq.po

this PR adds some Korean translations for docs.

add: Korean translation

---

src/ai/backend/storage/netapp/__init__.py

refactor: Remove duplicate methods in the NetApp volume

---

changes/1225.feature.md
src/ai/backend/agent/agent.py

fix: invalid mount point for sftp/scp binaries

---

docker/agent/Dockerfile
docker/manager/Dockerfile

Hi!
The Dockerfile placed at "docker/agent/Dockerfile" contains the best practice violation [DL3015](https://github.com/hadolint/hadolint/wiki/DL3015) detected by the [hadolint](https://github.com/hadolint/hadolint) tool.
The smell DL3015 occurs when the apt tool is used to install packages without the "--no-install-recommends" flag. This flag is recommended to be used to avoid installing additional packages not explicitly requested.
In this pull request, we propose a fix for that smell generated by our fixing tool. We have verified that the patch is correct before opening the pull request.
To fix this smell, specifically, the "--no-install-recommends" flag is added to the apt-get install command.
This change is only aimed at fixing that specific smell. If the fix is not valid or useful, …

Fix for Dockerfile smell DL3015

---

changes/1223.fix.md
configs/agent/sample.toml
configs/manager/sample.toml
src/ai/backend/agent/agent.py
src/ai/backend/agent/config.py
src/ai/backend/common/events.py
src/ai/backend/manager/api/session.py
src/ai/backend/manager/config.py

fix: considerations for improving manager scability

---

changes/1234.feature.md
src/ai/backend/manager/idle.py
src/ai/backend/manager/models/kernel.py

feat: support for idle checking ATOM accelerators

---

.github/workflows/coverage.yml
.github/workflows/default.yml
.github/workflows/integration.yml
.github/workflows/sbom.yml

ci: Remove manual installation of Python 3.9 for Pants

---

pants.toml
tools/pytest.lock

fix: pytest failing after yarl downgrade

---

src/ai/backend/manager/api/session.py
src/ai/backend/manager/models/scaling_group.py

fix: system sessions not being spawned

---

.github/workflows/default.yml

client.Dockerfile has been renamed to backend.ai-client.Dockerfile, and this has been reflected in the workflow file accordingly.

ci: Reflect the changed client Dockerfile name

---

changes/1298.fix.md
src/ai/backend/kernel/base.py
src/ai/backend/kernel/intrinsic.py

fix: remove vscode from intrinsic service app

---

src/ai/backend/manager/models/alembic/versions/210c4d9be768_add_keypair_resource_policy_max_.py

fix: merge branched migration head

---

.github/workflows/integration.yml
tests/common/redis/test_stream_consume.py
tests/common/redis/test_stream_consume_cluster.py

test: A follow-up fix to #1307

---

tests/common/redis/conftest.py

test: Ensure hostname config for Redis cluster tests

---

scripts/install-dev.sh

fix: Install `tomlkit` prior to running `scripts/tomltool.py`

---

pants.toml

https://github.com/pantsbuild/pants/blob/main/src/python/pants/notes/2.16.x.md

setup: Upgrade pants (2.16.0rc4 -> 2.16.0)

---

.github/CONTRIBUTING.md

Hello,
The previous versioning scheme document was pointing to an invalid link.
I changed the link to be valid.

docs: Renew versioning scheme document

---

.github/workflows/coverage.yml
.github/workflows/default.yml
.github/workflows/integration.yml
.github/workflows/sbom.yml

ci: Update init-pants action (v4-scie-pants -> v5-scie-pants)

---

changes/1364.feature.md
configs/webserver/sample.conf
docs/install/install-from-package/install-webserver.rst
src/ai/backend/web/config.py
src/ai/backend/web/templates/config.toml.j2

This PR resolves #1362.
related: [backend.ai-webui#1713](https://github.com/lablup/backend.ai-webui/issues/1713)

add: `directory_based_usage` setting to webserver config

---

changes/1382.feature.md
src/ai/backend/manager/models/minilang/__init__.py
src/ai/backend/manager/models/minilang/queryfilter.py
src/ai/backend/manager/models/session.py
tests/manager/test_queryfilter.py

feat: Implement per-item semantics for array-typed columns in queryfilter

---

src/ai/backend/manager/scheduler/dispatcher.py

fix: Fix typos

---

MIGRATION.md

Pretty much self-explanatory.
----
:books: Documentation preview :books:: https://sorna--1404.org.readthedocs.build/en/1404/
----
:books: Documentation preview :books:: https://sorna-ko--1404.org.readthedocs.build/ko/1404/

docs: update 22.09 to 23.03 guide of MIGRATION.md

---

scripts/install-dev.sh

- fix: Run `make compile` for the first time when installing the webui
as editable

fix: Ensure sudo for docker socket accessing scripts (check-docker.py)

---

scripts/install-dev.sh
src/ai/backend/client/cli/admin/vfolder.py
src/ai/backend/manager/api/auth.py
src/ai/backend/manager/api/session.py

fix: typos

---

src/ai/backend/storage/README.md

----
:books: Documentation preview :books:: https://sorna--1445.org.readthedocs.build/en/1445/
----
:books: Documentation preview :books:: https://sorna-ko--1445.org.readthedocs.build/ko/1445/

docs: fix typos

---

changes/.doc.md
changes/1452.feat.md
docs/README.md
src/ai/backend/manager/api/etcd.py
src/ai/backend/manager/api/manager.py
src/ai/backend/manager/api/resource.py
src/ai/backend/manager/api/session.py
src/ai/backend/manager/openapi.py

This PR updates OpenAPI spec generator for Backend.AI API. Changes include:
- Increase verbosity when running the script (prints the name of the handler which the script is currently working on)
- Fix generator generating documentation for duplicated handlers
- Add documentation
----
:books: Documentation preview :books:: https://sorna--1452.org.readthedocs.build/en/1452/
----
:books: Documentation preview :books:: https://sorna-ko--1452.org.readthedocs.build/ko/1452/

feat: enhancements on OpenAPI generator

---

docs/dev/daily-workflows.rst

----
:books: Documentation preview :books:: https://sorna--1458.org.readthedocs.build/en/1458/
----
:books: Documentation preview :books:: https://sorna-ko--1458.org.readthedocs.build/ko/1458/

doc: Update VSCode configuration guide

---

src/ai/backend/manager/api/scaling_group.py

fix: unable to use AppProxy v1 mode

---

changes/1477.feature.md
configs/webserver/sample.conf
docs/install/install-from-package/install-webserver.rst
src/ai/backend/web/config.py
src/ai/backend/web/templates/config.toml.j2

resolves https://github.com/lablup/giftbox/issues/482
related: https://github.com/lablup/backend.ai-webui/pull/1843

add: `max_count_for_preopen_ports` setting to webserver config

---

changes/1516.feature.md
src/ai/backend/common/plugin/__init__.py
src/ai/backend/storage/api/client.py
src/ai/backend/storage/api/manager.py
src/ai/backend/storage/api/types.py
src/ai/backend/storage/context.py
src/ai/backend/storage/migration.py
src/ai/backend/storage/plugin.py
src/ai/backend/storage/server.py

feat: allow loading storage backends as plugins

---

changes/1545.feature.md
configs/webserver/sample.conf
src/ai/backend/web/config.py
src/ai/backend/web/server.py
src/ai/backend/web/templates/config.toml.j2

feat: handle OpenID Connect authentication responses

---

.github/dependabot.yml

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow
Refer to the link above and modify it to fit the format.

ci: Modify dependabot allow list to suit format

---

tests/common/redis_helper/docker.py

The GitHub Action Runner Image (as of 2023 September 3rd) introduces Docker Compose v2.21 and it has a breaking change in the JSON-formatted `ps` command output.
- https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230903.1 (Compose v2.20.3 → v2.21.0)
- https://docs.docker.com/compose/release-notes/#2210
- docker/compose#10918

ci: Support docker compose v2.21 as it introduces a breaking change

---

changes/1588.fix.md
configs/webserver/halfstack.conf
configs/webserver/sample.conf
scripts/install-dev.sh
src/ai/backend/common/redis_helper.py
src/ai/backend/web/config.py

This resolves webserver not working issue after ad391fd421495d96635fa4c5edaab4d2ad8243d8 merged.

hotfix: Fix webserver not compatable with `webserver.conf`

---

fixtures/manager/example-session-templates.json
fixtures/manager/example-session-templates.yaml

With the merging of this [PR](https://github.com/lablup/backend.ai/pull/1406), the template file needs to be updated.
So, I have updated the JSON template file and added a new YAML template file.

feat: Add example-session-templates

---

tools/ruff-requirements.txt
tools/ruff.lock

ci: Upgrade ruff (0.0.287 -> 0.1.1)

---

changes/1637.fix.md
src/ai/backend/storage/gpfs/__init__.py
src/ai/backend/storage/gpfs/gpfs_client.py
src/ai/backend/storage/gpfs/types.py

Update outdated API parameters and queries

fix: Update outdated GPFS API usage

---

.github/workflows/build-static-wsproxy.yml

refs lablup/backend.ai-webui#2013

ci: Add a manually triggered workflow to build static wsproxy

---

changes/1702.doc.md
docs/_static/css/customTheme.css
docs/_static/js/custom.js

Template updates
- Heading hierarchy font sizes.
- flyout menu for selecting en and kr 
----
:books: Documentation preview :books:: https://sorna--1702.org.readthedocs.build/en/1702/
----
:books: Documentation preview :books:: https://sorna-ko--1702.org.readthedocs.build/ko/1702/

docs: update heading hierarchy & flyout menu

---

changes/1704.feature.md
configs/agent/sample.toml
src/ai/backend/agent/config.py
src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/scratch.py
src/ai/backend/agent/server.py

feat: Use loop mounted sparse file as scratch to limit its size

---

changes/1707.fix.md
src/ai/backend/manager/api/resource.py
src/ai/backend/manager/models/resource_usage.py

fix: add missing resource-usage fields

---

src/ai/backend/install/common.py
src/ai/backend/install/context.py
src/ai/backend/install/docker.py
src/ai/backend/install/types.py

A follow-up fix to #1694 in macOS environments.

fix: Community Installer running on macOS

---

src/ai/backend/manager/api/resource.py

At #1707, I left some `print()` codes for test.
I am sorry

chore: remove test print code

---

changes/1735.feature.md
src/ai/backend/web/config.py
src/ai/backend/web/templates/config.toml.j2

refer: https://github.com/lablup/backend.ai-webui/pull/1993

feature: add edu applauncher name prefix config

---

changes/1737.feature.md
src/ai/backend/manager/api/admin.py

Let GQL log errors for better visibility

feature: gql resolvers log error result

---

src/ai/backend/agent/agent.py
src/ai/backend/client/output/fields.py

I think it's a spelling error that could also affect the logic.

fix: Correct misspelling of resource

---

changes/1796.doc.md
docs/dev/development-setup.rst
docs/install/install-from-package/install-agent.rst
docs/install/install-from-package/install-manager.rst
docs/install/install-from-package/install-storage-proxy.rst
docs/install/install-from-package/install-webserver.rst
docs/install/install-from-package/os-preparation.rst
docs/install/install-from-package/prepare-cache-service.rst
docs/install/install-from-package/prepare-config-service.rst
docs/install/install-from-package/prepare-database.rst

resolves https://github.com/lablup/giftbox/issues/583
Update Backend.AI production installation guide doc
----
📚 Documentation preview 📚: https://sorna--1796.org.readthedocs.build/en/1796/
----
📚 Documentation preview 📚: https://sorna-ko--1796.org.readthedocs.build/ko/1796/

doc: Update Backend.AI production installation guide doc

---

src/ai/backend/common/bgtask.py
src/ai/backend/install/context.py
src/ai/backend/manager/container_registry/base.py
src/ai/backend/manager/models/user.py
src/ai/backend/manager/scheduler/dispatcher.py
src/ai/backend/storage/api/client.py
tests/common/redis_helper/docker.py
tests/common/test_identity.py
tools/ruff-requirements.txt
tools/ruff.lock

- setup: Upgrade ruff and ruff-lsp
- style: Reformat with updated ruff's preview style

ci: Update Ruff

---

.github/workflows/pr-prefix.yml

Add a workflow to easily check whether contributors have followed the pr prefix rule.

ci: Add workflow to verify pr prefix

---

.github/workflows/sbom.yml

ci: Bump pantsbuils/actions/init-pants from v5 to v8

---

changes/1965.doc.md
docs/_static/css/customTheme.css

This PR resolves cosmetic issue due to unexpected font-size in ethical ads by resizing into a `small` size with css customization.
| After | Before |
|------|--------|
| <img width="289" alt="Screenshot 2024-03-26 at 12 22 46 PM" src="https://github.com/lablup/backend.ai-docs-2023/assets/46954439/9e7ab374-1aa3-4560-822e-3d4b88b78038"> | <img width="293" alt="Screenshot 2024-03-26 at 12 23 06 PM" src="https://github.com/lablup/backend.ai-docs-2023/assets/46954439/484794fe-e46e-43e5-bde4-3b0e36b3a26a"> |
- docstrings in public …

docs: resize font-size of ads

---

changes/1976.doc.md
docs/client/index.rst
docs/locales/ko/LC_MESSAGES/client/index.po

----
📚 Documentation preview 📚: https://sorna--1976.org.readthedocs.build/en/1976/
----
📚 Documentation preview 📚: https://sorna-ko--1976.org.readthedocs.build/ko/1976/

docs: Add note about installing client library with same version as server

---

src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/group.py
src/ai/backend/manager/models/image.py
src/ai/backend/manager/models/kernel.py

chore: add missing GQL annotations

---

MIGRATION.md
README.md

docs: add instructions for migration from 23.09 to 24.03

---

.github/workflows/default.yml

ci: Modified to suit the usage of artifact@v4

---

scripts/install.sh

close #1777 
#2022 updates the details of the latest version, so use the shorten link to detect each platform and run the latest version of tui installer.

chore: Supports multi-platform install with one script

---

src/ai/backend/client/func/auth.py

feat: Implement encryption in the client SDK's login function

---

changes/2059.fix.md
src/ai/backend/manager/models/vfolder.py

This PR resolves #2058. For the test cases, please refer to the issue description (how to reproduce).

fix: prevent from mounting automount folder when status is dead

---

changes/2072.fix.md
src/ai/backend/manager/api/vfolder.py
src/ai/backend/manager/models/vfolder.py

Resolves lablup/giftbox#661. This PR fixes VFolder I/O operation APIs not working when user tries to call API to a VFolder which shares name with deleted one, which is caused by `vfolder_permission_required()` decorator selecting already removed VFolder instead of live one. Adding these kind of extra filters will make the codebase coarsened, so our ultimate goal is to retire every VFolder APIs utilizing VFolder name as its key to resolve target VFolder.
----
📚 Documentation preview 📚: https://sorna--2072.org.readthedocs.build/en/2072/
----
📚 Documentation preview 📚: https://sorna-ko--2072.org.readthedocs.build/ko/2072/
----
📚 Documentation preview 📚: https://sorna--2072.org.readthedocs.build/en/2072/
----
📚 Documentation preview 📚: …

fix: VFolder file listing not working

---

changes/2073.fix.md
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/group.py

Tested manually.
----
📚 Documentation preview 📚: https://sorna--2073.org.readthedocs.build/en/2073/
----
📚 Documentation preview 📚: https://sorna-ko--2073.org.readthedocs.build/ko/2073/

fix: add missing `type` argument in `group` query

---

changes/2081.feature.md
src/ai/backend/storage/context.py

feat: cache volume objects in `RootContext.get_volume`

---

src/ai/backend/test/cli_integration/user/test_vfolder.py

This is an auto-generated backport PR of #2140 to the 24.03 release.

fix: Wrong success check of vfolder cli integration test (#2140)

---

changes/2144.fix.md
src/ai/backend/storage/gpfs/gpfs_client.py

This is an auto-generated backport PR of #2144 to the 24.03 release.

fix: Make GPFS plugin reliable (#2144)

---

changes/2155.fix.md
src/ai/backend/manager/scheduler/dispatcher.py

This is an auto-generated backport PR of #2155 to the 24.03 release.

fix: Ensure that all pending sessions are picked by schedulers (#2155)

---

changes/2077.fix.md
src/ai/backend/manager/cli/__main__.py

This is an auto-generated backport PR of #2077 to the 24.03 release.

fix: clear-history sessions as well as kernels (#2077)

---

changes/2162.fix.md
src/ai/backend/agent/docker/agent.py
src/ai/backend/manager/registry.py
src/ai/backend/runner/entrypoint.sh

This is an auto-generated backport PR of #2162 to the 24.03 release.

fix: Security vulnerability of sudo session enablement (#2162)

---

changes/2170.fix.md
src/ai/backend/storage/api/manager.py
src/ai/backend/storage/netapp/__init__.py
src/ai/backend/storage/netapp/netappclient.py

This is an auto-generated backport PR of #2170 to the 24.03 release.

fix: Netapp  timing issue (#2170)

---

changes/2152.fix.md
src/ai/backend/client/config.py
src/ai/backend/manager/api/resource.py

This is an auto-generated backport PR of #2152 to the 24.03 release.

fix: bugs found check-presets sdk (#2152)

---

changes/1993.misc.md
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/endpoint.py
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/group.py
src/ai/backend/manager/models/image.py
src/ai/backend/manager/models/kernel.py
src/ai/backend/manager/models/resource_policy.py
src/ai/backend/manager/models/session.py
src/ai/backend/manager/models/storage.py

This is an auto-generated backport PR of #1993 to the 24.03 release.

chore: fix incorrect version notation of GQL Field (#1993)

---

src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/endpoint.py

This is an auto-generated backport PR of #2212 to the 24.03 release.

fix: invalid GQL version annotation (#2212)

---

changes/2096.fix.md
src/ai/backend/manager/registry.py

This is an auto-generated backport PR of #2096 to the 23.09 release.

fix:  failing occasionally (#2096)

---

src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/endpoint.py
src/ai/backend/manager/models/vfolder.py

This is an auto-generated backport PR of #2218 to the 24.03 release.

hotfix: Wrong GQL schema field definition & wrong access (#2218)

---

changes/2229.feature.md
src/ai/backend/manager/scheduler/dispatcher.py

This is an auto-generated backport PR of #2229 to the 24.03 release.

feat: collect zombie routes automatically (#2229)

---

changes/2136.feature.md
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/image.py
src/ai/backend/manager/models/kernel.py

This is an auto-generated backport PR of #2136 to the 24.03 release.

feature: Revamp images GQL query (#2136)

---

changes/2236.fix.md
src/ai/backend/manager/models/endpoint.py

This is an auto-generated backport PR of #2236 to the 23.09 release.

fix:  GQL Field resolver raising error (#2236)

---

src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/image.py

This is an auto-generated backport PR of #2238 to the 24.03 release.

fix:  GQL Query returning every images (#2238)

---

src/ai/backend/manager/models/image.py

This is an auto-generated backport PR of #2246 to the 24.03 release.

fix: images resolver not filtering out image objects correctly (#2246)

---

.github/workflows/backport.yml

ci: Check whether the branch actually exists

---

.github/workflows/backport.yml

ci: Check whether the milestone actually exists as a branch

---

changes/2041.feature.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/config.py
src/ai/backend/common/events_experimental.py
src/ai/backend/common/redis_client.py
src/ai/backend/manager/config.py
src/ai/backend/manager/server.py
src/ai/backend/storage/config.py
src/ai/backend/storage/server.py
tests/common/test_distributed.py
tests/common/test_events.py

This is an auto-generated backport PR of #2041 to the 24.03 release.

feat: bespoke redis client and event dispatcher (#2041)

---

changes/2220.feature.md
scripts/agent/build-dropbear.sh
scripts/agent/build-sftpserver.sh
scripts/agent/build-suexec.sh
scripts/agent/build-tmux.sh
src/ai/backend/runner/dropbear.centos8.0.aarch64.bin
src/ai/backend/runner/dropbear.centos8.0.x86_64.bin
src/ai/backend/runner/dropbearconvert.centos8.0.aarch64.bin
src/ai/backend/runner/dropbearconvert.centos8.0.x86_64.bin
src/ai/backend/runner/dropbearkey.centos8.0.aarch64.bin
src/ai/backend/runner/dropbearkey.centos8.0.x86_64.bin
src/ai/backend/runner/jail.centos8.0.x86_64.bin
src/ai/backend/runner/libbaihook.centos8.0.aarch64.so
src/ai/backend/runner/libbaihook.centos8.0.x86_64.so
src/ai/backend/runner/scp.centos8.0.aarch64.bin
src/ai/backend/runner/scp.centos8.0.x86_64.bin
src/ai/backend/runner/sftp-server.centos8.0.aarch64.bin
src/ai/backend/runner/sftp-server.centos8.0.x86_64.bin
src/ai/backend/runner/su-exec.centos8.0.aarch64.bin
src/ai/backend/runner/su-exec.centos8.0.x86_64.bin
src/ai/backend/runner/tmux.centos8.0.aarch64.bin
src/ai/backend/runner/tmux.centos8.0.x86_64.bin

This is an auto-generated backport PR of #2220 to the 24.03 release.

feat: Add CentOS 8.0 binaries (#2220)

---

changes/2255.feature.md
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/endpoint.py

This is an auto-generated backport PR of #2255 to the 24.03 release.

feat: allow modifying model service env var (#2255)

---

src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/api/service.py
src/ai/backend/manager/models/endpoint.py
src/ai/backend/manager/registry.py

----
📚 Documentation preview 📚: https://sorna--2257.org.readthedocs.build/en/2257/
----
📚 Documentation preview 📚: https://sorna-ko--2257.org.readthedocs.build/ko/2257/

feat: update REST API to alter `runtime_variant` option

---

changes/2258.feature.md
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/api/service.py
src/ai/backend/manager/models/endpoint.py

----
📚 Documentation preview 📚: https://sorna--2258.org.readthedocs.build/en/2258/
----
📚 Documentation preview 📚: https://sorna-ko--2258.org.readthedocs.build/ko/2258/

feat: add new API to show list of supported runtimes

---

src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/dummy/agent.py
src/ai/backend/agent/kubernetes/agent.py

feat: create and implement `AbstractAgent.extract_image_command()` interface

---

changes/2260.feature.md
src/ai/backend/agent/agent.py
src/ai/backend/kernel/base.py
src/ai/backend/manager/api/service.py

----
📚 Documentation preview 📚: https://sorna--2260.org.readthedocs.build/en/2260/
----
📚 Documentation preview 📚: https://sorna-ko--2260.org.readthedocs.build/ko/2260/

feat: automatic model definition creation based on selected runtime variant

---

src/ai/backend/common/events_experimental.py
src/ai/backend/common/redis_client.py

This is an auto-generated backport PR of #2286 to the 24.03 release.

fix: invalid msgpack package utilized on experimental `EventDispatcher` (#2286)

---

changes/2287.fix.md
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/gql.py

This is an auto-generated backport PR of #2287 to the 23.09 release.

fix: incorrect parameter defined under `endpoint_list` query (#2287)

---

.github/workflows/default.yml

ci: Bump action-gh-release from v1 to v2

---

changes/2320.fix.md
src/ai/backend/manager/scheduler/dispatcher.py

This is an auto-generated backport PR of #2320 to the 24.03 release.

fix: model service scheduler raising error (#2320)

---

changes/2319.fix.md
src/ai/backend/agent/docker/kernel.py

This is an auto-generated backport PR of #2319 to the 24.03 release.

hotfix: container commit not working (#2319)

---

.github/workflows/default.yml

Backported-from: main (24.09)
Backported-to: 23.09
Backport-of: 1897

ci: Change lfs to use actions/cache in test job (#1897)

---

src/ai/backend/manager/api/vfolder.py
src/ai/backend/manager/models/vfolder.py

fix: insert vfolders with domain_name when clone

---

changes/2205.fix.md
src/ai/backend/manager/idle.py

This is an auto-generated backport PR of #2205 to the 24.03 release.

fix: Ensure that utilization idleness is checked after a set period (#2205)

---

.github/workflows/pr-prefix.yml

This is an auto-generated backport PR of #2353 to the 24.03 release.

ci: Update the regex and list of the PR title prefix checker (#2353)

---

changes/2339.deps.md
python.lock
requirements.txt
src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/docker/intrinsic.py
src/ai/backend/agent/docker/kernel.py
src/ai/backend/agent/docker/utils.py
src/ai/backend/agent/dummy/kernel.py
src/ai/backend/agent/kernel.py
src/ai/backend/agent/kubernetes/intrinsic.py
src/ai/backend/agent/kubernetes/kernel.py
src/ai/backend/agent/kubernetes/utils.py

This is an auto-generated backport PR of #2339 to the 24.03 release.

deps: Upgrade aiodocker to 0.22 (#2339)

---

changes/2371.fix.md
src/ai/backend/manager/api/service.py
src/ai/backend/manager/models/endpoint.py

This is an auto-generated backport PR of #2371 to the 24.03 release.

fix: mismatches between runtime listing and service creation API (#2371)

---

src/ai/backend/manager/api/vfolder.py

This is an auto-generated backport PR of #2335 to the 24.03 release.

fix: malfunctioning VFolder delete API (#2335)

---

changes/2253.fix.md
configs/agent/sample-dummy-config.toml
src/ai/backend/agent/dummy/agent.py

This is an auto-generated backport PR of #2253 to the 24.03 release.

fix: Regression of dummy agent (#2253)

---

changes/2364.feature.md
src/ai/backend/client/cli/session/lifecycle.py
src/ai/backend/client/func/session.py
src/ai/backend/manager/api/exceptions.py
src/ai/backend/manager/api/session.py
src/ai/backend/manager/models/session.py
src/ai/backend/manager/registry.py

This is an auto-generated backport PR of #2364 to the 24.03 release.

feat: Fetch container logs of a specific kernel (#2364)

---

src/ai/backend/testutils/bootstrap.py

This is an auto-generated backport PR of #2398 to the 24.03 release.

fix: A minor range calculation bug in #2396 (#2398)

---

changes/2402.deps.md
python.lock
requirements.txt

This is an auto-generated backport PR of #2402 to the 24.03 release.

deps: Upgrade aiodocker to 0.22.1 (#2402)

---

scripts/install-dev.sh

This is an auto-generated backport PR of #2342 to the 24.03 release.

chore: Ensure referring the correct fixture file (#2342)

---

changes/2429.fix.md
src/ai/backend/manager/api/vfolder.py
src/ai/backend/manager/models/vfolder.py

This is an auto-generated backport PR of #2429 to the 24.03 release.

fix: Allow specific status of vfolders to query to purge (#2429)

---

changes/2327.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/server.py
src/ai/backend/manager/models/session.py
src/ai/backend/manager/registry.py

This is an auto-generated backport PR of #2327 to the 24.03 release.

fix: Run batch execution after session starts (#2327)

---

docs/README.md
docs/dev/adding-kernels.rst
docs/dev/development-setup.rst
docs/dev/version-management-and-upgrades.rst
docs/index.rst

This is an auto-generated backport PR of #2135 to the 24.03 release.

docs: fix typos (#2135)

---

docs/client/cli/sessions.rst
docs/locales/ko/LC_MESSAGES/client/cli/sessions.po

This is an auto-generated backport PR of #1758 to the 23.09 release.

docs: Update the docs for options of the session list command (#1758)

---

.github/workflows/pr-prefix.yml

This is an auto-generated backport PR of #2336 to the 24.03 release.

ci: Handle untrusted input safely using env (#2336)

---

changes/2424.fix.md
python.lock
requirements.txt

deps: Update `inquirer` to remove dependency on deprecated `distutils`

---

changes/2419.feature.md
src/ai/backend/storage/purestorage/__init__.py
src/ai/backend/storage/purestorage/rapidfiles.py
src/ai/backend/storage/purestorage/rapidfiles_v2.py

This is an auto-generated backport PR of #2419 to the 24.03 release.

feat: support for Pure Storage RapidFiles Toolkit v2 (#2419)

---

.github/workflows/default.yml

This is an auto-generated backport PR of #2465 to the 24.03 release.

chore(ci): Update the arm64 runner config (#2465)

---

changes/2478.fix.md
src/ai/backend/kernel/__main__.py
src/ai/backend/kernel/base.py
src/ai/backend/kernel/logging.py
src/ai/backend/kernel/utils.py

This is an auto-generated backport PR of #2478 to the 24.03 release.

fix: Improve error handling of initialization failure in kernel runner (#2478)

---

.github/workflows/ci.yml

ci: Bump init-pants from v5 to v8 (#2112)

---

.github/workflows/ci.yml

ci: Fix warnings when running Graphite CI Optimizer in non-PR contexts

---

.github/workflows/ci.yml

This is an auto-generated backport PR of #2499 to the 23.09 release.

ci: Fix warnings when running Graphite CI Optimizer in non-PR contexts (#2499)

---

docs/_static/css/customTheme.css

This is an auto-generated backport PR of #2518 to the 24.03 release.

doc: Update the inline-code style for better readability (#2518)

---

docs/dev/version-management-and-upgrades.rst

Ooops..
It's a follow-up fix to #2367.
----
📚 Documentation preview 📚: https://sorna--2521.org.readthedocs.build/en/2521/
----
📚 Documentation preview 📚: https://sorna-ko--2521.org.readthedocs.build/ko/2521/

doc: Fix yq commands to restore halfstack port numbers

---

.github/workflows/ci.yml

This is an auto-generated backport PR of #2524 to the 24.03 release.

ci: Fix if condition not working properly (#2524)

---

.github/workflows/ci.yml

This is an auto-generated backport PR of #2514 to the 23.09 release.

ci: Makes if conditions written in multi-line work properly (#2514)

---

.github/workflows/ci.yml

This is an auto-generated backport PR of #2536 to the 24.03 release.

ci: Fix job output evaluation for the CI optimizer (#2536)

---

changes/2505.enhance.md
src/ai/backend/manager/models/rbac/permission_defs.py
src/ai/backend/manager/models/rbac/storage.py
src/ai/backend/manager/models/rbac/vfolder.py
src/ai/backend/manager/models/storage.py

Implement storage host RBAC interface

feat: Implement storage host RBAC api

---

changes/2541.feature.md
src/ai/backend/install/app.tcss
src/ai/backend/install/cli.py
src/ai/backend/install/context.py
src/ai/backend/install/types.py

This is an auto-generated backport PR of #2541 to the 24.03 release.

feat: Add the configure menu to set public-facing addr in the TUI installer (#2541)

---

.github/workflows/ci.yml

This is an auto-generated backport PR of #2540 to the 23.09 release.

ci: Fix if condition not working properly (#2540)

---

changes/2556.fix.md
src/ai/backend/manager/models/image.py

This is an auto-generated backport PR of #2556 to the 23.09 release.

fix: New sessions always falling into `PULLING` status under specific setup (#2556)

---

changes/2558.enhance.md
src/ai/backend/manager/models/agent.py

This is an auto-generated backport PR of #2558 to the 24.03 release.

enhance: Apply batch dataloader to statistics fetched from Redis (#2558)

---

src/ai/backend/common/events.py
src/ai/backend/manager/models/agent.py
src/ai/backend/manager/registry.py
src/ai/backend/manager/scheduler/dispatcher.py

Add interfaces that update session and kernel status.
The interfaces are not used yet!

feat: Add interface that update session and kernel status

---

src/ai/backend/manager/models/agent.py

fix: typo in AgentSummary queryfilter fieldspec

---

changes/2635.fix.md
src/ai/backend/client/func/session.py
src/ai/backend/manager/api/exceptions.py
src/ai/backend/manager/api/session.py
src/ai/backend/manager/api/utils.py

This is an auto-generated backport PR of #2635 to the 23.09 release.

fix: Update the session-download API to use POST with custom verb (#2635)

---

changes/2555.fix.md
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/image.py

This is an auto-generated backport PR of #2555 to the 24.03 release.

fix: rename Image Filter to Image Type (#2555)

---

src/ai/backend/manager/api/session.py
src/ai/backend/manager/models/group.py

follows https://github.com/lablup/backend.ai/pull/2573
This PR addresses several minor issues in the session and group models for better code quality and consistency.
- Fixed a typo in the `delete_sessions` method (`sa.delet` to `sa.delete`).
- Improved readability by adjusting the formatting for `kernel_loading_strategy` and `total_resource_slots` for better code clarity.
1. Check delete project works well.
To correct minor typos and improve code readability for maintainability.
---
- docstrings in public interfaces and type …

fix: `delete_sessions` typo error

---

src/ai/backend/manager/api/session.py
src/ai/backend/manager/models/group.py

This is an auto-generated backport PR of #2656 to the 23.09 release.

fix: `delete_sessions` typo error (#2656)

---

scripts/install-dev.sh

fix: The URL of docker compose installation guide in install-dev.sh

---

scripts/pre-push.sh

This is an auto-generated backport PR of #2678 to the 23.09 release.

chore(pre-push): Consider direct pushes to release branches when detecting the base branch (#2678)

---

src/ai/backend/manager/models/scaling_group.py

chore: Migrate SQLAlchemy scaling_groups table to declarative style

---

src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/gql_models/group.py
src/ai/backend/manager/models/gql_models/user.py
src/ai/backend/manager/models/group.py
src/ai/backend/manager/models/user.py

----
📚 Documentation preview 📚: https://sorna--2710.org.readthedocs.build/en/2710/
----
📚 Documentation preview 📚: https://sorna-ko--2710.org.readthedocs.build/ko/2710/

chore: Move UserNode and GroupNode to gql_models module

---

src/ai/backend/manager/models/rbac/__init__.py
src/ai/backend/manager/models/rbac/permission_defs.py
src/ai/backend/manager/models/session.py

Implement Compute session RBAC interface

feat: Impl compute session RBAC interface

---

changes/1991.enhance.md
configs/manager/halfstack.toml
configs/manager/sample.toml
src/ai/backend/manager/config.py
src/ai/backend/manager/models/utils.py
tests/manager/conftest.py

Backported-from: main (24.09)
Backport-of: 1991

feat: Enable robust DB connection handling (#1991)

---

tests/wsproxy/BUILD
tests/wsproxy/test_utils.py

This is an auto-generated backport PR of #2502 to the 24.03 release.

feat: add tests for utility functions in wsproxy(app proxy) (#2502)

---

changes/2742.fix.md
src/ai/backend/manager/models/vfolder.py

fix: typo in VFolder status update

---

changes/2740.feature.md
src/ai/backend/manager/api/vfolder.py

This is an auto-generated backport PR of #2740 to the 24.03 release.

feat: Add new vfolder API to update sharing status (#2740)

---

changes/2742.fix.md
src/ai/backend/manager/models/vfolder.py

This is an auto-generated backport PR of #2742 to the 24.03 release.

fix: typo in VFolder status update (#2742)

---

changes/2723.feature.md
src/ai/backend/manager/models/endpoint.py

This is an auto-generated backport PR of #2723 to the 24.03 release.

feat: enable filter order in endpoint model (#2723)

---

.gitignore
changes/2688.feature.md
configs/account-manager/halfstack.alembic.ini
configs/account-manager/halfstack.toml
configs/account-manager/sample.toml
scripts/install-dev.sh
src/ai/backend/account_manager/BUILD
src/ai/backend/account_manager/api/BUILD
src/ai/backend/account_manager/api/application.py
src/ai/backend/account_manager/api/auth.py
src/ai/backend/account_manager/api/utils.py
src/ai/backend/account_manager/cli/BUILD
src/ai/backend/account_manager/cli/__main__.py
src/ai/backend/account_manager/cli/context.py
src/ai/backend/account_manager/config.py
src/ai/backend/account_manager/context.py
src/ai/backend/account_manager/exceptions.py
src/ai/backend/account_manager/models/BUILD
src/ai/backend/account_manager/models/alembic/BUILD
src/ai/backend/account_manager/models/alembic/README
src/ai/backend/account_manager/models/alembic/__init__.py
src/ai/backend/account_manager/models/alembic/env.py
src/ai/backend/account_manager/models/alembic/script.py.mako
src/ai/backend/account_manager/models/base.py
src/ai/backend/account_manager/models/utils.py
src/ai/backend/account_manager/plugin.py
src/ai/backend/account_manager/server.py
src/ai/backend/account_manager/types.py
src/ai/backend/account_manager/utils.py
src/ai/backend/common/config.py

chore: Introduce Account-manager

---

src/ai/backend/account_manager/models/utils.py

chore: Update account manager side model execute_with_txn_retry interface

---

changes/2797.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/docker/kernel.py
src/ai/backend/agent/dummy/agent.py
src/ai/backend/agent/kubernetes/agent.py

This is an auto-generated backport PR of #2797 to the 24.03 release.

fix: Explicitly specify protected service ports not to expose publicly (#2797)

---

changes/2456.feature.md
configs/webserver/sample.conf
src/ai/backend/common/web/session/__init__.py
src/ai/backend/common/web/session/redis_storage.py
src/ai/backend/web/config.py
src/ai/backend/web/proxy.py
src/ai/backend/web/server.py
src/ai/backend/web/templates/config.toml.j2

This PR provides extending login session expires timestamp by new API `extend-login-session`.
It only affects when user is already logged in and it's extends based on the time logged in and `max_age`.
Here's the scenario that sets the time to extend login session.
1. Set `login_session_extension_sec` configuration in Webserver.
2. Start Webserver process.
3. Client(User) logins.
4. Set `expires` value(as int) to Redis Storage and store it to session cookie in ISO8601 format string.
- `expires` value is sum of current time of Redis server and `max_age` value set in Webserver configuration.
6. Client(User) requests extend login session time.
7. Compares `expires` value and the current time of Redis server. If the current time of Redis server is bigger than `expires` value, then update …

feat: Provide extending login session expiration

---

changes/2803.fix.md
src/ai/backend/manager/models/session.py

fix: Correct session status determiner function

---

changes/2805.fix.md
src/ai/backend/manager/models/endpoint.py
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/minilang/__init__.py
src/ai/backend/manager/models/minilang/queryfilter.py

This is an auto-generated backport PR of #2805 to the 24.03 release.

fix: bugs related to `endpoint` and `endpoint_list` GQL queries (#2805)

---

am-alembic.ini
src/ai/backend/account_manager/BUILD
src/ai/backend/account_manager/defs.py
src/ai/backend/account_manager/models/__init__.py
src/ai/backend/account_manager/models/alembic/BUILD
src/ai/backend/account_manager/models/alembic/versions/1449797cc931_create_tables.py
src/ai/backend/account_manager/models/application.py
src/ai/backend/account_manager/models/keypair.py
src/ai/backend/account_manager/models/user.py
src/ai/backend/account_manager/models/userprofile.py
src/ai/backend/account_manager/types.py

chore: Add Account manager models

---

src/ai/backend/account_manager/models/alembic/versions/1449797cc931_create_tables.py
src/ai/backend/account_manager/models/application.py

feat: Allow each service to have own token secret

---

changes/2837.fix.md
src/ai/backend/manager/registry.py

fix: Create kernels with correct scaling group value

---

src/ai/backend/manager/models/alembic/script.py.mako

refs https://docs.makotemplates.org/en/latest/syntax.html#newline-filters
- Remove an extra newline after the import block.
- Reorder imports to conform with our isort rule.

chore: Update the alembic migration script template to match our code style

---

src/ai/backend/manager/models/alembic/script.py.mako

This is an auto-generated backport PR of #2839 to the 24.03 release.

chore: Update the alembic migration script template to match our code style (#2839)

---

src/ai/backend/account_manager/README
src/ai/backend/account_manager/README.md

chore: Add README in Account manager

---

changes/2844.feature.md
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/gql_models/session.py

feat: Add dependee/dependent/graph ComputeSessionNode connection queries

---

changes/2378.fix.md
scripts/install-dev.sh

This is an auto-generated backport PR of #2378 to the 24.03 release.

chore(install-dev): block until DB container stabilizes (#2378)

---

src/ai/backend/manager/models/container_registry.py

fix: Typo when query container registry

---

src/ai/backend/manager/models/agent.py
src/ai/backend/manager/models/rbac/__init__.py
src/ai/backend/manager/models/rbac/permission_defs.py
src/ai/backend/manager/models/scaling_group.py
src/ai/backend/manager/models/session.py
src/ai/backend/manager/models/storage.py
src/ai/backend/manager/models/vfolder.py

chore: Impl RBAC APIs for scaling group and agent

---

src/ai/backend/manager/models/agent.py
src/ai/backend/manager/models/session.py
src/ai/backend/manager/models/storage.py
src/ai/backend/manager/models/vfolder.py

chore: Add override annotations to RBAC methods

---

changes/2900.fix.md
src/ai/backend/storage/vast/__init__.py
src/ai/backend/storage/vast/vastdata_client.py

This is an auto-generated backport PR of #2900 to the 24.03 release.

fix: Update vast quota rather than raise error when quota exists (#2900)

---

changes/2863.feature.md
src/ai/backend/manager/api/schema.graphql
src/ai/backend/manager/models/base.py
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/gql_models/group.py

This is an backport PR of https://github.com/lablup/backend.ai/pull/2863 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--2919.org.readthedocs.build/en/2919/
----
📚 Documentation preview 📚: https://sorna-ko--2919.org.readthedocs.build/ko/2919/

feat: Add filter and order parameters to group relay API (#2863)

---

.github/workflows/backport.yml

follow-up #2913 
Specify the order of the logic to ensure that the pipe is passed properly.

ci: Fix `pr_number` parsing for backporting

---

src/ai/backend/storage/abc.py
src/ai/backend/storage/context.py
src/ai/backend/storage/gpfs/__init__.py
src/ai/backend/storage/vast/__init__.py
src/ai/backend/storage/weka/__init__.py
tests/storage-proxy/conftest.py

This is a backport PR of https://github.com/lablup/backend.ai/pull/2917 to the 24.03 release.

chore: fix typo in storage backend (#2917)

---

src/ai/backend/common/config.py
src/ai/backend/manager/idle.py

refactor: Utilization idle checker calculates resource name to avoid hard code

---

src/ai/backend/common/config.py
src/ai/backend/manager/idle.py

This is an auto-generated backport PR of #2702 to the 24.09 release.

refactor: Utilization idle checker calculates resource name to avoid hard code (#2702)

---

changes/2918.fix.md
src/ai/backend/storage/dellemc/__init__.py
src/ai/backend/storage/dellemc/config.py
src/ai/backend/storage/dellemc/onefs_client.py

This is a backport PR of https://github.com/lablup/backend.ai/pull/2918 to the 24.03 release.
----
📚 Documentation preview 📚: https://sorna--2935.org.readthedocs.build/en/2935/
----
📚 Documentation preview 📚: https://sorna-ko--2935.org.readthedocs.build/ko/2935/

fix: update Dellemc OneFS backend (#2918)

---

src/ai/backend/manager/models/domain.py
src/ai/backend/manager/models/group.py
src/ai/backend/manager/models/rbac/__init__.py
src/ai/backend/manager/models/rbac/permission_defs.py

chore: Add RBAC model schema

---

changes/2949.fix.md
src/ai/backend/manager/models/alembic/versions/1d42c726d8a3_migrate_container_registries_from_etcd_to_psql.py
src/ai/backend/manager/models/alembic/versions/e9e574a6e22d_add_extra_column_to_container_registrys.py

This is an auto-generated backport PR of #2949 to the 24.09 release.

fix: Wrong container registry migration script (#2949)

---

changes/2961.fix.md
src/ai/backend/storage/gpfs/gpfs_client.py

fix: Keep polling when GPFS job is running

---

changes/2961.fix.md
src/ai/backend/storage/gpfs/gpfs_client.py

This is an auto-generated backport PR of #2961 to the 24.03 release.

fix: Keep polling when GPFS job is running (#2961)

---

changes/3002.fix.md
src/ai/backend/manager/models/gql_models/image.py

fix: Wrong field reference in `ImageNode` resolver

---

src/ai/backend/manager/models/image.py
src/ai/backend/manager/models/rbac/permission_defs.py

chore: Impl Image RBAC interface

---

changes/3023.fix.md
src/ai/backend/storage/vast/__init__.py
src/ai/backend/storage/vast/config.py
src/ai/backend/storage/vast/vastdata_client.py

This is an auto-generated backport PR of #3023 to the 24.09 release.

fix: Check Vast data quota with the given quota name exists (#3023)

---

changes/2997.fix.md
src/ai/backend/common/docker.py
src/ai/backend/manager/api/session.py
src/ai/backend/manager/container_registry/harbor.py

This is an auto-generated backport PR of #2997 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3030.org.readthedocs.build/en/3030/
----
📚 Documentation preview 📚: https://sorna-ko--3030.org.readthedocs.build/ko/3030/

fix: customized image not pushed when target registry diverges (#2997)

---

changes/2978.fix.md
src/ai/backend/common/docker.py
src/ai/backend/manager/models/alembic/versions/1d42c726d8a3_migrate_container_registries_from_etcd_to_psql.py
src/ai/backend/manager/models/alembic/versions/7c8501cec07b_add_project_column_to_images_table.py
src/ai/backend/manager/models/container_registry.py
src/ai/backend/manager/models/image.py

This is an auto-generated backport PR of #2978 to the 24.09 release.

refactor: Make `project` column nullable and improve container registry migration script (#2978)

---

src/ai/backend/manager/models/gql_models/image.py

refactor: Add Image batch loader function

---

src/ai/backend/manager/models/base.py
src/ai/backend/manager/models/gql_models/image.py

This is an auto-generated backport PR of #3048 to the 24.09 release.

refactor: Add Image batch loader function (#3048)

---

changes/3061.fix.md
src/ai/backend/manager/models/vfolder.py

This is an auto-generated backport PR of #3061 to the 24.09 release.

fix: Change vfolder name when deleted to allow reusing the name (#3061)

---

src/ai/backend/common/types.py

chore: Add VFolderID string deserializer function

---

.github/workflows/assign-pr-number.yml
.github/workflows/update-api-schema.yml

Remove non-essential dependencies to make debugging and management easier.

ci: Remove the `git-auto-commit` dependency

---

changes/3046.fix.md
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/kernel.py

This is an auto-generated backport PR of #3046 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3088.org.readthedocs.build/en/3088/
----
📚 Documentation preview 📚: https://sorna-ko--3088.org.readthedocs.build/ko/3088/

fix: Regression of `LegacyComputeSession` GQL (#3046)

---

.github/workflows/assign-pr-number.yml
.github/workflows/backport.yml
.github/workflows/update-api-schema.yml

This is an auto-generated backport PR of #3095 to the 24.09 release.

ci: Setting up git commiter (#3095)

---

.github/workflows/pr-number-assign.yml
.github/workflows/update-api-schema.yml

This is an auto-generated backport PR of #3098 to the 24.03 release.

ci: Exit normally if no changes have been made (#3098)

---

src/ai/backend/manager/models/image.py
src/ai/backend/manager/registry.py

chore: Clean-up parameters of bulk_get_image_configs()

---

src/ai/backend/agent/docker/utils.py
src/ai/backend/agent/kubernetes/utils.py

This is an auto-generated backport PR of #3106 to the 24.03 release.

fix: Follow-up of #3101 (#3106)

---

.github/workflows/ci.yml

Let's see how GitHub triggers action workflows with what parameters.

ci: Add CI trigger debug info

---

src/ai/backend/agent/agent.py
src/ai/backend/agent/server.py
src/ai/backend/common/bgtask.py
src/ai/backend/common/docker.py
src/ai/backend/common/events.py
src/ai/backend/common/types.py
src/ai/backend/manager/models/container_registry.py
src/ai/backend/manager/models/image.py
src/ai/backend/manager/models/kernel.py
src/ai/backend/manager/registry.py

feat: Add check-and-pull RPC function 

---

changes/3011.fix.md
src/ai/backend/manager/models/agent.py
src/ai/backend/manager/models/kernel.py

This is a backport PR of https://github.com/lablup/backend.ai/pull/3011 to the 24.09 release

fix: Add missing resolver of Agent.compute_containers GraphQL field #3011

---

changes/2614.feature.md
src/ai/backend/client/cli/session/execute.py
src/ai/backend/client/cli/session/lifecycle.py
src/ai/backend/manager/api/session.py

This is an auto-generated backport PR of #2614 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3132.org.readthedocs.build/en/3132/
----
📚 Documentation preview 📚: https://sorna-ko--3132.org.readthedocs.build/ko/3132/

fix: Allow regular users to assign agent manually when creating sessions (#2614)

---

changes/3137.fix.md
src/ai/backend/manager/api/vfolder.py

This is a backport PR of https://github.com/lablup/backend.ai/pull/3137 to the 24.09 release.

fix: Allow admins to delete other user's vfolders (#3137)

---

MIGRATION.md

Follow-up to #2367, #2002.
- Add PostgreSQL migration guideline
- Add how to migrate DB schema
----
📚 Documentation preview 📚: https://sorna--3096.org.readthedocs.build/en/3096/
----
📚 Documentation preview 📚: https://sorna-ko--3096.org.readthedocs.build/ko/3096/

docs: add instructions for upgrading from 24.03 to 24.09 

---

.readthedocs.yaml
docs/install/install-from-package.rst
docs/install/install-from-package/install-agent.rst
docs/install/install-from-package/install-manager.rst
docs/install/install-from-package/install-webserver.rst
docs/install/install-from-package/install-wsproxy.rst
docs/install/install-from-package/prepare-cache-service.rst
docs/install/install-from-package/prepare-config-service.rst
docs/install/install-from-package/prepare-database.rst

This is an auto-generated backport PR of #2664 to the 24.03 release.
----
📚 Documentation preview 📚: https://sorna--3169.org.readthedocs.build/en/3169/
----
📚 Documentation preview 📚: https://sorna-ko--3169.org.readthedocs.build/ko/3169/

docs: Updated package-based installation documentation for version 24.03.6 (#2664)

---

changes/3031.fix.md
src/ai/backend/common/types.py
src/ai/backend/storage/server.py

This is an auto-generated backport PR of #3031 to the 24.09 release.

fix: Prevent redis password from being logged (#3031)

---

changes/3176.fix.md
src/ai/backend/manager/api/vfolder.py
src/ai/backend/manager/models/vfolder.py

This is an auto-generated backport PR of #3176 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3219.org.readthedocs.build/en/3219/
----
📚 Documentation preview 📚: https://sorna-ko--3219.org.readthedocs.build/ko/3219/

fix: Allow purging vfolders by enabling querying deleted vfolders by name (#3176)

---

tests/manager/api/test_bgtask.py
tools/pytest-requirements.txt
tools/pytest.lock

This is an auto-generated backport PR of #3226 to the 24.09 release.

chore(ci): Apply pytest-timeout to test_bgtask (#3226)

---

changes/3291.fix.md
src/ai/backend/manager/api/session.py

resolves #3290
----
📚 Documentation preview 📚: https://sorna--3291.org.readthedocs.build/en/3291/
----
📚 Documentation preview 📚: https://sorna-ko--3291.org.readthedocs.build/ko/3291/

fix: Invalid API version checks when creating sessions

---

src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/dummy/agent.py
src/ai/backend/agent/kubernetes/agent.py
src/ai/backend/agent/resources.py
tests/agent/test_resources.py

refactor: Container preparation step in Agent

---

src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/dummy/agent.py
src/ai/backend/agent/kubernetes/agent.py
src/ai/backend/agent/resources.py
tests/agent/test_resources.py

refactor: Container preparation step in Agent (#3267)

---

src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/dummy/agent.py
src/ai/backend/agent/dummy/kernel.py
src/ai/backend/agent/kernel.py
src/ai/backend/agent/kubernetes/agent.py
src/ai/backend/common/enum_extension.pyi
src/ai/backend/common/types.py

refactor: Resolve some pyright errors (#3299)

---

changes/.misc.md
changes/3302.misc.md
docs/dev/daily-workflows.rst
docs/install/install-from-package/os-preparation.rst
docs/locales/ko/LC_MESSAGES/install/install-from-package.po
docs/locales/ko/LC_MESSAGES/install/install-from-package/os-preparation.po
pants.toml
pyproject.toml
python-kernel.lock
python.lock
scripts/bootstrap-static-python.sh
scripts/delete-dev.sh
src/ai/backend/common/docker.py
src/ai/backend/install/README.md
tools/black.lock
tools/coverage-py.lock
tools/mypy.lock
tools/pants-plugins/scie/config.py
tools/pytest.lock
tools/ruff.lock
tools/setuptools.lock
tools/towncrier.lock

resolves #3300 (BA-413)
----
📚 Documentation preview 📚: https://sorna--3302.org.readthedocs.build/en/3302/
----
📚 Documentation preview 📚: https://sorna-ko--3302.org.readthedocs.build/ko/3302/

chore: Upgrade Python (3.12.6 -> 3.12.8)

---

changes/3029.fix.md
src/ai/backend/install/widgets.py

fix: Make the install path visible (#3029)

---

src/ai/backend/accelerator/cuda_open/README.md

----
📚 Documentation preview 📚: https://sorna--3312.org.readthedocs.build/en/3312/
----
📚 Documentation preview 📚: https://sorna-ko--3312.org.readthedocs.build/ko/3312/

docs: Update readme for the cuda_open plugin in the monorepo (#2869)

---

scripts/diff-release.py

chore(scripts): Update diff-releases.py to recognize auto-backported PRs (#3330)

---

tools/pants-plugins/scie/subsystems.py

Let's update the science package to handle recent changes in the PBS project.
- https://github.com/lablup/backend.ai/actions/runs/12607450535/job/35138880763

ci: Update science package to latest to handle recent changes in PBS

---

tools/pants-plugins/scie/subsystems.py

This is an auto-generated backport PR of #3371 to the 24.03 release.

ci: Update science package to latest to handle recent changes in PBS (#3371)

---

changes/3363.fix.md
src/ai/backend/common/defs.py
src/ai/backend/common/typed_validators.py
src/ai/backend/manager/api/vfolder.py
src/ai/backend/manager/models/alembic/versions/ef9a7960d234_extend_length_of_vfolders_name_column.py
src/ai/backend/manager/models/vfolder.py

This is an auto-generated backport PR of #3363 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3415.org.readthedocs.build/en/3415/
----
📚 Documentation preview 📚: https://sorna-ko--3415.org.readthedocs.build/ko/3415/

fix(BA-432): Enforce VFolder name length restriction through the API schema (#3363)

---

changes/3388.fix.md
src/ai/backend/manager/api/vfolder.py

This is an auto-generated backport PR of #3388 to the 24.03 release.
----
📚 Documentation preview 📚: https://sorna--3429.org.readthedocs.build/en/3429/
----
📚 Documentation preview 📚: https://sorna-ko--3429.org.readthedocs.build/ko/3429/

fix(BA-454): Directly retrieve VFolder by folder ID in purge API (#3388)

---

.github/PULL_REQUEST_TEMPLATE.md

This PR adds a reminder to explicitly link the GitHub issue and the corresponding Jira issue.

chore: Update PR template to remind mentioning both GitHub/Jira issues

---

.github/PULL_REQUEST_TEMPLATE.md

This is an auto-generated backport PR of #3448 to the 24.09 release.

chore: Update PR template to remind mentioning both GitHub/Jira issues (#3448)

---

changes/3442.fix.md
src/ai/backend/manager/idle.py

resolves #3441 
follow-up #2702 

fix(BA-510): Utilization idle checker computes kernel stat correctly

---

changes/3442.fix.md
src/ai/backend/manager/idle.py

This is an auto-generated backport PR of #3442 to the 24.09 release.

fix(BA-510): Utilization idle checker computes kernel stat correctly (#3442)

---

changes/3047.fix.md
src/ai/backend/manager/models/base.py
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/vfolder.py
tests/manager/conftest.py
tests/manager/models/test_base.py
tests/manager/models/test_vfolder.py

This is an auto-generated backport PR of #3047 to the 24.03 release.
----
📚 Documentation preview 📚: https://sorna--3452.org.readthedocs.build/en/3452/
----
📚 Documentation preview 📚: https://sorna-ko--3452.org.readthedocs.build/ko/3452/

fix(BA-420): Regression of outdated `vfolder` GQL resolver (#3047)

---

changes/3231.doc.md
docs/manager/graphql-reference/schema.graphql
src/ai/backend/manager/models/container_registry.py

This is an auto-generated backport PR of #3231 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3456.org.readthedocs.build/en/3456/
----
📚 Documentation preview 📚: https://sorna-ko--3456.org.readthedocs.build/ko/3456/

doc: Deprecate non relay container registry GQL explicitly (#3231)

---

changes/2979.fix.md
docs/manager/rest-reference/openapi.json
src/ai/backend/common/docker.py
src/ai/backend/manager/container_registry/aws_ecr.py
src/ai/backend/manager/container_registry/base.py
src/ai/backend/manager/container_registry/docker.py
src/ai/backend/manager/container_registry/github.py
src/ai/backend/manager/container_registry/gitlab.py
src/ai/backend/manager/container_registry/harbor.py
src/ai/backend/manager/container_registry/local.py
src/ai/backend/manager/exceptions.py
src/ai/backend/manager/models/image.py
tests/client/integration/test_image.py
tests/manager/models/test_image.py
tests/manager/test_image.py

This is an auto-generated backport PR of #2979 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3472.org.readthedocs.build/en/3472/
----
📚 Documentation preview 📚: https://sorna-ko--3472.org.readthedocs.build/ko/3472/

refactor(BA-462): Container registry project traversal logic of image rescanning (#2979)

---

changes/3237.feature.md
docs/manager/graphql-reference/schema.graphql
docs/manager/rest-reference/openapi.json
src/ai/backend/client/cli/admin/image.py
src/ai/backend/client/func/image.py
src/ai/backend/manager/api/session.py
src/ai/backend/manager/cli/image.py
src/ai/backend/manager/cli/image_impl.py
src/ai/backend/manager/models/gql_models/image.py
src/ai/backend/manager/models/image.py
tests/manager/conftest.py
tests/manager/models/test_image.py

Resolve #2994 (BA-72)
----
📚 Documentation preview 📚: https://sorna--3474.org.readthedocs.build/en/3474/
----
📚 Documentation preview 📚: https://sorna-ko--3474.org.readthedocs.build/ko/3474/

feat(BA-72): Enable image rescanning by project (restore)

---

changes/3457.feature.md
changes/3458.feature.md
configs/grafana/dashboards/dashboard.json
configs/grafana/provisioning/dashboards/dashboards.yaml
configs/grafana/provisioning/datasources/datasources.yaml
configs/prometheus/prometheus.yaml
docker-compose.halfstack-2409.yml
src/ai/backend/account_manager/server.py
src/ai/backend/wsproxy/config.py

resolves https://github.com/lablup/backend.ai-internal/issues/26 (BA-399)
----
📚 Documentation preview 📚: https://sorna--3458.org.readthedocs.build/en/3458/
----
📚 Documentation preview 📚: https://sorna-ko--3458.org.readthedocs.build/ko/3458/

feat(BA-399): Add Grafana and Prometheus to Docker Compose

---

changes/3451.fix.md
docs/manager/rest-reference/openapi.json
src/ai/backend/manager/api/exceptions.py
src/ai/backend/manager/api/vfolder.py
src/ai/backend/manager/models/vfolder.py
tests/manager/api/test_vfolder.py

This is an auto-generated backport PR of #3451 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3484.org.readthedocs.build/en/3484/
----
📚 Documentation preview 📚: https://sorna-ko--3484.org.readthedocs.build/ko/3484/

fix(BA-515): Let the vfolder REST API accept vfolder UUIDs as intended (#3451)

---

changes/3471.feature.md
src/ai/backend/client/func/vfolder.py
src/ai/backend/client/session.py
tests/client/test_vfolder.py
tests/client/test_vfolder_tus.py

This is an auto-generated backport PR of #3471 to the 24.09 release.

feat(BA-519): Update SDK to retrieve and use IDs for VFolder API operations instead of names (#3471)

---

src/ai/backend/account_manager/config.py
src/ai/backend/agent/config.py
src/ai/backend/manager/config.py
src/ai/backend/storage/config.py

fix(BA-536): Add pyroscope default config

---

changes/3461.fix.md
docs/manager/rest-reference/openapi.json
src/ai/backend/manager/models/gql_models/session.py
src/ai/backend/manager/models/session.py

This is an auto-generated backport PR of #3461 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3537.org.readthedocs.build/en/3537/
----
📚 Documentation preview 📚: https://sorna-ko--3537.org.readthedocs.build/ko/3537/

fix(BA-507): GQL `compute_session.vfolder_mounts` returns folder id (#3461)

---

changes/3581.fix.md
src/ai/backend/client/func/vfolder.py
tests/client/test_vfolder.py

fix(BA-640): vfolder delete SDK function not working

---

src/ai/backend/manager/api/vfolder.py
src/ai/backend/storage/api/manager.py

fix(BA-653): Wrong mode value of create argument

---

changes/3599.fix.md
src/ai/backend/manager/models/alembic/versions/ecc9f6322be4_remove_fk_constraint_from_endpoints_.py
src/ai/backend/manager/models/endpoint.py
src/ai/backend/manager/models/image.py

This is an auto-generated backport PR of #3599 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3603.org.readthedocs.build/en/3603/
----
📚 Documentation preview 📚: https://sorna-ko--3603.org.readthedocs.build/ko/3603/

fix(BA-584): Remove foreign key constraint from `EndpointRow.image` column (#3599)

---

changes/3654.fix.md
docs/manager/rest-reference/openapi.json
src/ai/backend/manager/models/kernel.py

This is an auto-generated backport PR of #3654 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3659.org.readthedocs.build/en/3659/
----
📚 Documentation preview 📚: https://sorna-ko--3659.org.readthedocs.build/ko/3659/

fix(BA-694): Number of concurrent sftp session queried incorrectly (#3654)

---

changes/3680.feature.md
configs/webserver/halfstack.conf
src/ai/backend/web/config.py
src/ai/backend/web/security.py
src/ai/backend/web/server.py

feat: Make security policy configurable

---

changes/3680.feature.md
configs/webserver/halfstack.conf
src/ai/backend/web/config.py
src/ai/backend/web/security.py
src/ai/backend/web/server.py

This is an auto-generated backport PR of #3680 to the 24.09 release.

feat(BA-720): Make security policy configurable (#3680)

---

changes/3682.feature.md
configs/webserver/halfstack.conf
src/ai/backend/web/config.py
src/ai/backend/web/security.py
src/ai/backend/web/server.py
tests/webserver/test_security_policy.py

This is an auto-generated backport PR of #3682 to the 24.09 release.

feat(BA-690): Make CSP configurable (#3682)

---

changes/3751.feature.md
src/ai/backend/manager/models/gql_models/session.py
src/ai/backend/manager/models/session.py

feat(BA-790): Sort vfolder list in compute session GQL objects

---

changes/3751.feature.md
src/ai/backend/manager/models/gql_models/session.py
src/ai/backend/manager/models/session.py

This is an auto-generated backport PR of #3751 to the 24.09 release.

feat(BA-790): Sort vfolder list in compute session GQL objects (#3751)

---

src/ai/backend/manager/models/endpoint.py

fix(BA-792): Cartesian product when querying endpoint auto scaling rules

---

.github/workflows/ci.yml
scripts/check-alembic-revision.py

This is an auto-generated backport PR of #2716 to the 24.09 release.

ci(BA-542): Verify that the current model schema and the migration file match (#2716)

---

python.lock
requirements.txt

chore(BA-816): Update etcd-client-py (0.3.0 -> 0.4.0)

---

changes/3782.fix.md
docs/manager/rest-reference/openapi.json
src/ai/backend/manager/models/gql_models/session.py

This is an auto-generated backport PR of #3782 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3797.org.readthedocs.build/en/3797/
----
📚 Documentation preview 📚: https://sorna-ko--3797.org.readthedocs.build/ko/3797/

fix(BA-814): Add service_ports resolver to GQL ComputeSessionNode type (#3782)

---

changes/3799.fix.md
src/ai/backend/manager/models/gql_models/vfolder.py
src/ai/backend/manager/models/storage.py

fix(BA-824): GQL VFolderNode filter argument

---

src/ai/backend/manager/BUILD

chore: Add network dependency to manager BUILD

---

changes/3816.fix.md
src/ai/backend/manager/models/alembic/versions/308bcecec5c2_add_groups_type.py

This is an auto-generated backport PR of #3816 to the 24.03 release.

fix(BA-844): add groups type DB migration (#3816)

---

changes/3829.fix.md
src/ai/backend/manager/models/alembic/versions/1f55a65cfc4f_add_status_column_to_vfolders.py
src/ai/backend/manager/models/alembic/versions/5ba7fde56ddb_add_vfolder_purge_status.py
src/ai/backend/manager/models/alembic/versions/7ff52ff68bfc_detail_vfolder_deletion_status.py
src/ai/backend/manager/models/alembic/versions/85984c98b90f_update_endpoint_and_routing_table.py
src/ai/backend/manager/models/alembic/versions/bedd92de93af_add_role_column_on_kernels_table.py

fix(BA-848): Wrong alembic scripts

---

changes/3829.fix.md
src/ai/backend/manager/models/alembic/versions/1f55a65cfc4f_add_status_column_to_vfolders.py
src/ai/backend/manager/models/alembic/versions/5ba7fde56ddb_add_vfolder_purge_status.py
src/ai/backend/manager/models/alembic/versions/7ff52ff68bfc_detail_vfolder_deletion_status.py
src/ai/backend/manager/models/alembic/versions/85984c98b90f_update_endpoint_and_routing_table.py
src/ai/backend/manager/models/alembic/versions/bedd92de93af_add_role_column_on_kernels_table.py

This is an auto-generated backport PR of #3829 to the 24.09 release.

fix(BA-848): Wrong alembic scripts (#3829)

---

changes/3851.fix.md
docs/manager/rest-reference/openapi.json
src/ai/backend/manager/models/rbac/permission_defs.py
src/ai/backend/manager/models/vfolder.py

This is an auto-generated backport PR of #3851 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3855.org.readthedocs.build/en/3855/
----
📚 Documentation preview 📚: https://sorna-ko--3855.org.readthedocs.build/ko/3855/

fix(BA-868): Missing vfolder mount permission (#3851)

---

changes/3859.feature.md
src/ai/backend/manager/BUILD
src/ai/backend/manager/actions/BUILD
src/ai/backend/manager/actions/action.py
src/ai/backend/manager/actions/middlewares/middleware.py
src/ai/backend/manager/actions/monitors/BUILD
src/ai/backend/manager/actions/monitors/monitor.py
src/ai/backend/manager/actions/processor.py

feat(BA-873): Add centralized action processor design

---

changes/3630.feature.md
src/ai/backend/manager/api/session.py
src/ai/backend/manager/api/vfolder.py
src/ai/backend/manager/models/endpoint.py
src/ai/backend/manager/models/gql_models/vfolder.py
src/ai/backend/manager/models/group.py
src/ai/backend/manager/models/storage.py
src/ai/backend/manager/models/user.py
src/ai/backend/manager/models/vfolder.py
src/ai/backend/manager/registry.py

resolves #3626 (BA-681)
----
📚 Documentation preview 📚: https://sorna--3630.org.readthedocs.build/en/3630/
----
📚 Documentation preview 📚: https://sorna-ko--3630.org.readthedocs.build/ko/3630/

feat(BA-681): Allow unmanaged vfolders to be created and mounted

---

changes/3780.fix.md
docs/manager/rest-reference/openapi.json
src/ai/backend/manager/api/auth.py
src/ai/backend/manager/models/keypair.py
src/ai/backend/manager/models/user.py

This is an auto-generated backport PR of #3780 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3864.org.readthedocs.build/en/3864/
----
📚 Documentation preview 📚: https://sorna-ko--3864.org.readthedocs.build/ko/3864/

fix(BA-781): Let Auth API handler check all keypairs owned by user (#3780)

---

changes/3861.fix.md
src/ai/backend/manager/idle.py

This is an auto-generated backport PR of #3861 to the 24.09 release.

fix(BA-880): Aggregate multi-kernel session utilization in idle checker (#3861)

---

configs/webserver/halfstack.conf
configs/webserver/sample.conf

fix(BA-872): Fix webserver CSP config

---

changes/3871.fix.md
src/ai/backend/manager/container_registry/harbor.py

This is an auto-generated backport PR of #3871 to the 23.09 release.

fix(BA-887): Rescan all tags in `HarborRegistryV2` (#3871)

---

changes/3814.feature.md
src/ai/backend/manager/container_registry/base.py
src/ai/backend/manager/container_registry/harbor.py

Resolves #3690 ([BA-741](https://lablup.atlassian.net/browse/BA-741)).
Tested on Harbor registry V2, and AWS ECR for `_scan_tag()` of `BaseContainerRegistry`.
[BA-741]: https://lablup.atlassian.net/browse/BA-741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(BA-741): Support `application/vnd.oci.image.manifest.v1+json` type images

---

changes/3883.fix.md
docs/manager/rest-reference/openapi.json
src/ai/backend/manager/models/image.py

This is an auto-generated backport PR of #3883 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3884.org.readthedocs.build/en/3884/
----
📚 Documentation preview 📚: https://sorna-ko--3884.org.readthedocs.build/ko/3884/

fix(BA-898): Image rescan DB serialization error (#3883)

---

src/ai/backend/manager/api/resource.py

fix(BA-902): Wrong resource-preset query

---

changes/3880.feature.md
changes/3880.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/config.py
src/ai/backend/agent/exception.py
src/ai/backend/agent/kernel.py
src/ai/backend/common/events.py

This is an auto-generated backport PR of #3880 to the 24.09 release.

fix(BA-871): Retry zmq socket from kernel (#3880)

---

changes/3891.feature.md
configs/grafana/dashboards/dashboard.json
src/ai/backend/common/metrics/metric.py
src/ai/backend/manager/api/admin.py
src/ai/backend/manager/models/gql.py
tests/manager/models/gql_models/test_agent.py
tests/manager/models/gql_models/test_container_registries.py
tests/manager/models/gql_models/test_container_registry_nodes.py
tests/manager/models/gql_models/test_container_registry_nodes_v2.py
tests/manager/models/gql_models/test_group.py
tests/manager/models/test_container_registries.py
tests/manager/models/test_image.py
tests/manager/models/test_vfolder.py

feat(BA-15): Add GQL Exception middleware

---

changes/3916.feature.md
docs/manager/graphql-reference/schema.graphql
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/resource_preset.py

resolves #3915 (BA-925)
----
📚 Documentation preview 📚: https://sorna--3916.org.readthedocs.build/en/3916/
----
📚 Documentation preview 📚: https://sorna-ko--3916.org.readthedocs.build/ko/3916/

feat(BA-925): Add filter/order to resource preset GQL query and follow-up delete mutation

---

src/ai/backend/common/BUILD

chore: Add agent dto to python distribution

---

changes/3928.fix.md
src/ai/backend/common/msgpack.py
src/ai/backend/manager/models/gql_models/agent.py
tests/common/test_msgpack.py

fix(BA-934): Resolve GQL Agent live_stat field

---

src/ai/backend/agent/metrics/metric.py

feat(BA-963): Separate metric name labels for container metric and device metric

---

changes/3935.feature.md
src/ai/backend/manager/api/vfolder.py

This is an auto-generated backport PR of #3935 to the 24.03 release.

feat(BA-430): Improve Performance of vfolder `list_host` API handler (#3935)

---

changes/3980.feature.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/docker/kernel.py
src/ai/backend/agent/dummy/agent.py
src/ai/backend/agent/dummy/kernel.py
src/ai/backend/agent/kernel.py
src/ai/backend/agent/kubernetes/agent.py
src/ai/backend/agent/kubernetes/kernel.py
src/ai/backend/agent/metrics/metric.py
src/ai/backend/agent/metrics/types.py
src/ai/backend/agent/server.py
src/ai/backend/agent/stats.py
src/ai/backend/agent/types.py
src/ai/backend/common/metrics/types.py
src/ai/backend/manager/registry.py

feat(BA-968): Add container labels for better metric query

---

changes/3996.fix.md
src/ai/backend/manager/models/gql_models/agent.py

fix(BA-1006): superadmin query agent nodes

---

changes/3989.feature.md
configs/account-manager/halfstack.toml
configs/account-manager/sample.toml
configs/manager/halfstack.toml
configs/manager/sample.toml
configs/prometheus/prometheus.yaml
configs/storage-proxy/halfstack.toml
configs/storage-proxy/sample.toml
configs/wsproxy/halfstack.toml
configs/wsproxy/sample.toml
src/ai/backend/account_manager/config.py
src/ai/backend/account_manager/server.py
src/ai/backend/manager/config.py
src/ai/backend/manager/server.py
src/ai/backend/storage/api/manager.py
src/ai/backend/storage/config.py
src/ai/backend/storage/context.py
src/ai/backend/storage/server.py
src/ai/backend/wsproxy/config.py
src/ai/backend/wsproxy/server.py

feat(BA-922): Add internal address config

---

changes/4010.fix.md
src/ai/backend/storage/server.py

fix(BA-1019): Correct initialization of Storage proxy event dispatcher

---

changes/4022.fix.md
src/ai/backend/manager/actions/action.py
src/ai/backend/manager/actions/processor.py
src/ai/backend/manager/server.py

fix(BA-1025): Update common structure

---

changes/4029.feature.md
src/ai/backend/manager/models/session.py
src/ai/backend/manager/registry.py

feat(BA-1030): Enhance session status transition management

---

changes/4056.feature.md
src/ai/backend/manager/actions/action.py
src/ai/backend/manager/actions/processor.py
tests/manager/actions/BUILD
tests/manager/actions/test_processor.py

feat(BA-1048): Add raise exception in action processor

---

changes/4057.fix.md
docs/manager/rest-reference/openapi.json
src/ai/backend/client/cli/admin/image.py
src/ai/backend/client/cli/service.py
src/ai/backend/client/cli/session/lifecycle.py
src/ai/backend/client/cli/vfolder.py
src/ai/backend/common/events.py
src/ai/backend/manager/cli/image_impl.py
src/ai/backend/manager/container_registry/base.py
src/ai/backend/manager/container_registry/harbor.py
src/ai/backend/manager/exceptions.py
src/ai/backend/manager/models/gql_models/image.py

Follow-up of #3883.
Resolves #4009 (BA-1018).
----
📚 Documentation preview 📚: https://sorna--4057.org.readthedocs.build/en/4057/
----
📚 Documentation preview 📚: https://sorna-ko--4057.org.readthedocs.build/ko/4057/

fix(BA-1018): Wrong exception handling in image rescanning

---

changes/3939.fix.md
src/ai/backend/manager/models/gql_models/image.py
src/ai/backend/manager/models/image.py

fix(BA-954): Customized image visibility issue

---

changes/4068.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/common/events.py
src/ai/backend/common/types.py
src/ai/backend/manager/api/session.py
src/ai/backend/manager/registry.py
src/ai/backend/manager/server.py
src/ai/backend/storage/migration.py
src/ai/backend/storage/server.py
tests/common/test_distributed.py
tests/common/test_events.py

fix(BA-1033): Setup source at producer creation

---

changes/4047.fix.md
src/ai/backend/agent/docker/agent.py

fix(BA-1041): Add newline at end of customized dotfiles

---

src/ai/backend/common/BUILD

chore: Add message queue to dependencies

---

changes/4086.fix.md
src/ai/backend/manager/models/kernel.py

fix(BA-1075): Avoid kernel full scan

---

changes/4094.fix.md
src/ai/backend/common/types.py

fix(BA-1080): pydantic validation error from wrong type aliasing

---

changes/4058.feature.md
src/ai/backend/manager/models/user.py
src/ai/backend/manager/models/utils.py
src/ai/backend/manager/server.py
src/ai/backend/manager/services/processors.py
src/ai/backend/manager/services/users/BUILD
src/ai/backend/manager/services/users/actions/BUILD
src/ai/backend/manager/services/users/actions/base.py
src/ai/backend/manager/services/users/actions/create_user.py
src/ai/backend/manager/services/users/actions/delete_user.py
src/ai/backend/manager/services/users/actions/modify_user.py
src/ai/backend/manager/services/users/actions/purge_user.py
src/ai/backend/manager/services/users/processors.py
src/ai/backend/manager/services/users/service.py
src/ai/backend/manager/services/users/type.py

resolves #3955  (BA-987)
----
📚 Documentation preview 📚: https://sorna--4058.org.readthedocs.build/en/4058/
----
📚 Documentation preview 📚: https://sorna-ko--4058.org.readthedocs.build/ko/4058/

refactor(BA-978): Add User Service & Processors

---

changes/4104.feature.md
src/ai/backend/common/contexts/BUILD
src/ai/backend/common/contexts/request_id.py
src/ai/backend/common/middlewares/BUILD
src/ai/backend/common/middlewares/request_id.py
src/ai/backend/manager/server.py
tests/common/test_request_id.py
tests/common/test_request_id_middleware.py

feat(BA-1085): Add RequestID context & middleware

---

src/ai/backend/manager/api/vfolder.py
src/ai/backend/manager/services/vfolder/actions/base.py

chore: fix wrong tristate case

---

src/ai/backend/manager/models/gql_models/group.py
src/ai/backend/manager/models/gql_models/user.py
src/ai/backend/manager/services/group/actions/modify_group.py
src/ai/backend/manager/services/group/service.py
src/ai/backend/manager/services/group/types.py
src/ai/backend/manager/services/user/actions/modify_user.py
src/ai/backend/manager/services/user/service.py

fix(BA-1130): Cannot modify user info

---

src/ai/backend/manager/models/gql_models/image.py
src/ai/backend/manager/models/gql_models/resource_preset.py
src/ai/backend/manager/models/gql_models/session.py
src/ai/backend/manager/models/resource_policy.py

fix(BA-1133): Broken API caused by wrong handling of graphql `Undefined` 

---

src/ai/backend/manager/api/vfolder.py
src/ai/backend/manager/services/vfolder/actions/base.py

fix: do null-check of VFolder Modify API params

---

src/ai/backend/manager/models/resource_policy.py
src/ai/backend/manager/services/keypair_resource_policy/actions/modify_keypair_resource_policy.py

fix(BA-1132): Broken `ModifyKeypairResource` mutation

---

src/ai/backend/manager/models/gql_models/image.py

fix(BA-1134): Broken `ModifyImage` mutation

---

src/ai/backend/manager/models/gql_models/group.py
src/ai/backend/manager/models/gql_models/user.py

fix(BA-1142): Fix wrong OptionalState init in `User` and `Group`

---

changes/4153.deps.md
docs/dev/daily-workflows.rst
docs/install/install-from-package/os-preparation.rst
pants.toml
pyproject.toml
python-kernel.lock
python.lock
requirements.txt
scripts/bootstrap-static-python.sh
scripts/delete-dev.sh
src/ai/backend/install/README.md
tools/black.lock
tools/build-macros.py
tools/coverage-py.lock
tools/mypy.lock
tools/pytest.lock
tools/ruff.lock
tools/setuptools.lock
tools/towncrier.lock

resolves #3285 (BA-4)
- **chore: Update mentions on 3.12.8 to 3.13.3**
- **chore: Update lockfiles**
----
📚 Documentation preview 📚: https://sorna--4153.org.readthedocs.build/en/4153/
----
📚 Documentation preview 📚: https://sorna-ko--4153.org.readthedocs.build/ko/4153/

chore(BA-4): Upgrade to Python 3.13

---

changes/4159.fix.md
docs/manager/rest-reference/openapi.json
src/ai/backend/manager/api/service.py

Follow-up to #4122.
Resolves #4158 (BA-1149).

fix(BA-1149): Broken model service creation logic

---

changes/3986.feature.md
docs/manager/graphql-reference/schema.graphql
src/ai/backend/manager/container_registry/base.py
src/ai/backend/manager/container_registry/harbor.py
src/ai/backend/manager/data/image/types.py
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/gql_models/image.py
src/ai/backend/manager/models/image.py
src/ai/backend/manager/services/image/actions/clear_image_custom_resource_limit.py
src/ai/backend/manager/services/image/actions/modify_image.py
src/ai/backend/manager/services/image/processors.py
src/ai/backend/manager/services/image/service.py

Resolves #3941 (BA-961)
----
📚 Documentation preview 📚: https://sorna--3986.org.readthedocs.build/en/3986/
----
📚 Documentation preview 📚: https://sorna-ko--3986.org.readthedocs.build/ko/3986/

feat(BA-961): Make Image Resource limit non-volatile

---

src/ai/backend/manager/models/gql_models/user.py

chore: fix wrong type casting

---

src/ai/backend/manager/cli/context.py

fix(BA-1165): Fix wrong redis init in cli context

---

changes/4177.fix.md
src/ai/backend/manager/models/gql_models/image.py

Backported-to: 24.09
Backported-of: #4177
----
📚 Documentation preview 📚: https://sorna--4178.org.readthedocs.build/en/4178/
----
📚 Documentation preview 📚: https://sorna-ko--4178.org.readthedocs.build/ko/4178/

fix(BA-1136): Broken UntagImageFromRegistry GQL mutation (#4177)

---

changes/4176.feature.md
src/ai/backend/manager/api/auth.py
src/ai/backend/manager/models/keypair.py

feat(BA-1139): Validate SSH keypair when upload

---

changes/4179.fix.md
configs/manager/sample.toml
python.lock
requirements.txt
src/ai/backend/manager/config.py
src/ai/backend/manager/reporters/smtp.py
src/ai/backend/manager/server.py

fix(BA-1166): Replace `aiosmtplib` with `smtplib`

---

src/ai/backend/manager/api/vfolder.py
src/ai/backend/manager/services/vfolder/exceptions.py
src/ai/backend/manager/services/vfolder/services/vfolder.py

feat(BA-1168): Handle vfolder creation action failure to return a valid respond

---

changes/4194.fix.md
src/ai/backend/manager/services/vfolder/actions/base.py

fix(BA-1178): VFolder permission edit mutation not working

---

changes/4200.fix.md
src/ai/backend/manager/services/vfolder/actions/base.py
src/ai/backend/manager/services/vfolder/actions/file.py

fix(BA-1181): Unify BaseAction's `operation_type` convention

---

changes/4225.fix.md
src/ai/backend/manager/models/gql_models/audit_log.py
src/ai/backend/manager/models/network.py

fix(BA-1194): Add missing `dtparse` for `created_at` in queryfilter

---

changes/4218.fix.md
src/ai/backend/manager/models/rbac/__init__.py

fix(BA-1189): calculate admin role in project correctly

---

changes/4227.fix.md
src/ai/backend/manager/api/vfolder.py

fix: Revert response schema of vfolder mkdir API

---

changes/4224.fix.md
src/ai/backend/manager/models/vfolder.py

fix(BA-1193): Allow extra mounts of model services

---

changes/4232.fix.md
src/ai/backend/manager/models/image.py

fix(BA-1205): `ImageAliasData` type not found in `ImageAliasData.to_dataclass()`

---

changes/4247.fix.md
src/ai/backend/manager/models/vfolder.py

fix(BA-1217): Filter duplicate vfolder mounts

---

src/ai/backend/manager/actions/action.py
src/ai/backend/manager/actions/processor.py
src/ai/backend/manager/actions/types.py
src/ai/backend/manager/models/audit_log.py
src/ai/backend/manager/models/gql_models/audit_log.py
src/ai/backend/manager/reporters/base.py
src/ai/backend/manager/reporters/smtp.py

fix(BA-1236): Remove import cycle

---

.github/workflows/ci.yml

ci: Bump twine from 5 to 6

---

changes/4309.fix.md
src/ai/backend/common/message_queue/hiredis_queue.py

fix(BA-1268): wrong msg id type

---

changes/4309.fix.md
src/ai/backend/common/message_queue/hiredis_queue.py

This is an auto-generated backport PR of #4309 to the 25.6 release.

fix(BA-1268): wrong msg id type (#4309)

---

README.md
changes/4313.misc.md
scripts/build-wheel.sh

feat(BA-1242): Add build wheel script

---

changes/4340.fix.md
src/ai/backend/common/bgtask.py

fix(BA-1281): Add default value of task_info value

---

changes/4339.fix.md
src/ai/backend/common/redis_helper.py

fix(BA-1302): Add TypeError handling in redis_helper

---

changes/4337.feature.md
src/ai/backend/common/bgtask.py
src/ai/backend/common/exception.py
src/ai/backend/common/metrics/http.py
src/ai/backend/common/metrics/metric.py
src/ai/backend/manager/actions/action.py
src/ai/backend/manager/actions/monitors/prometheus.py
src/ai/backend/manager/actions/processor.py
src/ai/backend/manager/models/gql.py
tests/manager/actions/test_processor.py

feat(BA-1301): Add error code to metric

---

changes/4336.feature.md
src/ai/backend/common/exception.py
src/ai/backend/manager/models/gql.py
tests/manager/api/test_exceptions.py

feat(BA-1300): Add error code to API exception message

---

changes/4343.feature.md
src/ai/backend/common/BUILD
src/ai/backend/common/service_discovery/BUILD
src/ai/backend/common/service_discovery/etcd_discovery/BUILD
src/ai/backend/common/service_discovery/etcd_discovery/service_discovery.py
src/ai/backend/common/service_discovery/service_discovery.py
tests/common/service_discovery/BUILD
tests/common/service_discovery/conftest.py
tests/common/service_discovery/test_etcd_discovery.py

feat(BA-1279): Add etcd service discovery

---

changes/4059.feature.md
tests/manager/services/test_users.py

resolves #3966 (BA-986)
----
📚 Documentation preview 📚: https://sorna--4059.org.readthedocs.build/en/4059/
----
📚 Documentation preview 📚: https://sorna-ko--4059.org.readthedocs.build/ko/4059/

feat(BA-986): Add Action Test Code for User

---

src/ai/backend/manager/cli/fixture.py

fix(BA-1330): Fixture populate not working

---

src/ai/backend/manager/registry.py
src/ai/backend/manager/scheduler/types.py

fix: Remove wrong shared config

---

changes/4364.doc.md
docs/dev/daily-workflows.rst

----
📚 Documentation preview 📚: https://sorna--4364.org.readthedocs.build/en/4364/
----
📚 Documentation preview 📚: https://sorna-ko--4364.org.readthedocs.build/ko/4364/

doc: Update towncrier command docs

---

changes/4363.misc.md
src/ai/backend/agent/agent.py
src/ai/backend/common/message_queue/hiredis_queue.py
src/ai/backend/common/redis_client.py
src/ai/backend/common/redis_helper.py
src/ai/backend/common/types.py
src/ai/backend/manager/api/ratelimit.py
src/ai/backend/manager/cli/context.py
src/ai/backend/manager/idle.py
src/ai/backend/manager/models/gql_models/keypair.py
src/ai/backend/manager/scheduler/dispatcher.py
src/ai/backend/manager/server.py
src/ai/backend/storage/migration.py
src/ai/backend/storage/server.py
src/ai/backend/web/server.py
tests/common/message_queue/test_hiredis_queue.py
tests/common/message_queue/test_redis_queue.py
tests/common/redis_helper/test_connect.py
tests/common/test_distributed.py
tests/common/test_events.py
tests/manager/api/test_bgtask.py

refactor: Rename redis target

---

changes/4144.fix.md
docs/manager/rest-reference/openapi.json
src/ai/backend/manager/api/vfolder.py

This is an auto-generated backport PR of #4144 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--4382.org.readthedocs.build/en/4382/
----
📚 Documentation preview 📚: https://sorna-ko--4382.org.readthedocs.build/ko/4382/

fix(BA-1141): Wrong project-id parsing when creating project vfolder (#4144)

---

changes/4379.feature.md
src/ai/backend/manager/actions/types.py
src/ai/backend/manager/services/agent/processors.py
src/ai/backend/manager/services/container_registry/processors.py
src/ai/backend/manager/services/domain/processors.py
src/ai/backend/manager/services/group/processors.py
src/ai/backend/manager/services/image/processors.py
src/ai/backend/manager/services/keypair_resource_policy/processors.py
src/ai/backend/manager/services/metric/processors/utilization_metric.py
src/ai/backend/manager/services/model_serving/processors/auto_scaling.py
src/ai/backend/manager/services/model_serving/processors/model_serving.py
src/ai/backend/manager/services/processors.py
src/ai/backend/manager/services/project_resource_policy/processors.py
src/ai/backend/manager/services/resource_preset/processors.py
src/ai/backend/manager/services/session/processors.py
src/ai/backend/manager/services/user/processors.py
src/ai/backend/manager/services/user_resource_policy/processors.py
src/ai/backend/manager/services/vfolder/processors/file.py
src/ai/backend/manager/services/vfolder/processors/invite.py
src/ai/backend/manager/services/vfolder/processors/vfolder.py

feat(BA-1158): Introduce ProcessorPackage

---

changes/4365.enhance.md
src/ai/backend/manager/config/unified.py

fix(BA-1331): Add `validation_alias` and `serialization_alias` to ManagerSharedConfig configs

---

changes/4395.fix.md
src/ai/backend/manager/config/unified.py
src/ai/backend/manager/models/utils.py
tests/manager/conftest.py

fix(BA-1362): Revert sane default config update

---

src/ai/backend/manager/services/group/service.py
src/ai/backend/manager/services/processors.py
src/ai/backend/manager/services/resource_preset/service.py
tests/manager/conftest.py
tests/manager/services/test_group.py
tests/manager/test_registry.py
tests/manager/test_scheduler.py

fix: Remove wrong unified config injection

---

src/ai/backend/manager/server.py

fix: ActionReporter not found crash

---

src/ai/backend/common/exception.py

fix(BA-1370): Use `orjson` in `BackendAIError`

---

changes/4413.feature.md
src/ai/backend/common/typed_validators.py

feat(BA-1374): Support relative path for `AutoDirectoryPath`

---

changes/4404.fix.md
src/ai/backend/common/bgtask/bgtask.py
src/ai/backend/common/events/bgtask.py
src/ai/backend/common/events/hub/propagators/bgtask.py
src/ai/backend/common/events/user_event/user_bgtask_event.py
src/ai/backend/manager/api/events.py
src/ai/backend/manager/event_dispatcher/dispatch.py
src/ai/backend/manager/event_dispatcher/propagator.py
src/ai/backend/manager/services/container_registry/service.py

resolves #4402 (BA-1366, BA-1371)

fix(BA-1366): Add missing `UserBgtaskEvent` implementation 

---

changes/4272.fix.md
src/ai/backend/common/bgtask/bgtask.py
src/ai/backend/common/events/bgtask.py
src/ai/backend/common/events/hub/hub.py
src/ai/backend/common/exception.py
src/ai/backend/manager/services/session/service.py

fix(BA-1231): `BgTaskFailedError` is not propagated to the client

---

src/ai/backend/manager/server.py

Backported-to: 25.6.5
Backported-of: #4406

fix: ActionReporter not found crash (#4406)

---

changes/4436.fix.md
src/ai/backend/common/events/__init__.py

fix(BA-1395): Add an import statement from .kernel and updates the all variable accordingly

---

changes/4314.fix.md
src/ai/backend/common/exception.py
src/ai/backend/common/types.py
src/ai/backend/manager/services/resource_preset/service.py

fix(BA-1276): Prevent invalid resource slot creation, and mutation

---

changes/4443.fix.md
src/ai/backend/manager/services/model_serving/services/model_serving.py

fix(BA-1398): Improve error handling for token generation in ModelServingService

---

changes/4438.feature.md
configs/grafana/dashboards/dashboard.json
configs/prometheus/prometheus.yaml
src/ai/backend/agent/config.py
src/ai/backend/agent/server.py
src/ai/backend/common/service_discovery/etcd_discovery/service_discovery.py
src/ai/backend/common/service_discovery/service_discovery.py
src/ai/backend/common/typed_validators.py
src/ai/backend/manager/api/context.py
src/ai/backend/manager/config/unified.py
src/ai/backend/manager/server.py
src/ai/backend/storage/config.py
src/ai/backend/storage/server.py
tests/common/service_discovery/test_etcd_discovery.py

resolves #4344, #4345 (BA-1305, BA-1306)

feat(BA-1305): Register service discovery and add http service discovery for prometheus

---

changes/4446.fix.md
src/ai/backend/manager/api/vfolder.py

This is an auto-generated backport PR of #4446 to the 25.6 release.

fix(BA-1369): Resolve admins vfolder leave issue (#4446)

---

changes/4448.fix.md
src/ai/backend/common/exception.py
src/ai/backend/manager/api/vfolder.py
src/ai/backend/manager/server.py
src/ai/backend/manager/services/vfolder/exceptions.py
src/ai/backend/manager/services/vfolder/services/invite.py

fix(BA-1399): Check unregistered email and update error code when vfolder invitation conflicts

---

changes/4453.fix.md
src/ai/backend/manager/config/bootstrap.py

fix(BA-1401): Add missing defaults to BootstrapConfig

---

changes/4457.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/kernel.py
src/ai/backend/agent/kernel.py
src/ai/backend/agent/kubernetes/kernel.py

fix(BA-1403): Resolve file-upload to session issue

---

changes/4457.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/kernel.py
src/ai/backend/agent/kernel.py
src/ai/backend/agent/kubernetes/kernel.py

This is an auto-generated backport PR of #4457 to the 25.6 release.

fix(BA-1403): Resolve file-upload to session issue (#4457)

---

changes/4463.fix.md
src/ai/backend/common/exception.py
src/ai/backend/manager/api/admin.py
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/utils.py

fix(BA-1002): Incorrect handling of disallowed permission in GQL middleware

---

changes/4459.fix.md
src/ai/backend/manager/models/gql_models/vfolder.py
src/ai/backend/manager/models/rbac/__init__.py
src/ai/backend/manager/models/vfolder.py

fix(BA-1404): Calculate correct permissions for admins

---

changes/4475.fix.md
configs/grafana/dashboards/dashboard.json
src/ai/backend/agent/server.py

fix(BA-1413): Fix wrong method name in rpc call metric

---

configs/storage-proxy/halfstack.toml

This is an auto-generated backport PR of #4473 to the 24.09 release.

chore: Changed the number of CPUs in the dev environment to one (#4473)

---

changes/4492.fix.md
src/ai/backend/common/service_discovery/etcd_discovery/service_discovery.py
src/ai/backend/common/service_discovery/service_discovery.py
tests/common/service_discovery/test_etcd_discovery.py

fix(BA-1430): heartbeat register service when service is dead

---

changes/4509.feature.md
src/ai/backend/common/BUILD
src/ai/backend/common/stage/BUILD
src/ai/backend/common/stage/types.py
tests/common/test_stage.py

feat(BA-1444): Add stage package to support deterministic step-by-step execution

---

changes/4538.misc.md
src/ai/backend/client/func/scaling_group.py

fix(BA-1456): Remove useless print in `ScalingGroup.list_available`

---

changes/4540.enhance.md
src/ai/backend/common/bgtask/bgtask.py
src/ai/backend/common/distributed.py
src/ai/backend/common/message_queue/hiredis_queue.py
src/ai/backend/common/message_queue/redis_queue.py
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/server.py

refactor(BA-1471): Improve logging for error handling in various modules

---

src/ai/backend/common/metrics/metric.py

fix: Correct typo in exception label for event failure metrics

---

changes/4537.misc.md
src/ai/backend/client/func/image.py

fix(BA-1442): Remove outdated Image SDK methods

---

changes/4550.fix.md
src/ai/backend/manager/actions/action.py
src/ai/backend/manager/actions/monitors/audit_log.py
src/ai/backend/manager/actions/monitors/prometheus.py
src/ai/backend/manager/actions/monitors/reporter.py
src/ai/backend/manager/actions/processor.py
tests/manager/actions/test_processor.py

fix(BA-1473): Fix missing entity id in processor

---

changes/4559.fix.md
src/ai/backend/common/message_queue/redis_queue.py
src/ai/backend/manager/server.py

fix(BA-1438): Skip processing messages with None data in RedisQueue

---

changes/4563.fix.md
src/ai/backend/common/bgtask/bgtask.py
tests/manager/api/test_bgtask.py

fix(BA-1475): Add missing message to `BgTaskFailedEvent`

---

changes/4573.fix.md
src/ai/backend/manager/models/image.py
tests/manager/services/image/actions/test_modify_image.py

fix(BA-1479): Incorrect resource label loading

---

changes/4581.fix.md
src/ai/backend/common/exception.py
src/ai/backend/manager/errors/exceptions.py
src/ai/backend/manager/models/session.py
src/ai/backend/manager/services/session/service.py

fix(BA-1495): Do null-check of kernel service-ports

---

changes/4599.fix.md
src/ai/backend/agent/agent.py

fix(BA-1501): Replace assert statements in `load_model_definition` with raising exception

---

changes/4609.feature.md
src/ai/backend/agent/config.py
src/ai/backend/agent/server.py
src/ai/backend/common/BUILD
src/ai/backend/common/service_discovery/redis_discovery/BUILD
src/ai/backend/common/service_discovery/redis_discovery/service_discovery.py
src/ai/backend/common/service_discovery/service_discovery.py
src/ai/backend/common/types.py
src/ai/backend/manager/config/unified.py
src/ai/backend/manager/server.py
src/ai/backend/storage/config.py
src/ai/backend/storage/server.py
tests/common/service_discovery/conftest.py
tests/common/service_discovery/test_etcd_discovery.py
tests/common/service_discovery/test_redis_discovery.py

feat(BA-1505): Add Redis-based Service Discovery

---

changes/4614.feature.md
src/ai/backend/test/cli/__main__.py
src/ai/backend/test/testcases/BUILD
src/ai/backend/test/testcases/template.py
src/ai/backend/test/testcases/testcases.py
src/ai/backend/test/tester/BUILD
src/ai/backend/test/tester/exporter.py
src/ai/backend/test/tester/runner.py
src/ai/backend/test/tester/tester.py

feat(BA-1508): Implement test specification management and execution framework

---

changes/4619.fix.md
src/ai/backend/manager/event_dispatcher/dispatch.py
src/ai/backend/manager/event_dispatcher/handlers/session.py

fix(BA-1518): Add event handler for SessionCheckingPrecondEvent

---

changes/4640.fix.md
src/ai/backend/manager/services/metric/container_metric.py

fix(BA-1536): Container utilization metric service config reload not working

---

changes/4627.fix.md
src/ai/backend/manager/container_registry/base.py

fix(BA-1522): Support more Accept headers in `BaseContainerRegistry.scan_tag`

---

changes/4663.fix.md
src/ai/backend/common/utils.py

fix(BA-1549): Prevent remount NFS path

---

src/ai/backend/manager/plugin/error_monitor.py

fix(BA-1566): Fix wrong import path of AgentErrorEvent

---

changes/4692.feature.md
src/ai/backend/test/contexts/auth.py
src/ai/backend/test/contexts/client_session.py
src/ai/backend/test/contexts/context.py
src/ai/backend/test/contexts/image.py
src/ai/backend/test/contexts/tester.py
src/ai/backend/test/testcases/spec_manager.py
src/ai/backend/test/tester/exporter.py
src/ai/backend/test/tester/tester.py

feat(BA-1568):Add parametrize functionality in tester spec

---

changes/4718.fix.md
src/ai/backend/manager/config/unified.py

fix(BA-1591): License config not included in PluginConfig

---

changes/4720.fix.md
src/ai/backend/client/func/image.py

fix(BA-1585): Broken `untag_image_from_registry` SDK method

---

src/ai/backend/test/contexts/session.py
src/ai/backend/test/data/session.py
src/ai/backend/test/templates/session/batch_session.py
src/ai/backend/test/templates/session/interactive_session.py
src/ai/backend/test/templates/session/session_template.py
src/ai/backend/test/testcases/session/container_log_retriever.py
src/ai/backend/test/testcases/session/execution.py
src/ai/backend/test/testcases/session/testspecs.py

feat(BA-1530): Add session container retriever test

---

changes/4710.feature.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/server.py
src/ai/backend/agent/types.py
src/ai/backend/common/dto/agent/response.py
src/ai/backend/common/types.py

This is a backport PR of https://github.com/lablup/backend.ai/pull/4710 to the 25.6 release.

feat(BA-1552): Add purge container RPC (#4710)

---

changes/4737.feature.md
src/ai/backend/agent/agent.py
src/ai/backend/common/defs.py

This is an auto-generated backport PR of #4737 to the 25.6 release.

feat(BA-1602): Add additional logging to kernel creation and termination (#4737)

---

src/ai/backend/test/testcases/session/testspecs.py

fix(BA-1605): Add cluster config param in container log test

---

changes/4740.fix.md
src/ai/backend/agent/kernel.py
src/ai/backend/common/asyncio.py

This is an auto-generated backport PR of #4740 to the 25.6 release.

fix(BA-1604): Close code runner properly (#4740)

---

changes/4754.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/kernel.py
src/ai/backend/agent/dummy/kernel.py
src/ai/backend/agent/kernel.py
src/ai/backend/agent/kubernetes/kernel.py
src/ai/backend/agent/server.py
src/ai/backend/common/dto/agent/response.py
src/ai/backend/kernel/base.py
src/ai/backend/manager/api/session.py
src/ai/backend/manager/registry.py
src/ai/backend/manager/services/session/actions/complete.py
src/ai/backend/manager/services/session/service.py

fix(BA-1452): Make kernel return code completion result

---

changes/4753.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/intrinsic.py
src/ai/backend/agent/kernel.py
src/ai/backend/agent/stats.py

fix(BA-1609): Skip gathering metric of non-existent process

---

changes/4795.fix.md
src/ai/backend/common/message_queue/redis_queue.py

fix(BA-1632): Cool down redis error log

---

src/ai/backend/common/message_queue/redis_queue.py

chore: leave redis queue comment

---

changes/4807.fix.md
src/ai/backend/manager/container_registry/harbor.py

fix(BA-1645): Wrong Accept Header on `HarborRegistryV2._process_oci_index`

---

changes/4831.fix.md
src/ai/backend/test/testcases/session/creation_failure_command_timeout.py
src/ai/backend/test/testcases/session/creation_failure_low_resources.py
src/ai/backend/test/testcases/session/creation_failure_schedule_timeout.py
src/ai/backend/test/testcases/session/creation_failure_too_many_container.py
src/ai/backend/test/testcases/session/creation_failure_wrong_command.py
src/ai/backend/test/testcases/session/session_status_history_retriever.py

fix(BA-1664): Name session test using `test_id` in failure cases

---

changes/4826.feature.md
src/ai/backend/manager/services/model_serving/services/model_serving.py
src/ai/backend/manager/services/model_serving/types.py

feat(BA-1656): Add `environ` to `service-definition.toml` schema

---

changes/4789.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/docker/intrinsic.py
src/ai/backend/agent/dummy/agent.py
src/ai/backend/agent/kubernetes/agent.py
src/ai/backend/agent/utils.py

This is an auto-generated backport PR of #4789 to the 25.6 release.

fix(BA-1627): Handle multiple IO device stat (#4789)

---

changes/4852.fix.md
src/ai/backend/manager/api/service.py

Backported-to: 24.09
Backported-of: 4852

fix(BA-1503): Prevent model service creation with project type vfolder (#4852)

---

changes/4884.feature.md
src/ai/backend/test/contexts/context.py
src/ai/backend/test/contexts/vfolder.py
src/ai/backend/test/data/vfolder.py
src/ai/backend/test/templates/vfolder/file_uploader.py
src/ai/backend/test/templates/vfolder/general_vfolder.py
src/ai/backend/test/templates/vfolder/utils.py
src/ai/backend/test/testcases/testspecs.py
src/ai/backend/test/testcases/vfolder/BUILD
src/ai/backend/test/testcases/vfolder/delete_files.py
src/ai/backend/test/testcases/vfolder/list_files.py
src/ai/backend/test/testcases/vfolder/move.py
src/ai/backend/test/testcases/vfolder/rename_file.py
src/ai/backend/test/testcases/vfolder/testspecs.py
src/ai/backend/test/tester/dependency.py

feat(BA-1693): Add VFolder file list, rename, move, deletion tests

---

changes/4875.fix.md
src/ai/backend/manager/models/endpoint.py
src/ai/backend/manager/services/model_serving/services/auto_scaling.py

fix(BA-1703): Prevent handling auto scaling rules for deleted model services

---

changes/4885.feature.md
configs/tester/tester.toml
src/ai/backend/test/testcases/vfolder/clone.py
src/ai/backend/test/testcases/vfolder/testspecs.py

feat(BA-1696): Add VFolder clone test

---

changes/4856.feature.md
src/ai/backend/client/func/vfolder.py

resolves #4855 (BA-1676)
This PR is created to resolve [comment](https://github.com/lablup/backend.ai/pull/4811/files/ec26b0b85041aaf0b75fc8d3f90f5cba21f84cdf#r2168152129) resolving #4676 (BA-1559)

feat(BA-1676): Implement `get_id` SDK function querying VFolder id with name 

---

changes/4895.fix.md
src/ai/backend/manager/event_dispatcher/dispatch.py

fix(BA-1719): Skip logging agent status heartbeat

---

changes/4906.fix.md
src/ai/backend/common/exception.py
src/ai/backend/manager/services/vfolder/exceptions.py
src/ai/backend/manager/services/vfolder/services/invite.py

resolves #4905 (BA-1727)
Since this is a relatively trivial issue, I will not backport it.

fix(BA-1727): Wrong error message when vfolder invitation row not found

---

changes/4912.feature.md
src/ai/backend/agent/agent.py

feat(BA-1723): Reduce dangling kernel log

---

changes/4934.fix.md
src/ai/backend/agent/stats.py

fix:(BA-1745) Handle invalid moving stat value

---

changes/4939.feature.md
src/ai/backend/web/server.py

feat(BA-1747): Add expire time to login history key

---

changes/4953.fix.md
src/ai/backend/test/templates/vfolder/file_uploader.py

fix(BA-1754): Broken `PlainTextFilesUploader` in macOS

---

src/ai/backend/agent/stats.py

chore: Better stat failure logging

---

changes/4957.fix.md
src/ai/backend/agent/kernel.py

feat(BA-1625): Use json.dumps to serialize yarl types correctly

---

changes/4962.fix.md
src/ai/backend/manager/models/rbac/__init__.py
src/ai/backend/manager/models/vfolder.py

This is a backport PR of https://github.com/lablup/backend.ai/pull/4459 to the 25.06 release.

fix(BA-1404): Calculate correct permissions for admins (#4459)

---

changes/4963.fix.md
src/ai/backend/manager/models/rbac/__init__.py
src/ai/backend/manager/models/vfolder.py

This is an auto-generated backport PR of https://github.com/lablup/backend.ai/pull/4459 to the 24.09 release.

fix(BA-1404): Calculate correct permissions for admins #4459

---

src/ai/backend/common/clients/valkey_client/valkey_stream/client.py

chore: Simplify logging in valkey_decorator by removing redundant arguments

---

changes/4954.fix.md
src/ai/backend/common/events/event_types/kernel/types.py
src/ai/backend/manager/models/alembic/versions/bf39b34717d4_remove_session_table_s_access_key_.py
src/ai/backend/manager/models/kernel.py
src/ai/backend/manager/models/keypair.py
src/ai/backend/manager/models/session.py
src/ai/backend/manager/models/user.py
src/ai/backend/manager/registry.py
src/ai/backend/manager/services/processors.py
src/ai/backend/manager/services/user/service.py
tests/manager/services/test_users.py

fix(BA-1644): PurgeUser not working when active compute session exist

---

changes/4987.feature.md
src/ai/backend/agent/agent.py
src/ai/backend/common/clients/valkey_client/client.py
src/ai/backend/common/clients/valkey_client/valkey_stream/client.py
src/ai/backend/common/message_queue/redis_queue.py
src/ai/backend/common/types.py
tests/common/conftest.py
tests/common/message_queue/test_redis_queue.py

feat(BA-1774): Implement ValkeySentinelClient with connection management and master monitoring

---

src/ai/backend/agent/agent.py

fix: Avoid using potential unbound service_port var

---

changes/4917.fix.md
src/ai/backend/manager/services/group/actions/purge_group.py
src/ai/backend/manager/services/group/service.py

This is an auto-generated backport PR of #4917 to the 25.6 release.

fix(BA-1720): Clean up endpoints when purge group (#4917)

---

changes/4975.feature.md
src/ai/backend/wsproxy/api/proxy.py
src/ai/backend/wsproxy/config.py
src/ai/backend/wsproxy/server.py

This is an auto-generated backport PR of #4975 to the 25.6 release.

feat(BA-1758): WSProxy expose advertise address (#4975)

---

src/ai/backend/manager/models/session.py

fix: Add missing `nullable` property to `SessionRow.user_uuid`

---

changes/4991.feature.md
src/ai/backend/logging/otel.py

feat(BA-1777): Add JSON log formatter for OTEL

---

changes/4777.feature.md
configs/tester/tester.toml
src/ai/backend/test/contexts/context.py
src/ai/backend/test/contexts/resource_policy.py
src/ai/backend/test/templates/model_service/endpoint.py
src/ai/backend/test/templates/model_service/utils.py
src/ai/backend/test/testcases/model_service/replicas_scale_successfully.py
src/ai/backend/test/testcases/model_service/scale_failure_too_many_sessions.py
src/ai/backend/test/testcases/model_service/testspecs.py
src/ai/backend/test/tester/dependency.py

feat(BA-1558): Add model service replica scale test

---

src/ai/backend/storage/server.py

fix: Update OpenTelemetry configuration

---

src/ai/backend/common/clients/valkey_client/valkey_stat/client.py

fix: incorrect msgpack import

---

changes/4991.feature.md
src/ai/backend/common/contexts/user_id.py
src/ai/backend/common/events/dispatcher.py
src/ai/backend/common/message_queue/types.py
src/ai/backend/common/middlewares/request_id.py
src/ai/backend/logging/utils.py
src/ai/backend/manager/api/auth.py

feat(BA-1778): Add metadata support to event handling and message payloads

---

src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/kubernetes/agent.py

fix: Agent local config type updates

---

changes/5114.feature.md
src/ai/backend/common/BUILD
src/ai/backend/common/clients/valkey_client/valkey_session/BUILD
src/ai/backend/common/clients/valkey_client/valkey_session/client.py
src/ai/backend/common/web/session/redis_storage.py
src/ai/backend/web/server.py

feat(BA-1853): Implement ValkeySessionClient for session management using Valkey-Glide

---

changes/5112.fix.md
src/ai/backend/agent/kernel.py

fix(BA-1839): Finish Agent execution task event correctly

---

src/ai/backend/common/clients/valkey_client/valkey_stat/client.py

fix: Remove unnecessary str() conversion for cursor in hscan and scan

---

changes/5137.fix.md
src/ai/backend/common/events.py

fix: Handle empty consumer handlers in EventDispatcher to avoid retry

---

changes/5107.enhance.md
src/ai/backend/manager/errors/exceptions.py
src/ai/backend/manager/repositories/group/admin_repository.py
src/ai/backend/manager/repositories/group/repositories.py
src/ai/backend/manager/repositories/group/repository.py
src/ai/backend/manager/repositories/image/repositories.py
src/ai/backend/manager/server.py
src/ai/backend/manager/services/group/service.py
src/ai/backend/manager/services/processors.py
tests/manager/services/test_group.py

feat(BA-1851): Separate repository layer from group service

---

changes/5076.enhance.md
src/ai/backend/manager/repositories/user/admin_repository.py
src/ai/backend/manager/repositories/user/repository.py
src/ai/backend/manager/services/processors.py
src/ai/backend/manager/services/user/service.py
tests/manager/services/test_users.py

feat(BA-1832): Separate repository layer from user service

---

changes/5128.enhance.md
src/ai/backend/manager/repositories/agent/repository.py
src/ai/backend/manager/services/agent/actions/sync_agent_registry.py
src/ai/backend/manager/services/agent/service.py
src/ai/backend/manager/services/agent/types.py
src/ai/backend/manager/services/processors.py

feat(BA-1859): Separate repository layer from agent service

---

changes/5072.enhance.md
src/ai/backend/manager/data/model_serving/BUILD
src/ai/backend/manager/data/model_serving/types.py
src/ai/backend/manager/errors/exceptions.py
src/ai/backend/manager/repositories/model_serving/admin_repository.py
src/ai/backend/manager/repositories/model_serving/repository.py
src/ai/backend/manager/services/model_serving/services/auto_scaling.py
src/ai/backend/manager/services/model_serving/services/model_serving.py
src/ai/backend/manager/services/processors.py

feat(BA-1830): Separate repository layer from model serving service

---

changes/5101.enhance.md
src/ai/backend/manager/repositories/schedule/repository.py
src/ai/backend/manager/scheduler/dispatcher.py
src/ai/backend/manager/server.py
tests/manager/test_scheduler.py

feat(BA-1847): Separate repository layer from scheduler

---

src/ai/backend/manager/models/vfolder.py

fix: Update status of already-gone vfolders

---

src/ai/backend/manager/server.py

fix: Init root_ctx.repository when start mgr

---

changes/5157.enhance.md
src/ai/backend/manager/clients/BUILD
src/ai/backend/manager/clients/agent/BUILD
src/ai/backend/manager/clients/agent/client.py
src/ai/backend/manager/registry.py
src/ai/backend/manager/scheduler/types.py

feat(BA-1876): Separate agent client layer

---

changes/5165.enhance.md
src/ai/backend/manager/clients/wsproxy/BUILD
src/ai/backend/manager/clients/wsproxy/client.py
src/ai/backend/manager/registry.py

feat(BA-1875): Separate wsproxy client

---

changes/5170.fix.md
src/ai/backend/web/config/unified.py
src/ai/backend/web/server.py

fix(BA-1884): Webserver 404 not found issue

---

src/ai/backend/manager/repositories/schedule/repository.py
src/ai/backend/manager/scheduler/dispatcher.py

fix: Correct SQL query in repository

---

src/ai/backend/manager/repositories/vfolder/repository.py
src/ai/backend/manager/services/vfolder/services/file.py
src/ai/backend/manager/services/vfolder/services/invite.py
src/ai/backend/manager/services/vfolder/services/vfolder.py

fix: vfolder logic

---

.github/workflows/pr-prefix.yml
changes/5197.test.md
pyproject.toml
src/ai/backend/common/exception.py
src/ai/backend/manager/data/user/BUILD
src/ai/backend/manager/data/user/types.py
src/ai/backend/manager/errors/user.py
src/ai/backend/manager/models/gql_models/user.py
src/ai/backend/manager/repositories/user/admin_repository.py
src/ai/backend/manager/repositories/user/repository.py
src/ai/backend/manager/services/user/README.md
src/ai/backend/manager/services/user/actions/create_user.py
src/ai/backend/manager/services/user/actions/modify_user.py
src/ai/backend/manager/services/user/actions/purge_user.py
src/ai/backend/manager/services/user/service.py
src/ai/backend/manager/services/user/types.py
tests/manager/integrations/services/user/BUILD
tests/manager/integrations/services/user/conftest.py
tests/manager/integrations/services/user/test_user_integration.py
tests/manager/repositories/user/BUILD
tests/manager/repositories/user/test_user_repository.py
tests/manager/services/test_users.py
tests/manager/services/user/BUILD
tests/manager/services/user/test_user.py

test(BA-1888): Add test code for user service

---

changes/5207.feature.md
docs/manager/graphql-reference/schema.graphql
src/ai/backend/manager/models/gql_models/image.py

resolves #5205 (BA-1913)
----
📚 Documentation preview 📚: https://sorna--5207.org.readthedocs.build/en/5207/
----
📚 Documentation preview 📚: https://sorna-ko--5207.org.readthedocs.build/ko/5207/

feat(BA-1913): Add `type` field to `ImageNode`

---

src/ai/backend/manager/services/user/actions/user_month_stats.py
src/ai/backend/manager/services/user/service.py
tests/manager/integrations/services/user/test_user_integration.py

fix: Remove UUID type cast

---

changes/5198.test.md
src/ai/backend/manager/services/user_resource_policy/README.md
tests/manager/integration/services/user_resource_policy/BUILD
tests/manager/integration/services/user_resource_policy/test_user_resource_policy.py
tests/manager/repositories/user_resource_policy/BUILD
tests/manager/repositories/user_resource_policy/test_user_resource_policy_repository.py
tests/manager/services/user_resource_policy/BUILD
tests/manager/services/user_resource_policy/test_user_resource_policy.py

test(BA-1889): Add test code for user resource policy service

---

src/ai/backend/manager/repositories/schedule/repository.py
src/ai/backend/manager/scheduler/dispatcher.py

fix: Correct scheduler repository of multinode session creation

---

changes/5223.feature.md
configs/webserver/sample.toml
src/ai/backend/client/session.py
src/ai/backend/common/BUILD
src/ai/backend/common/clients/http_client/BUILD
src/ai/backend/common/clients/http_client/client_pool.py
src/ai/backend/web/auth.py
src/ai/backend/web/config/unified.py
src/ai/backend/web/server.py
tests/webserver/test_auth.py

feat(BA-1415): Apply client pool in web component

---

src/ai/backend/manager/registry.py

chore: Update dependencies and clean up imports

---

src/ai/backend/manager/registry.py

fix: Incorrect handling when `mount_map`, `mount_id_map` is None

---

src/ai/backend/manager/clients/wsproxy/client.py

feat: Add client decorator to wsproxy client

---

changes/5253.feature.md
src/ai/backend/manager/clients/wsproxy/client.py
src/ai/backend/manager/registry.py

feat(BA-1942): Apply client pool to wsproxy client

---

changes/5255.feature.md
src/ai/backend/common/clients/valkey_client/client.py
src/ai/backend/common/metrics/metric.py
src/ai/backend/manager/decorators/client_decorator.py
src/ai/backend/manager/decorators/repository_decorator.py

feat(BA-1943): Add retry metrics for layer observer

---

changes/5258.test.md
src/ai/backend/manager/repositories/container_registry/repository.py
tests/manager/integration/services/container_registry/BUILD
tests/manager/integration/services/container_registry/test_container_registry_integration.py
tests/manager/repositories/container_registry/BUILD
tests/manager/repositories/container_registry/test_admin_container_registry_repository.py
tests/manager/repositories/container_registry/test_container_registry_repository.py
tests/manager/services/container_registry/service/BUILD
tests/manager/services/container_registry/service/test_clear_images_service.py
tests/manager/services/container_registry/service/test_get_container_registries_service.py
tests/manager/services/container_registry/service/test_load_all_container_registries_service.py
tests/manager/services/container_registry/service/test_load_container_registries_service.py
tests/manager/services/container_registry/service/test_rescan_images_service.py

test(BA-1900): Add tests for `Container Registry`

---

changes/4766.feature.md
changes/4767.enhance.md
src/ai/backend/manager/event_dispatcher/handlers/agent.py
src/ai/backend/manager/models/agent.py
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/gql_models/session.py
src/ai/backend/manager/models/group.py
src/ai/backend/manager/models/kernel.py
src/ai/backend/manager/models/scaling_group.py
src/ai/backend/manager/models/session.py
src/ai/backend/manager/models/types.py
src/ai/backend/manager/models/user.py
src/ai/backend/manager/repositories/user/admin_repository.py

refactor(BA-1616): Apply simple model query patterns

---

changes/5271.fix.md
src/ai/backend/common/events/dispatcher.py
src/ai/backend/common/message_queue/types.py

fix(BA-1962): Fixed a problem with deserializing dataclass

---

changes/5276.feature.md
pants.toml
src/ai/backend/common/clients/valkey_client/client.py
src/ai/backend/manager/services/permission_contoller/actions/list_access.py

feat(BA-1970): Implement reconnection logic in ValkeySentinelClient

---

changes/5272.fix.md
src/ai/backend/manager/clients/storage_proxy/manager_facing_client.py
src/ai/backend/manager/repositories/vfolder/repository.py
src/ai/backend/manager/services/vfolder/actions/base.py
src/ai/backend/manager/services/vfolder/services/vfolder.py

fix(BA-1963): Broken VFolder `GetTaskLogs` service

---

changes/5151.fix.md
src/ai/backend/account_manager/models/alembic/env.py
src/ai/backend/appproxy/coordinator/models/alembic/env.py
src/ai/backend/manager/models/alembic/env.py

fix(BA-1872): Correct the asyncio connection sharing pattern in alembic env.py

---

changes/5298.feature.md
src/ai/backend/common/clients/valkey_client/client.py

feat(BA-1996): Implement connection monitoring and reconnection logic in ValkeyStandaloneClient

---

.github/workflows/backport.yml

fix: Remove kv store logic in backport

---

src/ai/backend/common/dto/manager/response.py
src/ai/backend/manager/api/admin.py

fix(BA-2010): Add missing `extensions` field to `GraphQLResponse` of GQL API V2

---

changes/5342.fix.md
src/ai/backend/manager/scheduler/dispatcher.py

This is an auto-generated backport PR of #5342 to the 25.6 release.

fix(BA-2015): Reduce scheduler plugin loader overheads (#5342)

---

changes/5345.fix.md
configs/prometheus/prometheus-ha.yaml
docker-compose.halfstack-ha.yml
scripts/install-dev.sh

fix(BA-2022): Add missing components in HA development environment

---

src/ai/backend/common/clients/valkey_client/client.py

chore: Change log level from warning to debug for Redis ping failures in Valkey clients

---

src/ai/backend/plugin/entrypoint.py
tests/plugin/test_entrypoint_glob.py

fix: Missing suffix-match transition in #5377

---

.github/workflows/import-all-smi.yml
changes/5381.feature.md
src/ai/backend/agent/agent.py
src/ai/backend/runner/all-smi.aarch64.bin
src/ai/backend/runner/all-smi.x86_64.bin

feat(BA-1806): Ship all-smi with Backend.AI Core

---

changes/5394.fix.md
src/ai/backend/agent/docker/agent.py
src/ai/backend/manager/container_registry/base.py
src/ai/backend/manager/container_registry/harbor.py

fix(BA-2043): Image rescan exception handling where the image config is `None`

---

src/ai/backend/common/configs/redis.py

fix: Update alias for override-configs in RedisConfig to support validation and serialization

---

changes/5409.misc.md
src/ai/backend/manager/repositories/agent/repositories.py
src/ai/backend/manager/repositories/auth/repositories.py
src/ai/backend/manager/repositories/container_registry/repositories.py
src/ai/backend/manager/repositories/domain/repositories.py
src/ai/backend/manager/repositories/group/repositories.py
src/ai/backend/manager/repositories/image/repositories.py
src/ai/backend/manager/repositories/keypair_resource_policy/repositories.py
src/ai/backend/manager/repositories/metric/README.md
src/ai/backend/manager/repositories/metric/repositories.py
src/ai/backend/manager/repositories/model_serving/repositories.py
src/ai/backend/manager/repositories/project_resource_policy/repositories.py
src/ai/backend/manager/repositories/repositories.py
src/ai/backend/manager/repositories/resource_preset/repositories.py
src/ai/backend/manager/repositories/schedule/repositories.py
src/ai/backend/manager/repositories/session/repositories.py
src/ai/backend/manager/repositories/types.py
src/ai/backend/manager/repositories/user/repositories.py
src/ai/backend/manager/repositories/user_resource_policy/repositories.py
src/ai/backend/manager/repositories/vfolder/repositories.py
src/ai/backend/manager/server.py

refactor: weird RepositoryArg imports

---

docker-compose.halfstack-main.yml

fix(BA-2051): Fix wrong container volume mount for apollo router

---

changes/5403.feature.md
docs/manager/graphql-reference/schema.graphql
src/ai/backend/common/exception.py
src/ai/backend/manager/data/session/types.py
src/ai/backend/manager/models/gql_models/session.py
src/ai/backend/manager/models/gql_models/user.py
src/ai/backend/manager/models/session.py
src/ai/backend/manager/repositories/session/repository.py
src/ai/backend/manager/services/session/service.py
tests/manager/services/session/fixtures.py

resolves #5400 (BA-2055)
----
📚 Documentation preview 📚: https://sorna--5403.org.readthedocs.build/en/5403/
----
📚 Documentation preview 📚: https://sorna-ko--5403.org.readthedocs.build/ko/5403/

feat(BA-2055): Add `UserNode` as a field of `ComputeSessionNode`

---

changes/5435.fix.md
src/ai/backend/manager/models/gql_models/image.py

fix(BA-2078): Fix wrong image type search logic used in `ImageNode` instance creation

---

changes/5449.fix.md
src/ai/backend/web/proxy.py

fix(BA-2097): Wrong request header validation error handling of Webserver

---

changes/5448.fix.md
src/ai/backend/appproxy/coordinator/api/endpoint.py
src/ai/backend/appproxy/coordinator/models/circuit.py

fix(BA-2083): Change `Circuit` query logic in AppProxy for `Circuit`'s serializability

---

changes/5446.fix.md
src/ai/backend/manager/errors/user.py
src/ai/backend/manager/models/gql_models/user.py
src/ai/backend/manager/repositories/user/repository.py
src/ai/backend/manager/services/user/actions/create_user.py
src/ai/backend/manager/services/user/actions/delete_user.py
src/ai/backend/manager/services/user/actions/modify_user.py
src/ai/backend/manager/services/user/actions/purge_user.py
src/ai/backend/manager/services/user/service.py
tests/manager/integration/services/user/test_user_integration.py
tests/manager/repositories/user/test_user_repository.py
tests/manager/services/test_users.py
tests/manager/services/user/test_user.py

fix(BA-2093): Wrong error handling of `User` CRUD mutations

---

src/ai/backend/manager/server.py
src/ai/backend/manager/sokovan/scheduler/coordinator.py
src/ai/backend/manager/sokovan/scheduler/handlers.py
src/ai/backend/manager/sokovan/sokovan.py

feat(BA-2081): Implement temporal schedulers by injecting `scheduler_dispatcher`

---

.github/workflows/ci.yml

feat: Add build-isla-sorna-image workflow

---

changes/5469.fix.md
src/ai/backend/agent/agent.py

fix(BA-2108): Avoid producing error event in Agent heartbeat

---

src/ai/backend/manager/sokovan/scheduler/scheduler.py

fix: Handle kernel termination for sessions without agent or container ID

---

changes/5489.fix.md
src/ai/backend/agent/docker/agent.py
src/ai/backend/agent/utils.py

This is an auto-generated backport PR of #5489 to the 24.09 release.

fix(BA-2115): Respect inherited ulimits when creating new containers (#5489)

---

src/ai/backend/account_manager/api/utils.py
src/ai/backend/account_manager/models/base.py
src/ai/backend/account_manager/models/utils.py
src/ai/backend/agent/config/unified.py
src/ai/backend/appproxy/worker/metrics.py
src/ai/backend/common/events/event_types/bgtask/broadcast.py
src/ai/backend/manager/config/unified.py
src/ai/backend/manager/models/container_registry.py
src/ai/backend/manager/models/gql_models/container_registry_v2.py
src/ai/backend/manager/models/network.py
src/ai/backend/manager/public_api/health.py
src/ai/backend/storage/config/unified.py
src/ai/backend/web/config/unified.py

A simple refactor to silence extraneous warnings

refactor: Replace deprecated pydantic config class pattern

---

changes/5521.fix.md
src/ai/backend/agent/affinity_map.py
src/ai/backend/agent/alloc_map.py
tests/agent/test_affinity_map.py

This is an auto-generated backport PR of #5521 to the 25.6 release.

refactor: Document affinity-aware allocation logic and improve error messages (#5521)

---

changes/5579.feature.md
src/ai/backend/manager/repositories/scheduler/db_source/db_source.py
src/ai/backend/manager/repositories/scheduler/repository.py
src/ai/backend/manager/sokovan/scheduler/hooks/BUILD
src/ai/backend/manager/sokovan/scheduler/hooks/__init__.py
src/ai/backend/manager/sokovan/scheduler/hooks/base.py
src/ai/backend/manager/sokovan/scheduler/hooks/batch.py
src/ai/backend/manager/sokovan/scheduler/hooks/inference.py
src/ai/backend/manager/sokovan/scheduler/hooks/interactive.py
src/ai/backend/manager/sokovan/scheduler/hooks/registry.py
src/ai/backend/manager/sokovan/scheduler/hooks/system.py
src/ai/backend/manager/sokovan/scheduler/scheduler.py
src/ai/backend/manager/sokovan/scheduler/types.py

feat(BA-2159): Implement session transition hooks for various session types

---

src/ai/backend/manager/sokovan/scheduling_controller/preparers/cluster.py
src/ai/backend/manager/sokovan/scheduling_controller/scheduling_controller.py
src/ai/backend/manager/sokovan/scheduling_controller/validators/__init__.py
src/ai/backend/manager/sokovan/scheduling_controller/validators/cluster.py
src/ai/backend/manager/sokovan/scheduling_controller/validators/rules.py

fix: Enhance cluster configuration validation and preparation for multi-container sessions

---

changes/5589.feature.md
src/ai/backend/common/events/event_types/session/broadcast.py
src/ai/backend/common/events/types.py
src/ai/backend/common/types.py
src/ai/backend/manager/event_dispatcher/dispatch.py
src/ai/backend/manager/event_dispatcher/handlers/propagator.py
src/ai/backend/manager/event_dispatcher/handlers/schedule.py
src/ai/backend/manager/registry.py
src/ai/backend/manager/repositories/schedule/repository.py
src/ai/backend/manager/repositories/scheduler/db_source/db_source.py
src/ai/backend/manager/repositories/scheduler/repository.py
src/ai/backend/manager/repositories/scheduler/types/session.py
src/ai/backend/manager/server.py
src/ai/backend/manager/sokovan/scheduler/allocators/allocator.py
src/ai/backend/manager/sokovan/scheduler/allocators/repository_allocator.py
src/ai/backend/manager/sokovan/scheduler/coordinator.py
src/ai/backend/manager/sokovan/scheduler/factory.py
src/ai/backend/manager/sokovan/scheduler/handlers.py
src/ai/backend/manager/sokovan/scheduler/results.py
src/ai/backend/manager/sokovan/scheduler/scheduler.py
src/ai/backend/manager/sokovan/scheduler/types.py
src/ai/backend/manager/sokovan/sokovan.py
tests/manager/conftest.py
tests/manager/repositories/schedule/test_termination.py
tests/manager/sokovan/scheduler/test_coordinator.py
tests/manager/sokovan/scheduler/test_terminate_sessions.py

feat(BA-2151): Implement batch scheduling events and event propagation through Event Hub

---

changes/5592.feature.md
src/ai/backend/manager/defs.py
src/ai/backend/manager/sokovan/scheduler/coordinator.py
src/ai/backend/manager/sokovan/scheduler/handlers.py
src/ai/backend/manager/sokovan/scheduler/scheduler.py
src/ai/backend/manager/sokovan/sokovan.py
tests/manager/sokovan/scheduler/test_coordinator.py

feat(BA-2166): Apply centralized distributed locking for Sokovan scheduling operations

---

changes/5594.feature.md
src/ai/backend/common/clients/valkey_client/valkey_stat/client.py
src/ai/backend/manager/api/admin.py
src/ai/backend/manager/models/gql.py
src/ai/backend/manager/models/gql_models/keypair.py
src/ai/backend/manager/repositories/scheduler/cache_source/cache_source.py
src/ai/backend/manager/repositories/scheduler/db_source/db_source.py
src/ai/backend/manager/repositories/scheduler/db_source/types.py
src/ai/backend/manager/repositories/scheduler/repository.py
src/ai/backend/manager/repositories/scheduler/types/session.py
src/ai/backend/manager/sokovan/scheduler/coordinator.py
src/ai/backend/manager/sokovan/scheduler/handlers.py
src/ai/backend/manager/sokovan/scheduler/results.py
src/ai/backend/manager/sokovan/scheduler/scheduler.py
src/ai/backend/manager/sokovan/scheduler/types.py
tests/manager/models/gql_models/test_agent.py
tests/manager/models/gql_models/test_container_registries.py
tests/manager/models/gql_models/test_container_registry_nodes.py
tests/manager/models/gql_models/test_container_registry_nodes_v2.py
tests/manager/models/gql_models/test_group.py
tests/manager/models/test_container_registries.py
tests/manager/models/test_vfolder.py

feat(BA-2168): Implement cache-through pattern for keypair concurrency management in SchedulerRepository

---

src/ai/backend/common/clients/valkey_client/client.py
src/ai/backend/manager/metrics/scheduler.py
src/ai/backend/manager/repositories/scheduler/repository.py
src/ai/backend/manager/sokovan/scheduler/coordinator.py
src/ai/backend/manager/sokovan/scheduler/handlers.py
src/ai/backend/manager/sokovan/scheduler/results.py
tests/manager/sokovan/scheduler/test_coordinator.py

chore: enhance minor issues

---

changes/5519.feature.md
changes/5531.feature.md
changes/5555.feature.md
src/ai/backend/agent/agent.py
src/ai/backend/common/bgtask/bgtask.py
src/ai/backend/common/bgtask/reporter.py
src/ai/backend/common/bgtask/task/base.py
src/ai/backend/common/bgtask/types.py
src/ai/backend/common/clients/valkey_client/valkey_bgtask/client.py
src/ai/backend/common/data/bgtask/defs.py
src/ai/backend/common/defs.py
src/ai/backend/common/exception.py
src/ai/backend/common/metrics/metric.py
src/ai/backend/manager/api/context.py
src/ai/backend/manager/server.py
src/ai/backend/storage/context.py
src/ai/backend/storage/migration.py
src/ai/backend/storage/server.py

feat(BA-2131): Add Bgtask valkey client

---

changes/5600.feature.md
src/ai/backend/manager/repositories/deployment/db_source/db_source.py
src/ai/backend/manager/repositories/scheduler/db_source/db_source.py
tests/manager/repositories/scheduler/BUILD
tests/manager/repositories/scheduler/test_db_source_isolation.py

feat(BA-2169): Apply READ COMMITTED isolation level for scheduler operations

---

src/ai/backend/common/bgtask/bgtask.py

fix: Delete task after background task finish

---

changes/5611.feature.md
src/ai/backend/common/dto/storage/response.py
src/ai/backend/storage/api/manager.py
src/ai/backend/storage/bgtask/tasks/clone.py

feat(BA-1816): Apply retry to clone bgtask

---

src/ai/backend/manager/network/overlay.py
src/ai/backend/manager/server.py
src/ai/backend/manager/sokovan/scheduler/factory.py
src/ai/backend/manager/sokovan/scheduler/scheduler.py
src/ai/backend/manager/sokovan/scheduling_controller/calculators/resource_calculator.py
src/ai/backend/manager/sokovan/scheduling_controller/preparers/preparer.py
src/ai/backend/manager/sokovan/scheduling_controller/scheduling_controller.py
tests/manager/sokovan/scheduler/test_scheduler.py
tests/manager/sokovan/scheduler/test_terminate_sessions.py
tests/manager/sokovan/scheduling_controller/test_integration.py

fix: Caculate resource spec when scheduling multi-kernel session

---

changes/5623.feature.md
src/ai/backend/manager/sokovan/scheduling_controller/scheduling_controller.py

feat(BA-2183): Add operation metrics observer for session termination tracking

---

CLAUDE.md

- Reflect our coding standard with more details
- Remove "Verifying Code Changes" section to avoid confusion with the subagents

chore: Update CLAUDE.md with more concrete guides

---

src/ai/backend/manager/models/alembic/versions/29bbf3830309_relocate_artifact_readonly.py

chore: Rename migration script

---

.github/workflows/update-api-schema.yml
changes/5645.feature.md
src/ai/backend/manager/cli/api.py

feat(BA-2171): Add automated supergraph generation in CI workflow

---

changes/5649.fix.md
src/ai/backend/common/types.py

fix(BA-2197): Invalid address type of Valkey client

---

src/ai/backend/common/bgtask/bgtask.py
src/ai/backend/common/bgtask/exception.py
src/ai/backend/common/bgtask/types.py
src/ai/backend/common/clients/valkey_client/valkey_bgtask/client.py

fix(BA-2190): Bgtask valkey script error

---

.github/workflows/update-api-schema.yml

fix: Set PATH for rover CLI in GitHub Actions workflow

---

changes/5659.feature.md
src/ai/backend/manager/registry.py

feat(BA-2208): Implement session wait logic in AgentRegistry for improved scheduling handling

---

src/ai/backend/manager/models/alembic/versions/29bbf3830309_relocate_artifact_readonly.py

fix: Wrong migration script

---

changes/5682.fix.md
src/ai/backend/manager/models/gql.py

fix: Order of pending queue

---

changes/5683.fix.md
src/ai/backend/agent/server.py

fix: Ensure redis address is nullable

---

changes/5707.fix.md
src/ai/backend/appproxy/coordinator/api/endpoint.py
src/ai/backend/manager/sokovan/deployment/route/handlers/running.py

fix: Enhance endpoint creation logic to update existing records and handle circuits

---

changes/5721.fix.md
src/ai/backend/manager/repositories/scheduler/db_source/db_source.py
src/ai/backend/manager/repositories/scheduler/repository.py
src/ai/backend/manager/sokovan/scheduler/hooks/base.py
src/ai/backend/manager/sokovan/scheduler/hooks/batch.py
src/ai/backend/manager/sokovan/scheduler/hooks/inference.py
src/ai/backend/manager/sokovan/scheduler/hooks/interactive.py
src/ai/backend/manager/sokovan/scheduler/hooks/registry.py
src/ai/backend/manager/sokovan/scheduler/hooks/system.py
src/ai/backend/manager/sokovan/scheduler/scheduler.py
src/ai/backend/manager/sokovan/scheduler/types.py

fix(BA-2244): Add missing network cleanup

---

src/ai/backend/common/msgpack.py
src/ai/backend/manager/sokovan/scheduling_controller/calculators/resource_calculator.py

fix: Serialize custom path type for msgpack

---

changes/5730.fix.md
src/ai/backend/manager/repositories/scheduler/db_source/db_source.py
src/ai/backend/manager/repositories/scheduler/types/session_creation.py
src/ai/backend/manager/sokovan/scheduling_controller/calculators/resource_calculator.py
src/ai/backend/manager/sokovan/scheduling_controller/preparers/preparer.py
src/ai/backend/manager/sokovan/scheduling_controller/resolvers/scaling_group_resolver.py
src/ai/backend/manager/sokovan/scheduling_controller/scheduling_controller.py
tests/manager/sokovan/scheduling_controller/test_integration.py
tests/manager/sokovan/scheduling_controller/validators/test_rules.py

fix: Add missing scheduler options to AllowedScalingGroup and update related components

---

src/ai/backend/manager/services/artifact_revision/service.py

fix: Wrong artifact cleanup request

---

changes/5770.fix.md
src/ai/backend/manager/sokovan/scheduler/coordinator.py
src/ai/backend/manager/sokovan/scheduler/hooks/base.py
src/ai/backend/manager/sokovan/scheduler/scheduler.py
tests/manager/sokovan/scheduler/test_terminate_sessions.py

fix(BA-2281): Clean up dangling docker networks

---

changes/5774.feature.md
src/ai/backend/client/request.py
src/ai/backend/client/session.py
src/ai/backend/web/proxy.py

feat(BA-2284): Add session mode based error handling in FetchContextManager

---

changes/5739.feature.md
docs/manager/graphql-reference/supergraph.graphql
docs/manager/graphql-reference/v2-schema.graphql
src/ai/backend/manager/api/admin.py
src/ai/backend/manager/api/gql/artifact_registry.py
src/ai/backend/manager/api/gql/schema.py
src/ai/backend/manager/api/gql/types.py
src/ai/backend/manager/services/artifact_registry/actions/common/get_meta.py
src/ai/backend/manager/services/artifact_registry/service.py

resolves #5742 (BA-2260)
----
📚 Documentation preview 📚: https://sorna--5739.org.readthedocs.build/en/5739/
----
📚 Documentation preview 📚: https://sorna-ko--5739.org.readthedocs.build/ko/5739/

feat(BA-2260): Add `defaultArtifactRegistry` GQL resolver

---

changes/5865.fix.md
src/ai/backend/common/clients/valkey_client/valkey_schedule/client.py

fix(BA-2364): Set empty pending queue value

---

changes/5830.feature.md
configs/manager/halfstack.toml
src/ai/backend/common/events/event_types/artifact/anycast.py
src/ai/backend/manager/config/unified.py
src/ai/backend/manager/event_dispatcher/dispatch.py
src/ai/backend/manager/event_dispatcher/handlers/artifact.py
src/ai/backend/manager/server.py
src/ai/backend/storage/services/artifacts/huggingface.py
src/ai/backend/storage/services/artifacts/reservoir.py
tests/storage-proxy/artifacts/test_service.py

feat(BA-2324): Add config for disable artifact approve process

---

src/ai/backend/manager/data/permission/object_permission.py
src/ai/backend/manager/models/rbac_models/permission/object_permission.py
src/ai/backend/manager/repositories/permission_controller/role_manager.py

refactor: Better ORM usage in object permission creation

---

src/ai/backend/manager/repositories/resource_preset/db_source/db_source.py

fix: Apply from_known_slots method for empty slots

---

changes/5878.fix.md
docs/manager/rest-reference/openapi.json
src/ai/backend/manager/models/gql_models/image.py

This is an auto-generated backport PR of #5878 to the 25.6 release.
----
📚 Documentation preview 📚: https://sorna--5879.org.readthedocs.build/en/5879/
----
📚 Documentation preview 📚: https://sorna-ko--5879.org.readthedocs.build/ko/5879/

fix(BA-2358): Handle empty `supported_accelerators` list correctly in `Image`, `ImageNode` (#5878)

---

changes/5870.feature.md
docs/manager/graphql-reference/supergraph.graphql
docs/manager/graphql-reference/v2-schema.graphql
src/ai/backend/common/dto/storage/context.py
src/ai/backend/common/dto/storage/request.py
src/ai/backend/manager/api/gql/object_storage.py
src/ai/backend/manager/api/object_storage.py
src/ai/backend/manager/services/artifact/processors.py
src/ai/backend/manager/services/object_storage/actions/get_upload_presigned_url.py
src/ai/backend/manager/services/object_storage/service.py
src/ai/backend/storage/api/v1/storages/object_storage.py
src/ai/backend/storage/client/s3.py
src/ai/backend/storage/config/unified.py
src/ai/backend/storage/services/artifacts/huggingface.py
src/ai/backend/storage/services/storages/object_storage.py
tests/storage-proxy/storages/test_s3_client.py
tests/storage-proxy/storages/test_service.py

resolves #NNN (BA-2312)
----
📚 Documentation preview 📚: https://sorna--5870.org.readthedocs.build/en/5870/
----
📚 Documentation preview 📚: https://sorna-ko--5870.org.readthedocs.build/ko/5870/

feat(BA-2312): Add artifact presigned download, upload configs in the `storage-proxy.toml`

---

changes/5894.fix.md
src/ai/backend/manager/repositories/resource_preset/db_source/db_source.py

fix: Add missing scaling group filtering in AgentRow query

---

changes/5896.fix.md
src/ai/backend/manager/data/resource_preset/types.py
src/ai/backend/manager/repositories/resource_preset/db_source/types.py

fix: Resource preset shmem unit

---

changes/5899.fix.md
src/ai/backend/manager/repositories/resource_preset/db_source/types.py

fix: Serialize resource preset cache key

---

changes/5901.fix.md
src/ai/backend/manager/sokovan/scheduler/validators/pending_session_resource_limit.py
tests/manager/sokovan/scheduler/validators/test_pending_session_resource_limit.py

fix: Modify pending session resource limit validation logic

---

changes/5905.fix.md
src/ai/backend/manager/repositories/model_serving/repository.py

fix: Endpoint mutation by loading image of service endpoint

---

src/ai/backend/manager/services/container_registry/service.py

fix(BA-2390): Add missing progress reporter when rescanning images

---

.github/workflows/ci.yml

This is an auto-generated backport PR of #5466 to the 24.09 release.

feat: Add build-isla-sorna-image workflow (#5466)

---

docs/manager/rest-reference/openapi.json
src/ai/backend/manager/api/scaling_group.py

fix(BA-2386): Fix wrong error module import in scaling group api

---

changes/5893.fix.md
src/ai/backend/manager/repositories/permission_controller/role_manager.py

fix: Change object permission bulk insert to use ORM functions

---

changes/5958.feature.md
src/ai/backend/manager/sokovan/deployment/definition_generator/cmd.py
src/ai/backend/manager/sokovan/deployment/definition_generator/huggingface_tgi.py
src/ai/backend/manager/sokovan/deployment/definition_generator/nim.py
src/ai/backend/manager/sokovan/deployment/definition_generator/registry.py
src/ai/backend/manager/sokovan/deployment/definition_generator/vllm.py

resolves #5935, #5936, #5937, #5938, #5939 (BA-2413, BA-2414, BA-2415, BA-2416, BA-2417)

feat: Implement model definition generators for all runtime variants

---

changes/6028.fix.md
src/ai/backend/common/clients/valkey_client/valkey_stat/client.py

fix(BA-2504): Add missing null check for batch operation result in `ValkeyStatClient.get_image_distro()`

---

changes/5807.feature.md
docs/manager/graphql-reference/schema.graphql
docs/manager/rest-reference/openapi.json
src/ai/backend/manager/models/base.py
src/ai/backend/manager/models/gql_models/base.py
src/ai/backend/manager/models/gql_models/image.py
src/ai/backend/manager/models/image.py
src/ai/backend/manager/registry.py

This is a backport PR of https://github.com/lablup/backend.ai/pull/5807 to the 25.6 release.
----
📚 Documentation preview 📚: https://sorna--6038.org.readthedocs.build/en/6038/
----
📚 Documentation preview 📚: https://sorna-ko--6038.org.readthedocs.build/ko/6038/

feat(BA-2316): Remove obsolete max slot limit validation during session creation (#5807)

---

changes/6049.fix.md
src/ai/backend/manager/cli/fixture.py

fix(BA-2519): Wrong error code of `mgr fixture populate` command

---

scripts/app-proxy/migrate-health-check-configuration.py
src/ai/backend/account_manager/models/utils.py
src/ai/backend/appproxy/coordinator/models/utils.py
src/ai/backend/manager/cli/fixture.py
src/ai/backend/manager/models/utils.py
tests/manager/conftest.py

There are multiple places generating database connection URLs.
Some of them fully apply URL quotation to user, password, and database names, but some others do not or partially apply it.
Let's make them all consistent and move the responsibility of standard-compliant URL generation to `yarl.URL`.

refactor: Make DB URL generation consistent and std-compliant

---

changes/6081.fix.md
src/ai/backend/manager/models/gql_models/session.py

fix(BA-2543): Add missing Compute session node resource_opts field resolver

---

changes/6096.fix.md
src/ai/backend/common/config.py
src/ai/backend/manager/config/unified.py

fix(BA-2539): Apply BaseConfigSchema to Manager

---

changes/6021.fix.md
src/ai/backend/manager/errors/storage.py
src/ai/backend/manager/models/vfolder.py

This is an auto-generated backport PR of #6021 to the 25.14 release.

fix(BA-2490): Correct mount permission check when creating session (#6021)

---

changes/6098.fix.md
src/ai/backend/common/config.py
src/ai/backend/storage/config/unified.py
tests/storage-proxy/artifacts/test_service.py

fix(BA-2541): Apply BaseConfigSchema to Storage-proxy

---

changes/6108.feature.md
changes/6109.feature.md
src/ai/backend/manager/models/gql_models/session.py

feat(BA-2466): Implement node resolver in `ComputeSessionNode`

---

changes/6103.enhance.md
src/ai/backend/common/exception.py
src/ai/backend/manager/api/session.py
src/ai/backend/manager/repositories/agent/db_source/db_source.py
src/ai/backend/manager/repositories/agent/repository.py
src/ai/backend/manager/services/agent/actions/sync_agent_registry.py
tests/manager/repositories/agent/test_db_source.py

refactor(BA-2523): Explicitly raise error when agent not found instead of returning none

---

changes/6128.fix.md
src/ai/backend/manager/errors/container_registry.py
src/ai/backend/manager/models/container_registry.py
src/ai/backend/manager/models/gql_models/container_registry_v2.py
tests/manager/api/test_container_registries.py

resolves #6063, #6064 (BA-2527, BA-2528)

fix(BA-2527, BA-2528): Add Harbor registry creation argument validation

---

changes/6125.feature.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/observer/heartbeat.py
src/ai/backend/agent/observer/host_port.py
src/ai/backend/common/observer/types.py

feat(BA-2579): Add periodic container monitoring to release unused host ports

---

changes/6139.fix.md
src/ai/backend/agent/agent.py
src/ai/backend/agent/metrics/metric.py
src/ai/backend/agent/metrics/types.py
src/ai/backend/agent/stats.py
src/ai/backend/common/metrics/types.py

fix(BA-2596): Clean container utilization metric when destroy kernel

---

changes/6159.misc.md
src/ai/backend/manager/repositories/user/repository.py

chore(BA-2602): Add warning log when adding new user with no groups

---

changes/6160.fix.md
src/ai/backend/manager/models/container_registry.py
src/ai/backend/manager/models/gql_models/container_registry.py
src/ai/backend/manager/models/gql_models/container_registry_v2.py
tests/manager/api/test_container_registries.py

fix(BA-2587): Validate container registry input in `create`, `update` mutations

---

changes/6207.fix.md
src/ai/backend/testutils/bootstrap.py
tests/common/redis_helper/docker.py

fix(BA-2657): Resolve race conditions in test container port allocation
