lablup/backend.ai

src/ai/backend/manager/registry.py
`ai.backend.manager.agent_cache.AgentRPCCache.rpc_context()` provides a context with a RPC peer.
It raises a `RPCUserError` if the RPC invokes error.
We use `ai.backend.manager.exceptions.convert_to_status_data()` to parse `AgentError` or `MultiAgentError` to a readable dictionary but it does not work properly since the function gets only `RPCUserError`.
=> fix: Change context indent to handle RPC exception correctly when calling create kernel

docs/_static/css/customTheme.css
- Set font-family to monospace.
- Remove border
- Change code font color to `#1f2328`
----
📚 Documentation preview 📚: https://sorna--2518.org.readthedocs.build/en/2518/
----
📚 Documentation preview 📚: https://sorna-ko--2518.org.readthedocs.build/ko/2518/
=> doc: Update the inline-code style for better readability

.gitignore, changes/2367.deps.md, docker-compose.halfstack-2409.yml, docker-compose.halfstack-main.yml, docs/dev/daily-workflows.rst, docs/dev/version-management-and-upgrades.rst, docs/install/install-from-package/prepare-database.rst
> [!WARNING]
> This PR involves a major version change in the postgres halfstack container.
>
> You need to consult the updated docs (included in this PR) to choose the best option
> (reset or in-place upgrade) for your local development environment.
>
> In general, it is recommended to do a clean install of your dev setup
> when start working on a new release branch.
----
📚 Documentation preview 📚: https://sorna--2367.org.readthedocs.build/en/2367/
----
📚 Documentation preview 📚: https://sorna-ko--2367.org.readthedocs.build/ko/2367/
=> deps: Add the new 24.09 halfstack compose config

changes/2523.fix.md, src/ai/backend/storage/api/manager.py
This pull request is a follow-up to #1430 and simply corrects a typo in `check_status()` API's response.
| Before | After |
| ------- | ----- |
| ma**an**ger-facing | ma**na**ger-facing |
=> fix: Typo in storage `check_status()` API response

changes/2523.fix.md, src/ai/backend/storage/api/manager.py
This is an auto-generated backport PR of #2523 to the 24.03 release.
=> fix: Typo in storage `check_status()` API response (#2523)

.github/workflows/ci.yml
- ${{ }} syntax does not skip the step as intended when used in a split syntax.
If the ${{ }} statement in the if condition to wrap the whole thing.
- As a follow-up to #2265, we added additional permissions for uploading releases.
=> ci: Fix if condition not working properly

.github/workflows/backport.yml
close #2158 
In #2159, the label of the existing PR was added, but it was not working until now due to lack of permissions.
By adding a label when creating a pull-request, solve permission issues and prevent race problems between the CI and label states that occur when adding a label after creating a pull-request.
=> ci: Add the label of the original PR to the backport PR

.github/workflows/backport.yml
In #2247, the string was treated as a single quote to treat special characters such as backticks as regular characters.
However, the ${{ }} syntax in github actions was used to replace the relevant part of the script rather than using a shell string variable, so it did not work properly if the commit_message value included a single quote.
So, change it to use as a shell variable using env so that it operates normally.
=> ci: Treats special characters as regular characters

.github/workflows/ci.yml
Refactored the syntax with multiple if conditions to multi-line in #2499 to make the code more readable.
However, when using `${{ }}` as multi-line in github actions does not work correctly.
To use a grammar like `!` in an if condition, it would conflict with the existing keyword in YAML, so originally the `${{ }}` grammar, but using multi-line grammars like `|` or `>` is fine because all subsequent values are treated as literal.
To make sure it is labeled skip:ci, the kind of event must be pull_request.
So the ci is not being skipped in the case of ci fired by push trigger, and it is not merged in the case of required.
And there is also a problem that if you push a commit to the pr branch, the pull_request trigger and push trigger occur at the same time, so the ci is performed twice.
So …
=> ci: Makes if conditions written in multi-line work properly

src/ai/backend/manager/api/exceptions.py, src/ai/backend/manager/models/group.py, src/ai/backend/manager/models/rbac/__init__.py, src/ai/backend/manager/models/rbac/exceptions.py, src/ai/backend/manager/models/vfolder.py
Users have one or many roles {Owner, Admin, Monitor, Contributor, Member} in a scope.
`Contributor` is a role that user has if the user is part of a specific scope and has read(or some additional permissions) to objects that the scope has. e.g. project user has a Contributor role in the project and the user can mount folders of the project.
`Member` is a role that user has if the user is part of a specific scope and has **NO PERMISSION** to objects that the scope has. e.g. domain user has a Member role in the domain and the user cannot read, write or mount folders of the domain.
----
📚 Documentation preview 📚: https://sorna--2504.org.readthedocs.build/en/2504/
----
📚 …
=> refactor: Reorganize scope and roles in RBAC interface

.github/workflows/ci.yml
This is a follow-up of #2524.
In GitHub Actions, job outputs (and environment variables) are _always_ strings while context variables may have native types.
Although it looks weird, we should compare job output variables with string literals like `'false'`, `'true'`, instead of native values like `false`, `true` in the GitHub's expression syntax.
=> ci: Fix job output evaluation for the CI optimizer

changes/2574.fix.md, src/ai/backend/common/redis_helper.py
As I checked [how Redis client gets initialized](https://github.com/redis/redis-py/blob/4.5/redis/asyncio/client.py#L195), it passes keyword arguments to its connection pool only when it has to initialize new connection pool object.
As we pass connection pool object to Redis client, we should pass the connection options to connection pool's `from_url()`.
refs:
https://github.com/redis/redis-py/blob/4.5/redis/asyncio/connection.py#L1247
https://github.com/redis/redis-py/blob/4.5/redis/asyncio/connection.py#L1290-L1295
=> fix: Init Redis connection pool with appropriate connection opts

changes/2574.fix.md, src/ai/backend/common/redis_helper.py
This is an auto-generated backport PR of #2574 to the 24.03 release.
=> fix: Init Redis connection pool with appropriate connection opts (#2574)

changes/2558.enhance.md, src/ai/backend/manager/models/agent.py
Like other SQLAlchemy queries in GraphQL, apply the same dataloader mechanism to batch the Redis queries for stat metric fields of the agent query.
On a simulated 500 node cluster setup, it reduces the latency of the all-agent listing query from 1.62s to 212msec.
=> enhance: Apply batch dataloader to statistics fetched from Redis

.github/workflows/ci.yml
In our CI workflow, we are creating a release when push a tag.
The release-related jobs are preceded by `lint`, `typecheck`, `test`, and `check-alembic-migration` jobs to increase the stability of the release version.
However, the `check-alembic-migration` job is currently only triggered if the label `require:db-migration` exists, which is preventing the release-related jobs from running.
So we're modifying the `check-alembic-migration` job to also fire on the tag push event.
=> ci: run alembic migration checker on release situations

.github/workflows/ci.yml
This is an auto-generated backport PR of #2585 to the 24.03 release.
=> ci: run alembic migration checker on release situations (#2585)

.github/workflows/ci.yml
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
> If you define only tags/tags-ignore or only branches/branches-ignore, the workflow won't run for events affecting the undefined Git ref. If you define neither tags/tags-ignore or branches/branches-ignore, the workflow will run for events affecting either branches or tags. If you define both branches/branches-ignore and [paths/paths-ignore](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore), the workflow will only run when both filters are satisfied.
In #2514, we restricted the CI workflow to run only for pushes from the main and release branches.
However, this setting …
=> ci: make workflow also work for tag push events

.github/workflows/ci.yml
This is an auto-generated backport PR of #2588 to the 24.03 release.
=> ci: make workflow also work for tag push events (#2588)

.github/workflows/ci.yml
follow-up #2588
If a step in optimize-ci was previously skipped, the value of outputs.skip did not exist to satisfy the syntax `outputs.skip == 'false'`.
So we assign the value of outputs.skip to 'false' if the value doesn't exist.
In the future, if it is confirmed that graphite-ci-action returns false if the event is not a pull_request, we may want to remove this logic and change to using graphite-ci-action only
=> ci: always set `skip` output of `optimize-ci` workflow

.github/workflows/ci.yml
This is an auto-generated backport PR of #2593 to the 23.09 release.
=> ci: always set `skip` output of `optimize-ci` workflow (#2593)

changes/2583.feature.md, src/ai/backend/wsproxy/proxy/frontend/http/abc.py
This is an auto-generated backport PR of #2583 to the 24.03 release.
=> feat: allow `Bearer` as valid token type on model service authentication (#2583)

changes/2598.fix.md, src/ai/backend/manager/models/gql.py
This is an auto-generated backport PR of #2598 to the 24.03 release.
=> fix: Update `GQLPrivilegeCheckMiddleware` to align with upstream changes on `graphql-core` package (#2598)

changes/2605.fix.md, src/ai/backend/manager/models/agent.py, src/ai/backend/manager/models/kernel.py
=> fix: typo in minilang query field spec and column map

changes/2605.fix.md, src/ai/backend/manager/models/agent.py, src/ai/backend/manager/models/kernel.py
This is an auto-generated backport PR of #2605 to the 24.03 release.
=> fix: typo in minilang query field spec and column map (#2605)

src/ai/backend/manager/models/agent.py
This is an auto-generated backport PR of #2610 to the 24.03 release.
=> fix: typo in AgentSummary queryfilter fieldspec (#2610)

scripts/pre-push.sh
While working on #2625, I found that the current pre-push hook does not detect the correct base branch name when it run `pants ... --changed-since=...`.
To maintain independency of the toolchain from GitHub, let the pre-push script gracefully fallback to the full lint & check when `gh` (GitHub CLI) is not available.
=> chore: Update git pre-push hook to use correct base branch name

scripts/pre-push.sh
This is an auto-generated backport PR of #2626 to the 23.09 release.
=> chore: Update git pre-push hook to use correct base branch name (#2626)

changes/2604.fix.md, src/ai/backend/agent/docker/agent.py
This is an auto-generated backport PR of #2604 to the 23.09 release.
=> fix: Skip mounting zero-byte lxcfs files (#2604)

changes/2632.fix.md, src/ai/backend/common/redis_helper.py
This looks like an uncovered logical error after #2574.
When we retry the Redis command upon timeout errors, we should distinguish if the timeout is a "normally expected" one like blocking commands or if it's really a server/network failure.
For instance, in `common.redis_helper.read_stream()` and `common.redis_helper.read_stream_by_group()`, we apply 10 seconds command timeout for `XREAD` and `XREADGROUP`.
This PR silences retry warnings by resetting the `first_trial` timestamp when we loop through infinite retries for such blocking commands. It now emits the retry warning only if the detected elapsed time exceeds _the expected command timeout_ (only when explicitly given) + 1 second, **where the elapsed time is measured from the beginning of each iteration.**
**Checklist:** (if …
=> fix: Silence falsy Redis timeout warnings with blocking commands

changes/2632.fix.md, src/ai/backend/common/redis_helper.py
This is an auto-generated backport PR of #2632 to the 24.03 release.
=> fix: Silence falsy Redis timeout warnings with blocking commands (#2632)

changes/2635.fix.md, src/ai/backend/client/func/session.py, src/ai/backend/manager/api/exceptions.py, src/ai/backend/manager/api/session.py, src/ai/backend/manager/api/utils.py
This is a follow-up to #2483.
Now we should use the `POST` HTTP method with a custom verb following the resource identifier when designing a REST API.
This PR also adds the `DeprecatedAPI` error to guide the API users to use the POST HTTP method, and refactors `QueryNotImplemented` (503 Service Unavailable) to `NotImplementedAPI` (400 Bad Request) in analogy.
=> fix: Update the session-download API to use POST with custom verb

changes/2635.fix.md, src/ai/backend/client/func/session.py, src/ai/backend/manager/api/exceptions.py, src/ai/backend/manager/api/session.py, src/ai/backend/manager/api/utils.py
This is an auto-generated backport PR of #2635 to the 24.03 release.
=> fix: Update the session-download API to use POST with custom verb (#2635)

changes/2557.fix.md, src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/models/gql.py, src/ai/backend/manager/models/image.py
This is an auto-generated backport PR of #2557 to the 24.03 release.
=> fix: hide third-party customized image from GQL query (#2557)

changes/2573.fix.md, src/ai/backend/manager/models/group.py
This is an auto-generated backport PR of #2573 to the 24.03 release.
=> fix: delete dependent sessions when purging project (#2573)

changes/2648.fix.md, src/ai/backend/manager/models/base.py
This PR Implement missing `StrEnumType` handling in `populate_fixture()`
This PR is a prerequisite for PR #1917.
This issue was discovered during the process of changing `ContaineRegistryRow.registry_type` to an `StrEnum` type.
This is separated into a distinct PR for backporting.
---
=> fix: Implement missing `StrEnumType` handling in `populate_fixture()`

changes/2648.fix.md, src/ai/backend/manager/models/base.py
This is an auto-generated backport PR of #2648 to the 24.03 release.
=> fix: Implement missing `StrEnumType` handling in `populate_fixture()` (#2648)

changes/2611.feature.md, src/ai/backend/manager/models/domain.py
This PR includes the addition of `sqlalchemy.engine.result.Result` import, `from ai.backend.manager.models.group import ProjectType`, and enhancements to the `from_row` class method of the Domain model. **These changes introduce automatic creation of a 'model-store' group upon inserting a new domain to database**, only when `CreateDomain` mutation is performed. The process involves modifying the `mutate` async method to include a `_post_func` that inserts a 'model-store' group into the groups table using the `ProjectType.MODEL_STORE` value. The `total_resource_slots` field handling has also been refactored for clarity.
related PR: https://github.com/lablup/backend.ai-control-panel/pull/810
---
- …
=> feat: automate `model-store` project creation

changes/2661.fix.md, src/ai/backend/client/func/resource.py
=> fix: let GET requests contain data in param rather than body

changes/2661.fix.md, src/ai/backend/client/func/resource.py
This is an auto-generated backport PR of #2661 to the 24.03 release.
=> fix: let GET requests contain data in param rather than body (#2661)

changes/2667.fix.md, scripts/agent/build-dropbear.sh, scripts/agent/build-sftpserver.sh, src/ai/backend/agent/agent.py, src/ai/backend/kernel/intrinsic.py, src/ai/backend/runner/dropbear.aarch64.bin, src/ai/backend/runner/dropbear.x86_64.bin, src/ai/backend/runner/dropbearconvert.aarch64.bin, src/ai/backend/runner/dropbearconvert.x86_64.bin, src/ai/backend/runner/dropbearkey.aarch64.bin, src/ai/backend/runner/dropbearkey.x86_64.bin, src/ai/backend/runner/dropbearmulti.aarch64.bin, src/ai/backend/runner/dropbearmulti.x86_64.bin, src/ai/backend/runner/entrypoint.sh, src/ai/backend/runner/scp.aarch64.bin, src/ai/backend/runner/scp.x86_64.bin
When sudo-enabled users run `apt install` or `apt upgrade` in session containers, `openssh-client` package is often (re)installed as being dependencies to some other packages.
This fails with "Resources or device is busy" error in session containers because `/usr/bin/scp` and `/usr/libexec/sftp-server` are read-only mounts of our statically built openssh-portable binaries.
- Replace multiple `dropbear*` and `scp` binaries with a single `dropbearmulti` binary.
- Dropbear offers `MULTI=1` Makefile option to merge multiple executables into a single binary just like Busybox.
- Dropbear actually contains the `scp` implementation, so we don't have to build and ship scp from openssh-portable.
- In `entrypoint.sh`, symlink `/usr/bin/scp` to `/opt/kernel/dropbearmulti` so that it **could** be …
=> fix: Use dropbear 'multi' build and allow overwriting scp in containers

scripts/install-dev.sh
This is an auto-generated backport PR of #2673 to the 24.03 release.
=> fix: The URL of docker compose installation guide in install-dev.sh (#2673)

scripts/pre-push.sh
Let the `pre-push.sh` hook detect if we are directly pushing to release branches.
This is a follow-up fix to #2626.
=> chore(pre-push): Consider direct pushes to release branches when detecting the base branch

changes/2677.feature.md, configs/webserver/sample.conf, src/ai/backend/web/config.py, src/ai/backend/web/templates/config.toml.j2, src/ai/backend/web/templates/config_ini.toml.j2
related PR: https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2620
Enable/disable the LLM Playground tab in the service page via the new `enable_LLM_playground` configuration option.
- Added `enable_LLM_playground` option to `sample.conf`.
- Updated `config.py` to process the new option.
- Modified `config.toml.j2` and `config_ini.toml.j2` templates to incorporate the new option.
1. Go to `configs/webserver/sample.conf` and set `enable_LLM_playground` to true or false.
2. Restart the webserver.
3. Verify that the LLM Playground tab appears or disappears in the service page based on the configuration.
The change introduces a flexible way to enable or disable the LLM Playground tab in the service page, providing better control over the web server's UI configuration.
--- …
=> feat: add `enable_LLM_playground` config on webserver

src/ai/backend/agent/docker/agent.py, src/ai/backend/manager/defs.py
Follow-up of #2582. Fixes following things:
- image without minimum resource label not set not scanned
- image Libc version detection not working
=> fix: image without explicit metadata labels not working

changes/2677.feature.md, configs/webserver/sample.conf, src/ai/backend/web/config.py, src/ai/backend/web/templates/config.toml.j2, src/ai/backend/web/templates/config_ini.toml.j2
This is an auto-generated backport PR of #2677 to the 24.03 release.
=> feat: add `enable_LLM_playground` config on webserver (#2677)

changes/2608.fix.md, src/ai/backend/agent/docker/intrinsic.py
This is an auto-generated backport PR of #2608 to the 24.03 release.
=> fix: Remove duplicate CPU quota options when creating containers (#2608)

changes/2696.fix.md, src/ai/backend/storage/netapp/__init__.py
follow-up #2170 
When we create a quota after creating Netapp qtree, sometimes Netapp API responds not found error.
#2170 is to avoid such timing issue but it causes another error because Python's Path implementation cache directory data and it takes long to update the cache with newly created qtree directory.
So, let's scan directories from the parent directory of created qtree.
=> fix: Scan parent directory of created qtree for robust check

changes/2696.fix.md, src/ai/backend/storage/netapp/__init__.py
This is an auto-generated backport PR of #2696 to the 24.03 release.
=> fix: Scan parent directory of created qtree for robust check (#2696)

changes/2681.fix.md, src/ai/backend/web/server.py
This is an auto-generated backport PR of #2681 to the 24.03 release.
=> fix: Update `webserver` logout API to respond with HTTP 200 OK (#2681)

changes/2712.misc.md, gql-inspector-checker.js
Allow adding required GQL field argument by relaxing `BREAKING` criticality level to `DANGEROUS`.
It has been prohibited to add a required field argument to existing types.
```gql
type Queries {
vfolders(
"""Added in 24.09.0. This is a required argument and now it is allowed to add such field arguments."""
project_id: UUID!
}
}
```
=> ci: Allow adding required GQL field argument to schema

changes/2706.fix.md, src/ai/backend/client/func/vfolder.py, tests/client/test_vfolder.py
This is an auto-generated backport PR of #2706 to the 24.03 release.
=> fix:let vfolder GET requests contain data in params rather than body (#2706)

changes/2709.feature.md, src/ai/backend/manager/api/admin.py, src/ai/backend/manager/config.py, src/ai/backend/manager/models/base.py, src/ai/backend/manager/models/gql.py, src/ai/backend/manager/models/gql_relay.py
1. To set GQL query depth limit, set etcd's `config/api/max-gql-query-depth` value to integer bigger than 1. Default value is null, which means there is no depth limit.
2. To set GQL Connection page size limit, set etcd's `config/api/max-gql-connection-page-size` value to integer bigger than 1. Default value is null, which means there is no page size limit.
3. Default GQL Connection page size is 10.
----
📚 Documentation preview 📚: https://sorna--2709.org.readthedocs.build/en/2709/
----
📚 Documentation preview 📚: https://sorna-ko--2709.org.readthedocs.build/ko/2709/
=> feat: Configurable GQL query depth limit & Connection page limit

src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/models/base.py, src/ai/backend/manager/models/gql.py, src/ai/backend/manager/models/gql_models/vfolder.py
`vfolder_nodes` query resolver will use RBAC interface.
----
📚 Documentation preview 📚: https://sorna--2670.org.readthedocs.build/en/2670/
----
📚 Documentation preview 📚: https://sorna-ko--2670.org.readthedocs.build/ko/2670/
=> feat: Let vfolder relay resolver use RBAC apis

src/ai/backend/manager/idle.py, tests/manager/test_idle_checker.py
idle check report is stored in Redis and GQL session query resolver fetches the data one by one for each session object.
Let's add a function that load batch reports.
=> feat: Add function loads batch idle check report

changes/2717.feature.md, src/ai/backend/manager/models/base.py
Since we can hash a function object or a method object in Python, let `ai.backend.manager.model.base.DataLoaderManager` cache and get batch load functions by the function object itself.
=> feat: Allow `DataLoaderManager` to get a loader function by function itself

changes/2473.feature.md, src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/models/gql.py, src/ai/backend/manager/models/scaling_group.py
This pull request adds new mutations to the GraphQL schema in the backend. These mutations include `AssociateScalingGroupsWithDomain`, `AssociateScalingGroupsWithUserGroup`, `AssociateScalingGroupsWithKeyPair`, and their corresponding disassociate counterparts. Most of the modifications are in `schema.graphql`, while the supporting logic is implemented in `gql.py` and `scaling_group.py`. These new mutations aim to enhance the functionality by allowing bulk association and disassociation of scaling groups with domains, user groups, and key pairs. The newly added mutations are marked with the version `24.03.9`.
---
- Demonstrate the flow of …
=> feat: Add Associate and Disassociate Scaling Groups with Domain, User Group, and KeyPair mutations

changes/2254.feature.md, src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/models/agent.py, src/ai/backend/manager/models/scaling_group.py
=> feat: GQL resolvers for querying agent's total resource allocation (#2254)

changes/2502.feature.md, tests/wsproxy/BUILD, tests/wsproxy/test_utils.py
This pull request adds test for various utility functions in wsproxy. The tests ensure that the functions correctly handle different input types and provide consistent results across different environments.
- Added tests for `ensure_json_serializable` function:
- Tested with various input types including dictionaries, lists, UUIDs, HostPortPair, Path, BaseModel, enum.Enum, and datetime objects.
- Ensured consistency of datetime serialization across different time zones.
- Added tests for `config_key_to_kebab_case` function:
- Verified that dictionary keys are correctly converted to kebab-case.
- Handled nested dictionaries and lists.
- Added tests for `mime_match` function:
- Tested matching of MIME types with and without the strict parameter.
- Demonstrate …
=> feat: add tests for utility functions in wsproxy(app proxy)

src/ai/backend/wsproxy/proxy/frontend/http/port.py, tests/wsproxy/proxy/BUILD, tests/wsproxy/proxy/test_port.py
This is an auto-generated backport PR of #2480 to the 24.03 release.
=> feat: add tests for _ensure_slot method in PortFrontend (#2480)

changes/2584.fix.md, src/ai/backend/manager/api/vfolder.py
This is an auto-generated backport PR of #2584 to the 24.03 release.
=> fix: return `null` for missing user and group fields in VFolder lookup API response (#2584)

changes/2741.fix.md, src/ai/backend/storage/api/manager.py
This is an auto-generated backport PR of #2741 to the 24.03 release.
=> fix: Handle fs error when deleting vfolder (#2741)

changes/2731.fix.md, src/ai/backend/manager/api/vfolder.py
Updated the vfolder_id field in the list_shared_vfolders function to fix a potential naming conflict.
- Modified the `list_shared_vfolders` function in the `vfolder.py` file.
- Changed the `vfolders.c.id` column selection to `vfolders.c.id.label("vfolder_id")` in the SQL query.
- Updated the dictionary creation to use `shared.vfolder_id` instead of `shared.id` when setting the `vfolder_id` key.
1. Call the `list_shared_vfolders` API endpoint.
2. Verify that the response contains the correct `vfolder_id` for each shared folder.
3. Check if the Vfolder id matches.
This change addresses a potential naming conflict between the `id` field from the `vfolder_permissions` table and the `id` field from the `vfolders` table. By explicitly labeling the `vfolders.c.id` as `vfolder_id`, we ensure that …
=> fix: vfolder id doesn't match in `list_shared_vfolders`

changes/2740.feature.md, src/ai/backend/manager/api/vfolder.py
```
curl --location 'MANAGER_ADDR/folders/_/sharing' \
--header 'Content-Type: application/json' \
--data '{
"vfolder": "FOLDER_ID",
"user_perm_list": [
{
"user": "USER_ID",
"perm": "ro"
}
]
}'
```
=> feat: Add new vfolder API to update sharing status

changes/2723.feature.md, src/ai/backend/manager/models/endpoint.py
This is a follow up of #2722
Added filtering for ("name", "model", "domain", "url", "created_user_email")
and ordering for ("name", "created_at", "model", "domain", "url", "created_user_email")
(Used .minilang for filtering)
**CANNOT filter/order for the next items.** 
- Session_owner's columns(only filtering for created_user is available due to the label)
- Status(The manager resolves the status every time which isn't in the db)
Besides this adding more ways for filtering and ordering is welcome
Would be grateful for comments if this is an okay way, and if there is more filtering and ordering needed.
=> feat: enable filter order in endpoint model

changes/2754.fix.md, src/ai/backend/common/msgpack.py, tests/common/test_msgpack.py
Currently, when deserializing the `ResourceSlot` type with `msgpack.unpack()`, the following *"Unknown Type"* error occurs.
This PR resolves the issue by explicitly adding `ResourceSlot` to `ExtTypes`, allowing `msgpack.unpack()` to correctly deserialize the `ResourceSlot` type.
When restarting the session using the session restart command, the agent outputs the following error.
1. Create a session.
```
./backend.ai session create python
```
2. Restart the created session.
```
./backend.ai session restart <sess_id>
```
3. Now the following error is displayed on the agent with the assigned session.
```
2024-08-22 02:04:17.302 ERROR ai.backend.agent.agent [36527] restart_kernel(s:5becdfbb-747d-47d8-9a86-b682e137e646, k:e3251e6a-1986-4b2e-a069-0e848081c907): re-creation failure
Traceback …
```
=> fix: Correct `msgpack` deserialization of `ResourceSlot`

changes/2754.fix.md, src/ai/backend/common/msgpack.py, tests/common/test_msgpack.py
This is an auto-generated backport PR of #2754 to the 24.03 release.
=> fix: Correct `msgpack` deserialization of `ResourceSlot` (#2754)

changes/2761.fix.md, src/ai/backend/client/cli/session/lifecycle.py
Follow-up of #1838.
1. Create session template using `example-session-templates.yaml`
```
./backend.ai sesstpl create -f ./fixtures/manager/example-session-templates.yaml
```
2. Try to create a session using the created template.
```
./backend.ai session create-from-template <session_template_id>
```
Then the following error is displayed.
```
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/home/jopemachine/backend.ai/src/ai/backend/cli/__main__.py", line 10, in <module>
main(max_content_width=shutil.get_terminal_size().columns - 2)
File "/home/jopemachine/backend.ai/dist/export/python/virtualenvs/python-default/3.12.4/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
return …
```
=> fix: Regression of `session create-from-template` command

changes/2761.fix.md, src/ai/backend/client/cli/session/lifecycle.py
This is an auto-generated backport PR of #2761 to the 24.03 release.
=> fix: Regression of `session create-from-template` command (#2761)

src/ai/backend/agent/docker/agent.py, src/ai/backend/common/redis_client.py, src/ai/backend/kernel/base.py, src/ai/backend/manager/container_registry/base.py, src/ai/backend/storage/purestorage/__init__.py, src/ai/backend/wsproxy/api/proxy.py
This pull request is a follow-up of #1792.
Refs
- https://docs.python.org/3/library/logging.html#logging.Logger.warning
Replaced deprecated `log.warn()` calls with `log.warning()` to ensure consistency and support future maintenance across multiple files.
- Replaced all instances of `log.warn()` with `log.warning()` in various files:
- src/ai/backend/agent/docker/agent.py
- src/ai/backend/common/redis_client.py
- src/ai/backend/kernel/base.py
- src/ai/backend/manager/container_registry/base.py
- src/ai/backend/storage/purestorage/__init__.py
- src/ai/backend/wsproxy/api/proxy.py
1. Run the application and trigger scenarios that would generate warning logs.
2. Verify that warning messages are still being logged correctly.
3. Check the log output to ensure that all warnings use the …
=> refactor: Replace deprecated `log.warn()` with `log.warning()`

changes/2765.fix.md, src/ai/backend/common/types.py, src/ai/backend/manager/api/service.py
This is an auto-generated backport PR of #2765 to the 24.03 release.
=> fix: Silence `model_` namespace warnings in pydantic models (#2765)

src/ai/backend/agent/docker/agent.py, src/ai/backend/common/redis_client.py, src/ai/backend/kernel/base.py, src/ai/backend/manager/container_registry/base.py, src/ai/backend/storage/purestorage/__init__.py, src/ai/backend/wsproxy/api/proxy.py
This is an auto-generated backport PR of #2763 to the 24.03 release.
=> refactor: Replace deprecated `log.warn()` with `log.warning()` (#2763)

changes/2028.fix.md, src/ai/backend/manager/models/image.py
This is a backport PR of https://github.com/lablup/backend.ai/pull/2028 to the 24.03 release.
=> fix: Mishandling of undefined value in the `ModifyImage` mutation

changes/2771.fix.md, src/ai/backend/install/context.py
This is an auto-generated backport PR of #2771 to the 23.09 release.
=> fix: Make the config file be treated as multiline by re (#2771)

changes/2768.fix.md, src/ai/backend/install/cli.py
This is an auto-generated backport PR of #2768 to the 24.03 release.
=> fix: Reflect `target_path` changes in `PackageContext` (#2768)

changes/2777.fix.md, src/ai/backend/client/func/resource.py, src/ai/backend/manager/api/resource.py
For control panel testing, follow this way. ([Related threads.](https://teams.microsoft.com/l/message/19:14c484402d874dafb15806d093b95a82@thread.skype/1724735843276?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631&parentMessageId=1724644510871&teamName=devops&channelName=Frontend&createdTime=1724735843276))
1. ./run_in_container.sh bash
2. patch with this code
3. modify something in `manage.py` such as adding space.
=> fix: Omit null parameter when call usage per period API

changes/2777.fix.md, src/ai/backend/client/func/resource.py, src/ai/backend/manager/api/resource.py
This is an auto-generated backport PR of #2777 to the 24.03 release.
=> fix: Omit null parameter when call usage per period API (#2777)

changes/2786.fix.md, src/ai/backend/agent/docker/agent.py
Let's check port mapping and raise `ContainerCreationError` if any port mapping mismatch rather than raise assertion error.
=> fix: Handle container port mismatch when creating kernel

changes/2786.fix.md, src/ai/backend/agent/docker/agent.py
This is an auto-generated backport PR of #2786 to the 23.09 release.
=> fix: Handle container port mismatch when creating kernel (#2786)

src/ai/backend/storage/vast/vastdata_client.py
Change Vast data client's API token life span since there are some API call failure due to outdate tokens.
=> chore: change vastdata API token span

src/ai/backend/storage/vast/vastdata_client.py
This is an auto-generated backport PR of #2785 to the 23.09 release.
=> chore: change vastdata API token span (#2785)

scripts/scie-shell.sh
This PR adds a small helper script to easily access the Python interactive shell in the given SCIE executable's environment.
```shell
pants --tag=scie --tag=+lazy package src/ai/backend/manager::
scripts/scie-shell.sh dist/backendai-manager-linux-aarch64
```
=> chore: Add a helper script to esaily access the scie's internal shell

changes/2711.feature.md, src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/models/gql.py, src/ai/backend/manager/models/gql_models/kernel.py, src/ai/backend/manager/models/gql_models/session.py, src/ai/backend/manager/models/gql_relay.py
Here is an example query of compute session.
```graphql
query ComputeSession {
compute_session_nodes(
project_id: "PROJECT_ID",
permission: "read_attribute",
first: 3,
) {
edges {
cursor
node {
row_id
name
status
idle_checks
permissions
kernel_ids
kernel_nodes {
count
edges {
node {
id
row_id
session_id
status
live_stat
}
}
}
}
}
count
pageInfo {
hasNextPage
hasPreviousPage
}
}
}
```
----
📚 Documentation preview 📚: https://sorna--2711.org.readthedocs.build/en/2711/
----
📚 Documentation preview 📚: https://sorna-ko--2711.org.readthedocs.build/ko/2711/
=> feat: Add compute session GQL relay schema

changes/2796.feature.md, configs/agent/sample.toml, src/ai/backend/agent/config.py, src/ai/backend/agent/stats.py, src/ai/backend/common/types.py
refs #2791
As an interim measure, this PR adds an explicit agent local configuration to set its resource group type by itself: "compute" or "storage".  For backward compatibility, the default is "compute".
Currently this configuration only affects the behavior of the agent, as it is not reported to the manager.
> [!NOTE]
> To update the minor versions including this PR, the fieldops engineers should add the explicit `scaling-group-type` setting when upgrade the SFTP agents deployed on storage-proxy nodes.
=> feat: Add `scaling-group-type` in agent.toml

changes/2796.feature.md, changes/2797.fix.md, configs/agent/sample.toml, src/ai/backend/agent/agent.py, src/ai/backend/agent/config.py, src/ai/backend/agent/docker/agent.py, src/ai/backend/agent/docker/kernel.py, src/ai/backend/agent/dummy/agent.py, src/ai/backend/agent/kubernetes/agent.py, src/ai/backend/agent/stats.py, src/ai/backend/common/types.py
refs #2791
This is a temporary fix until we do full refactoring.
=> fix: Explicitly specify protected service ports not to expose publicly

changes/2796.feature.md, configs/agent/sample.toml, src/ai/backend/agent/config.py, src/ai/backend/agent/stats.py, src/ai/backend/common/types.py
This is an auto-generated backport PR of #2796 to the 24.03 release.
=> feat: Add `scaling-group-type` in agent.toml (#2796)

changes/2797.fix.md, src/ai/backend/agent/agent.py, src/ai/backend/agent/docker/agent.py, src/ai/backend/agent/docker/kernel.py, src/ai/backend/agent/dummy/agent.py, src/ai/backend/agent/kubernetes/agent.py
This is an auto-generated backport PR of #2797 to the 23.09 release.
=> fix: Explicitly specify protected service ports not to expose publicly (#2797)

changes/2805.fix.md, src/ai/backend/manager/models/endpoint.py, src/ai/backend/manager/models/gql.py, src/ai/backend/manager/models/minilang/__init__.py, src/ai/backend/manager/models/minilang/queryfilter.py
Fixes regressions created after PR #2723, where `total_count` value of `endpoint_list` GQL query does not match actual item count. Also fixes `endpoint.status` GQL field reporting `ready` instead of `destroyed` when the endpoint is in `DESTROYED` status.
----
📚 Documentation preview 📚: https://sorna--2805.org.readthedocs.build/en/2805/
----
📚 Documentation preview 📚: https://sorna-ko--2805.org.readthedocs.build/ko/2805/
=> fix: bugs related to `endpoint` and `endpoint_list` GQL queries

changes/2803.fix.md, src/ai/backend/manager/models/session.py
This is an auto-generated backport PR of #2803 to the 24.03 release.
=> fix: Correct session status determiner function (#2803)

.github/workflows/timeline-check.yml
CI like lint and test, which the PR author needs to check while writing the PR, and timeline-check, which the admin needs to check before merging the PR, do not need to be checked in draft, but only in the final version.
=> ci: Skip `timeline-check` on draft PR

.readthedocs.yml, docs/README.md, docs/conf.py
In #1529, after changing font in rtd build, all letters in the document are not visible.
Please download the relevant font and make it available before performing pdf build.
----
📚 Documentation preview 📚: https://sorna--2750.org.readthedocs.build/en/2750/
----
📚 Documentation preview 📚: https://sorna-ko--2750.org.readthedocs.build/ko/2750/
=> ci(doc): load extra fonts to correctly render non-latin characters

docs/_templates/layout.html
This is an auto-generated backport PR of #2732 to the 24.03 release.
=> ci(doc): fix HTML syntax error (#2732)

changes/2806.fix.md, src/ai/backend/client/func/service.py
=> fix: improper variable declaration position on service creation SDK

.readthedocs.yaml, changes/2814.misc.md
This is an auto-generated backport PR of #2814 to the 24.03 release.
=> ci: Upgrade `readthedocs` build environment to Python 3.12 (#2814)

changes/2816.fix.md, src/ai/backend/common/web/session/__init__.py, src/ai/backend/common/web/session/redis_storage.py, src/ai/backend/web/server.py
follow-up #2456 
- `redis.set()` has `ex` parameter and it allows numeric value bigger than 0 or `null`. Let's pass a fixed value (`max_age`) which is always bigger than 0 or null.
- Cannot login after login session expiration because expiration date-time is saved in session storage and it is always earlier than the current time. Let the login handler refresh the session with new expiration date time.
=> fix: login session does not expire or cannot login

changes/2827.fix.md, src/ai/backend/logging/handler/logstash.py
ref) https://github.com/lablup/backend.ai/security/code-scanning/27
=> fix: Use safer TLS version when creating SSL socket in logstash handler

changes/2829.fix.md, src/ai/backend/manager/models/session.py
=> fix: Wrong value of concurrency used

changes/2829.fix.md, src/ai/backend/manager/models/session.py
This is an auto-generated backport PR of #2829 to the 24.03 release.
=> fix: Wrong value of concurrency used (#2829)

changes/2312.feature.md, src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/api/session.py, src/ai/backend/manager/models/gql_models/session.py, src/ai/backend/manager/models/session.py
Add GQL mutation and `POST /session/_/transit-status` API to check and update the status of session
```
curl --location --request POST 'MANAGER_ADDR/session/_/transit-status' \
--header 'Content-Type: application/json' \
--data '{
"id": "SESSION_ID"
}'
```
```json
{"session_status": "RUNNING"}
```
----
📚 Documentation preview 📚: https://sorna--2312.org.readthedocs.build/en/2312/
----
📚 Documentation preview 📚: https://sorna-ko--2312.org.readthedocs.build/ko/2312/
=> feat: Add session status checker API

changes/2837.fix.md, src/ai/backend/manager/registry.py
This is an auto-generated backport PR of #2837 to the 24.03 release.
=> fix: Create kernels with correct scaling group value (#2837)

src/ai/backend/agent/agent.py, src/ai/backend/common/docker.py, src/ai/backend/common/types.py, src/ai/backend/manager/models/image.py, src/ai/backend/manager/registry.py
`ai.backend.common.types.ImageRegistry` is image registry info.
`ai.backend.common.types.ImageConf` contains image information to use when creating kernels including image reference and image registry.
Use both types to create kernels.
=> refactor: image configuration when create kernels

changes/2842.enhance.md, src/ai/backend/client/request.py, src/ai/backend/manager/models/base.py
This is an auto-generated backport PR of #2842 to the 24.03 release.
=> refactor: Avoid using OrderedDict in the manager API and client SDK (#2842)

src/ai/backend/manager/config.py, src/ai/backend/manager/scheduler/agent_selector.py, src/ai/backend/manager/scheduler/dispatcher.py, src/ai/backend/manager/scheduler/types.py
Follow up of #1655.
- Fix several typos.
- Change snake case mistakenly used in Etcd configuration key.
- `ResourceGroupState` -> `AbstractResourceGroupState`.
: Abstract type names should start with Abstract, similar to other types.
- Move the type declarations for `RoundRobinState` and `RRAgentSelectorState`.
: These types would be better placed in `types.py`.
---
=> chore: Correct typos and change agent selector plugin config key to kebab-case

changes/2820.fix.md, src/ai/backend/manager/api/session.py
This is an auto-generated backport PR of #2820 to the 24.03 release.
=> fix: Assign main kernel ID to `kernel_id` for correct log retrieval (#2820)

changes/2780.fix.md, src/ai/backend/manager/api/vfolder.py, src/ai/backend/manager/models/vfolder.py
vfolder deletion API does not delete `vfolder_invitations` and `vfolder_permissions` records currently.
Let's delete them when deleting vfolders.
`vfolder_invitations` and `vfolder_permissions` records are deleted when
- transiting a related vfolder to trash bin
- deleting a related vfolder forever
=> fix: Delete vfolder invitation and permission rows when deleting vfolders

changes/2852.feature.md, python.lock, requirements.txt, src/ai/backend/agent/agent.py, src/ai/backend/agent/config.py, src/ai/backend/agent/docker/agent.py, src/ai/backend/agent/dummy/agent.py, src/ai/backend/agent/kubernetes/agent.py, src/ai/backend/common/validators.py
This is an auto-generated backport PR of #2852 to the 24.03 release.
=> feat: Add support for setting a timeout when pulling Docker images (#2852)

python.lock, requirements.txt
It has numerous bug fixes: https://github.com/aio-libs/aiohttp/releases/tag/v3.10.6
=> deps: Upgrade aiohttp to 3.10.6 and yarl to 1.12.1

python.lock, requirements.txt
This is an auto-generated backport PR of #2862 to the 24.03 release.
=> deps: Upgrade aiohttp to 3.10.6 and yarl to 1.12.1 (#2862)

changes/2780.fix.md, src/ai/backend/manager/api/vfolder.py, src/ai/backend/manager/models/vfolder.py
This is an auto-generated backport PR of #2780 to the 24.03 release.
=> fix: Delete vfolder invitation and permission rows when deleting vfolders (#2780)

changes/2867.fix.md, src/ai/backend/install/context.py, src/ai/backend/install/widgets.py
This is an auto-generated backport PR of #2867 to the 24.03 release.
=> fix: Installer regression after upgrading Textual (#2867)

changes/2848.feature.md, src/ai/backend/manager/models/utils.py, src/ai/backend/manager/scheduler/dispatcher.py, src/ai/backend/manager/scheduler/types.py, tests/manager/BUILD, tests/manager/conftest.py, tests/manager/models/test_dbutils.py, tests/manager/scheduler_utils.py, tests/manager/test_agent_selector.py, tests/manager/test_priority_scheduler.py, tests/manager/test_scheduler.py
This PR refactors the scheduler test cases and implements the priority scheduler.
=> feat: Implement priority scheduler

changes/2615.feature.md, changes/2620.feature.md, src/ai/backend/agent/agent.py, src/ai/backend/agent/docker/agent.py, src/ai/backend/agent/dummy/agent.py, src/ai/backend/agent/kubernetes/utils.py, src/ai/backend/common/docker.py, src/ai/backend/common/exception.py, src/ai/backend/common/msgpack.py, src/ai/backend/common/types.py, src/ai/backend/common/utils.py, src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/api/service.py, src/ai/backend/manager/api/session.py, src/ai/backend/manager/cli/image_impl.py, src/ai/backend/manager/container_registry/base.py, src/ai/backend/manager/container_registry/harbor.py, src/ai/backend/manager/models/container_registry.py, src/ai/backend/manager/models/endpoint.py, src/ai/backend/manager/models/gql.py, src/ai/backend/manager/models/image.py, src/ai/backend/manager/models/kernel.py, src/ai/backend/manager/registry.py, src/ai/backend/manager/scheduler/drf.py, src/ai/backend/manager/scheduler/fifo.py, tests/common/test_docker.py, tests/common/test_msgpack.py, tests/manager/models/test_container_registries.py, tests/manager/models/test_container_registry_nodes.py, tests/manager/scheduler_utils.py
In the existing code, only `MEDIA_TYPE_DOCKER_MANIFEST_LIST` and `MEDIA_TYPE_OCI_INDEX` types were handled in `_scan_tag`, so a runtime error occurred when `MEDIA_TYPE_DOCKER_MANIFEST` type was passed as `content_type`.
However, in `harbor.py`, handling based on `manifest_media_type` is processed by separate functions such as `_process_oci_index` and `_process_docker_v2_multiplatform_image`, so handling for `MEDIA_TYPE_DOCKER_MANIFEST` has been added by extracting these functions with the same signatures.
Adding handling for the `MEDIA_TYPE_DOCKER_MANIFEST` type (`_process_docker_v2_image`) seems not to be specific only to ghcr, so it was added to `base.py`.
=> refactor: Base ContainerRegistry's `scan_tag` and implement `MEDIA_TYPE_DOCKER_MANIFEST` type handling

changes/2815.feature.md, src/ai/backend/manager/container_registry/base.py
This PR adds support for docker image manifest V2 schema1 for legacy system.
(Fix https://github.com/lablup/giftbox/issues/719)
About docker image manifest V2 schema1 refer to below link: 
https://github.com/openshift/docker-distribution/blob/master/docs/spec/manifest-v2-1.md
Manually tested it by following the steps below.
1. Create a private docker registry for testing.
```
❯ docker run -d -p 5000:5000 --restart always --name registry registry:2
```
The registry returns a content type of `application/vnd.docker.distribution.manifest.v1+prettyjws` in the response in the `/manifests` API.
2. Create a fixture file for testing this registry and apply.
```
{
"container_registries": [
{
"id": "abc42a05-4471-41fa-8772-10bf6452c7d9",
"registry_name": "localhost",
"url": "http://localhost:5000", …
```
=> feat: Support docker image manifest v2 schema1 scanning

changes/2621.feature.md, fixtures/manager/example-container-registries-ghcr.json, src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/container_registry/__init__.py, src/ai/backend/manager/container_registry/github.py, src/ai/backend/manager/models/alembic/versions/1d42c726d8a3_migrate_container_registries_from_etcd_to_psql.py, src/ai/backend/manager/models/container_registry.py
Partially fix #2337.
Manually tested it using the following methods.
In this PR, the `cr.backend.ai/stable/python:3.9-ubuntu20.04` image is used as a placeholder for testing.
1. Tag and push the `cr.backend.ai/stable/python` image to your GitHub package for testing.
```
❯ docker tag cr.backend.ai/stable/python:3.9-ubuntu20.04 ghcr.io/<github_username>/python:3.9-ubuntu20.04
❯ docker push ghcr.io/<github_username>/python:3.9-ubuntu20.04
```
2. After filling in the required fields in the fixtures/manager/example-container-registries-ghcr.json file, execute the following command.
```
❯ ./backend.ai mgr fixture populate ./fixtures/manager/example-container-registries-ghcr.json
```
> [!NOTE]  
The `entity_type` should be either "users" or "orgs".
3. Insert the following value into the …
=> feat: Support GitHub Container Registry based on `PostgreSQL`

changes/2622.feature.md, fixtures/manager/example-container-registries-gitlab.json, src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/container_registry/__init__.py, src/ai/backend/manager/container_registry/gitlab.py, src/ai/backend/manager/models/container_registry.py
Partially fix #2337.
Manually tested it using the following methods.
In this PR, the `cr.backend.ai/stable/python:3.9-ubuntu20.04` image is used as a placeholder for testing.
> Note: The example given refers to GitLab Hosted Registry, but it also works in an on-premises environment.
1. Tag and push the `cr.backend.ai/stable/python` image to your GitLab package for testing.
```
❯ docker tag cr.backend.ai/stable/python:3.9-ubuntu20.04 registry.gitlab.com/<gitlab_username>/python:3.9-ubuntu20.04
❯ docker push registry.gitlab.com/<gitlab_username>/python:3.9-ubuntu20.04
```
2. After filling in the required fields in the `fixtures/manager/example-container-registries-gitlab.json` file, execute the following command.
```
❯ ./backend.ai mgr fixture populate …
```
=> feat: Support GitLab Container Registry based on `PostgreSQL`

changes/2623.feature.md, fixtures/manager/example-container-registries-aws-ecr.json, src/ai/backend/common/docker.py, src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/container_registry/__init__.py, src/ai/backend/manager/container_registry/aws_ecr.py, src/ai/backend/manager/models/container_registry.py
Partially fix #2337.
Manually tested it using the following methods.
In this PR, the `cr.backend.ai/stable/python:3.9-ubuntu20.04` image is used as a placeholder for testing.
Create and configure the relevant users and policies appropriately through AWS IAM for testing this PR.
Then, generate the "access key" and store the `access_key` and `secret_access_key` in etcd.
---
1. Tag and push the `cr.backend.ai/stable/python` image to your AWS ECR package for testing.
```
❯ docker tag cr.backend.ai/stable/python:3.9-ubuntu20.04 public.ecr.aws/<registry_alias>/python:3.9-ubuntu20.04
❯ docker push public.ecr.aws/<registry_alias>/python:3.9-ubuntu20.04
```
2. After filling in the required fields in the `fixtures/manager/example-container-registries-aws-ecr.json` file, execute the following …
=> feat: Support AWS ECR Public Container Registry based on `PostgreSQL`

changes/2665.feature.md, fixtures/manager/example-container-registries-local.json, src/ai/backend/agent/docker/agent.py, src/ai/backend/manager/api/session.py, src/ai/backend/manager/cli/etcd.py, src/ai/backend/manager/cli/image.py, src/ai/backend/manager/cli/image_impl.py, src/ai/backend/manager/container_registry/base.py, src/ai/backend/manager/models/image.py
Partially fix [#411](https://github.com/lablup/backend.ai/issues/411), ref: https://github.com/lablup/backend.ai/pull/1097
This PR removes the existing image rescan code that uses the `--local` flag and instead uses a `Local` type container registry record to reuse existing code paths.
Manually tested according to the following procedure.
1. Create a `Dockerfile` with the following content.
(Copy-pasted from https://github.com/lablup/backend.ai/pull/1097#issuecomment-1442909515)
```dockerfile
FROM python:3.11
RUN python3.11 -m pip install ipython ipykernel
RUN python3.11 -m ipykernel install --display-name "Python 3.11 on Backend.AI" && \
cat /usr/local/share/jupyter/kernels/python3/kernel.json
LABEL ai.backend.kernelspec=1 \
ai.backend.features="uid-match batch query" \ …
```
=> feat: Replace image rescan command's `--local` flag with the `local` type ContainerRegistry record

src/ai/backend/common/docker.py, src/ai/backend/common/utils.py, src/ai/backend/manager/container_registry/base.py, src/ai/backend/manager/models/image.py, tests/common/test_docker.py
In the existing code, an `InvalidImageName` exception is raised when the image name is empty. I think this can be confusing when using the container registry from the user's perspective.
When the project is `username/python` in a GitLab-hosted registry, for example, only images with names like `registry.gitlab.com/username/python/python_img` are allowed, and images like `registry.gitlab.com/username/python` cannot be scanned because the image name is empty.
This PR updates the system to allow scanning of images when the image name is empty.
The empty name images can be used for operations such as session creation and commit just like other images.
If we allow the empty image name, image name parsing logic in the frontend that uses the `Images` GQL may need to be modified accordingly.
--- …
=> feat: Allow empty image name

python.lock, requirements.txt
This PR is a minor follow-up to #2862.
* aio-libs/aiohttp#9326
- This fix makes aiohttp's internal timeout handling mechanism to be consistent with async-timeout and `asyncio.timeout()` when there are nested task groups since Python 3.11.
- async-timeout has this fix as of 4.0.3 and we have been already using it while most codes are migrated to use `asyncio.timeout()`.
* aio-libs/aiohttp#9309
- This potentially may affect authentication handling in our WSProxy.
- According to [aio-libs/aiohttp#9360](https://github.com/aio-libs/aiohttp/issues/9360), this was a regression in 3.10.6.
* aio-libs/aiohttp#9171
* aio-libs/aiohttp#9301
=> deps: Upgrade aiohttp (3.10.6 -> 3.10.8) along with yarl (1.12.1 -> 1.13.1)

changes/2378.fix.md, scripts/install-dev.sh
This is an auto-generated backport PR of #2378 to the 23.09 release.
=> chore(install-dev): block until DB container stabilizes (#2378)

src/ai/backend/manager/models/alembic/env.py
This PR removes the extra exception context to check if there is no event loop running when executing alembic migrations, which makes it often confusing whether the migration failure is from the event loop handling mistake or actual migration scripts.
Before:
```
INFO  [alembic.runtime.migration] Running upgrade 20218a73401b -> 1d42c726d8a3, Migrate container registry config storage from `Etcd` to `PostgreSQL`
...
RuntimeError: no running event loop
During handling of the above exception, another exception occurred:
...
asyncpg.exceptions.NotNullViolationError: column "registry_id" of relation "images" contains null values
```
After:
```
INFO  [alembic.runtime.migration] Running upgrade 20218a73401b -> 1d42c726d8a3, …
```
=> fix: Prevent misinterpreting alembic migration errors as event loop errors

src/ai/backend/manager/models/alembic/env.py
This is an auto-generated backport PR of #2879 to the 24.03 release.
=> fix: Prevent misinterpreting alembic migration errors as event loop errors (#2879)

.gitignore, src/ai/backend/manager/models/alembic/versions/1d42c726d8a3_migrate_container_registries_from_etcd_to_psql.py
This is a follow-up fix of #1917 to prevent human mistakes.
When we try the alemibc migration multiple times, #1917's initial implementation has overwritten the backup with empty data as the etcd key is already removed.
=> fix: For repeated trials, add timestamp to etcd backups to prevent overwriting with empty data

changes/2884.fix.md, src/ai/backend/manager/models/session.py, src/ai/backend/manager/registry.py
follow-up #2327 #2311 
Manager does not call batch execution after batch-type session starts because the caller part is missing.
=> fix: Missing batch execution call after session starts

.github/workflows/ci.yml
The release process occurs on tag push events.
That's why github.ref_name is tag name, and tag name also contains the patch version, like 24.09.0, unlike the release branch.
So we modify it to make sure that the first half of the tag name is the same as the release branch name.
=> ci: Make sure the first half of the tag is the same as the latest release

.github/workflows/ci.yml
This is an auto-generated backport PR of #2885 to the 24.03 release.
=> ci: Make sure the first half of the tag is the same as the latest release (#2885)

src/ai/backend/manager/models/domain.py, src/ai/backend/manager/models/group.py, src/ai/backend/manager/models/keypair.py, src/ai/backend/manager/models/rbac/__init__.py, src/ai/backend/manager/models/rbac/exceptions.py, src/ai/backend/manager/models/scaling_group.py, src/ai/backend/manager/models/session.py, src/ai/backend/manager/models/storage.py, src/ai/backend/manager/models/vfolder.py
=> chore: Refactor RBAC interface for better readability

changes/2894.fix.md, src/ai/backend/agent/docker/agent.py
Resolves #2893.
This PR prevents the console from being flooded with duplicate error `Image name ... does not conform to Backend.AI's image naming rule` log messages.
Error log messages will now be printed only once, not being outputted on each image rescan cycle.
=> fix: Invalid image format log spam in Agent

changes/2894.fix.md, src/ai/backend/agent/docker/agent.py
This is an auto-generated backport PR of #2894 to the 24.03 release.
=> fix: Invalid image format log spam in Agent (#2894)

changes/2896.fix.md, src/ai/backend/manager/registry.py
Follow-up of #2707.
Fixed wrong logic generating `raw_configs`.
=> fix: Wrong creation of raw_configs in `_create_kernels_in_one_agent`

src/ai/backend/manager/models/session.py
For better readability, change the `determine_session_status()` function
=> chore: Refactor session status determine function

changes/2899.fix.md, src/ai/backend/manager/models/container_registry.py
This PR fixes the issue where all ContainerRegistryNodes in the ContainerRegistryNode API were returning the same ID.
Tested by manually.
=> fix: Assign valid value to `id` field in `ContainerRegistryNode` GQL schema query resolver

changes/2900.fix.md, src/ai/backend/storage/vast/__init__.py, src/ai/backend/storage/vast/vastdata_client.py
Let the vastdata storage backend update quota rather than raise error when quota exists
=> fix: Update vast quota rather than raise error when quota exists

changes/2908.feature.md, src/ai/backend/manager/models/container_registry.py
follows https://github.com/lablup/backend.ai/pull/1917
By using `id` instead of `registry_name`, I have resolved the issue where the `id` values returned in the `ContainerRegistry` API were all the same.
=> fix: Use a valid value for the `id` field in the GQL schema query resolver for `ContainerRegistry`.

changes/2911.fix.md, src/ai/backend/storage/vast/__init__.py, src/ai/backend/storage/vast/config.py, src/ai/backend/storage/vast/vastdata_client.py
1. Fix calculation of expiration datetime of VAST auth token by comparing current time with token's `exp` time.
2. Change config name from `use_auth_token` to `force_login`
3. Replace `dateutil.tz.tzutc()` with `datetime.timezone.utc`
=> fix: Calculate correct expiration time of VAST auth token

changes/2911.fix.md, src/ai/backend/storage/vast/__init__.py, src/ai/backend/storage/vast/config.py, src/ai/backend/storage/vast/vastdata_client.py
This is an auto-generated backport PR of #2911 to the 24.03 release.
=> fix: Calculate correct expiration time of VAST auth token (#2911)

src/ai/backend/common/types.py
Add `ai.backend.common.types.PromMetric` and `ai.backend.common.types.PromMetricGroup`.
[Doc: Prometheus exposition formats](https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md) shows the return schema of metric APIs.
This is an example format of metrics.
```text
metric_name{label_name=label_value} metric_value # Each PromMetric object creates one line.
metric_name{label_name=label_value} metric_value
...
```
A `PromMetricGroup` object creates one metric format and `PromMetric` object represents each metric value line of metric formats.
=> chore: Add metric type for Prometheus

.github/workflows/backport.yml
If it was merged into main but committed directly (not through a pr), the backport workflow will not work.
In this case, the workflow worked fine, so modify the logic to mark it as successful.
=> ci: Let backport workflow succeed with vanilla commits

src/ai/backend/storage/abc.py, src/ai/backend/storage/context.py, src/ai/backend/storage/gpfs/__init__.py, src/ai/backend/storage/vast/__init__.py, src/ai/backend/storage/weka/__init__.py, tests/storage-proxy/conftest.py
Change `event_dispathcer` to `event_dispatcher`
=> chore: fix typo in storage backend

src/ai/backend/manager/models/__init__.py, src/ai/backend/manager/models/health.py
Main usage of `ai.backend.manager.models.health` module is treating manager status.
It has functions related to DB connection status for now.
=> feat: Introduce models.health module that treats manager status

changes/2566.feature.md, src/ai/backend/manager/api/manager.py, src/ai/backend/manager/config.py, src/ai/backend/manager/models/health.py
Managers report DB connection info to Redis stat DB for every specified interval.
Able to set the interval and lifetime of reports.
Default value of the interval is 30 sec.
Default value of the lifetime of reports is null, which means infinite.
----
📚 Documentation preview 📚: https://sorna--2566.org.readthedocs.build/en/2566/
----
📚 Documentation preview 📚: https://sorna-ko--2566.org.readthedocs.build/ko/2566/
=> feat: Add manager status report bgtask

changes/2567.feature.md, src/ai/backend/manager/api/manager.py, src/ai/backend/manager/models/health.py, src/ai/backend/manager/public_api/health.py, src/ai/backend/manager/server.py
resolves #2522
`GET /manager/prom` API returns Prometheus-compatible text.
Here is an example response.
```
HELP sqlalchemy_total_connection The number of total connections in SQLAlchemy connection pool.
TYPE sqlalchemy_total_connection gauge
sqlalchemy_total_connection{mgr_id="i-SH-macbook.local:51809"} 1
HELP sqlalchemy_open_connection The number of open connections in SQLAlchemy connection pool.
TYPE sqlalchemy_open_connection gauge
sqlalchemy_open_connection{mgr_id="i-SH-macbook.local:51809"} 1
HELP sqlalchemy_closed_connection The number of closed connections in SQLAlchemy connection pool.
TYPE sqlalchemy_closed_connection gauge
sqlalchemy_closed_connection{mgr_id="i-SH-macbook.local:51809"} 0
HELP redis_connection The number of connections in Redis Client's connection pool.
TYPE …
```
=> feat: Add Prometheus-compatible manager stat API

changes/2052.doc.md, docs/install/install-from-package/install-manager.rst, docs/install/install-from-package/prepare-cache-service.rst, docs/install/install-from-package/prepare-config-service.rst, docs/install/install-from-package/prepare-database.rst
To add the manager's RPC client certificate entry to the guide.
Following the merged PR #887 , manager.toml config file's rpc-auth-manager-keypair filed is always required, even when no agents require authentication and encryption.
As a result, add the manager's RPC client certificate entry to the guide.
fix https://github.com/lablup/backend.ai/issues/2044
----
📚 Documentation preview 📚: https://sorna--2052.org.readthedocs.build/en/2052/
----
📚 Documentation preview 📚: https://sorna-ko--2052.org.readthedocs.build/ko/2052/
=> docs: add the manager's RPC client certificate entry to the guide

changes/2927.fix.md, src/ai/backend/manager/models/gql_models/group.py
=> fix: Wrong GQL ordering field spec parser

changes/2927.fix.md, src/ai/backend/manager/models/gql_models/group.py
This is an auto-generated backport PR of #2927 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--2928.org.readthedocs.build/en/2928/
----
📚 Documentation preview 📚: https://sorna-ko--2928.org.readthedocs.build/ko/2928/
=> fix: Wrong GQL ordering field spec parser (#2927)

src/ai/backend/storage/dellemc/config.py
=> fix: allow `ifs_path` config of PowerScale to not exists

.github/workflows/timeline-check.yml
This is an backport PR of https://github.com/lablup/backend.ai/pull/2265 to the 24.03 release.
=> ci: Explicitly adding permissions because the default permissions have changed (#2265)

src/ai/backend/manager/models/domain.py, src/ai/backend/manager/models/group.py, src/ai/backend/manager/models/rbac/permission_defs.py
=> chore: Add Domain & Project RBAC apis

changes/2934.feature.md, src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/models/base.py, src/ai/backend/manager/models/domain.py, src/ai/backend/manager/models/gql.py, src/ai/backend/manager/models/gql_models/base.py, src/ai/backend/manager/models/gql_models/domain.py, src/ai/backend/manager/models/gql_models/scaling_group.py, src/ai/backend/manager/models/rbac/__init__.py, src/ai/backend/manager/models/scaling_group.py
Add GQL Relay domain query schema
```graphql
query DomainQuery {
domain_nodes(
order: "created_at"
) {
edges {
node {
id
name
allowed_vfolder_hosts
allowed_docker_registries
scaling_groups {
edges {
node {
name
is_active
is_public
created_at
}
}
}
}
}
}
}
```
----
📚 Documentation preview 📚: https://sorna--2934.org.readthedocs.build/en/2934/
----
📚 Documentation preview 📚: https://sorna-ko--2934.org.readthedocs.build/ko/2934/
=> feat: Add Domain GQL schema and resolver

changes/2946.fix.md, src/ai/backend/manager/models/utils.py
`ExtendedAsyncSAEngine` begins readonly sessions by setting `postgres_readonly` flag of a given connection and it causes an error when any other generic transactions in the same connection try to insert or update.
```
<'asyncpg.exceptions.ReadOnlySQLTransactionError'>: cannot execute UPDATE in a read-only transaction
```
Let's set the `postgres_readonly` flag to false when begin generic sessions.
=> fix: Set readonly flag to false when begin new generic txn

changes/2946.fix.md, src/ai/backend/manager/models/utils.py
This is an auto-generated backport PR of #2946 to the 24.09 release.
=> fix: Set readonly flag to false when begin new generic txn (#2946)

changes/2949.fix.md, src/ai/backend/manager/models/alembic/versions/1d42c726d8a3_migrate_container_registries_from_etcd_to_psql.py, src/ai/backend/manager/models/alembic/versions/e9e574a6e22d_add_extra_column_to_container_registrys.py
Follow-up of https://github.com/lablup/backend.ai/pull/1917.
=> fix: Wrong container registry migration script

changes/2898.fix.md, src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/models/container_registry.py, src/ai/backend/manager/models/gql_relay.py
This is an auto-generated backport PR of #2898 to the 24.09 release.
=> fix: Disallow `None` id encoding in `AsyncNode.to_global_id()` (#2898)

changes/2579.fix.md, src/ai/backend/common/bgtask.py
This is an auto-generated backport PR of #2579 to the 24.09 release.
=> fix: Missing notification of bgtask cancellation or failure when shutting down the server (#2579)

changes/2962.fix.md, src/ai/backend/common/types.py
=> fix: Handle IndexError when parse BinarySize

changes/2962.fix.md, src/ai/backend/common/types.py
This is an auto-generated backport PR of #2962 to the 24.03 release.
=> fix: Handle IndexError when parse BinarySize (#2962)

changes/2836.feature.md, src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/api/session.py, src/ai/backend/manager/models/gql.py, src/ai/backend/manager/models/gql_models/session.py, src/ai/backend/manager/models/session.py
```gql
mutation CheckandtransitSession {
check_and_transit_session_status(
input: {ids: ["SESSION-ID",]}
) {
sessions {
id
row_id
name
status
status_history
occupied_slots
}
}
}
```
```json
{
"data": {
"check_and_transit_session_status": {
"item": [
{
"id": "NODE-ID",
"row_id": "SESSION-ID",
"name": "SESSION-NAME",
"status": "RUNNING",
"status_history": "{\"PENDING\": \"2024-09-14T03:35:54.218019+00:00\", \"RUNNING\": \"2024-09-14T03:36:05.431593+00:00\", \"PREPARING\": \"2024-09-14T03:35:55.013239+00:00\", \"SCHEDULED\": \"2024-09-14T03:35:54.996003+00:00\"}",
"occupied_slots": "{\"cpu\": \"90\", \"mem\": \"30198988800\", \"cuda.device\": \"0\"}"
}
]
}
}
}
```
----
📚 Documentation preview 📚: https://sorna--2836.org.readthedocs.build/en/2836/
----
📚 …
=> feat: Add session status checker GQL mutation

.github/workflows/backport.yml
Follow-up #2508 
The part calling labelinfo has been failing due to unauthorized permissions, but was not being tracked because it was not marked as fail.
Information about labels that may be essential for merging backport pr's, such as skip:changelog, was not being reflected, affecting backport automation.
Authorize via github.token authentication.
=> ci: Fix labeling of backport PRs due to missing github token

changes/2961.fix.md, src/ai/backend/storage/gpfs/gpfs_client.py
This is an auto-generated backport PR of #2961 to the 24.09 release.
=> fix: Keep polling when GPFS job is running (#2961)

changes/2982.fix.md, src/ai/backend/manager/scheduler/dispatcher.py
`manager.models.agent.recalc_agent_resource_occupancy()` accepts an SQLAlchemy AsyncSession type object rather than SQLAlchemy AsyncConnection type object.
This causes error since the result of AsyncSession.scalars() and AsyncConnection.scalars() are different
=> fix: Wrong parameter when call 'recalc_agent_resource_occupancy()'

changes/2986.fix.md, src/ai/backend/manager/models/alembic/versions/1d42c726d8a3_migrate_container_registries_from_etcd_to_psql.py
Hotfix of https://github.com/lablup/backend.ai/pull/1917 migration script.
Remove the incorrect length restriction applied to the password field in the existing migration script.
=> fix: Wrong `password` limit in container registry migration script

changes/2989.fix.md, src/ai/backend/manager/models/image.py
This is an auto-generated backport PR of #2989 to the 24.09 release.
=> fix: architecture condition not applied when querying image rows (#2989)

changes/2993.fix.md, src/ai/backend/manager/models/kernel.py
Currently `KernelRow.image_row` requires a join on `kernels.image` and `images.name` column which is not unique.
e.g. multiarch images may have multiple records with the same name value and in different architecture values.
Let's apply a strict join condition by check `architecture` column
=> fix: Strengthen join condition between kernels and images

changes/2993.fix.md, src/ai/backend/manager/models/kernel.py
This is an auto-generated backport PR of #2993 to the 24.09 release.
=> fix: Strengthen join condition between kernels and images (#2993)

.gitignore, configs/agent/sample-dummy-config.toml, src/ai/backend/agent/dummy/config.py, src/ai/backend/agent/dummy/intrinsic.py, tests/agent/test_resources.py
follow-up #2253 
- Allow extra keys dummy agent configs
- Change `core-indexes` to `num-cores` for easy config setup
- Update `.gitignore` to exclude any dummy config toml files
=> chore: Allow extra keys dummy agent configs

changes/3002.fix.md, src/ai/backend/manager/models/gql_models/image.py
This is an auto-generated backport PR of #3002 to the 24.09 release.
=> fix: Wrong field reference in `ImageNode` resolver (#3002)

changes/3004.fix.md, src/ai/backend/manager/container_registry/harbor.py
Follow-up of #1917.
Since the project is now stored as a separate field, the existing untag logic also needs to be updated.
=> fix: Obsolete logic of `untag()` of `HarborRegistry_v2`

changes/3004.fix.md, src/ai/backend/manager/container_registry/harbor.py
This is an auto-generated backport PR of #3004 to the 24.09 release.
=> fix: Obsolete logic of `untag()` of `HarborRegistry_v2` (#3004)

changes/3015.fix.md, src/ai/backend/client/cli/app.py
The following command currently raises the following error due to an issue with the filtering logic.
```
❯ ./backend.ai apps pysession sshd ttyd
✘ TypeError: filter expected 2 arguments, got 1
*** Traceback ***
File "/Users/jopemachine/Desktop/backend.ai/src/ai/backend/client/cli/app.py", line 370, in apps
asyncio_run(print_arguments())
File "/Users/jopemachine/.pyenv/versions/3.12.6/lib/python3.12/asyncio/runners.py", line 194, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "/Users/jopemachine/.pyenv/versions/3.12.6/lib/python3.12/asyncio/runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/jopemachine/.pyenv/versions/3.12.6/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
return …
```
=> fix: `backend.ai apps` command's faulty argument handling logic

changes/3015.fix.md, src/ai/backend/client/cli/app.py
=> fix: `backend.ai apps` command's faulty argument handling logic (#3015)

changes/3013.fix.md, src/ai/backend/manager/models/__init__.py, src/ai/backend/manager/models/base.py, src/ai/backend/manager/models/gql.py, src/ai/backend/manager/models/gql_models/agent.py
Fix regression of #2873.
Currently, attempting to use Agent GQL results in the following error.
It appears that this is due to the file location change of the Agent model not being handled properly in #2873.
```
2024-11-02 21:29:11.033 ERROR ai.backend.manager.api.admin [32559] ADMIN.GQL Exception: {'message': "module 'ai.backend.manager.models' has no attribute 'Agent'", 'locations': [{'line': 2, 'column': 3}], 'path': ['agent']}
2024-11-02 21:29:11.038 DEBUG ai.backend.manager.api.admin [32559] Traceback (most recent call last):
File "/Users/jopemachine/Desktop/backend.ai/dist/export/python/virtualenvs/python-default/3.12.6/lib/python3.12/site-packages/graphql/execution/execute.py", line 530, in await_result
return_type, field_nodes, info, path, await result
^^^^^^^^^^^^
File …
```
=> fix: `Agent` GQL Regression error

changes/3010.feature.md, configs/webserver/halfstack.conf, configs/webserver/sample.conf
This PR blocks the pipeline menu by default in both sample and halfstack configurations of webserver component which is copied during installation, since FastTrack is opened for enterprise only, and should not be exposed in open source installation.
**Checklist:**
=> feat: add pipeline menu to blocklist in webserver configs

changes/3010.feature.md, configs/webserver/halfstack.conf, configs/webserver/sample.conf
This is an auto-generated backport PR of #3010 to the 24.09 release.
=> feat: add pipeline menu to blocklist in webserver configs (#3010)

changes/3023.fix.md, src/ai/backend/storage/vast/__init__.py, src/ai/backend/storage/vast/config.py, src/ai/backend/storage/vast/vastdata_client.py
- Check Vast data quota with a given name exists before creating quota 
- Change default value of `force_login` config to true
=> fix: Check Vast data quota with the given quota name exists

changes/2997.fix.md, src/ai/backend/common/docker.py, src/ai/backend/manager/api/session.py, src/ai/backend/manager/container_registry/harbor.py
Modifies the existing incorrect code to allow committing and uploading sessions to different types of registries and other projects.
----
📚 Documentation preview 📚: https://sorna--2997.org.readthedocs.build/en/2997/
----
📚 Documentation preview 📚: https://sorna-ko--2997.org.readthedocs.build/ko/2997/
=> fix: customized image not pushed when target registry diverges

changes/3032.fix.md, src/ai/backend/manager/registry.py
This is an auto-generated backport PR of #3032 to the 24.03 release.
=> fix: Update `get_container_logs()` method to handle unassigned kernels (#3032)

changes/.fix.md, src/ai/backend/manager/models/session.py
This PR adds a new positional parameter `max_load_count` to `SessionRow.list_sessions()` class method, to control the `SessionRow. match_sessions()`'s `max_matches` positional parameter. By setting the default value of `max_load_count` to `None`, `update_appproxy_endpoint_routes()` will report full set of available routes to AppProxy endpoint.
=> fix: model service traffic not distributed equally

src/ai/backend/manager/models/base.py
=> chore: Allow kwargs only for batch-load function

.github/workflows/assign-pr-number.yml, changes/3054.fix.md, src/ai/backend/agent/BUILD, src/ai/backend/manager/BUILD, src/ai/backend/storage/BUILD, src/ai/backend/web/BUILD
This is an auto-generated backport PR of #3054 to the 24.09 release.
=> fix: Include missing legacy logging module in the pex (#3054)

changes/3042.fix.md, src/ai/backend/manager/models/kernel.py
Currently, when using `ComputeContainer` GQL, the following error occurs.
```
2024-11-07 13:57:19.382 ERROR ai.backend.manager.api.admin [4278] ADMIN.GQL Exception: {'message': "greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'locations': [{'line': 2, 'column': 3}], 'path': ['compute_container']}
2024-11-07 13:57:19.397 DEBUG ai.backend.manager.api.admin [4278] Traceback (most recent call last):
File "/Users/jopemachine/Desktop/backend.ai/dist/export/python/virtualenvs/python-default/3.12.6/lib/python3.12/site-packages/graphql/execution/execute.py", line 530, in await_result
return_type, field_nodes, info, path, await result
^^^^^^^^^^^^
File …
```
=> fix: Broken `ComputeContainer` GQL

changes/3042.fix.md, src/ai/backend/manager/models/kernel.py
This is an auto-generated backport PR of #3042 to the 24.09 release.
=> fix: Broken `ComputeContainer` GQL (#3042)

changes/3061.fix.md, src/ai/backend/manager/models/vfolder.py
resolves #3041 
Update vfolder name before delete-forever.
The deletion date time format is `%Y-%m-%dT%HH%MM%SS%z`, update the name to `{ORIGINAL}_deleted_{DATE-TIME}`.
=> fix: Change vfolder name when deleted to allow reusing the name

changes/3075.fix.md, src/ai/backend/wsproxy/proxy/backend/http.py, src/ai/backend/wsproxy/proxy/backend/tcp.py
=> fix: invalid `selected_route` calculation logic

changes/3075.fix.md, src/ai/backend/wsproxy/proxy/backend/http.py, src/ai/backend/wsproxy/proxy/backend/tcp.py
This is an auto-generated backport PR of #3075 to the 24.03 release.
=> fix: invalid `selected_route` calculation logic (#3075)

changes/3078.fix.md, src/ai/backend/manager/models/kernel.py
Follow-up to #3042.
> [!NOTE]
>  The two codes below do not have the same meaning.
> 
> ```py
> ...
>             .options(
>                 noload("*"),
>                 selectinload(KernelRow.group_row),
>                 selectinload(KernelRow.user_row),
>                 selectinload(KernelRow.image_row),
>             )
> ```
> ```py
> ...
>             .options(
>                 noload("*"),
>                 selectinload(
>                     KernelRow.group_row,
>                     KernelRow.user_row,
>                     KernelRow.image_row,
>                 ),
>             )
> ```
Since our code intends to load each relationship individually, the current code causes the following error:
```
graphql.error.graphql_error.GraphQLError: Attribute "KernelRow.user_row" does …
```
=> fix: Broken `ComputeContainer.batch_load_detail` due to misuse of `selectinload`

changes/3078.fix.md, src/ai/backend/manager/models/kernel.py
This is an auto-generated backport PR of #3078 to the 24.03 release.
=> fix: Broken `ComputeContainer.batch_load_detail` due to misuse of `selectinload` (#3078)

changes/3046.fix.md, src/ai/backend/manager/models/gql.py, src/ai/backend/manager/models/kernel.py
When using `LegacyComputeSession` GQL in the main branch, the following error occurs:
```
2024-11-07 17:53:22.275 ERROR ai.backend.manager.api.admin [61844] ADMIN.GQL Exception: {'message': "'bai-serve-robert64-7175c9c1-79d8-41bf-b8d9-ddc938422486'", 'locations': [{'line': 2, 'column': 5}], 'path': ['legacy_compute_session']}
2024-11-07 17:53:22.279 DEBUG ai.backend.manager.api.admin [61844] Traceback (most recent call last):
File "/Users/jopemachine/Desktop/backend.ai/dist/export/python/virtualenvs/python-default/3.12.6/lib/python3.12/site-packages/graphql/execution/execute.py", line 530, in await_result
return_type, field_nodes, info, path, await result
^^^^^^^^^^^^
File "/Users/jopemachine/Desktop/backend.ai/src/ai/backend/manager/models/base.py", line 1060, in wrapped
return await …
```
=> fix: Regression of `LegacyComputeSession` GQL

changes/3085.fix.md, src/ai/backend/agent/agent.py, src/ai/backend/common/events.py, src/ai/backend/manager/registry.py
Currently, the `status_info` column in the sessions table is being set to the same value regardless of batch execution result. Only the `result` column reflects the result as updating the value to "SUCCESS" or "FAILURE"
Let's update the `status_info` column to the reason value of Session result events.
=> fix: session `status_info` not reflecting batch failures

changes/3085.fix.md, src/ai/backend/agent/agent.py, src/ai/backend/common/events.py, src/ai/backend/manager/registry.py
This is an auto-generated backport PR of #3085 to the 24.09 release.
=> fix: session `status_info` not reflecting batch failures (#3085)

.github/workflows/assign-pr-number.yml, .github/workflows/backport.yml, .github/workflows/update-api-schema.yml
After #3083, an error like https://github.com/lablup/backend.ai/actions/runs/11811508600/job/32905198275?pr=3047 occurs.
Even if you set the author of git commit, it is treated separately from the commiter, so you need to explicitly set the commiter.
=> ci: Setting up git commiter

changes/3101.fix.md, src/ai/backend/agent/docker/kernel.py, src/ai/backend/agent/docker/utils.py
This is an auto-generated backport PR of #3101 to the 24.03 release.
=> fix: Invalid use of `subproceess.Popen` API with wrapped file objects (#3101)

src/ai/backend/agent/docker/utils.py, src/ai/backend/agent/kubernetes/utils.py
This is an auto-generated backport PR of #3106 to the 24.09 release.
=> fix: Follow-up of #3101 (#3106)

src/ai/backend/common/bgtask.py
This is a partial backport of #1973 to update the internal structure of the `common.bgtask` module, which I expect to fix CI hang issues.
=> backport: Refactoring internal structure of the common.bgtask module

changes/2647.breaking.md
Update the news fragmen of #2647 to provide more context about new `PREPARED` status
=> chore: better changelog of 2647

changes/3011.fix.md, src/ai/backend/manager/models/gql_models/agent.py, src/ai/backend/manager/models/kernel.py
```graphql
query AgentList {
agent_list(limit: 10, offset: 0) {
items {
id
status
compute_containers(status: "RUNNING") {
status
kernel_id
}
}
total_count
}
}
```
=> fix: Add missing resolver of `Agent.compute_containers` GraphQL field

changes/2954.feature.md, src/ai/backend/manager/models/endpoint.py
follows https://github.com/lablup/backend.ai/pull/2805
This PR adds `open_to_public` to filter and order of endpoint relay API. 
**Checklist:**
=> feat: Add `open_to_public` to filter and order of endpoint relay API

changes/3124.feature.md, configs/webserver/sample.conf, src/ai/backend/web/config.py, src/ai/backend/web/templates/config.toml.j2, src/ai/backend/web/templates/config_ini.toml.j2
related PR: https://app.graphite.dev/github/pr/lablup/backend.ai-webui/3124
This PR resolves [#3056](https://github.com/lablup/backend.ai/issues/3056)
Add an option whether to display all images regardless of installation.
- Added `show_non_installed_images` option to `sample.conf`.
- Updated `config.py` to process the new option.
- Modified `config.toml.j2` and `config_ini.toml.j2` templates to incorporate the new option.
1. Go to `configs/webserver/sample.conf` and set `show_non_installed_images` to true or false.
2. Restart the webserver.
3. Verify that the non-installed images are visible in Session launcher page.
---
- Demonstrate the flow of …
=> feat: Add `show_non_installed_images` config on webserver

changes/3124.feature.md, configs/webserver/sample.conf, src/ai/backend/web/config.py, src/ai/backend/web/templates/config.toml.j2, src/ai/backend/web/templates/config_ini.toml.j2
This is an auto-generated backport PR of #3124 to the 24.09 release.
=> feat: Add `show_non_installed_images` config on webserver (#3124)

changes/2614.feature.md, changes/2614.fix.md, src/ai/backend/client/cli/session/execute.py, src/ai/backend/client/cli/session/lifecycle.py, src/ai/backend/manager/api/session.py
related to 
- https://github.com/lablup/giftbox/issues/704
- https://github.com/lablup/backend.ai-webui/pull/2599
`hide-agents` configuration disallow regular users to get info of agents. When it is set to false, regular users should be allowed to get agent info and assign agents when creating compute sessions.
**Checklist:**
----
📚 Documentation preview 📚: https://sorna--2614.org.readthedocs.build/en/2614/
----
📚 Documentation preview 📚: https://sorna-ko--2614.org.readthedocs.build/ko/2614/
----
📚 Documentation preview 📚: https://sorna--2614.org.readthedocs.build/en/2614/
----
📚 Documentation preview 📚: https://sorna-ko--2614.org.readthedocs.build/ko/2614/
=> fix: Allow regular users to assign agent manually when creating sessions

changes/3063.enhance.md, src/ai/backend/common/events.py, src/ai/backend/manager/models/vfolder.py, src/ai/backend/manager/registry.py, src/ai/backend/storage/api/manager.py
resolves #3060
```mermaid
sequenceDiagram
participant Client
participant Manager
participant StorageProxy
participant FileSystem
Client->>Manager: Request VFolder deletion
Manager->>Manager: Update VFolder status to "DELETE-ONGOING"
Manager->>Client: Response
activate Manager
Note right of Manager: Spawn async task
Manager->>StorageProxy: HTTP Request
StorageProxy->>FileSystem: Delete tree
FileSystem->>FileSystem: Long term job
FileSystem->>StorageProxy: Finish
StorageProxy->>Manager: HTTP 204 Response
alt Deletion Success
Manager->>Manager: Update VFolder status to "DELETE-COMPLETE"
else
Manager->>Manager: Update VFolder status to "DELETE-ERROR"
end
deactivate Manager
```
```mermaid
sequenceDiagram
participant Client
participant Manager
participant StorageProxy
participant FileSystem …
```
=> refactor: Convert VFolder deletion from blocking response to event-driven pattern

changes/3114.breaking.md, docs/client/cli/sessions.rst, docs/dev/adding-kernels.rst, docs/locales/ko/LC_MESSAGES/client/cli/sessions.po, docs/locales/ko/LC_MESSAGES/client/func/session.po, docs/locales/ko/LC_MESSAGES/dev/adding-kernels.po, src/ai/backend/agent/server.py, src/ai/backend/client/cli/admin/session.py, src/ai/backend/client/cli/session/lifecycle.py, src/ai/backend/client/func/session.py, src/ai/backend/manager/models/kernel.py, src/ai/backend/manager/models/session.py, src/ai/backend/manager/registry.py, src/ai/backend/manager/scheduler/dispatcher.py
- Added new `CREATING` session(and kernel) status to represent the container creation phase
- Modified the meaning of existing `PREPARING` status to specifically represent pre-container preparation phases
- Updated status transition logic to accommodate new state
Previously, the `PREPARING` status was overloaded to represent both the pre-container preparation phase and the container creation phase. This made it difficult to:
- Track exactly where a session was in its lifecycle
- Debug issues specific to container creation
This change provides clearer visibility into session lifecycle stages, enabling:
- Better debugging capabilities
- Clearer session status tracking for users
- docstrings in public interfaces and type …
=> feat: Add CREATING status to compute session and kernel

changes/3128.feature.md, src/ai/backend/manager/registry.py
=> feat: Allow destruction of PULLING sessions

changes/2985.fix.md, src/ai/backend/common/validators.py, src/ai/backend/manager/api/session.py, src/ai/backend/manager/models/gql_models/session.py
This is an auto-generated backport PR of #2985 to the 24.09 release.
=> fix: Allow compute session mutation without the priority input field (#2985)

changes/3137.fix.md, src/ai/backend/manager/api/vfolder.py
resolves https://github.com/lablup/giftbox/issues/773
----
📚 Documentation preview 📚: https://sorna--3137.org.readthedocs.build/en/3137/
----
📚 Documentation preview 📚: https://sorna-ko--3137.org.readthedocs.build/ko/3137/
=> fix: Allow admins to delete other user's vfolders

changes/3137.fix.md, src/ai/backend/manager/api/vfolder.py
This is a backport PR of https://github.com/lablup/backend.ai/pull/3137 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3160.org.readthedocs.build/en/3160/
----
📚 Documentation preview 📚: https://sorna-ko--3160.org.readthedocs.build/ko/3160/
=> fix: Allow admins to delete other user's vfolders (#3137)

changes/3045.fix.md, src/ai/backend/manager/models/gql.py, src/ai/backend/manager/models/gql_models/agent.py
When using the `AgentSummary` GQL query in the main branch, the following error occurs.
```
{
"data": {
"agent_summary": null
},
"errors": [
{
"message": "Agent.batch_load() got an unexpected keyword argument 'scaling_group'",
"locations": [
{
"line": 2,
"column": 5
}
],
"path": [
"agent_summary"
]
}
]
}
```
This PR fixes the above error and additionally resolves several type errors.
----
📚 Documentation preview 📚: https://sorna--3045.org.readthedocs.build/en/3045/
----
📚 Documentation preview 📚: https://sorna-ko--3045.org.readthedocs.build/ko/3045/
=> fix: Regression of `AgentSummary` GQL resolver

changes/3031.fix.md, src/ai/backend/common/types.py, src/ai/backend/storage/server.py
Let's mask the password when outputting the Redis config.
=> fix: Prevent redis password from being logged

MIGRATION.md
This is an auto-generated backport PR of #3096 to the 24.09 release.
----
📚 Documentation preview 📚: https://sorna--3163.org.readthedocs.build/en/3163/
----
📚 Documentation preview 📚: https://sorna-ko--3163.org.readthedocs.build/ko/3163/
=> docs: add instructions for upgrading from 24.03 to 24.09  (#3096)

changes/3045.fix.md, src/ai/backend/manager/models/agent.py, src/ai/backend/manager/models/base.py, src/ai/backend/manager/models/gql.py
=> fix: Regression of `AgentSummary` GQL resolver (#3045)

changes/3173.fix.md, src/ai/backend/agent/docker/agent.py
This is an auto-generated backport PR of #3173 to the 24.09 release.
=> fix: libc version not parsed on images with custom `Entrypoint` set (#3173)

src/ai/backend/common/events.py
=> fix: Set names to vfolder deletion events

changes/3186.fix.md, src/ai/backend/manager/models/session.py
resolves #3187 
Whenever `_transit_session_status()` is called, it accumulates session's occupying slots
=> fix: Do not multiply session occupying slots

changes/3208.fix.md, src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/models/container_registry.py
=> fix: Add missing `extra` field to `ContainerRegistryNode` GQL query, mutations

changes/3208.fix.md, src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/models/container_registry.py
This is an auto-generated backport PR of #3208 to the 24.09 release.
=> fix: Add missing `extra` field to `ContainerRegistryNode` GQL query, mutations (#3208)

changes/3186.fix.md, src/ai/backend/manager/models/session.py
This is an auto-generated backport PR of #3186 to the 24.09 release.
=> fix: Do not multiply session occupying slots (#3186)

tests/manager/api/test_bgtask.py, tools/pytest-requirements.txt, tools/pytest.lock
resolves #3225
- chore: Add pytest-timeout and update pytest requirements
- test: Add timeout to test_bgtask tasks (60 seconds)
**Example screenshot for timeout:**
=> chore(ci): Apply pytest-timeout to test_bgtask

changes/3223.fix.md, src/ai/backend/manager/api/vfolder.py
resolves #3224. Follow-up of #3176.
Let admins query other user's VFolders when listing purge target VFolders.
----
📚 Documentation preview 📚: https://sorna--3223.org.readthedocs.build/en/3223/
----
📚 Documentation preview 📚: https://sorna-ko--3223.org.readthedocs.build/ko/3223/
=> fix: Allow admins to purge other user's vfolders

.github/workflows/backport.yml
close #3192 
Change the matrix to backport all commits, even if multiple commits are pushed at once using the merge queue.
=> ci: Make it possible to backport multiple commits

changes/3235.fix.md, src/ai/backend/client/auth.py
This is an auto-generated backport PR of #3235 to the 24.09 release.
=> fix: CLI test failures caused by `yarl.URL._val` type change (#3235)

src/ai/backend/account_manager/BUILD, src/ai/backend/agent/BUILD, src/ai/backend/manager/BUILD, src/ai/backend/storage/BUILD, src/ai/backend/testutils/BUILD, src/ai/backend/web/BUILD, src/ai/backend/wsproxy/BUILD
Resolves #3242.
1. Open any file within the `testutils` package and import the types of components such as `manager`.
2. Run `pants check ::` to verify if any visibility rule violation errors occur.
---
=> fix: Allow `testutils` component visibility rules

changes/3241.fix.md, src/ai/backend/storage/api/client.py
Fixes https://github.com/lablup/giftbox/issues/786.
The existing VFolder `request-download` API could download files outside of the vfolder.
For example, using the vfolder CLI command that utilizes this API, we can download host files as shown below.
```
❯ ./backend.ai vfolder download test ../some_host_file -b vfolder_name
Downloading to /home/jopemachine/backend.ai/vfolder_name/../some_host_file ...
0.00bytes [00:00, ?bytes/s]
✓ Done.
```
This is clearly a security vulnerability, as it can be exploited, for example, as shown in [issue 786](https://github.com/lablup/giftbox/issues/786).
After applying the PR, passing a path outside the VFolder will result in a 404 error.
Thanks to @fregataa for resolving this issue.
---
=> fix: Prevent vfolder `request-download` API from accessing host filesystem

changes/3241.fix.md, src/ai/backend/storage/api/client.py
This is an auto-generated backport PR of #3241 to the 24.03 release.
=> fix: Prevent vfolder `request-download` API from accessing host filesystem (#3241)

.github/workflows/backport.yml
It is also normal behavior to not perform a backport because the branch corresponding to the target milestone does not currently exist.
github actions does not judge an empty list as false, so it handles this explicitly.
[before]
[after]
=> ci: Handle cases where target milesones is empty

.github/workflows/backport.yml
This pull request includes a small but important change to the `.github/workflows/backport.yml` file. The change involves setting an environment variable for the commit message to simplify and clean up the script.
* Added `COMMIT_MESSAGE` environment variable to store the commit message and updated the script to use this variable instead of directly referencing the output from `needs.backport-target-branch.outputs.commit_message`. This change improves readability and maintainability of the script.
Make the same modifications as in #2512.
=> ci: backport to handle commit messages safely

changes/3248.feature.md, docs/dev/adding-kernels.rst, src/ai/backend/agent/agent.py, src/ai/backend/common/config.py, src/ai/backend/kernel/base.py, src/ai/backend/kernel/service.py, tests/kernel/BUILD, tests/kernel/test_service_variables.py
resolves #2909
- Allow specifying a full shell script string (with an optional `shell` field which defaults to "bash") in the `start_command` field of `model-definition.yaml`.
- Add a simple regex-based tokenizer to process variable interpolation while preserve shell-specific env-var expressions for the command arguments in both `model-definition.yaml` and `/etc/backend.ai/service-defs/*.json` files.
> [!NOTE]
> The tokenizer is a simplified version and cannot handle nested overlapping of shell variable expansion and intrinsic variable expansion as such implementation requires a more sophisticated stack-based parser.  For complex cases like that, users may just flatten their variables references into multiple local variable declarations avoiding syntactic overlaps.
It shows coexistence of …
=> feat: Allow shell command and env-var access in model-definition and service-definition

.github/workflows/backport.yml
This pull request includes a small change to the `jobs:` section in the `.github/workflows/backport.yml` file. The change modifies the `matrix` assignment line to use the `-sc` option with `jq` instead of just `-s`.
* [`.github/workflows/backport.yml`](diffhunk://#diff-1b2ad8b0da1ad4fac7eb4ef8cdeed82b48d00a80eb531a6f31db11f73182f491L98-R98): Changed `matrix` assignment to use `jq -sc` for more concise output.
GITHUB_OUTPUT does not allow whitespace in arrays.
To match its format, use the -c option to jq to remove spaces.
=> ci: matrix to match the `GITHUB_OUTPUT` format

changes/3254.fix.md, src/ai/backend/manager/models/alembic/versions/1d42c726d8a3_migrate_container_registries_from_etcd_to_psql.py
This is an auto-generated backport PR of #3254 to the 24.09 release.
=> fix: do not reuse `Base` class on alembic migration script (#3254)

.github/workflows/assign-pr-number.yml
https://github.com/lablup/backend.ai/actions/runs/11851900854/job/33029158862?pr=3101
The assign-pr-number action is throwing an error after the #3083 action.
The actions/checkout action is getting the current branch by default, but in the case of pull_request branch, it only gets information about the HEAD commit without branch information, so we need to get the branch information as well so we can push it.
https://github.com/actions/checkout#push-a-commit-to-a-pr-using-the-built-in-token
The checkout readmd also says the following.
=> ci: Make sure to check out the head branch, not the HEAD commit

.github/workflows/assign-pr-number.yml
This is an auto-generated backport PR of #3118 to the 24.09 release.
=> ci: Make sure to check out the head branch, not the HEAD commit (#3118)

tests/manager/api/test_bgtask.py
This is a retrospective follow-up of [`3c46849`](https://github.com/lablup/backend.ai/pull/3229/commits/3c468491a9a364f153d037eeb7212458fe7317a2) in #3229 (which is a manually patched auto-generated backport of #3226 which is a response to #3225) for 24.03 and later to introduce a refactored, fixed version of `test_bgtask` with a modernized fixture.
=> refactor: `test_bgtask`

.github/workflows/ci.yml, .github/workflows/skip-ci.yml
This is an auto-generated backport PR of #3122 to the 23.09 release.
=> ci: Remove labeled triggers for skip:ci (#3122)

MIGRATION.md, src/ai/backend/agent/docker/agent.py, src/ai/backend/common/types.py, src/ai/backend/manager/api/admin.py, src/ai/backend/manager/api/context.py, src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/api/session.py, src/ai/backend/manager/config.py, src/ai/backend/manager/models/gql.py, src/ai/backend/manager/models/network.py, src/ai/backend/manager/network/overlay.py, src/ai/backend/manager/registry.py, src/ai/backend/manager/server.py, tests/manager/conftest.py, tests/manager/models/test_container_registries.py, tests/manager/models/test_container_registry_nodes.py
This PR encapsulates container network allocation process as a separate plugin architecture. By default, Backend.AI Manager will ship with a default `overlay` plugin, which in previous supported as one and only option when establishing an inter-container network.    
To support multiple architectures, system operators will now have to explicitly specify which network drivers they will use when creating a multi-node session. Check `MIGRATION.md` for more details.
Just like other computational plugins, Backend.AI Manager Network Plugin is based on Backend.AI's plugin architecture. Create a new network class by inheriting `AbstractNetworkManagerPlugin` and implement every abstract methods. Then expose the class with entrypoint `backendai_network_manager_v1`.    
If your plugin requires any …
=> feat: update manager to utilize network plugin

MIGRATION.md, src/ai/backend/agent/BUILD, src/ai/backend/agent/docker/agent.py, src/ai/backend/agent/docker/intrinsic.py, src/ai/backend/agent/plugin/BUILD, src/ai/backend/agent/plugin/network.py, src/ai/backend/common/types.py, src/ai/backend/manager/api/admin.py, src/ai/backend/manager/api/context.py, src/ai/backend/manager/api/schema.graphql, src/ai/backend/manager/api/session.py, src/ai/backend/manager/config.py, src/ai/backend/manager/models/gql.py, src/ai/backend/manager/models/network.py, src/ai/backend/manager/network/overlay.py, src/ai/backend/manager/registry.py, src/ai/backend/manager/server.py, tests/manager/conftest.py, tests/manager/models/test_container_registries.py, tests/manager/models/test_container_registry_nodes.py
=> feat: implement network agent plugin architecture

changes/3272.fix.md, src/ai/backend/common/types.py, tests/common/test_types.py
=> fix: String formatting of BinarySize

.github/workflows/backport.yml
This pull request includes changes to the `.github/workflows/backport.yml` file to enhance the handling of environment variables and improve the matrix generation logic.
Improvements to environment variable handling:
* [`.github/workflows/backport.yml`](diffhunk://#diff-1b2ad8b0da1ad4fac7eb4ef8cdeed82b48d00a80eb531a6f31db11f73182f491R19-R22): Added an environment variable `COMMITS` to store the JSON representation of GitHub event commits, simplifying the retrieval of commit IDs.
Enhancements to matrix generation logic:
* [`.github/workflows/backport.yml`](diffhunk://#diff-1b2ad8b0da1ad4fac7eb4ef8cdeed82b48d00a80eb531a6f31db11f73182f491L121-R123): Changed the matrix generation to use `target_branches` instead of `target_milestones`, ensuring the correct branches are targeted for the …
=> ci: Fix matrix variable to use target_branches

.editorconfig, .gitignore
Add Zed-specific gitignore entries and let editors ignore line-length in diff files.
=> chore: Update gitignore and editorconfig

.github/workflows/backport.yml
This pull request introduces changes to the GitHub Actions workflow to support manual dispatch for backporting pull requests. The most important changes include adding inputs for the `workflow_dispatch` event and modifying the `jobs` section to handle commits based on the event type.
Enhancements to workflow dispatch:
* [`.github/workflows/backport.yml`](diffhunk://#diff-1b2ad8b0da1ad4fac7eb4ef8cdeed82b48d00a80eb531a6f31db11f73182f491R7-R11): Added `workflow_dispatch` event with an input for `pr_number` to allow manual triggering of the backport workflow.
Modifications to job steps:
* [`.github/workflows/backport.yml`](diffhunk://#diff-1b2ad8b0da1ad4fac7eb4ef8cdeed82b48d00a80eb531a6f31db11f73182f491L15-R37): Updated the `matrix` output to handle commits from either the `push` or …
=> ci: Add manual backport trigger via workflow_dispatch

.github/workflows/ci.yml
We decided to have a faster release cycle going forward.
This has led to a wider variety of versions in rules, where minor versions were only available in 03,09.
https://docs.github.com/ko/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
The github actions pattern match syntax does not provide a way to match only numbers, so we chose the current way without using *.
=> ci: Modify to accommodate the changed release naming convention

src/ai/backend/manager/api/session.py, src/ai/backend/manager/server.py
A hotfix follow-up to #3291 (refs #3290).
- Also update the API version history
- In this case (#3290), creation_config_v5 and v6 are compatible as the
added field is an optional one with a default value.
We do not need to bump the API version from v8 to v9.
=> fix: Broken input validation for session creation from templates

changes/3286.feature.md, src/ai/backend/agent/docker/kernel.py
Follow-up PR of #2100. Fixes cleanup process of kernels created before #2100 failing since `clean_kernel()` function tries to access `network_driver` variable on a rebuilt `DockerKernel` object, which has yet no reference to the variable (ref: https://github.com/lablup/backend.ai/blob/main/src/ai/backend/agent/docker/agent.py#L1763-L1770). This PR resolves the pitfall by setting up the `network_driver` value as `bridge` when deserializing dated `DockerKernel` object. By doing so, the `clean_kernel()` function will skip all network plugin-specific cleanup feature, which was not an interest on previous implementations anyways.
- Demonstrate the flow of …
=> fix: 'DockerKernel' object has no attribute 'network_driver'

changes/3275.feature.md, src/ai/backend/accelerator/cuda_open/plugin.py, src/ai/backend/accelerator/mock/plugin.py, src/ai/backend/agent/agent.py, src/ai/backend/agent/docker/agent.py, src/ai/backend/agent/dummy/agent.py, src/ai/backend/agent/kubernetes/agent.py, src/ai/backend/agent/resources.py, src/ai/backend/common/types.py, tests/agent/test_resources.py
resolves #3269
This implementation is agnostic to the agent backend as long as they support the accelerator device plugins and those plugins provide proper `get_attached_devices()` implementation.
**Example execution:**
=> feat: Implement GPU config with `get_attached_devices()`

.github/workflows/backport.yml
This pull request includes several changes to the `.github/workflows/backport.yml` file, primarily focusing on renaming the `backport-target-branch` to `get-backport-target-branch` in various sections of the workflow.
The most important changes include:
* Updated the `if` condition to use `needs.get-backport-target-branch.outputs.matrix` instead of `needs.backport-target-branch.outputs.matrix`.
* Changed the `needs` dependency from `backport-target-branch` to `get-backport-target-branch`.
* Modified the environment variables and commit message trailers to use `get-backport-target-branch` outputs instead of `backport-target-branch` outputs.
* Updated the author and PR details in the `create-pull-request` step to use `get-backport-target-branch` outputs.
* Adjusted the commit footer to …
=> ci: Change the job name to make sense

.github/workflows/backport.yml
This pull request includes a change to the GitHub Actions workflow configuration file `.github/workflows/backport.yml`. The change modifies the `jobs:` section to update the matrix strategy.
* [`.github/workflows/backport.yml`](diffhunk://#diff-1b2ad8b0da1ad4fac7eb4ef8cdeed82b48d00a80eb531a6f31db11f73182f491L145-R145): Changed the matrix key from `milestone` to `target_branch` to correctly reflect the output from the `get-backport-target-branch` job.
=> ci: Change the matrix variable to `target_branch`

.github/workflows/backport.yml
This pull request includes a small but important change to the `.github/workflows/backport.yml` file. The change updates the reference to the output labels of a GitHub Actions job.
Workflow file update:
* [`.github/workflows/backport.yml`](diffhunk://#diff-1b2ad8b0da1ad4fac7eb4ef8cdeed82b48d00a80eb531a6f31db11f73182f491L197-R197): Changed the reference from `needs.backport-target-branch.outputs.labels` to `needs.get-backport-target-branch.outputs.labels` to correct the job dependency.
=> ci: Reflect what's missing from the rename

changes/3275.feature.md, src/ai/backend/accelerator/cuda_open/plugin.py, src/ai/backend/accelerator/mock/plugin.py, src/ai/backend/agent/agent.py, src/ai/backend/agent/docker/agent.py, src/ai/backend/agent/resources.py, src/ai/backend/common/types.py
=> feat: Implement GPU config with `get_attached_devices()` (#3275)

src/ai/backend/agent/agent.py, src/ai/backend/agent/docker/agent.py, src/ai/backend/agent/dummy/agent.py, src/ai/backend/agent/dummy/kernel.py, src/ai/backend/agent/kernel.py, src/ai/backend/agent/kubernetes/agent.py, src/ai/backend/common/enum_extension.pyi, src/ai/backend/common/types.py
resolves #3298 (BA-412).
- Fix type definition mismatch of `common/enum_extenion.{py,pyi}`
- Fix possibly unbound variables in multiple places
- Use explicit enum types when possible and fix inconsistent use of enum/str values for `MountPermission` in `get_runner_mount()`
- Use `typing.Self` in `aobject.new()`
=> refactor: Resolve some pyright errors

changes/.feature.md, changes/3281.feature.md, src/ai/backend/manager/registry.py
This PR updates model service session creation logic to automatically populate `BACKEND_MODEL_NAME` as name of the model folder. Handing out the model name as environment variable will help inference runtimes understand the model better.
=> feat: populate `BACKEND_MODEL_NAME` environment variable automatically

.github/workflows/assign-pr-number.yml, scripts/assign-pr-number.py
This hotfix PR ensures git-removal of renamed news fragments files.
=> chore(ci): Ensure removal of renamed news fragment files

changes/3302.misc.md, docs/dev/daily-workflows.rst, docs/install/install-from-package/os-preparation.rst, docs/locales/ko/LC_MESSAGES/install/install-from-package.po, docs/locales/ko/LC_MESSAGES/install/install-from-package/os-preparation.po, pants.toml, pyproject.toml, python-kernel.lock, python.lock, scripts/bootstrap-static-python.sh, scripts/delete-dev.sh, src/ai/backend/common/docker.py, src/ai/backend/install/README.md, tools/black.lock, tools/coverage-py.lock, tools/mypy.lock, tools/pants-plugins/scie/config.py, tools/pytest.lock, tools/ruff.lock, tools/setuptools.lock, tools/towncrier.lock
----
📚 Documentation preview 📚: https://sorna--3304.org.readthedocs.build/en/3304/
----
📚 Documentation preview 📚: https://sorna-ko--3304.org.readthedocs.build/ko/3304/
=> chore: Upgrade Python (3.12.6 -> 3.12.8) (#3302)

src/ai/backend/logging/handler/intrinsic.py, src/ai/backend/logging/logger.py
This error is found while backporting #3302 to the 24.03 branch.
=> fix: Type error due to missing default type-var in zmq.Context

src/ai/backend/logging/handler/intrinsic.py, src/ai/backend/logging/logger.py
=> fix: Type error due to missing default type-var in zmq.Context (#3307)

.editorconfig, .gitignore
=> chore: Update gitignore and editorconfig (#3280)

.github/workflows/ci.yml
=> ci: Modify to accommodate the changed release naming convention (#2914)

.github/workflows/ci.yml
=> ci: Fixes behavior that was preventing proper comparison due to typos (#2907)

scripts/diff-release.py
Since auto-backported PRs have two references to the PR numbers in their merge-commit titles, we need to override the last PR number with the second-last PR number if present.
=> chore(scripts): Update diff-releases.py to recognize auto-backported PRs

.github/workflows/pr-prefix.yml
Now we can insert additional information slugs in all prefixes.
=> ci(BA-431): Update the PR prefix checker to accept additional-info slug in all prefixes

.github/workflows/pr-prefix.yml
=> ci(BA-431): Update the PR prefix checker to accept additional-info slug in all prefixes (#3338)

changes/3337.fix.md, src/ai/backend/manager/models/endpoint.py
=> fix(BA-433): Misuse of the walrus operator when taking ModifyEndpoint input

.github/workflows/backport.yml
https://github.com/lablup/backend.ai/pull/3289/files#diff-1b2ad8b0da1ad4fac7eb4ef8cdeed82b48d00a80eb531a6f31db11f73182f491L192
Revert 'outputs' after accidentally deleting it while renaming a variable.
This pull request includes a small but important change to the `.github/workflows/backport.yml` file. The change corrects the reference to the pull request number in the auto-generated backport PR body.
* [`.github/workflows/backport.yml`](diffhunk://#diff-1b2ad8b0da1ad4fac7eb4ef8cdeed82b48d00a80eb531a6f31db11f73182f491L194-R194): Corrected the reference from `needs.get-backport-target-branch.pr_number` to `needs.get-backport-target-branch.outputs.pr_number` in the `body` field of the auto-generated backport PR.
=> ci(BA-416): Fix invalid variable usage

.github/workflows/backport.yml
close #3350 
This pull request includes a small change to the `jobs:` section in the `.github/workflows/backport.yml` file. The change ensures that the backport job only runs if the `matrix` output is not empty or an empty string.
* [`.github/workflows/backport.yml`](diffhunk://#diff-1b2ad8b0da1ad4fac7eb4ef8cdeed82b48d00a80eb531a6f31db11f73182f491L140-R140): Modified the condition in the `if` statement to check that `matrix` is not empty and not an empty string.
=> ci(BA-434): Graceful exit if committed directly to main

changes/3222.fix.md, src/ai/backend/client/cli/session/lifecycle.py, src/ai/backend/client/func/session.py, tests/client/cli/BUILD, tests/client/cli/conftest.py, tests/client/cli/session/BUILD, tests/client/cli/session/test_lifecycle.py, tests/client/cli/test_cli_commands.py
Fix #3202 ([BA-19](https://lablup.atlassian.net/browse/BA-19))
This PR fixes following broken session CLI commands.
* `session rename`
* `session set-priority`
* `session events`
* `session commit`
Starting from version `24.09`, the code uses `session_id` (UUID) as an argument to create a `ComputeSession` object by calling `from_session_id`. However, this approach does not populate the `ComputeSession.name` field. As a result, it sends API calls like `/session/None (session_id_or_name)/rename?name=new-name`, leading to incorrect behavior.
So this PR only needs to be backported to version `24.09`.
---
[BA-19]: …
=> fix: Broken session CLI commands due to invalid initialization of `ComputeSession`

changes/3222.fix.md, src/ai/backend/client/cli/session/lifecycle.py, src/ai/backend/client/func/session.py, tests/client/cli/BUILD, tests/client/cli/conftest.py, tests/client/cli/session/BUILD, tests/client/cli/session/test_lifecycle.py, tests/client/cli/test_cli_commands.py
This is an auto-generated backport PR of #3222 to the 24.09 release.
=> fix: Broken session CLI commands due to invalid initialization of `ComputeSession` (#3222)

changes/template.md
This PR adds the required newlines to the end of `changes/template.md` with an explicit comment to prevent accidental removal of them.
The backport target is set to 24.03 which shares the same towncrier version (`~=24.8`).
=> ci: Fix the newlines of changelog between versions

changes/template.md
This is an auto-generated backport PR of #3364 to the 24.09 release.
=> ci: Fix the newlines of changelog between versions (#3364)

.github/workflows/ci.yml
This PR updates the GitHub Action runners when building scies and wheels.
* Upgrade the macOS runner versions to avoid deprecation
- actions/runner-images#10721
* Pin the Ubuntu runner version to 22.04 when building scies and wheels
to ensure a reproducible environment.
=> ci: Update action runners

.github/workflows/ci.yml
This is an auto-generated backport PR of #3367 to the 24.09 release.
=> ci: Update action runners (#3367)

changes/3341.fix.md, src/ai/backend/agent/docker/agent.py
Follow-up PR of #3173 and #2582. On #3173 we forced `Entrypoint` value as `sh` to force override the value set from the image, but it caused another shell script evaluation error. Along with that it seems that we can just let container use docker system's default value by passing `[""]` as the `Entrypoint` config.
=> fix(BA-438): Libc version not parsed on image without metadata label

changes/3341.fix.md, src/ai/backend/agent/docker/agent.py
This is an auto-generated backport PR of #3341 to the 24.09 release.
=> fix(BA-438): Libc version not parsed on image without metadata label (#3341)

changes/3391.fix.md, src/ai/backend/agent/agent.py, src/ai/backend/agent/docker/agent.py, src/ai/backend/agent/dummy/agent.py, src/ai/backend/agent/server.py
Resolves https://github.com/lablup/backend.ai-internal/issues/118.
=> fix(BA-450): do not set timeout on docker push API execution

changes/3387.fix.md, src/ai/backend/runner/entrypoint.sh
This is an auto-generated backport PR of #3387 to the 24.09 release.
=> fix(BA-459): password based SSH login not working (#3387)

changes/3410.fix.md, src/ai/backend/logging/formatter.py
This is an auto-generated backport PR of #3410 to the 24.09 release.
=> fix(BA-477): Logging and formatting exceptions raised from local process (#3410)

changes/3420.fix.md, src/ai/backend/manager/container_registry/local.py
This is an auto-generated backport PR of #3420 to the 24.09 release.
=> fix(BA-484): Missing architceture name lookup in LocalRegistry (#3420)

src/ai/backend/agent/server.py, src/ai/backend/agent/watcher.py
This is an auto-generated backport PR of #2906 to the 24.09 release.
=> chore: Describe the extension of the config file to use TOML (#2906)

changes/3231.doc.md, docs/manager/graphql-reference/schema.graphql, src/ai/backend/manager/models/container_registry.py
Mark the `ContainerRegistry` GQL API as deprecated since *24.09*.
----
📚 Documentation preview 📚: https://sorna--3231.org.readthedocs.build/en/3231/
----
📚 Documentation preview 📚: https://sorna-ko--3231.org.readthedocs.build/ko/3231/
=> doc: Deprecate non relay container registry GQL explicitly

changes/3451.fix.md, docs/manager/rest-reference/openapi.json, src/ai/backend/agent/server.py, src/ai/backend/agent/watcher.py, src/ai/backend/manager/api/exceptions.py, src/ai/backend/manager/api/vfolder.py, src/ai/backend/manager/models/vfolder.py, tests/manager/api/test_vfolder.py
resolves #3450 (BA-515)
----
📚 Documentation preview 📚: https://sorna--3451.org.readthedocs.build/en/3451/
----
📚 Documentation preview 📚: https://sorna-ko--3451.org.readthedocs.build/ko/3451/
=> fix(BA-515): Let the vfolder REST API accept vfolder UUIDs as intended

changes/3465.fix.md, src/ai/backend/manager/api/vfolder.py, tests/manager/api/test_vfolder.py
=> fix(BA-517): Raise exception if multiple VFolders exist in decorator

changes/3465.fix.md, src/ai/backend/manager/api/vfolder.py, tests/manager/api/test_vfolder.py
This is an auto-generated backport PR of #3465 to the 24.09 release.
=> fix(BA-517): Raise exception if multiple VFolders exist in decorator (#3465)

changes/3471.feature.md, src/ai/backend/client/func/vfolder.py, src/ai/backend/client/session.py, tests/client/test_vfolder.py, tests/client/test_vfolder_tus.py
=> feat(BA-519): Update SDK to retrieve and use IDs for VFolder API operations instead of names

changes/3471.feature.md, src/ai/backend/client/func/vfolder.py, src/ai/backend/client/session.py, tests/client/test_vfolder.py, tests/client/test_vfolder_tus.py
This is an auto-generated backport PR of #3471 to the 24.03 release.
=> feat(BA-519): Update SDK to retrieve and use IDs for VFolder API operations instead of names (#3471)

changes/3411.fix.md, src/ai/backend/manager/container_registry/base.py, src/ai/backend/manager/container_registry/harbor.py, src/ai/backend/manager/container_registry/local.py
This is an auto-generated backport PR of #3411 to the 24.09 release.
=> fix(BA-478): Accept container images that has the 'null' labels field in their manifests (#3411)

.gitignore
This is an auto-generated backport PR of #3498 to the 24.09 release.
=> chore: Update gitignore (#3498)

src/ai/backend/common/BUILD
In #3475, the metrics module was added to the common package.
This was not explicitly added to the dependencies when packaging, causing issues when building wheel.
=> chore: Ensure that metrics is included in the common package

changes/3412.feature.md, src/ai/backend/agent/config.py, src/ai/backend/agent/server.py
resolves #3401 
The default timeout value is `None`, which means infinite timeout
=> feat(BA-468): Add timeout conf for image push

changes/3513.fix.md, src/ai/backend/manager/container_registry/base.py, src/ai/backend/testutils/mock.py, tests/manager/models/test_image.py
Resolves #3513 ([BA-585](https://lablup.atlassian.net/browse/BA-585)).
This PR fixes an issue where an error occurs when rescanning images with empty tags (dangling images) in Docker registries.
After this PR, dangling images will be skipped, and only other valid images will be rescanned.
[BA-585]: https://lablup.atlassian.net/browse/BA-585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(BA-585): Empty tag image scan error in docker registry

scripts/get-platform-suffix.py
resolves #3534 (BA-605)
I will also need to rename all of the release files for the 25.1.1 version that were incorrectly registered in this PR.
=> ci: Unify suffixes in release names the same way as before

changes/3513.fix.md, src/ai/backend/manager/container_registry/base.py, src/ai/backend/testutils/mock.py, tests/manager/models/test_image.py
This is an auto-generated backport PR of #3533 to the 24.09 release.
=> fix(BA-585): Empty tag image scan error in docker registry (#3533)

changes/2937.fix.md, src/ai/backend/web/security.py, src/ai/backend/web/server.py, tests/webserver/test_security_policy.py
This is an auto-generated backport PR of #2937 to the 24.09 release.
=> fix(BA-82): Add request & response policy middleware for web security (#2937)

src/ai/backend/manager/models/alembic/versions/f6ca2f2d04c1_add_uid_and_gid_columns.py, src/ai/backend/manager/models/kernel.py, src/ai/backend/manager/models/user.py
resolves #3477 (BA-527)
----
📚 Documentation preview 📚: https://sorna--3278.org.readthedocs.build/en/3278/
----
📚 Documentation preview 📚: https://sorna-ko--3278.org.readthedocs.build/ko/3278/
=> feat(BA-527): Add uid and gid columns to users and kernels tables

changes/3572.fix.md, src/ai/backend/web/security.py, tests/webserver/test_security_policy.py
Fixes #3571 ([BA-632](https://lablup.atlassian.net/browse/BA-632)).
This PR fixes the issue of the Backend.AI WebUI broken CSS by allowing the use of `unsafe-inline` in the CSP.
---
[BA-632]: https://lablup.atlassian.net/browse/BA-632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(BA-632): Fix Broken CSS by allowing `unsafe-inline` CSP

changes/3572.fix.md, src/ai/backend/web/security.py, tests/webserver/test_security_policy.py
This is an auto-generated backport PR of #3572 to the 24.09 release.
=> fix(BA-632): Fix Broken CSS by allowing `unsafe-inline` CSP (#3572)

.github/workflows/ci.yml
#3575 (BA-635)
Since the build-scies job runs as a matrix, it will be overwritten by checksum.txt when uploading the artifact with all the same names.
We need to keep all the values, so we use platform-suffix to separate the files and have them merged into one file in the final step.
=> ci: Merge checksum files into one

changes/3583.fix.md, src/ai/backend/agent/docker/agent.py
=> fix(BA-641): Check intrinsic time files exist before mount

changes/3583.fix.md, src/ai/backend/agent/docker/agent.py
This is an auto-generated backport PR of #3583 to the 24.09 release.
=> fix(BA-641): Check intrinsic time files exist before mount (#3583)

changes/3548.feature.md, src/ai/backend/storage/abc.py, src/ai/backend/storage/context.py, src/ai/backend/storage/vfs/__init__.py, src/ai/backend/storage/watcher.py
=> feat(BA-533): Add delete path API to storage watcher

changes/3352.feature.md, docs/manager/graphql-reference/schema.graphql, src/ai/backend/manager/models/gql_models/user.py, src/ai/backend/manager/models/user.py
resolves #3478 (BA-528)
```graphql
mutation ModifyUser {
modify_user (
email: "admin@lablup.com",
props: {
container_uid: 1101,
container_main_gid: 1102,
container_gids: [1103,1104]
}
){
ok
msg
user {
username
container_uid
container_main_gid
container_gids
}
}
}
```
The fields are described as follows:
- container_uid: The user ID (UID) assigned to processes running inside the container. Integer type, nullable.
- container_main_gid: The primary group ID (GID) assigned to processes running inside the container. Integer type, nullable.
- container_gids: Supplementary group IDs assigned to processes running inside the container. Array of integers, nullable.
When connecting to a container created with container_uid = 1100, container_main_gid = 1101, and container_gids = [1102, 1103], the id …
=> feat(BA-528): Update GQL user mutation to allow set uid/gid

changes/3361.feature.md, src/ai/backend/cli/params.py, src/ai/backend/client/cli/admin/user.py, src/ai/backend/client/cli/session/execute.py, src/ai/backend/client/cli/session/lifecycle.py, src/ai/backend/client/func/user.py
=> feat(BA-530): Update SDK and CLI to follow-up per-user uid/gid

changes/3599.fix.md, src/ai/backend/manager/models/alembic/versions/ecc9f6322be4_remove_fk_constraint_from_endpoints_.py, src/ai/backend/manager/models/endpoint.py, src/ai/backend/manager/models/image.py
Resolves #3509 ([BA-584](https://lablup.atlassian.net/browse/BA-584)).
This PR prevents issues like #3509 by removing the foreign key constraint on `EndpointRow.image`.
It also modifies the `EndpointRow.image` column to be conditionally nullable.
`EndpointRow.image` can only be null when in the "Destroyed" state.
This prevents the creation of a new session with an empty image when `EndpointRow.replicas` is modified.
[BA-584]: https://lablup.atlassian.net/browse/BA-584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(BA-584): Remove foreign key constraint from `EndpointRow.image` column

src/ai/backend/account_manager/server.py, src/ai/backend/agent/server.py, src/ai/backend/common/metrics/profiler.py, src/ai/backend/manager/server.py, src/ai/backend/storage/server.py, src/ai/backend/wsproxy/server.py
Follow-up of #3459 and resolves #3600 (BA-657)
According to the pyroscope implementation, `pyroscope.configure()` always returns `None`. Therefore, this pull request suggests to remove meaningless assignment for the return value of `pyroscope.configure()`.
https://github.com/grafana/pyroscope-rs/blob/9f71fd08a314518119d33e7a3a8bcfb9f60ba868/pyroscope_ffi/python/pyroscope/__init__.py#L10-L59%7Csmart-link
This pull request includes a modification to the `Profiler` class in the `src/ai/backend/common/metrics/profiler.py` file. The change removes the assignment of the `pyroscope.configure` call to the `_pyroscope` attribute, simplifying the initialization process.
* [`src/ai/backend/common/metrics/profiler.py`](diffhunk://#diff-48e98260c65436406f498f4b4f6ec43152355668366d333f9ccc7c567bc0dbb9L1 …
=> refactor(BA-657): Remove assignment of `pyroscope.configure()` return value

changes/3599.fix.md, src/ai/backend/manager/models/alembic/versions/ecc9f6322be4_remove_fk_constraint_from_endpoints_.py, src/ai/backend/manager/models/endpoint.py, src/ai/backend/manager/models/image.py
This is an auto-generated backport PR of #3599 to the 23.09 release.
=> fix(BA-584): Remove foreign key constraint from `EndpointRow.image` column (#3599)

changes/3565.enhance.md, src/ai/backend/storage/api/vfolder/manager_handler.py, src/ai/backend/storage/api/vfolder/response_model.py, src/ai/backend/storage/api/vfolder/types.py, tests/storage-proxy/vfolder/test_handler.py
resolves #3562  (BA-589)
Applied pydantic decorator to vfolder APIs in sotrage-proxy.
Tests are not done yet.
----
📚 Documentation preview 📚: https://sorna--3565.org.readthedocs.build/en/3565/
----
📚 Documentation preview 📚: https://sorna-ko--3565.org.readthedocs.build/ko/3565/
=> refactor(BA-589): Apply pydantic handling decorator to VFolder APIs in storage-proxy (#3562)

changes/3654.fix.md, src/ai/backend/manager/models/kernel.py
=> fix(BA-694): Number of concurrent sftp session queried incorrectly

changes/3654.fix.md, src/ai/backend/manager/models/kernel.py
This is an auto-generated backport PR of #3654 to the 24.03 release.
=> fix(BA-694): Number of concurrent sftp session queried incorrectly (#3654)

changes/3682.feature.md, configs/webserver/halfstack.conf, src/ai/backend/web/config.py, src/ai/backend/web/security.py, src/ai/backend/web/server.py, tests/webserver/test_security_policy.py
=> feat(BA-690): Make CSP configurable

changes/3065.feature.md, src/ai/backend/manager/models/__init__.py, src/ai/backend/manager/models/alembic/versions/8f85e9d0bd4e_add_association_containerregistries_.py, src/ai/backend/manager/models/association_container_registries_groups.py, src/ai/backend/manager/models/container_registry.py, src/ai/backend/manager/models/group.py
Implement `AssociationContainerRegistriesGroups` as m2m table of `container_registries`, and `groups` for resolving https://github.com/lablup/backend.ai/issues/1908 ([BA-147](https://lablup.atlassian.net/browse/BA-147)).
> [!NOTE]
> #1908 mentions both user and project, but since project needs to be implemented first, this PR stack addresses only the project aspect.
> Refer to #1960 for adding an association table with the User table and related tasks.
[BA-147]: https://lablup.atlassian.net/browse/BA-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
----
📚 Documentation preview 📚: https://sorna--3065.org.readthedocs.build/en/3065/
----
📚 Documentation preview 📚: …
=> feat(BA-147): Implement m2m table for `container_registries`, and `groups`

changes/3035.feature.md, src/ai/backend/manager/models/image.py
Resolves #3397 ([BA-464](https://lablup.atlassian.net/browse/BA-464)).
Ref: #1908.
Implement per-project scope to images RBAC (Role-Based Access Control) API.
[BA-464]: https://lablup.atlassian.net/browse/BA-464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
----
📚 Documentation preview 📚: https://sorna--3035.org.readthedocs.build/en/3035/
----
📚 Documentation preview 📚: https://sorna-ko--3035.org.readthedocs.build/ko/3035/
=> feat(BA-464): Implement `Image` RBAC project scope

changes/3036.feature.md, docs/manager/graphql-reference/schema.graphql, src/ai/backend/manager/models/gql.py, src/ai/backend/manager/models/gql_models/image.py, src/ai/backend/manager/models/image.py, src/ai/backend/manager/models/rbac/__init__.py
Resolve #1910 ([BA-512](https://lablup.atlassian.net/browse/BA-512)).
This PR adds an interface for testing the per-project image GQL API based on #2999.
----
📚 Documentation preview 📚: https://sorna--3036.org.readthedocs.build/en/3036/
----
📚 Documentation preview 📚: https://sorna-ko--3036.org.readthedocs.build/ko/3036/
[BA-512]: https://lablup.atlassian.net/browse/BA-512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(BA-512): Implement `ImageNode` GQL resolver based on RBAC

changes/3679.fix.md, src/ai/backend/kernel/base.py
resolves #3672  (BA-725)
Increased the kernel-timeout value in `kernel/base.py`:
- prev: `5.0s`
- curr: `30.0s`
=> fix(BA-725): Increase Backend.AI Kernel's app startup timeout (#3672)

changes/3701.fix.md, docs/manager/rest-reference/openapi.json, src/ai/backend/manager/api/container_registry.py, src/ai/backend/manager/api/exceptions.py, src/ai/backend/manager/client/container_registry/harbor.py, src/ai/backend/manager/models/gql_models/container_registry.py, src/ai/backend/manager/models/image.py, src/ai/backend/manager/server.py, src/ai/backend/manager/service/container_registry/harbor.py
Follow-up of #3090, #3116.
Resolves #3702 ([BA-754](https://lablup.atlassian.net/browse/BA-754)).
The following bugs have been fixed.
---
----
📚 Documentation preview 📚: https://sorna--3701.org.readthedocs.build/en/3701/
----
📚 Documentation preview 📚: https://sorna-ko--3701.org.readthedocs.build/ko/3701/
[BA-754]: https://lablup.atlassian.net/browse/BA-754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(BA-754): ContainerRegistry per-project API misc bugs

changes/3685.enhance.md, src/ai/backend/common/dto/storage/response.py, src/ai/backend/common/lock.py, src/ai/backend/storage/api/manager.py, src/ai/backend/storage/plugin.py, src/ai/backend/storage/volumes/abc.py, src/ai/backend/storage/volumes/cephfs/__init__.py, src/ai/backend/storage/volumes/ddn/__init__.py, src/ai/backend/storage/volumes/dellemc/__init__.py, src/ai/backend/storage/volumes/gpfs/__init__.py, src/ai/backend/storage/volumes/gpfs/gpfs_client.py, src/ai/backend/storage/volumes/netapp/__init__.py, src/ai/backend/storage/volumes/netapp/netappclient.py, src/ai/backend/storage/volumes/purestorage/__init__.py, src/ai/backend/storage/volumes/purestorage/rapidfiles.py, src/ai/backend/storage/volumes/purestorage/rapidfiles_v2.py, src/ai/backend/storage/volumes/vast/__init__.py, src/ai/backend/storage/volumes/vast/vastdata_client.py, src/ai/backend/storage/volumes/vfs/__init__.py, src/ai/backend/storage/volumes/weka/__init__.py, src/ai/backend/storage/volumes/xfs/__init__.py
resolves #3656  (BA-696)
To follow the import convention:
- Use **relative** imports when importing modules within the **same package**.
- Use **absolute** imports when importing modules from a **different package**.
Files are changed:
- `common/dto/storage/*.py`
- `storage/api/vfolder/handler.py`
- `storage/services/service.py`
- `storage/volumes/*.py` _(includes cephfs, ddn, etc.)_
=> refactor(BA-696): Change Absolute Imports to Relative Imports in Storage-Proxy (#3656)

changes/3614.fix.md, configs/agent/sample.toml, configs/manager/sample.toml, configs/storage-proxy/halfstack.toml, configs/storage-proxy/sample.toml, configs/wsproxy/sample.toml, src/ai/backend/account_manager/config.py, src/ai/backend/agent/config.py, src/ai/backend/manager/config.py, src/ai/backend/storage/config.py, src/ai/backend/wsproxy/config.py
resolves #3614 (BA-669)
As aiomonitor in wsproxy, manager, agent, halfstack use port number included in Ephemeral ports, It needs to be changed. 
I've changed port number around 38000~39000, and confirmed it not used by other protocol or services
=> fix(BA-669): Change ports using ephemeral ports

changes/3657.feature.md, src/ai/backend/agent/agent.py, src/ai/backend/agent/config.py
=> feat(BA-695): Configurable setup for kernel initialization polling

changes/3657.feature.md, src/ai/backend/agent/agent.py, src/ai/backend/agent/config.py
This is an auto-generated backport PR of #3657 to the 24.09 release.
=> feat(BA-695): Configurable setup for kernel initialization polling (#3657)

changes/3746.fix.md, src/ai/backend/manager/api/session.py
=> fix(BA-788): Cannot query session in rename API handler

changes/3746.fix.md, src/ai/backend/manager/api/session.py
This is an auto-generated backport PR of #3746 to the 24.03 release.
=> fix(BA-788): Cannot query session in rename API handler (#3746)

src/ai/backend/manager/scheduler/dispatcher.py
This PR fixes model service autoscale process always reporting `no statistics` when rule is set. This PR also updates the metric evaluation target from raw value to `pct` on kernel source metrics.
=> fix: Model service autoscaling not working

src/ai/backend/manager/models/base.py, src/ai/backend/manager/models/gql_models/endpoint.py
=> fix(BA-793): Filter GQL sentinel value during endpoint rule creation

changes/3731.feature.md, src/ai/backend/common/dto/storage/field.py, src/ai/backend/common/dto/storage/response.py, src/ai/backend/storage/services/service.py, src/ai/backend/storage/utils.py, src/ai/backend/storage/volumes/types.py
resolves #3724  (BA-770)
To align with pydantic dataclasses in service layer of storage-proxy,
added a new logger function in `storage/utils.py`.
=> feat(BA-770): Add New API Logging Aligned with Pydantic (#3724)

changes/3773.fix.md, src/ai/backend/common/events_experimental.py
=> fix: Missing event observer argument

.github/workflows/ci.yml
In the recent release, the release is failing due to github api rate limit issue when building scie on arm mac.
It is speculated that the lack of github hosted arm runner is the cause, so we will change to using self hosted r
unner. 
Also, I think that using self hosted runner will save cost.
=> ci: Using a self-hosted runner

changes/3821.fix.md, src/ai/backend/manager/container_registry/harbor.py
Fixes #3820 ([BA-847](https://lablup.atlassian.net/browse/BA-847)).
[BA-847]: https://lablup.atlassian.net/browse/BA-847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Broken image rescanning on `HarborRegistry_v1`

changes/3821.fix.md, src/ai/backend/manager/container_registry/harbor.py
This is an auto-generated backport PR of #3821 to the 24.03 release.
=> fix: Broken image rescanning on `HarborRegistry_v1` (#3821)

changes/3810.fix.md, src/ai/backend/install/BUILD, src/ai/backend/plugin/entrypoint.py
hotfix follow-up to #3791 (BA-822)
=> fix(BA-822): Wrong Python interpreter in the installer due to a missing build-macro reference

.github/workflows/pr-prefix.yml
=> ci: Allow `releases` with pr prefix

changes/3555.feature.md, src/ai/backend/agent/metrics/BUILD, src/ai/backend/agent/metrics/metric.py, src/ai/backend/agent/server.py
=> feat(BA-615): Collect metrics for the RPC server

changes/3725.feature.md, scripts/install-dev.sh, src/ai/backend/agent/agent.py, src/ai/backend/common/config.py, src/ai/backend/common/defs.py, src/ai/backend/common/events.py, src/ai/backend/common/events_experimental.py, src/ai/backend/common/redis_client.py, src/ai/backend/common/redis_helper.py, src/ai/backend/common/types.py, src/ai/backend/manager/api/ratelimit.py, src/ai/backend/manager/cli/context.py, src/ai/backend/manager/idle.py, src/ai/backend/manager/models/keypair.py, src/ai/backend/manager/scheduler/dispatcher.py, src/ai/backend/manager/server.py, src/ai/backend/web/server.py, tests/agent/conftest.py, tests/common/redis_helper/test_connect.py, tests/common/test_distributed.py, tests/common/test_events.py, tests/manager/conftest.py
=> feat(BA-24): Split redis config for each connection pool

changes/3831.fix.md, src/ai/backend/client/cli/admin/user.py
This is an auto-generated backport PR of #3831 to the 24.09 release.
=> fix(BA-849): Omit `description` field in user update CLI command when not provided (#3831)

changes/3861.fix.md, src/ai/backend/manager/idle.py
=> fix(BA-880): Aggregate multi-kernel session utilization in idle checker

changes/3861.fix.md, src/ai/backend/manager/idle.py
This is an auto-generated backport PR of #3861 to the 24.03 release.
=> fix(BA-880): Aggregate multi-kernel session utilization in idle checker (#3861)

changes/3871.fix.md, src/ai/backend/manager/container_registry/harbor.py
Resolves #3872 ([BA-887](https://lablup.atlassian.net/browse/BA-887)).
> [!NOTE]
> This bug occurs only in HarborRegistryV2 (it does not occur in V1 or other registries).
---
[BA-887]: https://lablup.atlassian.net/browse/BA-887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(BA-887): Rescan all tags in `HarborRegistryV2`

changes/3871.fix.md, src/ai/backend/manager/container_registry/harbor.py
This is an auto-generated backport PR of #3871 to the 24.09 release.
=> fix(BA-887): Rescan all tags in `HarborRegistryV2` (#3871)

changes/3647.feature.md, docs/manager/graphql-reference/schema.graphql, src/ai/backend/manager/api/session.py, src/ai/backend/manager/cli/image_impl.py, src/ai/backend/manager/container_registry/base.py, src/ai/backend/manager/container_registry/local.py, src/ai/backend/manager/models/gql.py, src/ai/backend/manager/models/gql_models/image.py, src/ai/backend/manager/models/image.py
Resolves #3618 ([BA-675](https://lablup.atlassian.net/browse/BA-675)).
Images marked as "DELETED" cannot be used in CLI commands by default (e.g., `inspect`).
Similarly, "DELETED" images are not retrieved in GQL by default.
[BA-675]: https://lablup.atlassian.net/browse/BA-675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
----
📚 Documentation preview 📚: https://sorna--3647.org.readthedocs.build/en/3647/
----
📚 Documentation preview 📚: https://sorna-ko--3647.org.readthedocs.build/ko/3647/
=> feat(BA-675): Implement `Image` status filtering logics

changes/3883.fix.md, src/ai/backend/manager/models/image.py
Fixes #3879 ([BA-898](https://lablup.atlassian.net/browse/BA-898)).
[BA-898]: https://lablup.atlassian.net/browse/BA-898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(BA-898): Image rescan DB serialization error

src/ai/backend/manager/models/gql_models/session.py
=> fix(BA-912): GQL compute session node resolver misses kernel ORM object loading

changes/3900.fix.md, src/ai/backend/manager/models/gql_models/vfolder.py, src/ai/backend/manager/models/vfolder.py
=> fix(BA-913): GQL vfolder_node type does not resolve permissions field

changes/3880.feature.md, changes/3880.fix.md, src/ai/backend/agent/agent.py, src/ai/backend/agent/config.py, src/ai/backend/agent/exception.py, src/ai/backend/agent/kernel.py, src/ai/backend/common/events.py
=> fix(BA-871): Retry zmq socket from kernel

scripts/install-dev.sh
By default, install-dev.sh uses the $docker_sudo variable to handle cases where sudo is required to run docker commands.
Only in the wait_for_docker() function is that logic missing, so we add it.
=> fix: Missing cases where sudo is required to run docker

scripts/install-dev.sh
This is an auto-generated backport PR of #3909 to the 24.03 release.
=> fix: Missing cases where sudo is required to run docker (#3909)

docs/manager/graphql-reference/schema.graphql, src/ai/backend/manager/models/resource_preset.py
----
📚 Documentation preview 📚: https://sorna--3913.org.readthedocs.build/en/3913/
----
📚 Documentation preview 📚: https://sorna-ko--3913.org.readthedocs.build/ko/3913/
=> fix: Relax required resource-preset GQL mutation fields to not-required

changes/3693.feature.md, src/ai/backend/manager/models/kernel.py, src/ai/backend/manager/models/scaling_group.py, src/ai/backend/manager/scheduler/agent_selector.py, src/ai/backend/manager/scheduler/dispatcher.py, src/ai/backend/manager/scheduler/types.py, tests/manager/scheduler_utils.py, tests/manager/test_agent_selector.py
Resolves #3349 ([BA-442](https://lablup.atlassian.net/browse/BA-442)).
[BA-442]: https://lablup.atlassian.net/browse/BA-442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(BA-442): Distribute model service replica containers whenever possible

configs/webserver/sample.conf, src/ai/backend/web/config.py, src/ai/backend/web/templates/config.toml.j2
resolves #3886 (BA-901)
Removes the `show_kernel_list` configuration option as it is no longer used in the codebase. This option previously controlled the visibility of kernel information in the session detail panel.
**Checklist:**
=> fix(BA-901): remove `show_kernel_list` configuration

configs/webserver/halfstack.conf, configs/webserver/sample.conf, docs/install/install-from-package/install-webserver.rst, src/ai/backend/web/config.py, src/ai/backend/web/templates/config.toml.j2, src/ai/backend/web/templates/config_ini.toml.j2
resolves #nnn (BA-941)
Related PR : https://github.com/lablup/backend.ai-webui/pull/3325
Removes unused configuration options from the web server:
- Removes `brand` field from UI section
- Removes `enable_model_store` from service section
- Removes `enable_LLM_playground` from UI section
**Checklist:**
----
📚 Documentation preview 📚: https://sorna--3934.org.readthedocs.build/en/3934/
----
📚 Documentation preview 📚: https://sorna-ko--3934.org.readthedocs.build/ko/3934/
=> chore(BA-941): clean up unused configuration of webserver.conf

changes/3925.fix.md, src/ai/backend/common/types.py, src/ai/backend/manager/registry.py
This is an auto-generated backport PR of #3925 to the 24.03 release.
=> fix(BA-926): Properly handle zero-value unknown resource limits when creating session (#3925)

src/ai/backend/client/cli/image.py, src/ai/backend/client/func/image.py
=> fix(BA-970): Prevent `image forget` CLI from deleting registry image

changes/4006.fix.md, src/ai/backend/manager/api/resource.py
=> fix(BA-1016): Wrong uuid parse in list presets API handler

changes/3990.fix.md, src/ai/backend/kernel/base.py
=> fix(BA-1003): Wrong error message logging when `model_path` does not exist

changes/3990.fix.md, src/ai/backend/kernel/base.py
This is an auto-generated backport PR of #3990 to the 24.09 release.
=> fix(BA-1003): Wrong error message logging when `model_path` does not exist (#3990)

changes/4025.fix.md, src/ai/backend/manager/models/vfolder.py
=> fix(BA-1024): Fix wrong parse of auto-mount vfolders inputs

changes/4032.fix.md, src/ai/backend/manager/models/gql_models/session.py
Resolves #4031 (BA-1032).
FYI, The milestone is set to 24.09, when `ModifyComputeSession` was created.
=> fix(BA-1032): `modify_compute_session` error caused by missing kernel loading option

changes/4032.fix.md, src/ai/backend/manager/models/gql_models/session.py
This is an auto-generated backport PR of #4032 to the 24.09 release.
=> fix(BA-1032): `modify_compute_session` error caused by missing kernel loading option (#4032)

.github/workflows/ci.yml
resolves #4014 (BA-1010)
Check alembic multihead in the merge queue to prevent multiheads from occurring even when merging multiple prs at the same time.
This will work when merging all PRs because it is hard to check for alembic related changes in the merge queue.
=> ci: Check alembic multi head in merge queue

changes/4045.fix.md, src/ai/backend/manager/models/vfolder.py
=> fix(BA-1039): Do not check storage host permission

changes/4050.feature.md, docs/manager/rest-reference/openapi.json, src/ai/backend/manager/models/resource_policy.py
resolves https://github.com/lablup/backend.ai/issues/4049 (BA-1042)
This PR fixes a typo in the resource policy mutation function where `max_concurrent_sftp_sessions` was incorrectly assigned the value of `max_concurrent_sessions` instead of its own property value. The fix ensures that the correct value is used for SFTP session limits.
Also updates the API version to 25.5.1 in the OpenAPI specification.
----
📚 Documentation preview 📚: …
=> fix(BA-1042): fix typo in keypair resource policy affecting `max_concurrent_sftp_sessions`

changes/4047.fix.md, src/ai/backend/agent/docker/agent.py
This is an auto-generated backport PR of #4047 to the 24.03 release.
=> fix(BA-1041): Add newline at end of customized dotfiles (#4047)

changes/4079.fix.md, src/ai/backend/manager/models/__init__.py, src/ai/backend/manager/models/alembic/versions/683ca0a32f41_add_imageauditlogrow_table.py, src/ai/backend/manager/models/alembic/versions/c4ea15b77136_ensure_auditlogs_table_exist.py
Resolves #4084 (BA-1073).
The cause of the error is that the import of auditlog.py was missing in the `backend/manager/models/__init__.py` file.
Let's add the missing import to ensure that the `AuditLog` table is properly created during the initial installation, and also add a new duplicate migration script to guarantee that the `AuditLog` table definitely exists.
=> fix(BA-1073): Add missing `AuditLog` module import

changes/4098.fix.md, python.lock, requirements.txt, src/ai/backend/manager/models/base.py
=> chore(BA-1082): Replace aiodataloader package to the managed upstream one

changes/4131.feature.md, src/ai/backend/manager/actions/action.py, src/ai/backend/manager/actions/monitors/monitor.py, src/ai/backend/manager/actions/processor.py, tests/manager/actions/test_processor.py
=> feat(BA-1131): Add `action_id` in ActionProcessor for tracking Action

changes/4066.fix.md, src/ai/backend/common/types.py, src/ai/backend/manager/container_registry/harbor.py, src/ai/backend/manager/models/gql_models/image.py, tests/manager/conftest.py, tests/manager/models/test_image.py
Resolves #4054 (BA-1049).
To run the image rescanning test on cr.backend.ai,
```
pants test --pytest-args="--rescan-cr-backend-ai" ./tests/manager/models/test_image.py
```
=> fix(BA-1049): Remove wrong `Accept` header from Image rescanning logic 

changes/4066.fix.md, src/ai/backend/manager/container_registry/harbor.py
=> fix(BA-1049): Remove wrong `Accept` header from Image rescanning logic (#4066)

changes/4161.fix.md, src/ai/backend/manager/container_registry/harbor.py
=> fix(BA-1150): Broken single image rescan on `HarborRegistryV2`

changes/4161.fix.md, src/ai/backend/manager/container_registry/harbor.py
This is an auto-generated backport PR of #4161 to the 24.03 release.
=> fix(BA-1150): Broken single image rescan on `HarborRegistryV2` (#4161)

changes/3923.fix.md, src/ai/backend/agent/agent.py, src/ai/backend/agent/docker/agent.py, src/ai/backend/agent/dummy/agent.py, src/ai/backend/agent/kubernetes/agent.py, src/ai/backend/common/events.py, src/ai/backend/manager/registry.py
Resolves #3924 (BA-927, BA-932)
Previously, there was no feature to remove images, so the absence of the Unload logic does not seem like a bug. 
So I think we don't need to backport this PR. So I will set the milestone to 25Q1.
=> fix(BA-932): Unload removed docker images from Redis

changes/4177.fix.md, src/ai/backend/manager/services/image/service.py
=> fix(BA-1136): Broken `UntagImageFromRegistry` GQL mutation

changes/4181.fix.md, src/ai/backend/manager/models/image.py
=> fix(BA-1167): Wrong custom image owner check logic

changes/4188.fix.md, src/ai/backend/manager/container_registry/harbor.py
Follow-up to #3814.
Resolves #4187 (BA-1173).
=> fix(BA-1173): Add missing `application/vnd.oci.image.manifest.v1` type handling on HarborRegistryV2's single image rescan

changes/4190.fix.md, src/ai/backend/client/cli/vfolder.py, src/ai/backend/manager/models/vfolder.py
=> fix(BA-1174): Remove misleading representation of VFolder deletion permissions for invited users

changes/4198.fix.md, src/ai/backend/manager/models/gql_models/image.py
=> fix(BA-1176): Chunk too big error of `admin image rescan` command

changes/4191.fix.md, src/ai/backend/manager/container_registry/base.py, src/ai/backend/manager/container_registry/harbor.py
Follow-up to #4066.
Revert #4066's change, and fix the correct `Accept` header wherever it is used.
Resolves #4192 (BA-1175).
=> fix(BA-1175): Wrong `Accept` header handling in image rescanning

changes/4191.fix.md, src/ai/backend/manager/container_registry/base.py, src/ai/backend/manager/container_registry/harbor.py
This is an auto-generated backport PR of #4191 to the 24.09 release.
=> fix(BA-1175): Wrong `Accept` header handling in image rescanning (#4191)

changes/4215.fix.md, src/ai/backend/manager/registry.py
=> fix(BA-1187): Skip destroying network if reference name is None

.github/workflows/osv-scanner.yml
resolves #4206 (BA-1182)
https://github.com/google/osv-scanner/pull/1584
The skip-git option is now included as a default behavior in osv scanner.
=> ci(BA-1182): Remove the skip-git option from the osv scanner

changes/4214.fix.md, src/ai/backend/manager/models/exceptions.py, src/ai/backend/manager/models/group.py, src/ai/backend/manager/models/types.py, src/ai/backend/manager/models/user.py, src/ai/backend/manager/services/vfolder/services/vfolder.py
=> fix(BA-1186): VFolder clone not working

changes/4154.fix.md, src/ai/backend/manager/models/resource_policy.py, src/ai/backend/manager/services/keypair_resource_policy/actions/modify_keypair_resource_policy.py, src/ai/backend/manager/services/keypair_resource_policy/types.py
=> fix(BA-1200): Wrong types in ResourcePolicy GQL modifier

changes/4264.fix.md, src/ai/backend/agent/agent.py
=> fix(BA-1227): Destroy kernels that fail during initialization

scripts/install-dev.sh
Fixes #2526
This PR addresses an issue where the script did not check if the currently installed Node.js version matches the required version. 
If Node.js was already installed but with a different version, the script would not update it to the required version. 
I have written logic to check if the Node version is `exactly a specific version`, not just above a certain version. Let me know if you find anything wrong with this!
---
The part of setting environment variables was refactored into a function and generalized for future reuse!
(add "config/fish/config.fish" for fish shell user too!)
I also eliminated the possibility of duplicating the script_content by using grep.
```shell
append_to_profiles() {
script_content="$1"
PROFILE_FILES=("zshrc" "bashrc" "profile" "bash_profile" …
```
=> feat(BA-107): ensure correct nodejs version is installed

changes/4268.fix.md, src/ai/backend/manager/models/gql_models/user.py
=> fix(BA-1229): Change wrong fieldspec

changes/4276.fix.md, src/ai/backend/manager/api/session.py
=> fix: Wrong session download-single API result

changes/4339.fix.md, src/ai/backend/common/redis_helper.py
This is an auto-generated backport PR of #4339 to the 25.6 release.
=> fix(BA-1302): Add TypeError handling in redis_helper (#4339)

changes/4341.fix.md, src/ai/backend/manager/models/image.py
This is an auto-generated backport PR of #4341 to the 25.6 release.
=> fix(BA-1282): Use label's items for making resource info (#4341)

changes/4051.feature.md, tests/manager/services/test_group.py
resolves #3968 (BA-988)
This pull request includes significant changes to the group management functionality in the backend manager. The changes focus on adding action test code, handling exceptions more effectively, and refactoring the group models and related classes to use new processor services.
* [`changes/4051.feature.md`](diffhunk://#diff-bab3863d1c2fa9ff7bafe229bc40ec907138d00f949b5c8399591030eae55a31R1): Added action test code for group management.
* [`src/ai/backend/manager/actions/processor.py`](diffhunk://#diff-60a3be5c74c14445913aec0347d2556daff928538b3de0099cc1b2cf2c88797dR29-R39): Enhanced exception handling in the `_run` method by capturing exceptions in the `exc` variable and re-raising them if necessary. [[1]](diffhunk://#diff-60a3be5c74c14445913aec0347d2556daff928538b3de …
=> feat(BA-988): Add Action Test Code for Group

changes/4371.fix.md, src/ai/backend/manager/models/kernel.py
This is an auto-generated backport PR of #4371 to the 25.6 release.
=> fix(BA-1334): Add missing `KernelStatus.ERROR` to dead kernel status set (#4371)

changes/4384.fix.md, src/ai/backend/manager/models/kernel.py, src/ai/backend/manager/models/session.py, src/ai/backend/manager/sweeper/kernel.py
This is an auto-generated backport PR of #4384 to the 25.6 release.
=> fix(BA-1345): Revert addition of `SessionStatus.ERROR` and `KernelStatus.ERROR` to dead status sets (#4384)

changes/4405.fix.md, python-kernel.lock, src/ai/backend/kernel/requirements.txt
This is an auto-generated backport PR of #4405 to the 24.09 release.
=> fix(BA-1367): Change pyzmq version on the python-kernel, compatible with python 3.13 (#4405)

changes/4353.feature.md, docs/manager/rest-reference/openapi.json, src/ai/backend/client/func/vfolder.py, src/ai/backend/manager/api/vfolder.py, tests/client/test_vfolder.py
This is an auto-generated backport PR of #4353 to the 25.6 release.
----
📚 Documentation preview 📚: https://sorna--4420.org.readthedocs.build/en/4420/
----
📚 Documentation preview 📚: https://sorna-ko--4420.org.readthedocs.build/ko/4420/
=> feat(BA-1321): Add force-delete support for VFolder in Python client SDK (#4353)

changes/4425.fix.md, src/ai/backend/client/cli/vfolder.py
=> fix(BA-1389): vfolder ls cmd not working

changes/4008.fix.md, src/ai/backend/kernel/utils.py
This is an auto-generated backport PR of #4008 to the 24.09 release.
=> fix: Improve handling of process termination races in the krunner's OOM logger (#4008)

changes/4447.fix.md, src/ai/backend/manager/api/service.py, src/ai/backend/manager/registry.py
This is an auto-generated backport PR of #4447 to the 25.6 release.
=> fix(BA-1382): Initialize route session environment variables with fallback for `None` (#4447)

changes/4446.fix.md, src/ai/backend/manager/api/vfolder.py
=> fix(BA-1369): Resolve admins vfolder leave issue

configs/storage-proxy/halfstack.toml
All other components are using only 1 CPU by default in the development environment.
Change the default setting to 1 for compatibility in smaller environments.
=> chore: Changed the number of CPUs in the dev environment to one

configs/storage-proxy/halfstack.toml
This is an auto-generated backport PR of #4473 to the 25.6 release.
=> chore: Changed the number of CPUs in the dev environment to one (#4473)

changes/4450.fix.md, src/ai/backend/client/func/service.py, src/ai/backend/common/typed_validators.py
This is an auto-generated backport PR of #4450 to the 25.6 release.
=> fix(BA-1379): Truncate generated session name in service creation to max allowed length (#4450)

src/ai/backend/manager/config/unified.py, src/ai/backend/manager/server.py
=> fix: Add missing validator to Redis Sentinel Config

changes/2572.fix.md, python.lock, requirements.txt, src/ai/backend/agent/docker/agent.py
This is an auto-generated backport PR of #2572 to the 24.09 release.
=> fix: Silent failure of `DockerAgent`'s `push_image()`, `pull_image()` (#2572)

changes/4547.fix.md, src/ai/backend/client/func/keypair.py
resolves #NNN (BA-1457).
```
async def test():
async with AsyncSession() as session:
r = await session.KeyPair.activate("AKIAIOSFODNN7EXAMPLE")
print(r)
```
```
{'ok': False, 'msg': 'integrity error: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class \'asyncpg.exceptions.NotNullViolationError\'>: null value in column "resource_policy" of relation "keypairs" violates not-null constraint\nDETAIL:  Failing row contains (admin@lablup.com, AKIAIOSFODNN7EXAMPLE, wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY, t, null, 2025-05-15 04:20:51.421069+00, 2025-05-29 03:27:57.697798+00, null, null, 0, null, null, f38dea23-50fa-42a0-b5ae-338f5f4693f4, null, \\x90, ).\n[SQL: UPDATE keypairs SET is_active=%s, is_admin=%s, modified_at=CURRENT_TIMESTAMP, rate_limit=%s, resource_policy=%s WHERE …
```
=> fix(BA-1457): Broken `Keypair` SDK methods

changes/4547.fix.md, src/ai/backend/client/func/keypair.py
This is an auto-generated backport PR of #4547 to the 24.09 release.
=> fix(BA-1457): Broken `Keypair` SDK methods (#4547)

changes/4546.fix.md, docs/manager/rest-reference/openapi.json, src/ai/backend/client/func/resource.py, src/ai/backend/manager/api/resource.py, src/ai/backend/manager/openapi.py
resolves #4525 (BA-1460).
```python
async def test():
async with AsyncSession() as session:
r = await session.Resource.usage_per_month("202505", ["2de2b969-1d04-48a6-af16-0bc8adb3c831", "8e32dd28-d319-4e3b-8851-ea37837699a5"])
print(r)
```
```
{'result': {'PENDING': '2025-05-29T02:11:56.602497+00:00', 'RUNNING': '2025-05-29T02:11:59.551399+00:00', 'CREATING': '2025-05-29T02:11:57.351795+00:00', 'PREPARED': '2025-05-29T02:11:57.342391+00:00', 'PREPARING': '2025-05-29T02:11:57.306649+00:00', 'SCHEDULED': '2025-05-29T02:11:57.297149+00:00'}}
```
----
📚 Documentation preview 📚: https://sorna--4546.org.readthedocs.build/en/4546/
----
📚 Documentation preview 📚: https://sorna-ko--4546.org.readthedocs.build/ko/4546/
=> fix(BA-1460): Broken `Resource.usage_per_month` SDK method

scripts/build-scies.sh, scripts/build-wheels.sh
Updated `build-scies.sh` and `build-wheels.sh` to include `set -e` for error handling, ensuring the scripts exit immediately on failure. Also added a shebang to `build-wheels.sh` for consistency.
=> ci: Add error handling to build scripts

changes/4576.fix.md, src/ai/backend/agent/docker/agent.py
This is an auto-generated backport PR of #4576 to the 25.6 release.
=> fix(BA-1488): Gracefully handle missing `Config.Labels` in Docker image inspection (#4576)

changes/4594.fix.md, src/ai/backend/manager/api/service.py
=> fix: Include endpoint loading in route retrieval for delete_route function

changes/4599.fix.md, src/ai/backend/agent/agent.py
This is an auto-generated backport PR of #4599 to the 25.6 release.
=> fix(BA-1501): Replace assert statements in `load_model_definition` with raising exception (#4599)

changes/4612.fix.md, src/ai/backend/manager/config/unified.py
=> fix(BA-1511): `rpc_auth_manager_keypair` not found error in `generate-rpc-keypair`

changes/4604.misc.md, changes/4606.misc.md, configs/prometheus/prometheus.yaml, docker-compose.halfstack-2409.yml
Resolves #4603 (BA-1504).
- Import the desired Grafana dashboard.
(For example, you can use 3070 for Etcd or 736 for Redis, 9628 for PostgreSQL DB)
=> feat(BA-1504): Add Etcd, Redis, and PostgreSQL exporters, scraper configs

changes/4619.fix.md, src/ai/backend/manager/registry.py
This is a backport PR of https://github.com/lablup/backend.ai/pull/4619 to the 25.6 release.
=> fix(BA-1518): Add event handler for SessionCheckingPrecondEvent (#4619)

changes/4627.fix.md, src/ai/backend/manager/container_registry/base.py
This is an auto-generated backport PR of #4627 to the 24.09 release.
=> fix(BA-1522): Support more Accept headers in `BaseContainerRegistry.scan_tag` (#4627)

changes/4679.fix.md, src/ai/backend/agent/agent.py, src/ai/backend/agent/kernel.py
This is an auto-generated backport PR of #4679 to the 25.6 release.
=> fix(BA-1560): Skip failure of code runner init (#4679)

changes/4720.fix.md, src/ai/backend/client/func/image.py
This is an auto-generated backport PR of #4720 to the 24.09 release.
=> fix(BA-1585): Broken `untag_image_from_registry` SDK method (#4720)

changes/4690.fix.md, src/ai/backend/manager/services/session/service.py
=> fix(BA-1567): Fix Session Rename API to prevent duplicate names

src/ai/backend/agent/agent.py
=> fix: Skip cleaning non-running kernels

changes/4697.feature.md, src/ai/backend/test/testcases/session/session_status_history_retriever.py, src/ai/backend/test/testcases/session/testspecs.py
=> feat(BA-1561): Add session status history retriever test

changes/4749.feature.md, src/ai/backend/client/cli/service.py, src/ai/backend/client/func/service.py
=> feat(BA-1607): Add runtime_variant parameter to Service creation SDK function

changes/4753.fix.md, src/ai/backend/agent/agent.py, src/ai/backend/agent/docker/intrinsic.py, src/ai/backend/agent/kernel.py, src/ai/backend/agent/stats.py
This is an auto-generated backport PR of #4753 to the 25.6 release.
=> fix(BA-1609): Skip gathering metric of non-existent process (#4753)

changes/3951.feature.md, docs/manager/graphql-reference/schema.graphql, src/ai/backend/client/cli/image.py, src/ai/backend/client/func/image.py, src/ai/backend/manager/cli/image.py, src/ai/backend/manager/cli/image_impl.py, src/ai/backend/manager/models/gql_models/image.py, src/ai/backend/manager/models/image.py, src/ai/backend/manager/services/image/service.py, tests/manager/services/fixtures.py
Resolves #3979 (BA-997).
----
📚 Documentation preview 📚: https://sorna--3951.org.readthedocs.build/en/3951/
----
📚 Documentation preview 📚: https://sorna-ko--3951.org.readthedocs.build/ko/3951/
=> feat(BA-997): Add `image purge` CLI command for hard deleting ImageRow

changes/4795.fix.md, src/ai/backend/common/message_queue/redis_queue.py
This is an auto-generated backport PR of #4795 to the 25.6 release.
=> fix(BA-1632): Cool down redis error log (#4795)

changes/4807.fix.md, src/ai/backend/manager/container_registry/harbor.py
This is an auto-generated backport PR of #4807 to the 24.09 release.
=> fix(BA-1645): Wrong Accept Header on `HarborRegistryV2._process_oci_index` (#4807)

.github/workflows/ci.yml
This is an auto-generated backport PR of #3818 to the 24.09 release.
=> ci: Using a self-hosted runner (#3818)

changes/4798.fix.md, src/ai/backend/kernel/base.py, src/ai/backend/test/testcases/session/execution.py, src/ai/backend/test/testcases/session/testspecs.py
=> fix(BA-1584): Wrong exit code when `BaseRunner.query` fails

changes/4836.feature.md, configs/webserver/sample.conf, src/ai/backend/web/config.py, src/ai/backend/web/templates/config.toml.j2
Resolves #4836 ([BA-1668](https://lablup.atlassian.net/browse/BA-1668))
This PR adds a new configuration option `default_file_browser_image` to specify a default file browser image. When not specified, a random installed file browser image will be used as before.
The changes include:
- Adding the new configuration option to the sample config file with documentation
- Adding the option to the config schema validation
- Exposing the setting in the frontend config template as `defaultFileBrowserImage`
**Checklist:**
- docstrings in public interfaces and type …
=> feat(BA-1668): Add the `default_file_browser_image` option to the webserver configuration.

changes/4843.fix.md, src/ai/backend/manager/models/gql_models/image.py
=> fix(BA-1671): GQL image node has wrong query filter definition

changes/4843.fix.md, docs/manager/rest-reference/openapi.json, src/ai/backend/manager/models/gql_models/image.py
This is an auto-generated backport PR of #4843 to the 25.6 release.
=> fix(BA-1671): GQL image node has wrong query filter definition (#4843)

changes/4879.fix.md, src/ai/backend/manager/services/user/actions/modify_user.py
=> fix(BA-1708): Allow update users main_access_key

changes/4788.fix.md, src/ai/backend/wsproxy/proxy/frontend/http/abc.py, src/ai/backend/wsproxy/server.py
This is an auto-generated backport PR of #4788 to the 25.6 release.
=> fix(BA-1630): Omission of status code in wsproxy exception middleware (#4788)

changes/4922.fix.md, src/ai/backend/agent/docker/intrinsic.py
This is an auto-generated backport PR of #4922 to the 25.6 release.
=> fix(BA-1744): Handle NoSuchProcess properly when gather process stat (#4922)

changes/4929.fix.md, src/ai/backend/agent/docker/intrinsic.py
=> fix(BA-1722): Check daemon process before query docker netstat

changes/4923.fix.md, src/ai/backend/agent/agent.py, src/ai/backend/manager/api/manager.py, src/ai/backend/manager/registry.py
This is an auto-generated backport PR of #4923 to the 25.6 release.
=> fix(BA-1746): Skip kernel destroy when agent shutdown (#4923)

changes/4946.fix.md, src/ai/backend/agent/agent.py
This is an auto-generated backport PR of #4946 to the 24.09 release.
=> fix(BA-1752): Wrong indent in Agent container stat function (#4946)

changes/4950.deps.md, python.lock, requirements.txt
=> deps(BA-1753): Fix aiodns version to 3.2.0

src/ai/backend/manager/services/session/service.py
=> fix(BA-1768): Remove the incorrect warning logs that `BgtaskUpdated` is not supported

changes/4917.fix.md, src/ai/backend/manager/services/group/actions/purge_group.py, src/ai/backend/manager/services/group/service.py
=> fix(BA-1720): Clean up endpoints when purge group

changes/5018.fix.md, src/ai/backend/storage/volumes/purestorage/rapidfiles.py, src/ai/backend/storage/volumes/purestorage/rapidfiles_v2.py
This is an auto-generated backport PR of #5018 to the 25.6 release.
=> fix(BA-1741): Incorrect filetype check of `PureStorage` VFolder (#5018)

changes/5047.fix.md, src/ai/backend/manager/registry.py
=> fix(BA-1847): Wrong `service ports` field name of Session creation response

changes/5047.fix.md, src/ai/backend/manager/registry.py
This is an auto-generated backport PR of #5047 to the 25.6 release.
=> fix(BA-1847): Wrong `service ports` field name of Session creation response (#5047)

changes/4971.feature.md, configs/tester/tester.toml, src/ai/backend/client/session.py, src/ai/backend/test/contexts/context.py, src/ai/backend/test/contexts/vfolder.py, src/ai/backend/test/data/vfolder.py, src/ai/backend/test/templates/vfolder/share.py, src/ai/backend/test/testcases/vfolder/share.py, src/ai/backend/test/testcases/vfolder/testspecs.py, src/ai/backend/test/tester/dependency.py, src/ai/backend/test/utils/exceptions.py
=> feat(BA-1699): Add vfolder share test

changes/5059.fix.md, src/ai/backend/client/func/service.py
This is an auto-generated backport PR of #5059 to the 25.6 release.
=> fix(BA-1824): Unbound local variable when model-folder is used in service `extra_mounts` (#5059)

changes/5080.fix.md, src/ai/backend/common/exception.py, src/ai/backend/manager/errors/exceptions.py, src/ai/backend/manager/models/storage.py
=> fix(BA-1834): Manager handles already deleted vfolder correctly

changes/5118.fix.md, src/ai/backend/agent/agent.py, src/ai/backend/agent/docker/resources.py
=> fix(BA-1854): Handle scratch already cleaned before destroy container

changes/5118.fix.md, src/ai/backend/agent/agent.py
This is an auto-generated backport PR of #5118 to the 25.6 release.
=> fix(BA-1854): Handle scratch already cleaned before destroy container (#5118)

changes/5112.fix.md, src/ai/backend/agent/kernel.py
This is an auto-generated backport PR of #5112 to the 25.6 release.
=> fix(BA-1839): Finish Agent execution task event correctly (#5112)

changes/5095.enhance.md, src/ai/backend/manager/repositories/container_registry/admin_repository.py, src/ai/backend/manager/repositories/container_registry/repositories.py, src/ai/backend/manager/repositories/container_registry/repository.py, src/ai/backend/manager/services/container_registry/service.py, src/ai/backend/manager/services/processors.py, tests/manager/services/container_registry/conftest.py
=> feat(BA-1843): Separate repository layer from container registry service

changes/5213.feature.md, src/ai/backend/agent/agent.py, src/ai/backend/agent/config/unified.py, src/ai/backend/common/utils.py
=> feat(BA-1917): Add chown util for Agent volume mount

changes/5217.fix.md, src/ai/backend/manager/repositories/schedule/repository.py
=> fix(BA-1921): `status_data` not initialized properly when creating single node session

src/ai/backend/manager/services/vfolder/exceptions.py, src/ai/backend/manager/services/vfolder/services/invite.py
=> fix: Extend VFolderAlreadyExists exception to inherit from web.HTTPConflict

configs/storage-proxy/halfstack.toml
#5172 In pr, the halfstack config of storage-proxy was overwritten with the contents of the sample config.
The sample config is redundant because it contains all the configuration contents.
The halfstack config should have only the minimum configuration to create a development environment.
=> chore: Revert halfstack config of storage-proxy to previous state

scripts/install-dev.sh
The setup_environment function now creates directories for pyroscope-data and tempo-data under HALFSTACK_VOLUME_PATH to support new services or data storage requirements.
=> chore: Add pyroscope and tempo data directories to setup

CLAUDE.md
Let it write or update BUILD files when necesary and not use `--debug` in pants commands other than `pants test`.
=> chore: Update CLAUDE.md to work better

changes/5329.fix.md, src/ai/backend/manager/registry.py
This is an auto-generated backport PR of #5329 to the 25.6 release.
=> fix(BA-2008): Add missing db transaction retry when setting network ID of new sessions (#5329)

scripts/install-dev.sh
The '-it' flags were removed from docker exec commands when setting up databases in install-dev.sh. This change prevents unnecessary interactive mode during automated database initialization.
=> chore: Remove interactive flag from docker exec in DB setup

changes/5327.fix.md, src/ai/backend/manager/api/auth.py
=> fix(BA-1999): Handle None user when request context setup in auth middleware

src/ai/backend/appproxy/common/config.py, src/ai/backend/logging/config_pydantic.py
=> fix(BA-2037): Add validation alias for `pkg_ns` in logging config

src/ai/backend/appproxy/common/config.py, src/ai/backend/logging/config_pydantic.py
=> feat(BA-2040): Add serialization alias for `pkg_ns` in logging config

changes/5366.fix.md, src/ai/backend/account_manager/cli/context.py, src/ai/backend/account_manager/config.py, src/ai/backend/account_manager/server.py, src/ai/backend/agent/server.py, src/ai/backend/appproxy/coordinator/cli/context.py, src/ai/backend/appproxy/coordinator/config.py, src/ai/backend/appproxy/coordinator/server.py, src/ai/backend/appproxy/worker/config.py, src/ai/backend/appproxy/worker/server.py, src/ai/backend/logging/config_pydantic.py, src/ai/backend/manager/config/bootstrap.py, src/ai/backend/manager/config_legacy.py, src/ai/backend/manager/server.py, src/ai/backend/storage/server.py, src/ai/backend/web/server.py, src/ai/backend/wsproxy/config.py
Make `--log-level` and `--debug` flag behavior and description consistent across all daemon services.
Now the log-level CLI option ONLY overrides:
- the global log-level filter (`[logging].level` in toml files)
- the log-level of "ai.backend" namespace (`[logging.pkg-ns]` in toml files)
The default `[logging.pkg-ns]` is also unified to:
```
[logging.pkg-ns]
"" = "WARNING"
"ai.backend" = "INFO"
"tests" = "DEBUG"
```
> [!NOTE]
> If you have relied on the previous behavior that synchronizes the log-level of `aiohttp` with `ai.backend`, you need to specify the aiohttp log-level explicitly:
> ```
> [logging.pkg-ns]
> ...
> "aiohttp" = "INFO"  # aiohttp access logs are INFO level.
> ```
=> fix: Make log-level/debug flag handling consistent in all components

src/ai/backend/plugin/entrypoint.py
Follow-up fix to #5377 and #5379
=> fix: Nested app-proxy pkgs missing in the entrypoint glob

changes/5394.fix.md, src/ai/backend/agent/docker/agent.py, src/ai/backend/manager/container_registry/base.py, src/ai/backend/manager/container_registry/harbor.py
This is an auto-generated backport PR of #5394 to the 25.6 release.
=> fix(BA-2043): Image rescan exception handling where the image config is `None` (#5394)

changes/5416.feature.md, src/ai/backend/appproxy/common/config.py, src/ai/backend/appproxy/coordinator/api/worker_v2.py, src/ai/backend/appproxy/worker/proxy/frontend/traefik.py, src/ai/backend/appproxy/worker/server.py
=> feat(BA-2066): Add TTL support to Redis key operations in AppProxy

scripts/start-dev.sh, scripts/stop-dev.sh
Introduces start-dev.sh and stop-dev.sh scripts to automate launching and terminating multiple Backend.AI components in tmux sessions for development purposes.
=> chore: Add dev environment start/stop scripts

changes/5469.fix.md, src/ai/backend/agent/agent.py
This is an auto-generated backport PR of #5468 to the 25.6 release.
=> fix(BA-2108): Avoid producing error event in Agent heartbeat (#5468)

changes/5473.fix.md, src/ai/backend/common/web/session/__init__.py, src/ai/backend/common/web/session/redis_storage.py, src/ai/backend/web/server.py
=> fix(BA-2110): Skip saving session for failed login attempts

changes/5454.fix.md, src/ai/backend/agent/affinity_map.py, src/ai/backend/agent/alloc_map.py, tests/agent/test_affinity_map.py
This is an auto-generated backport PR of #5454 to the 24.09 release.
=> fix(BA-2100): NUMA-aware allocation with existing allocations of the first-seen device type (#5454)

.github/workflows/coverage.yml
Inspecting Github Actions cache, the coverage workflow excessively occupies the cache capacity.
Let's fix this.
=> chore: Sync init-pants action of coverage workflow to reduce actions cache pressure

.github/workflows/coverage.yml
This is an auto-generated backport PR of #5537 to the 24.09 release.
=> chore: Sync init-pants action of coverage workflow to reduce actions cache pressure (#5537)

pyproject.toml
This is an auto-generated backport PR of #5541 to the 24.09 release.
=> chore: Add "kubernetes" to the known 3rd-party list for Ruff isort (#5541)

changes/5574.misc.md, pyproject.toml, tools/BUILD, tools/mypy-requirements.txt, tools/mypy.lock
=> chore(BA-2154): Enable mypy support for Strawberry GraphQL

changes/5573.feature.md, src/ai/backend/common/clients/valkey_client/client.py, src/ai/backend/common/config.py, src/ai/backend/common/configs/redis.py, src/ai/backend/common/redis_helper.py, src/ai/backend/common/types.py
resolves #5577 (BA-2158)
related to #5571
=> feat(BA-2158): Add Valkey Client TLS configuration

.claude/agents/linter.md, .claude/agents/tester.md, .claude/agents/typechecker.md
Let Claude Code subagents use pipe-friendly output options in pants commands regardless of user configuration (e.g., `~/.pants.rc`).
=> chore: Update subagents to use pipe-optimized pants options

changes/5625.test.md, tests/common/bgtask/BUILD, tests/common/bgtask/test_bgtask.py, tests/common/bgtask/test_reporter.py, tests/common/bgtask/test_task_base.py, tests/common/bgtask/test_task_registry.py, tests/common/bgtask/test_types.py
=> test(BA-2181): Add Bgtask unit tests

scripts/install-dev.sh, scripts/pyscript.sh, scripts/python.sh
Updates install-dev.sh, pyscript.sh, and python.sh to export $HOME/.local/bin to PATH after installing uv, ensuring the uv command is immediately available in the current session and future shells.
=> chore: Ensure uv is added to PATH after install

src/ai/backend/agent/config/unified.py
Plugin allowlist/blocklist uses the package namespaces.
=> chore: Fix config examples of plugin allowlist/blocklist

changes/5688.feature.md, scripts/agent/build-ttyd.sh, src/ai/backend/agent/agent.py, src/ai/backend/appproxy/worker/proxy/backend/base.py, src/ai/backend/appproxy/worker/proxy/backend/http.py, src/ai/backend/kernel/intrinsic.py, src/ai/backend/runner/.tmux.conf, src/ai/backend/runner/BUILD, src/ai/backend/runner/ttyd_linux.aarch64.bin, src/ai/backend/runner/ttyd_linux.x86_64.bin, src/ai/backend/runner/yank.sh
resolves #5687 (BA-2218)
* Update ttyd to the latest source version to enable **the xterm.js clipboard plugin** which handles OSC 52 sequences.
- Previously, ttyd was imported from `backend.ai-krunner-static-gnu` package, but now it is embedded in `backend.ai-kernel-binary` package with the automated build script: `scripts/agent/build-ttyd.sh`.
* Update `.tmux.conf` to use the new `/opt/kernel/yank.sh` script for copying the buffer selection.
- Explicitly enable the clipboard support and allow-passthrough option in the tmux config.
- `yank.sh` transforms the piped text into a base64-encoded OSC 52 sequence and prints it into the tty device used by the tmux pane.
* Fix the app proxy's aiohttp worker NOT to send empty HTTP bodies when the frontend request does not have the body at all, by …
=> feat(BA-2218): Improve clipboard support in ttyd + tmux mouse mode

changes/5706.fix.md, src/ai/backend/manager/repositories/scheduler/db_source/db_source.py
This PR fixes `ScheduleDBSource. _query_allowed_scaling_groups()` excluding resource groups allowed by project settings. This issue is caused by `ai.backend.manager.models.group._build_group_query` ([ref](https://github.com/lablup/backend.ai/blob/7fc621cb5e857c6ddfdb374a991f211098bd75c8/src/ai/backend/manager/models/group.py#L386)) assuming target parameter as a reference of group ID only if the parameter type is `UUID`.
=> fix: scaling group check failing

changes/5704.feature.md, src/ai/backend/manager/cli/scheduler.py
resolves #BA-2218
change keys to scan_iter for manager cli
=> feat: Improvement redis keys command to scan_iter for manager cli

changes/5736.feature.md, src/ai/backend/common/bgtask/bgtask.py, src/ai/backend/common/clients/valkey_client/valkey_bgtask/client.py, src/ai/backend/common/data/bgtask/defs.py
=> feat: Set expiry to Bgtask metadata id sets

changes/5869.fix.md, src/ai/backend/manager/models/gql_models/image.py
Backported-to: 25.6
Backported-of: 5869
=> fix(BA-2358): Handle empty `supported_accelerators` list in `Image`, `ImageNode`

changes/5872.fix.md, src/ai/backend/manager/models/gql_models/endpoint.py
This is an auto-generated backport PR of #5872 to the 25.6 release.
=> fix(BA-2372): Explicitly use UTC when resolving model service token expiration time (#5872)

pyproject.toml, python.lock, requirements.txt, src/ai/backend/agent/affinity_map.py, src/ai/backend/client/cli/admin/image.py, src/ai/backend/client/cli/pretty.py, src/ai/backend/client/cli/service.py, src/ai/backend/client/cli/session/lifecycle.py, src/ai/backend/client/cli/vfolder.py, src/ai/backend/test/cli_integration/admin/test_domain.py, src/ai/backend/test/cli_integration/admin/test_group.py, src/ai/backend/test/cli_integration/admin/test_image.py, src/ai/backend/test/cli_integration/admin/test_keypair.py, src/ai/backend/test/cli_integration/admin/test_keypair_resource_policy.py, src/ai/backend/test/cli_integration/admin/test_scaling_group.py, src/ai/backend/test/cli_integration/admin/test_storage.py, src/ai/backend/test/cli_integration/admin/test_user.py, src/ai/backend/test/cli_integration/user/test_vfolder.py, src/ai/backend/test/utils/cli.py, tools/mypy-requirements.txt, tools/mypy.lock
* Upgrade mypy (1.17.1 -> 1.18.1)
- https://mypy.readthedocs.io/en/stable/changelog.html#mypy-1-18
* Add missing type stub packages:
- types-colorama
- types-networkx
- types-pexpect
- types-psutil
- types-requests
- types-tqdm
* Fix newly found type errors
* Along with types-tqdm, rewrite `client.cli.pretty.ProgressViewer` (→ `ProgressBarWithSpinner`) in #1049 to make type checkers happy.
- Use tqdm's own `set_description_str()` method to print the spinner character to prevent garbling the terminal output.
- Now it fully utilizes the tqdm inheritance and temporarily overrides the `format_meter()` method so that the progress bar is hidden at first but first assignment to `total` attribute reactivates the progress bar display. If `total` is not set, it just works as a spinner.
- Previously …
=> chore: Upgrade mypy and add type stubs

changes/5903.fix.md, src/ai/backend/manager/sokovan/scheduler/scheduler.py, tests/manager/sokovan/scheduler/test_terminate_sessions.py
=> fix: Set kernel status to terminated when the kernel is missing

.github/workflows/ci.yml
This is an auto-generated backport PR of #5466 to the 25.6 release.
=> feat: Add build-isla-sorna-image workflow (#5466)

changes/5893.fix.md, src/ai/backend/manager/repositories/permission_controller/role_manager.py
This is an auto-generated backport PR of #5893 to the 25.14 release.
=> fix: Change object permission bulk insert to use ORM functions (#5893)

changes/5955.fix.md, src/ai/backend/manager/models/gql_models/user.py, src/ai/backend/manager/repositories/user/repository.py, src/ai/backend/manager/services/user/actions/modify_user.py, src/ai/backend/manager/services/user/service.py, tests/manager/integration/services/user/test_user_integration.py, tests/manager/repositories/user/test_user_repository.py
=> fix(BA-2430): Handle Undefined group ids when modifying user

changes/5924.enhance.md, changes/5924.fix.md, src/ai/backend/common/exception.py, src/ai/backend/manager/services/model_serving/types.py, src/ai/backend/manager/sokovan/deployment/definition_generator/base.py, src/ai/backend/manager/sokovan/deployment/definition_generator/custom.py, src/ai/backend/manager/sokovan/deployment/definition_generator/registry.py, src/ai/backend/manager/sokovan/deployment/deployment_controller.py, src/ai/backend/manager/sokovan/deployment/executor.py
resolves #5889 #5933 #5934 (BA-2385, BA-2411, BA-2412)
=> refactor(BA-2385): Introduce `ModelDefinitionGenerator` pattern to support multiple runtime variant in model service

changes/6050.fix.md, src/ai/backend/manager/repositories/scheduler/db_source/db_source.py, src/ai/backend/manager/sokovan/scheduler/types.py
=> fix(BA-2514): Add missing `kernel_host` field in `KernelCreationInfo`

changes/6049.fix.md, src/ai/backend/manager/cli/fixture.py
This is an auto-generated backport PR of #6049 to the 25.6 release.
=> fix(BA-2519): Wrong error code of `mgr fixture populate` command (#6049)

docs/dev/daily-workflows.rst, pyproject.toml
[basedpyright](https://docs.basedpyright.com/latest/) is an open source alternative of pylance, which is a VSCode-specific proprietary extension to pyright.
It provides faster performance and more LSP features and now became [the default in the Zed editor as of v204.](https://zed.dev/releases/stable/0.204.1)
As it shares the configuration with pyright (e.g., `[tool.pyright]` section in `pyproject.toml`),
this PR explicitly sets `typeCheckingMode = "standard"` to ensure consistency because the defaults in pyright and basedpyright are different.
----
📚 Documentation preview 📚: https://sorna--6052.org.readthedocs.build/en/6052/
----
📚 Documentation preview 📚: https://sorna-ko--6052.org.readthedocs.build/ko/6052/
=> chore: Update pyproject.toml and IDE guides for basedpyright

changes/6055.feature.md, configs/webserver/halfstack.conf, configs/webserver/sample.conf, src/ai/backend/web/config/unified.py, src/ai/backend/web/templates/config.toml.j2
resolves #6055 (BA-2522)
This PR adds enable-reservoir option to enable management of reservoir-related functions in the webui
**changes**
* add `enable-reservoir` to `configs/webserver/halfstack.conf` and `configs/webserver/sample.conf`
* add type for `enable-reservoir` to `src/ai/backend/web/config/unified.py`
* add `enable-reservoir` to `src/ai/backend/web/templates/config.toml.j2` 
=> feat(BA-2522): add enable-reservoir webserver option to enable management of reservoir-related features in the webui

changes/6085.feature.md, src/ai/backend/kernel/__init__.py, src/ai/backend/kernel/__main__.py
This is an auto-generated backport PR of #6085 to the 25.6 release.
=> feat(BA-2547): Prevent accidental container termination by `pkill -f python` command (#6085)

changes/6091.fix.md, src/ai/backend/appproxy/worker/proxy/frontend/traefik.py
resolves #6089 (BA-2549)
- **fix: Prevent last-used marker sync timer from being shut down inadvertently**
- **fix: Make missing-key a warning instead of a loud error**
=> fix(BA-2549): Improve error handling in the traefik frontend of App Proxy

changes/6021.fix.md, src/ai/backend/manager/errors/storage.py, src/ai/backend/manager/models/vfolder.py
=> fix(BA-2490): Correct mount permission check when creating session

changes/6095.fix.md, src/ai/backend/appproxy/coordinator/api/worker_v2.py
This is an auto-generated backport PR of #6095 to the 25.14 release.
=> fix: appproxy worker shutdown clears all circuits (#6095)

changes/6115.deps.md, src/ai/backend/agent/BUILD
This is an auto-generated backport PR of #6115 to the 25.6 release.
=> fix: Build missing agent watcher wheel (#6115)

src/ai/backend/install/context.py
The '-y' flag is not supported by Homebrew's 'brew install' command on Darwin systems. This commit removes the flag to prevent installation errors.
The `-y` option does not exist in `brew`.
=> fix: Remove unsupported '-y' flag from brew install command

changes/5921.enhance.md, src/ai/backend/manager/data/agent/modifier.py, src/ai/backend/manager/event_dispatcher/handlers/agent.py, src/ai/backend/manager/registry.py, src/ai/backend/manager/repositories/agent/cache_source/cache_source.py, src/ai/backend/manager/repositories/agent/db_source/db_source.py, src/ai/backend/manager/repositories/agent/repository.py, src/ai/backend/manager/services/agent/actions/mark_agent_exit.py, src/ai/backend/manager/services/agent/actions/mark_agent_running.py, src/ai/backend/manager/services/agent/processors.py, src/ai/backend/manager/services/agent/service.py
=> refactor: Introduce service, repository layer when handling agent status change event

changes/5976.enhance.md, src/ai/backend/manager/repositories/resource_preset/cache_source/cache_source.py
resolves #5975 (BA-2451)
Though currently using a context manager that suppresses exceptions, duplicate try-except blocks are being employed within the cache source to control exception occurrence. We intend to remove these redundant try-except structures.
```python
@repository_decorator()
async def check_presets(
self,
...
) -> CheckPresetsResult:
...
with suppress_with_log([Exception], message="Failed to get check presets data from cache"):
cached_data = await self._cache_source.get_check_presets_data(
access_key, group_name, domain_name, scaling_group
)
if cached_data:
log.info(
"Cache hit for check_presets: {}, {}, {}", access_key, group_name, domain_name
)
return CheckPresetsResult.from_cache(cached_data)
async def get_check_presets_data(
self,
...
) -> Optional[bytes]:
...
try:
data …
```
=> refactor(BA-2451): Remove duplicated exception handling in `ResourcePresetCacheSource`

changes/6156.fix.md, src/ai/backend/manager/models/gql_models/session.py
=> fix(BA-2588): Resolve kernel `resource_opts` field in `ComputeSessionNode` using dataloader

changes/6139.fix.md, src/ai/backend/agent/agent.py, src/ai/backend/agent/metrics/metric.py, src/ai/backend/agent/metrics/types.py, src/ai/backend/agent/stats.py, src/ai/backend/common/metrics/types.py
This is an auto-generated backport PR of #6139 to the 25.14 release.
=> fix(BA-2596): Clean container utilization metric when destroy kernel (#6139)

changes/2599.fix.md, src/ai/backend/manager/services/vfolder/services/vfolder.py
=> fix(BA-2599): Insert model-store vfolder data in `VFolderPermissionRow` only when vfolder ownership type is user

.github/workflows/backport.yml
Updated the backport workflow to use version sort (-V) when sorting milestones, ensuring correct ordering for versioned milestone names.
=> chore: Sort milestones using version sort in workflow
